### PR TITLE
[2.1] Fix #11689 - DbContext service parameter throws when FastQuery …

### LINKED ISSUE #11689: DbContext service parameter throws when FastQuery is chosen.
I found the following bug while reading through the source code and made a test case.

The `RelationalEntityQueryModelVisitor` [rewrites the materializer expression](https://github.com/aspnet/EntityFrameworkCore/blob/90d9021f22887354cdd4aa78bb75b03776327e87/src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs#L117) when it determines it can use the `FastQuery` method. It rewrites it to directly use a `DbDataReader` instead of `ValueBuffer`. Due to the rewrite, the materializer lambda no longer takes a `MaterializationContext`, instead it takes a `DbDataReader`.

This is fine when only the `ValueBuffer` property of the `MaterializationContext` is used by the code generated by the `IEntityMaterializerSource`, but when the `Context` property is used it throws because it isn't rewritten.

The `Context` parameter will used in the code generated by `IEntityMaterializerSource` when the `DbContext` will be injected as a service parameter in the entity constructor binding.

```
Exception message: System.InvalidOperationException : variable 'materializationContext' of type 'Microsoft.EntityFrameworkCore.Storage.MaterializationContext' referenced from scope '', but it is not defined.

Stack trace:
at System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(ParameterExpression node)
   at System.Linq.Expressions.ParameterExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitNew(NewExpression node)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateExecutorLambda[TResults]()
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at TestCase.Run()
```

### Steps to reproduce
I've made an unit test to make a reproducible example.
I've used `Microsoft.EntityFrameworkCore.SqlServer`, but any relational provider should exhibit the same bug. I also had to call `AsNoTracking` for the `FastQuery` path to trigger, I'm not sure if this is intended behaviour either.

```c#
[Fact]
public void Repro()
{
    var context = new ReproContext();
    context.Database.EnsureCreated();

    context.ReproEntities.AsNoTracking().AsEnumerable().Count();
}

class ReproEntity
{
    public ReproEntity(DbContext context)
    {
    }

    public int Id { get; set; }
}

class ReproContext : DbContext
{
    public DbSet<ReproEntity> ReproEntities { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer("Server=.;Database=Repro;Trusted_Connection = yes;");

        base.OnConfiguring(optionsBuilder);
    }
}
```

### Further technical details
EF Core version: 2.1.0-preview2-final
Database Provider: Microsoft.EntityFrameworkCore.Relational
Operating system: Windows 10
IDE: Visual Studio 2017 15.6.6

### Possible solution
A possible solution is to use the `QueryContext.Context` property seeing as the `QueryContext` is available within the `RelationalQueryModelVisitor`.

In the `FastQueryMaterializerCreatingVisitor`, add the following two fields:
- `MethodInfo` of `MaterializationContext.Context.get` to detect the usage. This is a copy of `MaterializationContext.GetContextMethod`, but that method is internal.
- `MethodInfo` of `QueryContext.Context.get` to which to rewrite.
```C#
private sealed class FastQueryMaterializerCreatingVisitor : ExpressionVisitor
{
    private static readonly MethodInfo _getMaterializerContextContextMethod
        = typeof(MaterializationContext).GetProperty(nameof(MaterializationContext.Context)).GetMethod;

    private static readonly MethodInfo _getQueryContextContextMethod
        = typeof(QueryContext).GetProperty(nameof(QueryContext.Context)).GetMethod;

   // ...
```

And add an `else` statement that checks for the usage of `MaterializationContext.Context.get` and rewrite it to `QueryContext.Context.get`.

```C#
    return _valueBufferAssignmentExpressions[index];
}
else if (node.Method == _getMaterializerContextContextMethod)
{
    return Expression.Call(EntityQueryModelVisitor.QueryContextParameter, _getQueryContextContextMethod);
}

return base.VisitMethodCall(node);
```

### PR DESCRIPTION
**Pull request by anpete**
…is chosen

- When performing the fast query rewrite, transform materializationContext.Context access to a parameter on the materialization lambda.

### CODE REVIEW

File: src/EFCore.Relational/Query/AsyncQueryMethodProvider.cs [hunk 1]
```diff
@@ -73,50 +73,71 @@ private class FastQueryAsyncEnumerable<TEntity> : IAsyncEnumerable<TEntity>
             }
 
             public IAsyncEnumerator<TEntity> GetEnumerator()
-                => new FastQueryAsyncEnumerator(this);
+                => new FastQueryAsyncEnumerator(
+                    _relationalQueryContext,
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/AsyncQueryMethodProvider.cs]: We could pass this to ctor and deconstruct inside ctor into component

**Comment by anpete** [comment]
Why fix it: Regression in many simple no-tracking customer queries.
Risk: Medium, change to generated compiled query code.
Testing: Modified standard query model to use both ctor and property binding.

**Comment by ajcvickers** [comment]
@anpete Approved for RC1
