### PR TITLE
Fix #9741 - AddDbContextPool in asp.net core System.InvalidOperationException

### LINKED ISSUE #9741: AddDbContextPool in asp.net core System.InvalidOperationException
I'm using db context pooling in a Asp.Net core MVC application.
When I launch multiple simultaneous requests I get an error :

```
Exception message: System.InvalidOperationException occurred in Microsoft.EntityFramework.Core.dll
A second operation started on this context before a previous operation completed. Any instance members are not guaranteed to be thread safe.

or 
Exception message: System.ObjectDisposedException: 'Cannot access a disposed object.

code;
IQueryable<TEntity> query = DbSet;
            if (filter != null)
                query = query.Where(filter); // exception occurs here

```
Maybe I'm not using DbContext pooling the right way...

### Steps to reproduce
I launch mutiple requests in browser to the same web api controller method, which retrieves some data from the database.

```c#
 // Dependency injection is configured in Startup as follows
    services.AddScoped<IMyDbContext>(provider => provider.GetService<MyDbContext>());

// if I use service.AddScoped<IMyDbContext,MyDbContext>();
//  I get the impression db context pooling is not working, 
//  but I don't get the exception message either.

// db context pooling in Startup class
   services.AddDbContextPool<MyDbContext>(options =>
            {
                string connectionString = Configuration.GetConnectionString("MyConnection");
                options.UseSqlServer(connectionString);
            },10);
```

### Further technical details
EF Core version:Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.0"
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer
Operating system: Win10
IDE: Visual Studio 2017

### PR DESCRIPTION
**Pull request by anpete**
Problem: Pooling was not resilient to multiple DbContext.Dispose calls, which meant that a context instance could incorrectly be returned to the pool twice.
Solution: Adds a DbContext async local to track which "context" (e.g. request scope) owns the context and use it to ensure a single return to the pool.

### CODE REVIEW

File: src/EFCore/DbContext.cs [hunk 1]
```diff
@@ -94,7 +96,7 @@ public DbContext([NotNull] DbContextOptions options)
             }
 
             _options = options;
-
+
```
Comment (AndriySvyryd) [inline src/EFCore/DbContext.cs]: Reformat

File: src/EFCore/DbContext.cs [hunk 2]
```diff
@@ -64,6 +64,8 @@ public class DbContext :
         private bool _initializing;
         private bool _disposed;
 
+        private AsyncLocal<bool> _leased;
```
Comment (AndriySvyryd) [inline src/EFCore/DbContext.cs]: Wouldn't this work with a `bool?` instead of `AsyncLocal`?

Comment (anpete) [reply src/EFCore/DbContext.cs]: No.

Comment (AndriySvyryd) [reply src/EFCore/DbContext.cs]: Can you elaborate? The tests pass with `bool?`

Comment (anpete) [reply src/EFCore/DbContext.cs]: Are you sure? Double_dispose_concurrency_test fails for me without the async local.

Request A calls Dispose - context A is returned to pool.
Request B calls Rent and acquires context A.
Request A calls Dispose and context A is returned to pool. Boom!

Comment (AndriySvyryd) [reply src/EFCore/DbContext.cs]: I see. The test passes unless I ran it on its own.

File: src/EFCore/DbContext.cs [hunk 3]
```diff
@@ -482,17 +484,18 @@ void IDbContextPoolable.SetPool(IDbContextPool contextPool)
             Check.NotNull(contextPool, nameof(contextPool));
 
             _dbContextPool = contextPool;
+            _leased = new AsyncLocal<bool> { Value = true };
```
Comment (ajcvickers) [inline src/EFCore/DbContext.cs]: Is this thread-safe? Depending on what caches have been flushed, thread A could see the old value for _leased even though thread B has set a new value, Thread A would then see this instance as not leased and attempt to lease it.

Comment (anpete) [reply src/EFCore/DbContext.cs]: AFAIK, I thought that was the point of AsyncLocal. Perhaps @AndriySvyryd or @divega can comment.

Comment (ajcvickers) [reply src/EFCore/DbContext.cs]: My understanding is that if you set a value on an AsyncLocal, then it will only be visible to the current execution context--i.e. `_leased.Value = true;` But unless the compiler is doing some magic on the _leased field, then it's just a normal field holding something that happens to be an AsyncLocal.

Comment (anpete) [reply src/EFCore/DbContext.cs]: Oh, you mean the _leased field. SetPool is only ever call once when the context is created.

Comment (ajcvickers) [reply src/EFCore/DbContext.cs]: Got it! :-)
