### PR TITLE
Query: Materialize results of FirstOrDefault in subquery only when th…

### LINKED ISSUE #17287: Query: FirstOrDefault on anonymous type in subquery gives wrong results
We initialize the new Expression with default values rather than returning null.
Uncovered while discovering that we didn't take care of returning default part. It worked on top level since there was no row.

### PR DESCRIPTION
**Pull request by smitpatel**
…ere are rows

Issue: When we generate translation for subquery.FirstOrDefault() using Left join, we get null in values when there is no associated record.
Then we try to create result with default values rather than returning default of result type.

Fix: Whenever we go through path where we are adding subquery.FirstOrDefault in projection, we inject 1 as dummy column. If we see 1 in result then only we materialize the object else we return default of the type.
- For entityTypes this is not needed because we return null if key values are null.
- For scalar which is server eval (i.e. only 1 column), we generate projectionBinding using resultType so we will get correct default back.
- For scalar result which is client eval, we inject 1 into client projections.
- For non scalar results (anonymous/nominal types), in client/server eval case, we inject 1 into projection/projectionMapping.

Resolves #17287

### CODE REVIEW

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 1]
```diff
@@ -799,6 +799,31 @@ EntityProjectionExpression LiftEntityProjectionFromSubquery(EntityProjectionExpr
         public Expression AddSingleProjection(ShapedQueryExpression shapedQueryExpression)
         {
             var innerSelectExpression = (SelectExpression)shapedQueryExpression.QueryExpression;
+            var shaperExpression = shapedQueryExpression.ShaperExpression;
+            var innerExpression = RemoveConvert(shaperExpression);
+            if (!(innerExpression is EntityShaperExpression))
+            {
+                var dummy1Expression = innerSelectExpression.Limit;
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs]: Why `.Limit` and can we be sure it's not null?

File: test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs [hunk 2]
```diff
@@ -1283,7 +1284,7 @@ public virtual Task Where_compare_anonymous_types_with_uncorrelated_members(bool
             return AssertQuery(
                 isAsync,
                 ss => from g in ss.Set<Gear>()
-                      // ReSharper disable once EqualExpressionComparison
+                          // ReSharper disable once EqualExpressionComparison
```
Comment (AndriySvyryd) [inline test/EFCore.Specification.Tests/Query/GearsOfWarQueryTestBase.cs]: Move the comments before the query if you can't get VS to format them correctly

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 3]
```diff
@@ -816,7 +841,13 @@ public Expression AddSingleProjection(ShapedQueryExpression shapedQueryExpressio
             }
 
             return new ShaperRemappingExpressionVisitor(this, innerSelectExpression, indexOffset)
-                .Visit(shapedQueryExpression.ShaperExpression);
+                .Visit(shaperExpression);
+
+            static Expression RemoveConvert(Expression expression)
```
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs]: we already have helper method for this in core ExpressionExtensions

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 1 above)
Comment (maumar) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs]: sentinelExpression?

Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs]: This code path is hit only when it is inside subquery single result scenario so there is always going to be top(1).

Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs]: Filed #18711

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs (hunk 3 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs]: RemoveConvert is obsolete and should be removed. We have it in few places. We can discuss how to DRY the code at the same time, avoid misuse of that API.

**Comment by smitpatel** [comment]
cc: @Pilchie
