### PR TITLE
Query: Use correct overload of DelimitIdentifier() in DefaultQuerySqlGenerator

### LINKED ISSUE #9560: Query: Ensure ISqlGenerationHelper is used when generating identifiers
Investigate: It looks like we may be incorrectly outputing a configured schema when generating table names in Sqlite queries.

### PR DESCRIPTION
**Pull request by bricelam**
Fixes #9560

I reviewed all places we generate SQL for schema and table name to ensure they were consistent.

You may want to review [ignoring whitespace changes](https://github.com/aspnet/EntityFrameworkCore/pull/9903/files?w=1) since the R# settings have diverged from Visual Studio's default formatting.

### CODE REVIEW

File: src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs [hunk 1]
```diff
@@ -645,14 +645,7 @@ public virtual Expression VisitTable(TableExpression tableExpression)
         {
             Check.NotNull(tableExpression, nameof(tableExpression));
 
-            if (SupportsSchemas
```
Comment (bricelam) [inline src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs]: @anpete Can we get rid of `SupportsSchemas`? It was introduced for Oracle, but SQLite was already handling this by overriding the `SqlGenerator.DelimitIdentifier()` overload. That overload is used by Query, Update, and Migrations.

Comment (anpete) [reply src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs]: I'm fine if it works. Can you check that we don't break the Oracle sample.

**Comment by anpete** [comment]
Can we decide on the whitespace formatting one or the other? We either need to update our R# settings, or the changes here should be reverted. cc @ajcvickers

**Comment by ajcvickers** [comment]
Filed #9911 for R# settings

File: src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs (hunk 1 above)
Comment (bricelam) [reply src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs]: This is turning into a yak shaving exercise. Oracle solution was broken by #9629. Need to install Oracle Database... lol, I'll keep at it.

Comment (bricelam) [reply src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs]: I'm getting thousands of test failures with the following:

> ORA-00972: identifier is too long

I'm using version 12.1. Is the sample only compatible with 12.2?

Comment (smitpatel) [reply src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs]: According to stack overflow max length was 30 upto 12.1 and was increased in 12.2.
We need to have a vm setup somewhere for this kind of testing so that all of us don't have to install oracle. May be efci host machine.

Comment (anpete) [reply src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs]: Yep, the required version is listed in the [readme](https://github.com/aspnet/EntityFrameworkCore/tree/dev/samples/OracleProvider): 12c Release 2.

Comment (bricelam) [reply src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs]: Lame. Latest Docker image is 12.1. I'll spin up a VM.

Comment (bricelam) [reply src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs]: (But when there's a 12.2 Docker image, I'll send out instructions to the team since I've got it all working.)

**Comment by smitpatel** [comment]
@bricelam - You need to rebase this on latest dev. All the issues with running Oracle has been fixed.

**Comment by bricelam** [comment]
Total tests: 5474. Passed: 5400. Failed: 0. Skipped: 74.
