### PR TITLE
Fix propagation of fixed length facet

### LINKED ISSUE #14163: Infer RelationalTypeMappingInfo.IsFixedLength correctly
https://github.com/aspnet/EntityFrameworkCore/pull/14162 is making it to set to false, whenever inferring it from a store type or member. Filing this issue so we can determine, if that is the right thing to do.

### LINKED ISSUE #18961: IsFixedLength() isn't propagated to foreign keys
A foreign key referencing a `string` column that has `IsFixedLength` set to true doesn't automatically receive `IsFixedLength`, resulting in a database error because the column types don't match.

### Steps to reproduce

```c#
using Microsoft.EntityFrameworkCore;

namespace ConsoleApp3
{
    public sealed class Country
    {
        public string IsoCode { get; set; }
    }

    public sealed class Address
    {
        public int Id { get; set; }
        public string CountryCode { get; set; }
    }

    public sealed class ApplicationDbContext : DbContext
    {
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            base.OnConfiguring(optionsBuilder);
            optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=aspnet-WebApplication-6E483A89-BEE6-4A76-96CC-CEB276E5E112;Trusted_Connection=True;MultipleActiveResultSets=true");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Entity<Country>().HasKey(c => c.IsoCode);

            modelBuilder.Entity<Country>().Property(c => c.IsoCode)
                .IsRequired()
                .IsUnicode(false)
                .HasMaxLength(2)
                .IsFixedLength(); // Removing this works.

            modelBuilder.Entity<Address>().Property(a => a.CountryCode)
                .IsRequired();

            modelBuilder.Entity<Address>().HasOne<Country>().WithMany().HasForeignKey(a => a.CountryCode).OnDelete(DeleteBehavior.Restrict);
        }
    }

    public static class Program
    {
        public static void Main()
        {
            using (var context = new ApplicationDbContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();
            }
        }
    }
}
```

When running this, I get an exception from the database:

> Microsoft.Data.SqlClient.SqlException: 'Column 'Country.IsoCode' is not the same data type as referencing column 'Address.CountryCode' in foreign key 'FK_Address_Country_CountryCode'.
Could not create constraint or index. See previous errors.'

If I remove `IsFixedLength`, everything works properly - both `IsUnicode` and `HasMaxLength` are set up on the foreign key to be the same as on the primary key - both columns end up being `varchar(2)`. Since both of these are transferred automatically to the foreign key, I would expect that to be the case with `IsFixedLength` as well.

This isn't a critical issue of course because we can always specify `IsFixedLength` on the foreign key manually.

### Further technical details

EF Core version: 3.0.0
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.0
Operating system: Windows 10 Version 1903
IDE: Visual Studio 16.4.0 Preview 5.0

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #18961
Fixes #14163

### CODE REVIEW

File: src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs [hunk 1]
```diff
@@ -360,24 +360,16 @@ private static object ConvertDefaultValue([NotNull] IProperty property, [CanBeNu
         /// </summary>
         /// <param name="property"> The property. </param>
         /// <returns> A flag indicating if the property as capable of storing only fixed-length data, such as strings. </returns>
-        public static bool IsFixedLength([NotNull] this IProperty property)
-            => (bool?)property[RelationalAnnotationNames.IsFixedLength] ?? GetDefaultIsFixedLength(property);
-
-        private static bool GetDefaultIsFixedLength(IProperty property)
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Extensions/RelationalPropertyExtensions.cs]: Why was this removed?
