### PR TITLE
Don't throw on missing discriminator in seed data

### LINKED ISSUE #11083: EF Core 2.1 Preview 1 SeedData method throws The seed entity for entity type 'XXX' cannot be added because the was no value provided for the required property 'Discriminator'.
SeedData has an issue with Entities that rely on Discriminators. Updated ef core tutorial highlights the issue.

```
update-database
Microsoft.EntityFrameworkCore.Model[10601]
      The index {'CourseID'} was not created as the properties are already covered by the index {'CourseID', 'InstructorID'}.
System.InvalidOperationException: The seed entity for entity type 'Student' cannot be added because the was no value provided for the required property 'Discriminator'. 
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.ValidateSeedData(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Internal.SqlServerModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__0(Object k)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.GetModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.EntityFrameworkCore.Infrastructure.EntityFrameworkServicesBuilder.<>c.<TryAddCoreServices>b__7_1(IServiceProvider p)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(IServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.DbContext.Microsoft.EntityFrameworkCore.Infrastructure.IInfrastructure<System.IServiceProvider>.get_Instance()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Infrastructure.AccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.UpdateDatabase(String targetMigration, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.UpdateDatabase.<>c__DisplayClass0_1.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
The seed entity for entity type 'Student' cannot be added because the was no value provided for the required property 'Discriminator'.
```

### Steps to reproduce
Using the following sample:
https://github.com/aspnet/Docs/tree/master/aspnetcore/data/ef-mvc/intro/samples/cu-final

Comment out everything in Data\DbInitializer\Initialize 

Add the following code at the end of Data\SchoolContext\OnModelCreating 
```C#
            modelBuilder.Entity<Student>().SeedData(new Student
            {
                ID = 1,
                EnrollmentDate = DateTime.Now,
                FirstMidName = "FirstName",
                LastName = "Lastname"
            });
```

Run update-database from the package manager console.

### Further technical details
EF Core version: "Microsoft.EntityFrameworkCore.Relational" Version="2.1.0-preview1-final"
Database Provider: "Microsoft.EntityFrameworkCore.SqlServer": "2.1.0-preview1-final"
Operating system: Win 10 Pro x64 1709 16299.248
IDE: VisualStudio.15.Preview/15.6.0-pre.6.0+27421.1

### LINKED ISSUE #11097: Migrations generates invalid code for data seeding
I was trying to try out the new data seeding feature from Preview 1. However, it seems like EF is generating invalid C# code sometimes, depending on entity.

Please refer to [this repository](https://github.com/alaatm/EF21MigrationsIssue) where I have already generated migrations but the code is invalid with the message: **No best type found for implicitly-typed array** in both designer and snapshot files.

### Further technical details
EF Core version: 2.1 Preview 1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Don't generated implicitly-typed array for seed data in the snapshot

Fixes #11083
Fixes #11097

### CODE REVIEW

File: src/EFCore/Infrastructure/ModelValidator.cs [hunk 1]
```diff
@@ -481,29 +481,26 @@ protected virtual void ValidateSeedData([NotNull] IModel model)
                     foreach (var property in entityType.GetProperties())
                     {
                         if (!seedDatum.TryGetValue(property.Name, out var value)
-                            || value == null)
+                            || value == null
+                            || property.ClrType.IsDefaultValue(value))
```
Comment (smitpatel) [inline src/EFCore/Infrastructure/ModelValidator.cs]: IsDefaultValue already verifies for value == null

Comment (AndriySvyryd) [reply src/EFCore/Infrastructure/ModelValidator.cs]: Only if `ClrType` is nullable
