### PR TITLE
Fix #10740: Repair the database name with apostrophe

### LINKED ISSUE #10740: Database with apostrophe in name throws an exception on create
I'm trying to create a named Test'1 database, the code below throws an exception but creates the database in server. Once the database is created, the code works fine:

```
    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new AppContext())
            {
                var entity = new Entity();
                ctx.Add(entity);
                ctx.SaveChanges();
            }
        }
    }

    public class AppContext : DbContext
    {
        public DbSet<Entity> Entities { get; set; }

        public AppContext()
        {
            Database.EnsureCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test'1;Trusted_Connection=True;");
        }
    }

    public class Entity
    {
        public int Id { get; set; }
    }
```

Exception message: 
> System.Data.SqlClient.SqlException: 'Incorrect syntax near '1'.
> 'READ_COMMITTED_SNAPSHOT' is not a recognized SET option.
> Unclosed quotation mark after the character string ');
> '.'

StackTrace:  
>  en System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    en System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    en System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    en System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    en System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
>    en System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
>    en System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
>    en Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
>    en Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
>    en Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
>    en Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
>    en Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.Create()
>    en Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
>    en Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
>    en EFCoreTest.AppContext..ctor() en C:\Users\User\Projects\EFCoreTest\EFCoreTest\Program.cs:línea 29
>    en EFCoreTest.Program.Main(String[] args) en C:\Users\User\Projects\EFCoreTest\EFCoreTest\Program.cs:línea 14

If I use double apostrophe to escape the character in connection string, the database is also created but throws a different error:
`optionsBuilder.UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test''1;Trusted_Connection=True;");`

Exception message:
> System.Data.SqlClient.SqlException: 'User does not have permission to alter database 'Test'1', the database does not exist, or the database is not in a state that allows access checks.
> ALTER DATABASE statement failed.'

StackTrace:  

>    en System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    en System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
>    en System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
>    en System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
>    en System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
>    en System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
>    en System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
>    en Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
>    en Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
>    en Microsoft.EntityFrameworkCore.Migrations.MigrationCommand.ExecuteNonQuery(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
>    en Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQuery(IEnumerable`1 migrationCommands, IRelationalConnection connection)
>    en Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerDatabaseCreator.Create()
>    en Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.EnsureCreated()
>    en Microsoft.EntityFrameworkCore.Infrastructure.DatabaseFacade.EnsureCreated()
>    en EFCoreTest.AppContext..ctor() en C:\Users\User\Projects\EFCoreTest\EFCoreTest\Program.cs:línea 29
>    en EFCoreTest.Program.Main(String[] args) en C:\Users\User\Projects\EFCoreTest\EFCoreTest\Program.cs:línea 14

### Further technical details
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.5.4

### PR DESCRIPTION
**Pull request by ralmsdeveloper**
Fixes #10740 

* Solve apostrophe problem in database name

New SQL output:

```sql
IF SERVERPROPERTY('EngineEdition') <> 5
BEGIN
    ALTER DATABASE [Migrations'Test] SET READ_COMMITTED_SNAPSHOT ON;
END;
```

### CODE REVIEW

File: src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs [hunk 1]
```diff
@@ -657,12 +657,20 @@ protected override void Generate(EnsureSchemaOperation operation, IModel model,
...
                 .AppendLine(Dependencies.SqlGenerationHelper.StatementTerminator)
                 .EndCommand(suppressTransaction: true)
-                .Append("IF SERVERPROPERTY('EngineEdition') <> 5 EXEC(N'ALTER DATABASE ")
-                .Append(Dependencies.SqlGenerationHelper.DelimitIdentifier(operation.Name))
-                .Append(" SET READ_COMMITTED_SNAPSHOT ON")
-                .Append(Dependencies.SqlGenerationHelper.StatementTerminator)
-                .Append("')")
-                .AppendLine(Dependencies.SqlGenerationHelper.StatementTerminator)
+                .AppendLine("IF SERVERPROPERTY('EngineEdition') <> 5")
+                .AppendLine("BEGIN");
```
Comment (bricelam) [inline src/EFCore.SqlServer/Migrations/SqlServerMigrationsSqlGenerator.cs]: I think we need `EXEC` for SQL Azure. Even though it never executes `ALTER DATABASE`, it still needs to parse it.

**Comment by ralmsdeveloper** [comment]
@bricelam,
I did some tests, I did not find anything that was incompatible!
Also I looked for some basic information of the commands, all are compatible with SQL Azure.

[Transact Sql](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/execute-transact-sql)

[Statements](https://docs.microsoft.com/en-us/sql/t-sql/statements/statements)

[Begin End](https://docs.microsoft.com/en-us/sql/t-sql/language-elements/begin-end-transact-sql)

If there is something you know about it, could you share it?
I do not think it's cool to insert a `'` escape.

**Comment by ralmsdeveloper** [comment]
@bricelam,
I've done several local tests here simulating the situation: Creating and deleting the database.
Would you like me to add a specific test for this?
