### PR TITLE
Don't discover FK properties named the same as the principal properties

### LINKED ISSUE #13274: Don't detect FK properties that match exactly the principal key properties
`OwnsOne` is throwing an exception when owned type has the same key name and type, even if the root entity id and the child entity id were marked with `HasColumnName` differently.

```c#
systems.Property(s => s.Id).HasColumnName("SystemId")
```
```c#
var accountForPartner = systems.OwnsOne(s => s.AccountForPartners);
accountForPartner
    .Property(ap => ap.Id)
    .HasColumnName("AccountForPartnerId")
    .IsRequired();
accountForPartner
    .Property(ap => ap.Number)
    .HasColumnName("AccountForPartnerNumber");
```

This code was working in the previous version(the latest working version is 2.0.3), but starting from 2.1.0 it doesn't work anymore.

Exception message:
```c#
The keys {'Id'} on 'System.AccountForPartners#Account' and {'Id'} on 'System' are both mapped to 'System.SystemId' but with different columns ({'AccountForPartnerId'} and {'SystemId'}).
```
Stack trace:
```c#
System.InvalidOperationException: The keys {'Id'} on 'System.AccountForPartners#Account' and {'Id'} on 'System' are both mapped to 'System.SystemId' but with different columns ({'AccountForPartnerId'} and {'SystemId'}).
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedKeysCompatibility(IReadOnlyList`1 mappedTypes, String tableName)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.ValidateSharedTableCompatibility(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.RelationalModelValidator.Validate(IModel model)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.CreateModel()
   at Microsoft.EntityFrameworkCore.Internal.DbContextServices.get_Model()
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.EntityFrameworkCore.DbContext.get_DbContextDependencies()
   at Microsoft.EntityFrameworkCore.DbContext.get_InternalServiceProvider()
   at Microsoft.EntityFrameworkCore.Internal.InternalAccessorExtensions.GetService[TService](IInfrastructure`1 accessor)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(Func`1 factory)
   at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.CreateContext(String contextType)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
```

### Steps to reproduce
It throws when you try to add a migration `dotnet ef migrations add [Name]`

```c#

public class System
{
    public Guid Id { get; private set; }

    public Account AccountForPartners { get; private set; }

    private System() { }
}

public class Account
{
    public Guid Id { get; private set; }

    public string Number { get; private set; }

    private Account() { }
}

var systems = modelBuilder.Entity<System>().ToTable("System");
systems.HasKey(s => s.Id);
systems.Property(s => s.Id).HasColumnName("SystemId").IsRequired();

var accountForPartner = systems.OwnsOne(s => s.AccountForPartners);
accountForPartner.Property(ap => ap.Id).HasColumnName("AccountForPartnerId").IsRequired();
accountForPartner.Property(ap => ap.Number).HasColumnName("AccountForPartnerNumber");
```

### Further technical details
EF Core version: 2.1.0-2.1.3
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.3

### PR DESCRIPTION
**Pull request by AndriySvyryd**
This mostly affects owned types, because on non-owned types the properties we would've used for the FK are likely to be part of the PK and thus wouldn't be used.

Fixes #13274

### CODE REVIEW

File: src/EFCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs [hunk 1]
```diff
@@ -49,6 +49,11 @@ public virtual InternalRelationshipBuilder Apply(InternalRelationshipBuilder rel
         {
             relationshipBuilder = DiscoverProperties(relationshipBuilder);
 
+            if (relationshipBuilder.Metadata.DeclaringEntityType.GetForeignKeysInHierarchy().Count() < 2)
```
Comment (smitpatel) [inline src/EFCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs]: Can you explain this condition? lol

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/Internal/ForeignKeyPropertyDiscoveryConvention.cs]: This is just a short circuit for perf, since if there's only one fk then it's the one we just ran through the convention and we don't need to process anything else.
 I'll add some comments or remove this.
