### PR TITLE
Fix to #18916 - Query: regression in EFCore 3.1 Preview 2 and Preview3 for query with conditional expression whose element is a comparison containing null-value parameter

### LINKED ISSUE #18916: Query: regression in EFCore 3.1 Preview 2 and Preview 3 for query with conditional expression whose element is a comparison containing null-value parameter
I have the following Query filter which worked in EFCore 3.1 Preview 1. Starting with Preview 2, it stopped working and gives a SQL error. The error persists in the latest Preview 3 of EFCore.

**Query filter**

```
HasQueryFilter(item => (
    function.Bar()  == null
    ?
    (Foo.Where(t => t.Id == EF.Property<Guid>(item, "FooId")).Single().Bar == bar.Bar())
    :
    (EF.Property<Guid>(item, "Foo") == function.Bar())
));
```

The generated SQL in 3.1 Preview 1 is along the following:

```
 SELECT [snip]
  FROM [snip] AS [a]
  WHERE (CASE
      WHEN @__ef_filter__p_0 = CAST(1 AS bit) THEN CASE
          WHEN (((
              SELECT TOP(1) [f].[Bar]
              FROM [Foo] AS [f]
              WHERE [f].[Id] = [a].[FooId]) = @__ef_filter__p_1) AND ((
              SELECT TOP(1) [f].[Bar]
              FROM [Foo] AS [f]
              WHERE [f].[Id] = [a].[FooId]) IS NOT NULL AND @__ef_filter__p_1 IS NOT NULL)) OR ((
              SELECT TOP(1) [f].[Bar]
              FROM [Foo] AS [f]
              WHERE [f].[Id] = [a].[FooId]) IS NULL AND @__ef_filter__p_1 IS NULL) THEN CAST(1 AS bit)
          ELSE CAST(0 AS bit)
      END
      ELSE CASE
          WHEN ([a].[FooId] = @__ef_filter__p_2) AND @__ef_filter__p_2 IS NOT NULL THEN CAST(1 AS bit)
          ELSE CAST(0 AS bit)
      END
      END = CAST(1 AS bit)) AND (([a].[Id] = @__p_0) AND @__p_0 IS NOT NULL)
```

However, starting with Preview 2 it generates the following SQL:

````
Failed executing DbCommand (1ms) [Parameters=[@__ef_filter__p_0='?' (DbType = Boolean), @__ef_filter__p_1='?' (Size = 450), @__p_0='?' (DbType = Guid)], CommandType='Text', CommandTimeout='30']
SELECT [snip]
FROM [snip] AS [a]
WHERE (CASE
    WHEN @__ef_filter__p_0 = CAST(1 AS bit) THEN CASE
        WHEN ((
            SELECT TOP(1) [f].[Bar]
            FROM [Foo] AS [f]
            WHERE [f].[Id] = [a].[FooId]) = @__ef_filter__p_1) AND (
            SELECT TOP(1) [f].[Bar]
            FROM [Foo] AS [f]
            WHERE [f].[Id] = [a].[FooId]) IS NOT NULL THEN CAST(1 AS bit)
        ELSE CAST(0 AS bit)
    END
    ELSE CASE
        WHEN CAST(0 AS bit) THEN CAST(1 AS bit)
        ELSE CAST(0 AS bit)
    END
END = CAST(1 AS bit)) AND ([a].[Id] = @__p_0)
`````

Which results in an error: 

`````
Microsoft.Data.SqlClient.SqlException (0x80131904): An expression of non-boolean type specified in a context where a condition is expected, near 'THEN'.
`````

It seems EFCore tries to be clever here and is optimizing away the second condition? (which is nullable)

### Further technical details

EF Core version: 3.1.0-preview3.19554.8
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET Core 3.1 Preview 3
Operating system: Windows 10
IDE: Visual Studio 2019 16.4.0 Preview 5.0

### PR DESCRIPTION
**Pull request by maumar**
Problem was that now we are peeking into parameter values and simplifying the queries. As a result comparisons of non-nullable expressions with null-value parameter are optimized out to a simple constant false. Sql server expects search condition in some places (e.g. WHERE, HAVING or WHEN parts of CASE statements).
Before we look into parameter values we run SearchConditionConvertingExpressionVisitor which fixes those cases. However, this visitor is currently sql server specific, and the part of the pipeline that looks into parameter values is not provider specific, so we can't re-run it.

Fix is to manually convert constants encountered in those areas into conditions. We used to do it already for WHERE and HAVING but we missed WHEN.

Resolves #18916

### CODE REVIEW

File: src/EFCore.Relational/Query/Internal/ParameterValueBasedSelectExpressionOptimizer.cs [hunk 1]
```diff
@@ -122,6 +124,38 @@ protected override Expression VisitExtension(Expression extensionExpression)
...
+                    for (var i = 0; i < newCaseExpression.WhenClauses.Count; i++)
+                    {
+                        if (newCaseExpression.WhenClauses[i].Test is SqlConstantExpression whenConstantTestExpression
+                            && whenConstantTestExpression.Value is bool whenBoolValue)
+                        {
+                            changed = true;
+                            newWhenClauses.Add(
+                                new CaseWhenClause(
+                                    SqlExpressionFactory.Equal(
+                                        whenConstantTestExpression,
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/ParameterValueBasedSelectExpressionOptimizer.cs]: create local function to generate Equal expression.

**Comment by smitpatel** [comment]
This has build check failures. Can you investigate?

**Comment by maumar** [comment]
Customer Impact
Query failure (invalid sql) when using conditional expression when result expression is a comparison with null-valued parameter.

How found
Customer-reported (#18916)

Test coverage
We did not have tests when all necessary conditions were met.

Regression?
Yes, from 3.0.

Risk
Risk is very small - fix is very targeted and we already apply the same logic in two other places. Just missed the 3rd case where it was needed.

Workaround:
Workaround is to rewrite the query so that comparison with null-value parameter is not happening in the result of case expression. Workaround is relatively simple to implement but not intuitive. Alternatively, 2 separate queries can be written, one for `prm2` being null and one when its not null.

original query:

```cs
var prm1 = true;
var prm2 = default(string);
var query = customers.Where(c => c.IsVip == true ? true : c.Name == prm2);
```

workaround:

```cs
var prm1 = true;
var prm2 = default(string);
var query = customers.Where(c => c.IsVip == true ? true : prm2 == null ? c.Name == null : c.Name == prm2);
```

**Comment by maumar** [comment]
@Pilchie @ajcvickers

**Comment by ajcvickers** [comment]
@Pilchie @wtgodbe @dougbu Can this now be merged for 3.1.1?
