### PR TITLE
Reset relationship uniqueness when removing the navigation to dependent.

### LINKED ISSUE #15512: EF Core 3.0 : Why does it automatically generate a unique index?
I have a `class` (I removed some irrelevant properties)

```C#
public class Comment
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public long CommentID { get; set; }

    public long? ReplyCommentID { get; set; }

    public long? ParentCommentID { get; set; }

    [ForeignKey("ParentCommentID")]
    public virtual Comment ParentComment { get; set; }

    [ForeignKey("ReplyCommentID")]
    public virtual Comment ReplyComment { get; set; }
}

```

In my `DbContext`

```C#
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Comment>()
        .ToTable("Comments")
        .HasQueryFilter(x => x.IsDeleted == false);

    var cascadeFKs = modelBuilder.Model.GetEntityTypes()
        .SelectMany(t => t.GetForeignKeys())
        .Where(fk => !fk.IsOwnership && fk.DeleteBehavior == DeleteBehavior.Cascade);
    foreach (var fk in cascadeFKs)
        fk.DeleteBehavior = DeleteBehavior.Restrict;
}
```

### Steps to reproduce
In `PMC` run this:
```
PM> dotnet ef migrations add init
```

After run it, the tool generates the following:

```C#
migrationBuilder.CreateIndex(
    name: "IX_Comments_ParentCommentID",
    table: "Comments",
    column: "ParentCommentID",
    unique: true,
    filter: "[ParentCommentID] IS NOT NULL");

migrationBuilder.CreateIndex(
    name: "IX_Comments_ReplyCommentID",
    table: "Comments",
    column: "ReplyCommentID");
```

Interestingly, only `ParentCommentID` generates a unique index, while `ReplyCommentID` does not. I don't want to specify `IsUnique(false)` in DbContext. So, what exactly is this situation? 😄

### Further technical details
EF Core version: 3.0.0-preview3.19153.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 1903
IDE: Visual Studio 2019 16.0.2

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Fixes #15512

### CODE REVIEW

**Comment by AndriySvyryd** [comment]
I was too optimistic. Tests _seemed_ to pass locally because I didn't see the debug asserts failing

File: src/EFCore/Metadata/Internal/ConventionAnnotation.cs [hunk 1]
```diff
@@ -43,6 +43,6 @@ public ConventionAnnotation([NotNull] string name, [CanBeNull] object value, Con
         ///     doing so can result in application failures when updating to a new Entity Framework Core release.
         /// </summary>
         public virtual ConfigurationSource UpdateConfigurationSource(ConfigurationSource configurationSource)
-            => _configurationSource = _configurationSource.Max(configurationSource);
+            => _configurationSource = configurationSource.Max(_configurationSource);
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/ConventionAnnotation.cs]: No functional impact, just consistency
