### PR TITLE
Tools: Make the migration script path relative to the current directory

### LINKED ISSUE #10036: Script output ends up in unexpected directory
I have two projects.  For simplicity lets call them Widgets.Core and Widgets.UI.  Widgets.Core is a `netstandard2` library and houses all my EF models and DbContexts, so I run my migrations from there.  Widgets.UI is my ASP.NET Core front end running on .NET Core 2.

I want all my .cs migrations to go to Widgets.Core\Data\Migrations.  I also want to generate .sql migrations and have them go to Widgets.Core\Data\Migrations\SQL.

When I'm in the Widgets.Core project at the command land I run:
`dotnet ef migrations add MigrationName --startup-project ..\Widgets.UI\Widgets.UI.csproj --output-dir Data\Migrations` everything works fine

Within the same directory if I run
`dotnet ef migrations script --startup-project ..\Widgets.UI\Widgets.UI.csproj --output Data\Migrations\SQL\MigrationName.sql`

This SQL script ends up in the Widgets.UI, not Widgets.Core.  I would expect `--output-dir` in `ef migrations add` to behave the same as `--output` in `ef migrations script` and output in the my current directory, not the directory of my startup project.

Obviously I can just .. my way back, but would be nice if these behaved the same.

### PR DESCRIPTION
**Pull request by bricelam**
This passes the working directory of `dotnet ef` and the PMC commands to `ef.exe` so we can use it to resolve some relative paths (currently just `--output` on `ef migrations script`)

Fixes #10036

### CODE REVIEW

File: src/ef/Commands/MigrationsScriptCommand.cs [hunk 1]
```diff
@@ -24,14 +24,20 @@ protected override int Execute()
...
+                    output = Path.Combine(WorkingDir.Value(), output);
+                }
+
+                var directory = Path.GetDirectoryName(output);
                 if (!string.IsNullOrEmpty(directory))
                 {
                     Directory.CreateDirectory(directory);
                 }
 
                 Reporter.WriteVerbose(Resources.WritingFile(_output.Value()));
```
Comment (smitpatel) [inline src/ef/Commands/MigrationsScriptCommand.cs]: Should this be updated to the `output`?

Comment (bricelam) [reply src/ef/Commands/MigrationsScriptCommand.cs]: I had it like that, but decided to revert. You'll see it when running `dotnet ef --verbose` and I'd rather see "my.sql" than "C:\Where\You\Invoked\Dotnet\EF\my.sql"
