### PR TITLE
Move NonNullableConventionState to CoreAnnotationNames

### LINKED ISSUE #34996: ReadOnlyCollection<string> with private backing field throws exception on NullabilityInfoContext when trying to add migration
## Adding a Migration throws 'System.InvalidOperationException'

After adding a new public property with a private backing field to the model, the create and drop apis (context.Database.EnsureDeleted()/context.Database.EnsureCreated()) produce the expected database and table. But trying to add a new migration throws the following:

```bash
dotnet ef migrations add SampleMigration
Build started...
Build succeeded.
System.InvalidOperationException: Cannot scaffold C# literals of type 'System.Reflection.NullabilityInfoContext'. The provider should implement CoreTypeMapping.GenerateCodeLiteral to support using it at design time.
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.UnknownLiteral(Object value)
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.<Fragment>g__AppendMethodCall|57_0(IMethodCallCodeFragment current, <>c__DisplayClass57_0&)
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.Fragment(IMethodCallCodeFragment fragment, Int32 indent)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateAnnotations(String builderName, IAnnotatable annotatable, IndentedStringBuilder stringBuilder, Dictionary`2 annotations, Boolean inChainedCall, Boolean leadingNewline, MethodInfo hasAnnotationMethodInfo)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.Generate(String modelBuilderName, IModel model, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationsGenerator.GenerateMetadata(String migrationNamespace, Type contextType, String migrationName, String migrationId, IModel targetModel)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language, Boolean dryRun)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace, Boolean dryRun)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace, Boolean dryRun)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Cannot scaffold C# literals of type 'System.Reflection.NullabilityInfoContext'. The provider should implement CoreTypeMapping.GenerateCodeLiteral to support using it at design time.
```

### Sample code

Please find the minimum code project here:

https://github.com/Red-F/EfCoreMigrationIssue

This was code added to the model

```C#

    public IReadOnlyCollection<string> Uids => _uids.ToList();
    private List<string> _uids = [];
    
    public void AddUids(IEnumerable<string> uids)
    {
        _uids.AddRange(uids);
    }
    
    public void RemoveUids(IEnumerable<string> uids)
    {
        foreach (var uid in uids)
        {
            _uids.Remove(uid);
        }
    }

```

### Stack traces

See above.

### Verbose output

```bash
dotnet ef --verbose migrations add SampleMigration
Using project '/home/fred/projects/EfCoreMigrationIssue/EfCoreMigrationIssue.csproj'.
Using startup project '/home/fred/projects/EfCoreMigrationIssue/EfCoreMigrationIssue.csproj'.
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/tmp/tmpw9FrlF.tmp /verbosity:quiet /nologo /home/fred/projects/EfCoreMigrationIssue/EfCoreMigrationIssue.csproj
dotnet msbuild /target:GetEFProjectMetadata /property:EFProjectMetadataFile=/tmp/tmp0ai4Yq.tmp /verbosity:quiet /nologo /home/fred/projects/EfCoreMigrationIssue/EfCoreMigrationIssue.csproj
Build started...
dotnet build /home/fred/projects/EfCoreMigrationIssue/EfCoreMigrationIssue.csproj /verbosity:quiet /nologo /p:PublishAot=false

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.88

Build succeeded.
dotnet exec --depsfile /home/fred/projects/EfCoreMigrationIssue/bin/Debug/net8.0/EfCoreMigrationIssue.deps.json --additionalprobingpath /home/fred/.nuget/packages --runtimeconfig /home/fred/projects/EfCoreMigrationIssue/bin/Debug/net8.0/EfCoreMigrationIssue.runtimeconfig.json /home/fred/.dotnet/tools/.store/dotnet-ef/9.0.0-rc.1.24451.1/dotnet-ef/9.0.0-rc.1.24451.1/tools/net8.0/any/tools/netcoreapp2.0/any/ef.dll migrations add SampleMigration --assembly /home/fred/projects/EfCoreMigrationIssue/bin/Debug/net8.0/EfCoreMigrationIssue.dll --project /home/fred/projects/EfCoreMigrationIssue/EfCoreMigrationIssue.csproj --startup-assembly /home/fred/projects/EfCoreMigrationIssue/bin/Debug/net8.0/EfCoreMigrationIssue.dll --startup-project /home/fred/projects/EfCoreMigrationIssue/EfCoreMigrationIssue.csproj --project-dir /home/fred/projects/EfCoreMigrationIssue/ --root-namespace EfCoreMigrationIssue --language C# --framework net8.0 --nullable --working-dir /home/fred/projects/EfCoreMigrationIssue --verbose
Using assembly 'EfCoreMigrationIssue'.
Using startup assembly 'EfCoreMigrationIssue'.
Using application base '/home/fred/projects/EfCoreMigrationIssue/bin/Debug/net8.0'.
Using working directory '/home/fred/projects/EfCoreMigrationIssue'.
Using root namespace 'EfCoreMigrationIssue'.
Using project directory '/home/fred/projects/EfCoreMigrationIssue/'.
Remaining arguments: .
Finding DbContext classes...
Finding IDesignTimeDbContextFactory implementations...
Finding DbContext classes in the project...
Found DbContext 'DemoDbContext'.
Finding application service provider in assembly 'EfCoreMigrationIssue'...
Finding Microsoft.Extensions.Hosting service provider...
Using environment 'Development'.
Using application service provider from Microsoft.Extensions.Hosting.
Using context 'DemoDbContext'.
Finding design-time services referenced by assembly 'EfCoreMigrationIssue'...
Finding design-time services referenced by assembly 'EfCoreMigrationIssue'...
No referenced design-time services were found.
Finding design-time services for provider 'Microsoft.EntityFrameworkCore.SqlServer'...
Using design-time services from provider 'Microsoft.EntityFrameworkCore.SqlServer'.
Finding IDesignTimeServices implementations in assembly 'EfCoreMigrationIssue'...
No design-time services were found.
System.InvalidOperationException: Cannot scaffold C# literals of type 'System.Reflection.NullabilityInfoContext'. The provider should implement CoreTypeMapping.GenerateCodeLiteral to support using it at design time.
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.UnknownLiteral(Object value)
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.<Fragment>g__AppendMethodCall|57_0(IMethodCallCodeFragment current, <>c__DisplayClass57_0&)
   at Microsoft.EntityFrameworkCore.Design.Internal.CSharpHelper.Fragment(IMethodCallCodeFragment fragment, Int32 indent)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.GenerateAnnotations(String builderName, IAnnotatable annotatable, IndentedStringBuilder stringBuilder, Dictionary`2 annotations, Boolean inChainedCall, Boolean leadingNewline, MethodInfo hasAnnotationMethodInfo)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpSnapshotGenerator.Generate(String modelBuilderName, IModel model, IndentedStringBuilder stringBuilder)
   at Microsoft.EntityFrameworkCore.Migrations.Design.CSharpMigrationsGenerator.GenerateMetadata(String migrationNamespace, Type contextType, String migrationName, String migrationId, IModel targetModel)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language, Boolean dryRun)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType, String namespace, Boolean dryRun)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType, String namespace, Boolean dryRun)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Cannot scaffold C# literals of type 'System.Reflection.NullabilityInfoContext'. The provider should implement CoreTypeMapping.GenerateCodeLiteral to support using it at design time.```

### Include provider and version information

EF Core version: 9.0.0-rc.2.24473.5 
Database provider: Microsoft.EntityFrameworkCore.SqlServer
Target framework: .NET 8.0
Operating system: Linux
IDE: Rider/CLI

### PR DESCRIPTION
**Pull request by ajcvickers**
This means it gets correctly filtered out when using the model for code generation, and hence we don't try to generate a literal for it.

Fixes #34996

### CODE REVIEW

**Review by cincuranet — APPROVED** [review]

File: src/EFCore/Metadata/Conventions/NonNullableConventionBase.cs [hunk 1]
```diff
@@ -69,5 +68,5 @@ protected virtual bool TryGetNullabilityInfo(
     public virtual void ProcessModelFinalizing(
         IConventionModelBuilder modelBuilder,
         IConventionContext<IConventionModelBuilder> context)
-        => modelBuilder.Metadata.RemoveAnnotation(StateAnnotationName);
+        => modelBuilder.Metadata.RemoveAnnotation(CoreAnnotationNames.NonNullableConventionState);
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Conventions/NonNullableConventionBase.cs:71]: Why was the annotation left in the model in the repro? This should've removed it.

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/NonNullableConventionBase.cs:71]: The relational model is produced from the normal model and the normal model should not have this annotation after this convention runs.
How does the annotation end up in the model?
