### PR TITLE
🔥 One liner bug fix - Challenge accepted 🔥 

### LINKED ISSUE #10430: Missing multi-part identifier when executing ToListAsync
### Failing query
```c#
var query = await ctx
.Profiles
.Include(i => i.ProfileInstagrams)
.ThenInclude(i => i.Instagram)
.Where(p => !p.Deleted)
.OrderBy(p => (int?)p.ProfileInstagrams.Sum(i => i.Instagram.FollowCount) ?? 0)
.ToListAsync();
```

Corresponding `ToList()` version works (see code at the bottom). Just paste the code into an empty WebApplication project and launch it.

The async version works if the `OrderBy` references a single property e.g. `OrderBy(p => (int?) p.ProfileInstagram.FollowCount) ?? 0)`

SQL Server Express 13.0.4001.0 (English)

### StackTrace
```
WebApplication3> System.Data.SqlClient.SqlException (0x80131904): The multi-part identifier "t.c" could not be bound.
WebApplication3> The multi-part identifier "t.Id" could not be bound.
WebApplication3>    at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__108_0(Task`1 result)
WebApplication3>    at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
WebApplication3>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
WebApplication3>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
WebApplication3>    at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__10.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__9.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Linq.AsyncEnumerable.JoinAsyncIterator`4.<MoveNextCore>d__20.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
WebApplication3>    at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
WebApplication3>    at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.<IncludeCollectionAsync>d__12.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.<_IncludeAsync>d__20`1.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
WebApplication3>    at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TaskLiftingExpressionVisitor.<_ExecuteAsync>d__8`1.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
WebApplication3>    at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.AsyncSelectEnumerable`2.AsyncSelectEnumerator.<MoveNext>d__3.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
WebApplication3>    at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
WebApplication3>    at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
WebApplication3> --- End of stack trace from previous location where exception was thrown ---
WebApplication3>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
WebApplication3>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
WebApplication3>    at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
WebApplication3> ClientConnectionId:b8a1ac8b-8515-4c53-a7e8-433b99af31b5
WebApplication3> Error Number:4104,State:1,Class:16
```

### Further technical details
Microsoft.AspNetCore.All.2.0.3
EF Core version: 2.0.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer.2.0.1
Operating system: Windows 10 Pro 1709 16299.64
IDE: Visual Studio Community 2017

### Steps to reproduce
Empty WebApp start project then just paste code
```c#
    public class ProfileInstagram
    {
        public int ProfileId { get; set; }

        public Profile Profile { get; set; }

        public int InstagramId { get; set; }

        public Instagram Instagram { get; set; }
    }

    public class Profile
    {
        public int Id { get; set; }

        public ICollection<ProfileInstagram> ProfileInstagrams { get; set; }
    }

    public class Instagram
    {
        public int Id { get; set; }

        public int FollowCount { get; set; }

        public ICollection<ProfileInstagram> ProfileInstagrams { get; set; }
    }

    public class Context : DbContext
    {
        public DbSet<Profile> Profiles { get; set; }

        public DbSet<Instagram> Instagrams { get; set; }

        // ReSharper disable once SuggestBaseTypeForParameter
        // Must declare type explicitly when used with pooling
        public Context(DbContextOptions<Context> options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ProfileInstagram>(e =>
            {
                e.HasKey(_ => new
                {
                    _.ProfileId,
                    _.InstagramId
                });
                e.HasOne(_ => _.Profile)
                 .WithMany(_ => _.ProfileInstagrams);

                e.HasOne(_ => _.Instagram)
                 .WithMany(_ => _.ProfileInstagrams);
            });
            base.OnModelCreating(modelBuilder);
        }
    }

    public class Startup
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public void ConfigureServices(IServiceCollection services)
        {
            const string cs =
                "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=Test1;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False";
            services.AddEntityFrameworkSqlServer()
                    .AddDbContext<Context>(options => options.UseSqlServer(cs));
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(
            IApplicationBuilder app,
            IHostingEnvironment env,
            IServiceProvider prv)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            Seed(prv);

            app.Run(async context => { await Query(prv); });
        }

        private static async Task Query(IServiceProvider prv)
        {
            // ReSharper disable once ConstantNullCoalescingCondition
            // Force COALESCE in case no Instagram for Profile
            using (var scope = prv.CreateScope())
            {
                var ctx = scope.ServiceProvider.GetRequiredService<Context>();
                var query = ctx
                    .Profiles
                    .Include(i => i.ProfileInstagrams)
                    .ThenInclude(i => i.Instagram)
                    .OrderBy(p => (int?) p.ProfileInstagrams.Sum(i => i.Instagram.FollowCount) ?? 0);

                var influencers = query.ToList();
                var influencersAsync = await query.ToListAsync();
            }
        }

        private static void Seed(IServiceProvider prv)
        {
            using (var scope = prv.CreateScope())
            {
                var ctx = scope.ServiceProvider.GetRequiredService<Context>();
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

                var instagrams = new List<Instagram>
                {
                    new Instagram
                    {
                        FollowCount = 10
                    },
                    new Instagram
                    {
                        FollowCount = 20
                    },
                    new Instagram
                    {
                        FollowCount = 31
                    }
                };
                ctx.Instagrams.AddRange(instagrams);
                var influencers = new List<Profile>
                {
                    new Profile
                    {
                        ProfileInstagrams = new List<ProfileInstagram>
                        {
                            new ProfileInstagram
                            {
                                Instagram = instagrams[0]
                            }
                        }
                    },
                    new Profile
                    {
                        ProfileInstagrams = new List<ProfileInstagram>
                        {
                            new ProfileInstagram
                            {
                                Instagram = instagrams[1]
                            }
                        }
                    },
                    new Profile(),
                    new Profile
                    {
                        ProfileInstagrams = new List<ProfileInstagram>
                        {
                            new ProfileInstagram
                            {
                                Instagram = instagrams[0]
                            },
                            new ProfileInstagram
                            {
                                Instagram = instagrams[1]
                            }
                        }
                    },
                    new Profile
                    {
                        ProfileInstagrams = new List<ProfileInstagram>
                        {
                            new ProfileInstagram
                            {
                                Instagram = instagrams[2]
                            }
                        }
                    }
                };
                ctx.Profiles.AddRange(influencers);
                ctx.SaveChanges();
            }
        }
    }
```

### LINKED ISSUE #11037: Invalid included navigation query generated
I have run into situation when Npgsql.EF.Core generates invalid SQL query when complex OrderBy expression used in async query.

```
Exception message: "42P01: missing FROM-clause entry for table \"t0\""
Stack trace: "   at Npgsql.NpgsqlConnector.<DoReadMessage>d__155.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnector.<ReadMessage>d__154.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlConnector.<ReadMessage>d__154.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlConnector.<ReadExpecting>d__161`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlDataReader.<NextResult>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlDataReader.<<NextResultAsync>b__31_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.<Execute>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlCommand.<ExecuteDbDataReader>d__92.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlCommand.<>c__DisplayClass90_0.<<ExecuteDbDataReaderAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NpgsqlExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.JoinAsyncIterator`4.<MoveNextCore>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.<IncludeCollectionAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.<_IncludeAsync>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TaskLiftingExpressionVisitor.<_ExecuteAsync>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.AsyncSelectEnumerable`2.AsyncSelectEnumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at QueryExample.Program.Main(String[] args) in D:\\Git\\pgefcore2-query-bug\\QueryExample\\Program.cs:line 34"
```

### Steps to reproduce

I wrote example project where this error is reproduced:
https://github.com/grayver/pgefcore2-query-bug

Briefly:

Here is LINQ expression:
```c#
            return _context.Competitions
                .Include(c => c.Quest)
                .Include(c => c.Quest).ThenInclude(q => q.Author)
                .Include(c => c.Quest).ThenInclude(q => q.QuestTags).ThenInclude(qt => qt.Tag)
                .Where(c => c.Passes.Any(qp => qp.User.UserFriends.Any(uf => uf.FriendId == userId)))
                .OrderByDescending(c => c.Passes
                    .Where(qp => qp.User.UserFriends.Any(uf => uf.FriendId == userId))
                    .Max(qp => qp.CreatedAt))
                .Skip(1)
                .Take(3)
                .ToListAsync();
```
 
and here are SQL queries:
```sql
SELECT "c"."Id", "c"."DislikeCount", "c"."LikeCount", "c"."QuestId", "c.Quest"."Id", "c.Quest"."Answer1Text", "c.Quest"."Answer2Text", "c.Quest"."Answer3Text", "c.Quest"."Answer4Text", "c.Quest"."AuthorId", "c.Quest"."Name", "c.Quest"."QuestionText", "c.Quest.Author"."Id", "c.Quest.Author"."Email", "c.Quest.Author"."Fullname", "c.Quest.Author"."IsEmailConfirmed"
FROM "Competitions" AS "c"
INNER JOIN "Quests" AS "c.Quest" ON "c"."QuestId" = "c.Quest"."Id"
INNER JOIN "Users" AS "c.Quest.Author" ON "c.Quest"."AuthorId" = "c.Quest.Author"."Id"
WHERE EXISTS (
    SELECT 1
    FROM "QuestPasses" AS "qp"
    INNER JOIN "Users" AS "qp.User" ON "qp"."UserId" = "qp.User"."Id"
    WHERE EXISTS (
        SELECT 1
        FROM "UserFriends" AS "uf"
        WHERE ("uf"."FriendId" = @__userId_0) AND ("qp.User"."Id" = "uf"."UserId")) AND ("c"."Id" = "qp"."CompetitionId"))
ORDER BY (
    SELECT MAX("qp0"."CreatedAt")
    FROM "QuestPasses" AS "qp0"
    INNER JOIN "Users" AS "qp.User0" ON "qp0"."UserId" = "qp.User0"."Id"
    WHERE EXISTS (
        SELECT 1
        FROM "UserFriends" AS "uf0"
        WHERE ("uf0"."FriendId" = @__userId_1) AND ("qp.User0"."Id" = "uf0"."UserId")) AND ("c"."Id" = "qp0"."CompetitionId")
) DESC, "c.Quest"."Id"
LIMIT @__p_3 OFFSET @__p_2

SELECT "c.Quest.QuestTags"."QuestId", "c.Quest.QuestTags"."TagId", "q.Tag"."Id", "q.Tag"."Value"
FROM "QuestTags" AS "c.Quest.QuestTags"
INNER JOIN "Tags" AS "q.Tag" ON "c.Quest.QuestTags"."TagId" = "q.Tag"."Id"
ORDER BY "t0"."c" DESC, "t0"."Id"
```

However, if I use sync query instead of async - error disappears and valid query generated.

### Further technical details
EF Core version: 2.0.1
Database Provider: Npgsql.EntityFrameworkCore.PostgreSQL version 2.0.1
Operating system: Windows 10, Windows 7, Ubuntu 16.04
IDE: Visual Studio 2017 15.5.7

### PR DESCRIPTION
**Pull request by smitpatel**
Query: Async Collection Include produces invalid subquery with complex OrderBy

Issue: Current pipeline fails at lifting inner subquery in collection querymodel for async case. This causes client side join.
The OrderBy clause were dependent on inner subquery projection (through AnonymousObject). And while translating them we did not consider that select expression could be different.
Hence we added ordering to wrong select expression generating invalid SQL.

Resolves #10430
Resolves #11037

### CODE REVIEW

**Comment by smitpatel** [comment]
@dotnet-bot test windows release x64 build

File: src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs [hunk 1]
```diff
@@ -642,7 +642,8 @@ var boundExpression
                 var selectExpression
                     = _queryModelVisitor.TryGetQuery(querySourceReferenceExpression.ReferencedQuerySource);
 
-                if (selectExpression != null)
+                if (selectExpression != null
```
Comment (anpete) [inline src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs]: Two lines :trollface:

**Comment by anpete** [comment]
Separate issue for lifting bug?

**Comment by smitpatel** [comment]
@dotnet-bot test windows release x64 build

**Comment by smitpatel** [comment]
Filed #11635 for lifting bug
