### PR TITLE
Fix #11635 - Query: Collection Include with scalar subquery order by …

### LINKED ISSUE #11635: Query: Collection Include with scalar subquery order by causes client join for async
Test `Include_collection_with_complex_OrderBy`
```C#
await AssertIncludeQuery<Gear>(
    os => os.OfType<Officer>()
            .Include(o => o.Reports)
            .OrderBy(o => o.Weapons.Count),
    new List<IExpectedInclude> { new ExpectedInclude<Officer>(o => o.Reports, "Reports") });
```
This fails to lift the join in collection QM and causes N+1 eval. This happens only for async path. Sync works fine.

### PR DESCRIPTION
**Pull request by anpete**
…causes client join for async

- Add _SelectAsync to pattern match when performing TypedProjectionShaper optimization.

### CODE REVIEW

File: src/EFCore/Query/Internal/CompiledQueryCache.cs [hunk 1]
```diff
@@ -54,12 +54,10 @@ public CompiledQueryCache([NotNull] IMemoryCache memoryCache)
         private Func<QueryContext, TFunc> GetOrAddQueryCore<TFunc>(
             object cacheKey, Func<Func<QueryContext, TFunc>> compiler)
         {
-            Func<QueryContext, TFunc> compiledQuery;
-
             retry:
-            if (!_memoryCache.TryGetValue(cacheKey, out compiledQuery))
+            if (!_memoryCache.TryGetValue(cacheKey, out Func<QueryContext, TFunc> compiledQuery))
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/CompiledQueryCache.cs]: `var`?

Comment (anpete) [reply src/EFCore/Query/Internal/CompiledQueryCache.cs]: memory cache values are untyped
