### PR TITLE
Fix type mapping for GETDATE and GETUTCDATE in SqlServer.

### LINKED ISSUE #36479: EFCore generated an incorrect SQL for DATE
### Bug description

SQL by EFCore:

```sql
SELECT COUNT(*)
FROM [Foo] AS [f]
WHERE GETDATE() > '2026-01-01T00:00:00.0000000'
```

this is not a valid date format string

[22007] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]THE DATE, TIME, OR TIMESTAMP VALUE IS INVALID.

### Your code

```csharp
using var dbContext = new MyDbContext();
var set = dbContext.Set<Foo>();
var count = set.Where(x => DateTime.Now > new DateTime(2026, 1, 1)).Count();
```

### Stack traces

```text

```

### Verbose output

```text

```

### EF Core version

9.0.0

### Database provider

_No response_

### Target framework

_No response_

### Operating system

_No response_

### IDE

_No response_

### PR DESCRIPTION
**Pull request by cincuranet**
Fixes #36479.

### Description

Fixes type mapping for GETDATE and GETUTCDATE in SqlServer, which is especially important when comparing with non-column (i.e. constant).

### Customer impact

Generated query is rejected by SQL Server and throws error.

### How found

Customer reported on 9.

### Regression

No.

### Testing

Tests added.

### Risk

Low. This is a specific case for only these two functions.

### CODE REVIEW

File: src/EFCore.SqlServer/Query/Internal/Translators/SqlServerDateTimeMemberTranslator.cs [hunk 1]
```diff
@@ -69,8 +69,19 @@ public class SqlServerDateTimeMemberTranslator(
...
                 => sqlExpressionFactory.Function(
-                    declaringType == typeof(DateTime) ? "GETDATE" : "SYSDATETIMEOFFSET",
+                    "GETDATE",
+                    arguments: [],
+                    nullable: false,
+                    argumentsPropagateNullability: [],
+                    returnType,
+                    typeMappingSource.FindMapping(typeof(DateTime), "datetime")),
+
+            nameof(DateTime.Now)
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/Translators/SqlServerDateTimeMemberTranslator.cs]: nit:
 
```suggestion
            nameof(DateTimeOffset.Now)
```

Same below for DateTimeOffset.UtcNow

**Review by roji — COMMENTED** [review]
Shouldn't we do the same for the other functions down below (e.g. DateTimeOffset.UtcNow)?

The fix looks accurate, but I think there's an additional problem here, in that we always translate `DateTime.Now` to `GETDATE()` which returns `datetime`, although we generally map .NET DateTime to the higher-precision `datetime2`. I opened #36616 to fix (I don't think it's super important).

File: test/EFCore.SqlServer.FunctionalTests/Query/AdHocMiscellaneousQuerySqlServerTest.cs [hunk 2]
```diff
@@ -2620,4 +2620,58 @@ FROM [TestEntities] AS [t]
 """);
         }
     }
+
+    #region 36479
+
+    [ConditionalTheory, MemberData(nameof(IsAsyncData))]
+    public async Task DateTime_Now_has_proper_type_mapping(bool async)
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/Query/AdHocMiscellaneousQuerySqlServerTest.cs]: Does this require an ad-hoc test? Why not just add a test to Northwind or whatever?

Comment (roji) [reply test/EFCore.SqlServer.FunctionalTests/Query/AdHocMiscellaneousQuerySqlServerTest.cs]: My bad for mentioning Northwind - we have a nice play for translation tests exactly like this - with Temporal/DateTimeTranslationsTestBase for any tests covering DateTime translations specifically... So the test would be better there than in Northwind, where everything is a mess.

But not critical as you've already moved the test once (again, my bad for suggesting Northwind rather than the translation tests before). We need to do a lot of cleanup on Northwind in any case.

**Comment by roji** [comment]
> Shouldn't we do the same for the other functions down below (e.g. DateTimeOffset.UtcNow)?

I'm still seeing an explicit return type mapping for DateTimeOffset.Now, for not for the DateTimeOffset.UtcNow right under it.

File: test/EFCore.SqlServer.FunctionalTests/Query/AdHocMiscellaneousQuerySqlServerTest.cs (hunk 2 above)
Comment (cincuranet) [reply test/EFCore.SqlServer.FunctionalTests/Query/AdHocMiscellaneousQuerySqlServerTest.cs]: Isn't "Temporal/" for temporal tables?

**Review by roji — APPROVED** [review]
