### PR TITLE
[2.1 RC] Query: Fix for GroupBy with Where Aggregate produces incorrect SQL

### LINKED ISSUE #11695: GroupBy with Where Aggregate produces incorrect SQL
```c#
var StartDate = DateTime.UtcNow;
var EndDate = DateTime.UtcNow;
var Test = (from orderPlaced in db.Orders
            where orderPlaced.OrderDate > StartDate && orderPlaced.OrderDate < EndDate
            group orderPlaced by new { orderPlaced.Id } into orderPlacedGrp
            select new OrderPlaced()
            {
                Placed = orderPlacedGrp.Where(x => x.IsPlaced == true).Count(),
                UnPlaced = orderPlacedGrp.Where(x => x.IsPlaced == false).Count(),
            }).AsQueryable().ToList();


public class Order
{
    public int Id { get; set; }
    public bool IsPlaced { get; set; }
    public DateTime OrderDate { get; set; }
}

public class OrderPlaced
{
    public int Placed { get; set; }
    public int UnPlaced { get; set; }
}
```
Generates
```SQL
SELECT COUNT(*) AS [UnPlaced]
FROM [Orders] AS [orderPlaced]
WHERE ([orderPlaced].[OrderDate] > @__StartDate_0) AND ([orderPlaced].[OrderDate] < @__EndDate_1)
GROUP BY [orderPlaced].[Id]
```

### PR DESCRIPTION
**Pull request by smitpatel**
Issue: Due to the shape of QM we incorrectly identified the query for Group By SQL translation.
Which is not the case hence we generate a SQL which produces incorrect result
Fix: During result operator processing, we more carefully identify if we are selecting from a grouping source.
Also relax criterea that group by aggregate should be only 1 level deep. This also allows us to translate group by aggregate when it is inside join

Resolves #11695

### CODE REVIEW

File: src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs [hunk 1]
```diff
@@ -840,9 +840,11 @@ var subQueryModelVisitor
                         || !subSelectExpression.IsCorrelated()
                         || !(querySource is AdditionalFromClause)))
                 {
+                    var groupByNotRequiringPushdown = subSelectExpression.GroupBy.Count > 0
```
Comment (maumar) [inline src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs]: flip the condition to avoid double negation

File: src/EFCore/Query/ExpressionVisitors/Internal/RequiresMaterializationExpressionVisitor.cs [hunk 2]
```diff
@@ -237,7 +237,7 @@ private bool IsGroupByAggregateSubQuery(QueryModel queryModel)
                 && queryModel.ResultOperators.Count == 1
                 && !(queryModel.SelectClause.Selector is ConstantExpression)
                 && _aggregateResultOperators.Contains(queryModel.ResultOperators[0].GetType())
-                && _queryModelStack.Count == 1
+                && _queryModelStack.Count > 0
```
Comment (maumar) [inline src/EFCore/Query/ExpressionVisitors/Internal/RequiresMaterializationExpressionVisitor.cs]: add some more tests for this, since we enable much more complex scenarios now

**Comment by smitpatel** [comment]
@maumar - Updated.

**Comment by ajcvickers** [comment]
@smitpatel Approved for RC1. /cc @divega
