### PR TITLE
Fallback to OPENJSON with many parameters

### LINKED ISSUE #37185: Contains fails to fallback to OPENJSON with many parameters in complex queries
### Bug description

Here is the premise to understand the bug:
- you have a `Candidates` table
- each candidate can have many `Projects` (candidateId → many ProjectIds)
- each project can have some date (eg when email for that project was sent to the candidate)

Now you want to write a query to show candidates that are in any projectIds of `1,2,3,…` and those candidates should be sorted by max date of whatever email they were sent to.

EF generates the following code ↓ As you can see, project ids are not reused between `where` and `order by` portions — they are duplicated → hence the double number of actual parameters.

```
exec sp_executesql N'SELECT [c].[CandidateId]
FROM [dbo].[Candidates] AS [c]
WHERE EXISTS (
    SELECT 1
    FROM [dbo].[Projects] AS [p]
    WHERE [c].[CandidateId] = [p].[CandidateId] AND [p].[ProjectId] IN (@ids1, @ids2))
ORDER BY (
    SELECT MAX([p0].[InviteSentTime])
    FROM [dbo].[Projects] AS [p0]
    WHERE [c].[CandidateId] = [p0].[CandidateId] AND [p0].[ProjectId] IN (@projectIds1, @projectIds2)) DESC, [c].[CandidateId] DESC
OFFSET @p ROWS FETCH NEXT @p ROWS ONLY',N'@ids1 bigint,@ids2 bigint,@projectIds1 bigint,@projectIds2 bigint,@p int',@ids1=1,@ids2=2,@projectIds1=1,@projectIds2=2,@p=25
```

If you have let's say 1500 ids, each part of the query seems ok for EF to use parametrised version. By because total number of parameters in the final query is ×2 (3000), this query will fail to execute with:

> Microsoft.Data.SqlClient.SqlException (0x80131904): The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.

Probably, it is safe to say, that some even more complex queries could result in even ×3, ×4 number of parameters compared to actual different number of ids.

---

How I currently fixed this for EF 10 (obviously, wasn’t needed in EF9 because of openjson)

```
        // EF is supposed to use openjson and what have you when the parameters
        // list exceeds 2000 items, but if we have something like order by project’s
        // max completion date, we basically double the number of parameters
        // (project IDs in “where” and project Ids in “order by”).
        // So 700 is basically 1400 parameters with some safe margin for other parameters.

        var hasTooManyProjects = ids.Count > TOO_MANY_PROJECTS_THRESHOLD;

        return query.Where(
            c => c.Projects.Any(
                p => hasTooManyProjects
                    ? EF.Constant(ids).Contains(p.ProjectId) // uses inline values that poison SQL plan cache but works
                    : ids.Contains(p.ProjectId) // doesn’t poison SQL plan cache but is limited in params number
                      && (filter.IsProjectCompleted == null
// ... other filtering applied
```

(the logic above is repeated in `where` and in `order by` parts)

Is there something like `EF.OpenJsonConstant(ids)` to force openjson so I don't need to use `EF.Constant(ids)`? (cc @roji) 

---

So basically this thing boils to four parts:
1. Can one really rely on EF ability in .NET 10 to count the total number of parameters?
2. If the answer to previous question is no, fallback to openjson is not guaranted.
3. Can one manually trigger openjson logic in a single specific linq query? I see that you've added `EF.Constant(ids)`, is there something like EF.OpenJsonConstant(ids)? As I understand, you 100% have this nob internally when you determine when to switch to openjson. I don't need for the entire context but only for some heavy linq queries like in the case above. Though, I guess, for my example openjson is almost twice less performance of ordnirary `in` but is a great to have if for some god-forsaken reason we need more than 64k(?) items in contains.
4. Was changing the default from EF9 OpenJson to EF10 parametrised logic a breaking change (in a sense that it definitely broke our code in a way we were not expected)? It would be nice to see it in breaking changes list of ef 10.

### Your code

```csharp
-
```

### Stack traces

```text

```

### Verbose output

```text

```

### EF Core version

10.0.0

### Database provider

Microsoft.EntityFrameworkCore.SqlServer

### Target framework

.NET 10

### Operating system

_No response_

### IDE

_No response_

### PR DESCRIPTION
**Pull request by cincuranet**
Fixes #37185.

### CODE REVIEW

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs [hunk 1]
```diff
@@ -368,3 +380,75 @@ valuesExpression is not null
...
+    private readonly HashSet<SqlParameterExpression> _visitedParameters = new();
+
+    /// <summary>
+    /// Foo
+    /// </summary>
+    protected override Expression VisitExtension(Expression node)
+    {
+        switch (node)
+        {
+            case ValuesExpression valuesExpression when valuesExpression.ValuesParameter is { } valuesParameter:
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs]: nit:

```suggestion
            case ValuesExpression { ValuesParameter: { } valuesParameter }:
```

(and below)

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs [hunk 2]
```diff
@@ -368,3 +380,75 @@ valuesExpression is not null
...
+            Count += count;
+            if (bucketization)
+            {
+                var elementTypeMapping = (RelationalTypeMapping)sqlParameterExpression.TypeMapping!.ElementTypeMapping!;
+                Count += bucketizationPadding(count, elementTypeMapping);
+            }
+        }
+        else
+        {
+            ProcessParameter(sqlParameterExpression);
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs]: I think we also need to take Constants mode into account no? In that case the parameter shouldn't be counted at all (since its contents are fully inlined)

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs [hunk 3]
```diff
@@ -30,6 +32,7 @@ public class SqlServerSqlNullabilityProcessor : SqlNullabilityProcessor
     private readonly ISqlServerSingletonOptions _sqlServerSingletonOptions;
 
     private int _openJsonAliasCounter;
+    private int _parametersCount;
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs]:
```suggestion
    private int _totalParameterCount;
```

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs [hunk 4]
```diff
@@ -368,3 +380,75 @@ valuesExpression is not null
...
+        }
+
+        if ((sqlParameterExpression.TranslationMode ?? collectionParameterTranslationMode) is ParameterTranslationMode.MultipleParameters)
+        {
+            var parameters = parametersDecorator.GetAndDisableCaching();
+            var count = ((IEnumerable?)parameters[sqlParameterExpression.Name])?.Cast<object>().Count() ?? 0;
+            Count += count;
+            if (bucketization)
+            {
+                var elementTypeMapping = (RelationalTypeMapping)sqlParameterExpression.TypeMapping!.ElementTypeMapping!;
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs]: Remind me - we need the type mapping just in case the padding/bucketization needs to work differently depending on the parameter type (e.g. bucketize on int but not on big varbinary)? If so, we don't actually currently do that, do we?

Comment (cincuranet) [reply src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs]: > work differently depending on the parameter type

Correct.

> we don't actually currently do that, do we

Our providers don't do that. But we added it there possibly for other providers.

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs [hunk 5]
```diff
@@ -368,3 +378,88 @@ valuesExpression is not null
...
+    {
+        if (_visitedParameters.Contains(sqlParameterExpression))
+        {
+            return;
+        }
+
+        if ((sqlParameterExpression.TranslationMode ?? collectionParameterTranslationMode) is ParameterTranslationMode.MultipleParameters)
+        {
+            var parameters = parametersDecorator.GetAndDisableCaching();
+            var count = ((IEnumerable?)parameters[sqlParameterExpression.Name])?.Cast<object>().Count() ?? 0;
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs]: Just pointing out more cases of multiple enumeration of IEnumerable parameters. This isn't new with your PR or anything, but we're really enumerating such parameters all around the place... We'd ideally get rid of this super early in the funcletizer (#37267).

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs [hunk 6]
```diff
@@ -368,3 +378,88 @@ valuesExpression is not null
...
+    Func<int, RelationalTypeMapping, int> bucketizationPadding) : ExpressionVisitor
+{
+    /// <summary>
+    ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
+    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
+    ///     any release. You should only use it directly in your code with extreme caution and knowing that
+    ///     doing so can result in application failures when updating to a new Entity Framework Core release.
+    /// </summary>
+    [EntityFrameworkInternal]
+    public virtual int Count { get; private set; } = 0;
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs]: nit: can omit the explicit initialization:

```suggestion
    public virtual int Count { get; private set; }
```

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs [hunk 7]
```diff
@@ -368,3 +378,88 @@ valuesExpression is not null
...
+
+    private readonly HashSet<SqlParameterExpression> _visitedParameters = new();
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs]: This does reference comparison on the SqlParameterExpression, but unless I'm mistaken if a parameter is referenced twice in the tree, you'll find two separate instances with the same InvariantName (maybe run a quick manual test to confirm this).

If that's the case, this HashSet should be over the invariant names, not over the SqlParameterExpression instances themselves. Don't forget to rename the field as well.

Note that we have [RelationalParameterProcessor](https://github.com/dotnet/efcore/blob/main/src/EFCore.Relational/Query/Internal/RelationalParameterProcessor.cs) which, among other things, deduplicate parameters with the same InvariantName. However, it's executed only after SqlNullabilityProcessor... We could reconsider the ordering of these two visitors, but I think that's beyond what we'd allow ourselves in a patch.

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs [hunk 8]
```diff
@@ -368,3 +378,88 @@ valuesExpression is not null
...
+        {
+            case ValuesExpression { ValuesParameter: { } valuesParameter }:
+                ProcessCollectionParameter(valuesParameter, false);
+                break;
+
+            case InExpression { ValuesParameter: { } valuesParameter }:
+                ProcessCollectionParameter(valuesParameter, true);
+                break;
+
+            case SqlParameterExpression sqlParameterExpression:
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs:440]: One missing case here is FromSqlExpression, whose Arguments can also be QueryParameterExpression (check out RelationalParameterProcessor.VisitFromSql). To be precise we should also handle that here, though I can't think of a way where those parameters are collections (so they're unlikely to add any significant number of parameters, but...).

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs [hunk 9]
```diff
@@ -368,3 +378,88 @@ valuesExpression is not null
...
+                ProcessParameter(sqlParameterExpression);
+                break;
+        }
+        return base.VisitExtension(node);
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs:448]:
```suggestion

        return base.VisitExtension(node);
```

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs (hunk 2 above)
Comment (roji) [reply src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs]: Isn't this still unresolved?

**Review by roji — CHANGES_REQUESTED** [review]
Looks pretty good, see comments for some minor fixes.

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs (hunk 2 above)
Comment (cincuranet) [reply src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs]: Line 432 deals with it.

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs (hunk 7 above)
Comment (cincuranet) [reply src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs]: That's what test `Parameter_collection_Count_with_huge_number_of_values_over_5_operations_same_parameter` is doing. if I understood you correctly. There is only one _instance_ of that `@extra` parameter.

But I think I found another flaw. I'll add test for that.

Comment (roji) [reply src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs]: That's... interesting... the funcletizer produces QueryParameterExpression instances, which [we translate](https://github.com/cincuranet/efcore/blob/bd7e33cc295c6cb5bd3cf76b1d9c292001b0a3c6/src/EFCore.Relational/Query/RelationalSqlTranslatingExpressionVisitor.cs#L502) to SqlParameterExpression, each time instantiating a new instance. So I'm not quite sure how we're getting the same instance of SqlParameterExpression in the tree...

(in general, with expression trees, it's a good idea to be suspicious of reference equality across the tree - it might work until some visitor in the middle kicks in and rewrites the node, at which point you suddenly get two nodes that are equal structurally but not referentially)

I'd personally err on the side of comparing SqlParameterExpression.InvariantName - that's precisely what it's there for... Or at least understand how you're seeing the multiple instances in the tree. It's possible that Parameter_collection_Count_with_huge_number_of_values_over_5_operations_same_parameter is very simple and this works, but if the query becomes slightly more complicated it doesn't.

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs (hunk 2 above)
Comment (roji) [reply src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs]: OK, I see. But isn't it problematic that in that line (in ProcessParameter) you're checking `collectionParameterTranslationMode` even when that parameter is not at all a collection parameter? In other words, I'm not sure it's correct to share ProcessParameter between the collection and non-collection cases.

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs (hunk 7 above)
Comment (cincuranet) [reply src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs]: I missed the override of `GetHashCode` and `Equals` and saw same hash code. So it's not the _instance_, but works because of the hashset and equality. 

There's a problem there anyway, so I'll be changing the logic as we discussed offline.

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs [hunk 10]
```diff
@@ -368,3 +378,102 @@ valuesExpression is not null
...
+    ParameterTranslationMode collectionParameterTranslationMode,
+    Func<int, RelationalTypeMapping, int> bucketizationPadding) : ExpressionVisitor
+{
+    /// <summary>
+    ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
+    ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
+    ///     any release. You should only use it directly in your code with extreme caution and knowing that
+    ///     doing so can result in application failures when updating to a new Entity Framework Core release.
+    /// </summary>
+    [EntityFrameworkInternal]
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs]: nit: not needed since the entire is in an Internal namespace

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs [hunk 11]
```diff
@@ -368,3 +378,102 @@ valuesExpression is not null
...
+    public virtual int Count { get; private set; }
+
+    private readonly HashSet<SqlParameterExpression> _visitedSqlParameters =
+        new(EqualityComparer<SqlParameterExpression>.Create(
+            (lhs, rhs) =>
+                ReferenceEquals(lhs, rhs)
+                || (lhs is not null && rhs is not null
+                    && lhs.InvariantName == rhs.InvariantName
+                    && lhs.TranslationMode == rhs.TranslationMode),
+            x => HashCode.Combine(x.InvariantName, x.TranslationMode)));
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs:408]: Unimportant: as discussed offline, it's not necessary to include the translation model in the hash code, only in the equality check (having the same InvariantName with different translation modes is a really contrived scenario in any case). I'd personally just return `x.InvariantName.GetHashCode()`, but no problem with leaving the code as-is.

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs [hunk 12]
```diff
@@ -368,3 +378,102 @@ valuesExpression is not null
...
+
+                if (bucketization)
+                {
+                    var elementTypeMapping = (RelationalTypeMapping)sqlParameterExpression.TypeMapping!.ElementTypeMapping!;
+                    Count += bucketizationPadding(count, elementTypeMapping);
+                }
+
+                break;
+
+            case not ParameterTranslationMode.Parameter:
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs]: Inverse logic? Shouldn't we do `Count++` if the translation mode **is** ParameterTranslationMode.Parameter?

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs [hunk 13]
```diff
@@ -368,3 +378,102 @@ valuesExpression is not null
...
+                Count++;
+                break;
+        }
```
Comment (roji) [inline src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs:482]: nit: I'd include all cases and have a `default` that throws UnreachableException (that's a thing I universally do on switches over enums) - this makes things super explicit and also future-compatible in case we change the enum in any way.

**Comment by SamMonoRT** [comment]
@cincuranet - confirming this is targetting main and we will backport a fix as necessary.

File: src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs (hunk 12 above)
Comment (cincuranet) [reply src/EFCore.SqlServer/Query/Internal/SqlServerSqlNullabilityProcessor.cs]: 🤦‍♂️

**Comment by cincuranet** [comment]
@SamMonoRT Yes. And for sure we'll backport.

**Review by roji — APPROVED** [review]
LGTM @cincuranet

**Review by SamMonoRT — APPROVED** [review]
