### PR TITLE
Query: Clear out projection when GroupBy has element selector as anon type

### LINKED ISSUE #12032: Query: GroupBy with element selector with aggregate over complex expression throws
```C#
var query = db.Blogs
     .GroupBy(
         b => b.Title, 
         b => new { b.Value })
     .Select(
         g => g.Sum(e => e.Value + 2))
     .ToList();
```
Throws 
```
Unhandled Exception: System.ArgumentException: Value does not fall within the expected range.
   at System.SharedTypeExtensions.GetSequenceType(Type type)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitMainFromClause(MainFromClause fromClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.SqlTranslatingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.RelationalProjectionExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EFSampleApp.Program.Main(String[] args)
```

Removing complex expression from aggregate make it work on server.
Removing element selector make it work with streaming group by.

### PR DESCRIPTION
**Pull request by smitpatel**
Issue: When ElementSelector is NewExpression/MemberInitExpression, it could easily bind through mapping and we don't need to preserve projection. In this case when projection is preserved and actual expression is complex, we ended up with multiple projections which we failed to lift during aggregate operation.
Fix: is to clear out projection for NewExpression/MemberInitExpression.
ElementSelector with single property requires aggregate expression over member only for server eval. So with complex aggregate it would do streaming group by.
If elementselector is made complex property then aggregate can be made simple and it still translates.

Resolves #12032

### CODE REVIEW

File: src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs [hunk 1]
```diff
@@ -528,7 +528,8 @@ var sqlExpression
                             new SelectClause(groupResultOperator.ElementSelector),
                             handlerContext.QueryModel);
 
-                        if (selectExpression.Projection.Count > 1)
+                        if (groupResultOperator.ElementSelector is NewExpression
+                            || groupResultOperator.ElementSelector is MemberInitExpression)
```
Comment (anpete) [inline src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs]: Check NodeType

Comment (smitpatel) [reply src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs]: There are other places too where we match like this. I will update those too.
