### PR TITLE
[2.1] Query: Remap MemberInfo mapping while eleminating joins

### LINKED ISSUE #11818: Query: qsres don't get properly remapped after join elimination for queries with table splitting and group by, which leads to incorrect SQL being generated
repro:

```cs
    class Program
    {
        static void Main(string[] args)
        {
            using (var ctx = new MyContext())
            {
                ctx.Database.EnsureDeleted();
                ctx.Database.EnsureCreated();

            }

            using (var ctx = new MyContext())
            {
                var query3 = (from f in ctx.Foos
                              join b in ctx.Bars on f.Id equals b.Id into grouping
                              from b in grouping.DefaultIfEmpty()
                              select new { fname = f.Name, bname = b.Name }).GroupBy(g => g.bname).Select(g => new { g.Key, cnt = g.Count() + 5 }).ToList();
            }
        }
    }

    public class MyContext : DbContext
    {
        public DbSet<Foo> Foos { get; set; }
        public DbSet<Bar> Bars { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
           optionsBuilder.UseSqlServer(@"Server=.;Database=TableSplittin;Trusted_Connection=True;MultipleActiveResultSets=True");
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Foo>().ToTable("Fubar");
            modelBuilder.Entity<Bar>().ToTable("Fubar");

            modelBuilder.Entity<Foo>().HasOne<Bar>().WithOne().HasForeignKey<Bar>(b => b.Id);
        }
    }

    public class Foo
    {
        public int Id { get; set; }

        public string Name { get; set; }
    }

    public class Bar
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
```

We generate the following query:

```sql
SELECT [b].[Name] AS [Key], COUNT(*) + 5 AS [cnt]
FROM [Fubar] AS [f]
GROUP BY [f].[Name]
```

### PR DESCRIPTION
**Pull request by smitpatel**
Issue: When eliminating joins, we updated projections and alongwith their tied member info mappings.
But in this case projection was empty so we did not update the mappings.
Fix is to update the mapping regardless of projection being there or not.

Resolves #11818

### CODE REVIEW

File: src/EFCore.Relational/Query/Expressions/SelectExpression.cs [hunk 1]
```diff
@@ -1295,6 +1295,11 @@ internal void UpdateTableReference(TableExpressionBase oldTable, TableExpression
             UpdateProjection(visitor, _starProjection);
             UpdateProjection(visitor, _projection);
 
+            foreach (var kvp in _memberInfoProjectionMapping.ToList())
```
Comment (anpete) [inline src/EFCore.Relational/Query/Expressions/SelectExpression.cs]: Need to buffer here?

Comment (smitpatel) [reply src/EFCore.Relational/Query/Expressions/SelectExpression.cs]: Modifying the collection while iterating. I will convert to `ToArray` call though.
