### PR TITLE
Fix handling of readonly fields using abstract classes (i.e. FrozenSet<T>) in parameters for primitive collections.

### LINKED ISSUE #36496: `FrozenSet.Contains` is not translateable to `IN` clause
### Bug description

When using a `FrozenSet` as a container for a `IN` clause, EF throws an exception that the expression isn't translatable. The interesting part is that it complains about `System.Linq.Enumerable.Contains` (see stack-trace).

### Your code

```csharp
The following code throws the error:

FrozenSet<string> types = ["A", "B"];

var result = await _dbContext.Foo.Where(f => types.Contains(f.Bar)).ToListAsync();
```

Switching just to any other readonly collection works:

```diff
-FrozenSet<string> types = ["A", "B"];
+IReadOnlyCollection<string> types = ["A", "B"];
```

### Stack traces

```text
-class
System.InvalidOperationException: The LINQ expression 'DbSet<MeasurementDeviationData>()
    .Where(m => __measurementIds_0
        .Contains(m.MeasurementId))
    .Where(m => (FrozenSet<string>)LengthBucketsFrozenSet { "A", "B" }
        .Contains(m.DeviationDataType))' could not be translated. Additional information: Translation of method 'System.Linq.Enumerable.Contains' failed. If this method can be mapped to your custom function, see https://go.microsoft.com/fwlink/?linkid=2132413 for more information. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutorExpression[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass11_0`1.<ExecuteCore>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteCore[TResult](Expression query, Boolean async, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
... user code comes here ...
```

### Verbose output

```text

```

### EF Core version

9.0.7

### Database provider

Microsoft.EntityFrameworkCore.SqlServer

### Target framework

.NET 9.0

### Operating system

MacOSX 15.5

### IDE

Rider

### PR DESCRIPTION
**Pull request by cincuranet**
Fixes #36496

### CODE REVIEW

File: src/EFCore/Query/QueryRootProcessor.cs [hunk 1]
```diff
@@ -83,18 +83,22 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
-
+        // A:
         // In case the collection was value type, in order to call methods like AsQueryable,
         // we need to convert it to IEnumerable<T> which requires boxing.
         // We do that with Convert expression which we need to unwrap here.
+        //
+        // B:
+        // For collections that are abstract (i.e. FrozenSet<T>) the compiler uses some "internal"
+        // implementation and for readonly fields the compiler adds explicit cast. We need to
+        // unwrap here.
```
Comment (roji) [inline src/EFCore/Query/QueryRootProcessor.cs]:
```suggestion
        // For collections that are abstract (i.e. FrozenSet<T>), some internal type is used
        // and for readonly fields the compiler adds explicit cast. We need to unwrap here.
```

File: src/EFCore/Query/QueryRootProcessor.cs [hunk 2]
```diff
@@ -83,18 +83,22 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
         if (expression is UnaryExpression { NodeType: ExpressionType.Convert } convertExpression
-            && convertExpression.Type.GetGenericTypeDefinition() == typeof(IEnumerable<>))
+            && convertExpression.Type.GetGenericTypeImplementations(typeof(IEnumerable<>)) is not null)
```
Comment (roji) [inline src/EFCore/Query/QueryRootProcessor.cs]: Given that below we match on non-generic IEnumerable, should we match for this here as well instead of the generic variant?

File: test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs [hunk 3]
```diff
@@ -1,13 +1,21 @@
...
 
+using System.Collections.Frozen;
 using System.Collections.Immutable;
 
 namespace Microsoft.EntityFrameworkCore.Query;
 
 public abstract class PrimitiveCollectionsQueryTestBase<TFixture>(TFixture fixture) : QueryTestBase<TFixture>(fixture)
     where TFixture : PrimitiveCollectionsQueryTestBase<TFixture>.PrimitiveCollectionsQueryFixtureBase, new()
 {
+    // List<T> is a regular class
```
Comment (roji) [inline test/EFCore.Specification.Tests/Query/PrimitiveCollectionsQueryTestBase.cs:12]: 👍

File: src/EFCore/Query/QueryRootProcessor.cs (hunk 2 above)
Comment (cincuranet) [reply src/EFCore/Query/QueryRootProcessor.cs]: Good idea.
