### PR TITLE
Migration Fix for Oracle

### LINKED ISSUE #10380: ORA-00923: FROM keyword not found where expected
I have applications made in .Net461, which use Oracle Database.
I decided to test EFCore, If the tables are created with the EnsureCreated it works, more if I run the migration, I found the error, I followed all the steps. I downloaded the fonts and followed the steps correctly, where I'm failing.

Line meeting the problem is:
```
at OracleSample.Program.Main(String[] args) na C:\Users\Manfred\Source\MyTestOracle\Programa.cs:linha 17</StackTrace><ExceptionString>Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-00923: FROM keyword not found where expected 
```
In my searches I only found this:
http://www.dba-oracle.com/t_ora_00923_from_keyword_not_found_where_expected.htm

### Steps to reproduce

Steps create database:

https://github.com/aspnet/EntityFrameworkCore/tree/dev/samples/OracleProvider

sqlplus / as sysdba

CREATE PLUGGABLE DATABASE oracle_ef_core
ADMIN USER manfred IDENTIFIED BY manfred
ROLES = (DBA)
FILE_NAME_CONVERT = ('\pdbseed\', '\pdb_oracle_ef_core\');

ALTER PLUGGABLE DATABASE oracle_ef_core OPEN;

My Programs.cs file: 

```c#
using System;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Extensions.Logging;

namespace MyTestOracle
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var db = new MyTestOracleContext())
            {
                db.Database.EnsureCreated();
                db.Database.Migrate();
            }
            Console.ReadKey();
        }
    }

    public class MyTestOracleContext : DbContext
    {
        public DbSet<Blog> Blogs { get; set; }
        public DbSet<Post> Posts { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseOracle("DATA SOURCE=127.0.0.1:1521/oracle_ef_core;USER ID=manfred;PASSWORD=manfred");
        }
    }

    public class Blog
    {
        public int BlogId { get; set; }
        public string Url { get; set; }
        public int Rating { get; set; }
        public List<Post> Posts { get; set; }
    }

    public class Post
    {
        public int PostId { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }

        public int BlogId { get; set; }
        public Blog Blog { get; set; }
    }
}
```
Create migration:

PM> Add-Migration -name MyFirstMigration -Context MyTestOracleContext

### Further technical details
EF Core version: (2.1-sources)
Database Provider: (Microsoft.EntityFrameworkCore.Oracle)
Operating system: 
IDE: (Visual Studio 2017)

### PR DESCRIPTION
**Pull request by ralmsdeveloper**
Resolves #10380

### Basics Implementations
 
✔️Create Column
✔️Create Index
✔️Rename Table
✔️Rename Column
✔️Rename Index
✔️Drop Index
✔️Drop Column
✔️Drop Table

### Simple SQL Example Generated from migrations!

```sql
DECLARE
    v_Count INTEGER;
BEGIN
    SELECT COUNT(*) INTO v_Count FROM all_tables t WHERE t.table_name = N'__EFMigrationsHistory'
    IF v_Count = 0 THEN
        EXECUTE IMMEDIATE
        '
            CREATE TABLE "__EFMigrationsHistory" (
                "MigrationId" NVARCHAR2(150) NOT NULL,
                "ProductVersion" NVARCHAR2(32) NOT NULL,
                CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
            )
        ';
    END IF;
END;
GO

CREATE TABLE "Product" (
    "Id" NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY,
    "Description" NVARCHAR2(450) DEFAULT ('BOOK') NULL,
    "Quanty" NUMBER(10) NOT NULL,
    "Price" NUMBER(29,4) NOT NULL,
    "Date" TIMESTAMP NOT NULL,
    "Logo" BLOB NULL,
    CONSTRAINT "PK_Product" PRIMARY KEY ("Id")
)
GO

-- SEED DATA --

BEGIN
INSERT INTO "Product" ("Id", "Date", "Description", "Logo", "Price", "Quanty")
VALUES (1, TO_DATE('0001-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'Book EF Core', NULL, 100.0, 1000);
END;
GO

BEGIN
INSERT INTO "Product" ("Id", "Date", "Description", "Logo", "Price", "Quanty")
VALUES (2, TO_DATE('0001-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), N'Book Asp.Net Core', NULL, 100.0, 1000);
END;
GO

BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX "Idx_Description" ON "Product" ("Description")';
END;
GO

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20171105004010_First', N'2.1.0-preview1-t000')
GO

-- RENAME COLUMN --


ALTER TABLE "Product" RENAME COLUMN "Description" TO "Description2"
GO

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20171105004654_ChangeNameColumn', N'2.1.0-preview1-t000')
GO

-- RENAME INDEX -- 

ALTER INDEX "Idx_Description" RENAME TO "Idx_Description2"
GO

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES (N'20171105004836_ChangeNameIndex', N'2.1.0-preview1-t000')
GO

```

### CODE REVIEW

File: samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs [hunk 1]
```diff
@@ -233,17 +270,35 @@ public virtual void AlterColumnOperation_with_identity()
...
+        EXECUTE IMMEDIATE 'ALTER TABLE ""People"" DROP CONSTRAINT' || p_constraint;
+    END IF;
+
+    EXCEPTION
+    WHEN NO_DATA_FOUND THEN
+    NULL;
+END;
+GO
+
+ALTER TABLE ""People"" MODIFY ""Id"" NUMBER(10) NOT NULL",
```
Comment (bricelam) [inline samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs]: The above code isn't needed. This statement should include a `GENERATED..AS IDENTITY` clause.

File: samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs [hunk 2]
```diff
@@ -518,13 +729,31 @@ public virtual void AlterColumnOperation_identity()
...
+        EXECUTE IMMEDIATE 'ALTER TABLE ""Person"" DROP CONSTRAINT' || p_constraint;
+    END IF;
+
+    EXCEPTION
+    WHEN NO_DATA_FOUND THEN
+    NULL;
+END;
+GO
+
+ALTER TABLE ""Person"" MODIFY ""Id"" NUMBER(19) NOT NULL",
```
Comment (bricelam) [inline samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs]: Again, the above code isn't needed--we know it remained an `IDENTITY` column.

`AlterColumnOperation_add_identity` shouldn't throw, just include the `GENERATE..IDENTITY` clause.

`AlterColumnOperation_remove_identity` shouldn't throw; include a statement like this:
``` sql
ALTER TABLE MyTable MODIFY MyColumn DROP IDENTITY
```

File: samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs [hunk 3]
```diff
@@ -186,40 +185,78 @@ public virtual void AddPrimaryKeyOperation()
...
+        EXECUTE IMMEDIATE 'ALTER TABLE ""People"" DROP CONSTRAINT' || p_constraint;
+    END IF;
+
+    EXCEPTION
+    WHEN NO_DATA_FOUND THEN
+    NULL;
+END;
+GO
+
+ALTER TABLE ""People"" MODIFY ""LuckyNumber"" NUMBER(10) NOT NULL",
```
Comment (bricelam) [inline samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs]: All `AlterColumnOperation`s when not `IsOldColumnSupported` and not `IDENTITY` should be querying `ALL_TAB_IDENTITY_COLS` and conditionally issuing a statement like this:

``` sql
ALTER TABLE MyTable MODIFY MyColumn DROP IDENTITY
```

In other words, if it's not an `IDENTITY` column, but we don't know if it *was* an `IDENTITY` column, we should check if we need to drop the `IDENTITY` constraint.

File: samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs [hunk 4]
```diff
@@ -293,20 +368,48 @@ public virtual void AlterColumnOperation_computed_with_index()
...
+        EXECUTE IMMEDIATE 'ALTER TABLE ""Person"" DROP CONSTRAINT' || p_constraint;
+    END IF;
+
+    EXCEPTION
+    WHEN NO_DATA_FOUND THEN
+    NULL;
+END;
+GO
+
+ALTER TABLE ""Person"" DROP COLUMN ""FullName""
```
Comment (bricelam) [inline samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs]: Do you have to drop the existing column, or can `ALTER TABLE..MODIFY` handle this?

File: samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs [hunk 5]
```diff
@@ -369,19 +490,45 @@ public virtual void AlterColumnOperation_with_index()
...
-                "DECLARE @var0 sysname;" + EOL +
-                "SELECT @var0 = \"d\".\"name\"" + EOL +
-                "FROM \"sys\".\"default_constraints\" \"d\"" + EOL +
-                "INNER JOIN \"sys\".\"columns\" \"c\" ON \"d\".\"parent_column_id\" = \"c\".\"column_id\" AND \"d\".\"parent_object_id\" = \"c\".\"object_id\"" + EOL +
-                "WHERE (\"d\".\"parent_object_id\" = OBJECT_ID(N'Person') AND \"c\".\"name\" = N'Name');" + EOL +
-                "IF @var0 IS NOT NULL EXEC(N'ALTER TABLE \"Person\" DROP CONSTRAINT \"' + @var0 + '\";');" + EOL +
-                "ALTER TABLE \"Person\" ALTER COLUMN \"Name\" NVARCHAR2(30) NULL;" + EOL +
-                "CREATE INDEX \"IX_Person_Name\" ON \"Person\" (\"Name\");" + EOL,
+@"BEGIN
+    EXECUTE IMMEDIATE 'DROP INDEX ""IX_Person_Name""';
```
Comment (bricelam) [inline samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs]: Do you have to rebuild indexes here on Oracle or can we remove this logic?

File: samples/OracleProvider/src/OracleProvider/Migrations/OracleMigrationsSqlGenerator.cs [hunk 6]
```diff
@@ -416,23 +402,37 @@ protected override void Generate(DropTableOperation operation, IModel model, Mig
...
+                base.Generate(operation, model, builder, false);
+
+                builder
+                   .Append("'")
+                   .AppendLine(Dependencies.SqlGenerationHelper.StatementTerminator)
+                   .DecrementIndent()
+                   .Append("END")
+                   .AppendLine(Dependencies.SqlGenerationHelper.StatementTerminator)
+                   .EndCommand();
+            }
```
Comment (bricelam) [inline samples/OracleProvider/src/OracleProvider/Migrations/OracleMigrationsSqlGenerator.cs]: What is this code doing? Why is it needed?

File: samples/OracleProvider/src/OracleProvider/Migrations/OracleMigrationsSqlGenerator.cs [hunk 7]
```diff
@@ -612,15 +511,27 @@ protected override void Generate(DropForeignKeyOperation operation, IModel model
...
 
+            if (terminate)
+            {
+                builder
+                    .AppendLine("BEGIN")
+                    .IncrementIndent()
+                    .Append("EXECUTE IMMEDIATE ")
+                    .Append("'");
+
+            }
```
Comment (bricelam) [inline samples/OracleProvider/src/OracleProvider/Migrations/OracleMigrationsSqlGenerator.cs]: Again, this doesn't seem right. Why is it needed? Does Oracle not support statement batching? Instead of using `EXECUTE IMMEDIATE`, we should just put each statement in its own command.

File: samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs [hunk 8]
```diff
@@ -765,28 +1005,36 @@ public virtual void SqlOperation_handles_backslash()
...
+VALUES (0, NULL);
+INSERT INTO ""People"" (""Id"", ""Full Name"")
+VALUES (1, N'Daenerys Targaryen');
+INSERT INTO ""People"" (""Id"", ""Full Name"")
+VALUES (2, N'John Snow');
+INSERT INTO ""People"" (""Id"", ""Full Name"")
+VALUES (3, N'Arya Stark');
+INSERT INTO ""People"" (""Id"", ""Full Name"")
+VALUES (4, N'Harry Strickland');
+END;",
```
Comment (bricelam) [inline samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs]: Why `BEGIN` and `END`?

Comment (ralmsdeveloper) [reply samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs]: @bricelam , this is necessary.
To insert batch data, we do not have the same SQL Server support.
Oracle returns us error "ORA-00933" command not terminated!

Thanks for all the reviews, I'll be analyzing every case!

Comment (bricelam) [reply samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs]: Thanks for the hard work! In some ways, I hate that we used the SQL Server code as a starting point since all of its quirks almost certainly don't apply to Oracle.

Comment (ralmsdeveloper) [reply samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs]: I'm going to start working on it and we'll see the progress.

File: samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs (hunk 5 above)
Comment (ralmsdeveloper) [reply samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs]: @bricelam , this may not seem nice, but stay with it, because we can remove a batch of indices, with more security.

And it is necessary to declare the block "BEGIN .. END"

File: samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs (hunk 2 above)
Comment (ralmsdeveloper) [reply samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs]: I'll check this out, and do some testing!

File: samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs (hunk 3 above)
Comment (ralmsdeveloper) [reply samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs]: I'm looking at this, thank you it makes really sense!

Comment (ralmsdeveloper) [reply samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs]: Was your idea to have something like that?

File: samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs (hunk 1 above)
Comment (ralmsdeveloper) [reply samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs]: This is one more problem that we have to think about as we will solve later, Oracle's version 11 is different from the increment.
For now, I will only be compatible with version 12.

File: samples/OracleProvider/src/OracleProvider/Migrations/Internal/OracleHistoryRepository.cs [hunk 9]
```diff
@@ -106,24 +108,40 @@ public override string GetCreateIfNotExistsScript()
...
+                .AppendLine("DECLARE")
+                .AppendLine("    v_Count INTEGER;")
+                .AppendLine("BEGIN")
+                .IncrementIndent()
+                .Append("SELECT COUNT(*) INTO v_Count FROM all_tables t ")
+                .Append("WHERE t.table_name")
+                .Append(" = N'")
+                .Append(TableName)
+                .AppendLine("'")
+                .AppendLine("IF v_Count = 0 THEN");
```
Comment (smitpatel) [inline samples/OracleProvider/src/OracleProvider/Migrations/Internal/OracleHistoryRepository.cs]: Why define a function and not use Exists directly as condition?

Comment (smitpatel) [reply samples/OracleProvider/src/OracleProvider/Migrations/Internal/OracleHistoryRepository.cs]:
```
If Exists (...)
Then ....
Else ....
End
```
What is wrong with above. What goes inside is different between SqlServer/Oracle.
If count of something is 0 then selecting without count will give you false for `Exists` query. So unless we are matching count to some specific numbers other than 0 or 1, function is not necessary.

Comment (ralmsdeveloper) [reply samples/OracleProvider/src/OracleProvider/Migrations/Internal/OracleHistoryRepository.cs]: In fact I did not follow his logic, I want to understand.
My reasoning was if the count is 0 is why there is no table, since we can not use EXISTS here.

**Comment by ralmsdeveloper** [comment]
@smitpatel and @bricelam 

I'm working on it, trying to get better.
What do you think of the output below?

```sql
BEGIN
  EXECUTE IMMEDIATE ('SELECT * FROM "__EFMigrationsHistory" WHERE ROWNUM = 1');
EXCEPTION
WHEN OTHERS THEN
  IF(SQLCODE = -942)THEN
  EXECUTE IMMEDIATE 'CREATE TABLE "__EFMigrationsHistory" (
    "MigrationId" NVARCHAR2(150) NOT NULL,
    "ProductVersion" NVARCHAR2(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId"))';
  END IF;
END;
GO
```

That way I leave the oracle accountable to give me back if the table exists.
Capturing your exception is a more readable code. opinion.

**Comment by bricelam** [comment]
Oh I like it. It can be further simplified:

``` sql
BEGIN
  EXECUTE IMMEDIATE 'CREATE TABLE "__EFMigrationsHistory" (
    "MigrationId" NVARCHAR2(150) NOT NULL,
    "ProductVersion" NVARCHAR2(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId"))';
EXCEPTION
WHEN OTHERS THEN
  IF(SQLCODE != -942)THEN
      RAISE;
  END IF;
END;
GO
```

**Comment by bricelam** [comment]
(But I'm also fine with `SELECT..INTO`)

File: samples/OracleProvider/src/OracleProvider/Migrations/Internal/OracleHistoryRepository.cs (hunk 9 above)
Comment (bricelam) [reply samples/OracleProvider/src/OracleProvider/Migrations/Internal/OracleHistoryRepository.cs]: @smitpatel No `IF EXISTS` in PL/SQL

**Comment by ralmsdeveloper** [comment]
@bricelam 
I liked it too, can I follow your suggestion?
I found her more appropriate.

**Comment by bricelam** [comment]
I'll merge either way. I spent three years writing PL/SQL, so it looks perfectly normal to me. 😉

**Comment by ralmsdeveloper** [comment]
I will rebase and push!

**Comment by ralmsdeveloper** [comment]
ping @bricelam 

For some reason, Travis did not finish the tests!
Do you know why?

**Comment by bricelam** [comment]
> exceeded the maximum time limit

It happens sometimes. Nothing to worry about.

File: samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs [hunk 10]
```diff
@@ -256,18 +262,17 @@ public virtual void AlterColumnOperation_computed()
...
             Assert.Equal(
-                "DECLARE @var0 sysname;" + EOL +
-                "SELECT @var0 = \"d\".\"name\"" + EOL +
-                "FROM \"sys\".\"default_constraints\" \"d\"" + EOL +
-                "INNER JOIN \"sys\".\"columns\" \"c\" ON \"d\".\"parent_column_id\" = \"c\".\"column_id\" AND \"d\".\"parent_object_id\" = \"c\".\"object_id\"" + EOL +
-                "WHERE (\"d\".\"parent_object_id\" = OBJECT_ID(N'People') AND \"c\".\"name\" = N'FullName');" + EOL +
-                "IF @var0 IS NOT NULL EXEC(N'ALTER TABLE \"People\" DROP CONSTRAINT \"' + @var0 + '\";');" + EOL +
-                "ALTER TABLE \"People\" DROP COLUMN \"FullName\";" + EOL +
-                "ALTER TABLE \"People\" ADD \"FullName\" AS \"FirstName\" + ' ' + \"LastName\";" + EOL,
+@"ALTER TABLE ""People"" MODIFY ""FullName"" DEFAULT NULL
```
Comment (bricelam) [inline samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs]: Why `MODIFY` when the next statement is `DROP COLUMN`?

File: samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs [hunk 11]
```diff
@@ -332,17 +344,11 @@ public virtual void AlterColumnOperation_with_index_no_narrowing()
...
 
             Assert.Equal(
-                "DECLARE @var0 sysname;" + EOL +
-                "SELECT @var0 = \"d\".\"name\"" + EOL +
-                "FROM \"sys\".\"default_constraints\" \"d\"" + EOL +
-                "INNER JOIN \"sys\".\"columns\" \"c\" ON \"d\".\"parent_column_id\" = \"c\".\"column_id\" AND \"d\".\"parent_object_id\" = \"c\".\"object_id\"" + EOL +
-                "WHERE (\"d\".\"parent_object_id\" = OBJECT_ID(N'Person') AND \"c\".\"name\" = N'Name');" + EOL +
-                "IF @var0 IS NOT NULL EXEC(N'ALTER TABLE \"Person\" DROP CONSTRAINT \"' + @var0 + '\";');" + EOL +
-                "ALTER TABLE \"Person\" ALTER COLUMN \"Name\" NVARCHAR2(450) NULL;" + EOL,
+                "ALTER TABLE \"Person\" MODIFY \"Name\" NVARCHAR2(450)",
```
Comment (bricelam) [inline samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs]: 🎉 So much prettier than SQL Server!

File: samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs (hunk 10 above)
Comment (ralmsdeveloper) [reply samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs]: @bricelam , I believe it is necessary.
because if it is a computed field, it will remove the default value.

I will follow your recommendation as you see fit.
My opinion is to stick with it!

Comment (bricelam) [reply samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs]: https://github.com/ralmsdeveloper/EntityFrameworkCore/blob/a666e9ef2bd867151f374b22028b99399d5e8b43/samples/OracleProvider/src/OracleProvider/Migrations/OracleMigrationsSqlGenerator.cs#L536

I don't think this line is needed on Oracle.

**Comment by bricelam** [comment]
Is any of the column narrowed code actually needed on Oracle?

https://github.com/ralmsdeveloper/EntityFrameworkCore/blob/a666e9ef2bd867151f374b22028b99399d5e8b43/samples/OracleProvider/src/OracleProvider/Migrations/OracleMigrationsSqlGenerator.cs#L217-L222

File: samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs (hunk 10 above)
Comment (ralmsdeveloper) [reply samples/OracleProvider/test/OracleProvider.FunctionalTests/OracleMigrationSqlGeneratorTest.cs]: I removed it.

**Comment by ralmsdeveloper** [comment]
That was already [here](https://github.com/ralmsdeveloper/EntityFrameworkCore/blob/a666e9ef2bd867151f374b22028b99399d5e8b43/samples/OracleProvider/src/OracleProvider/Migrations/OracleMigrationsSqlGenerator.cs#L217-L222)!

We need to re-create the indexes and constraints on the auto increment columns!
