### PR TITLE
[preview9] Add non-owned table splitting support to query

### LINKED ISSUE #16032: Nested owned entity not populated when no other property in first owned entity has a value
We are working with a nested owned type. We recognized that the nested owned type gets NULL if it's the only property having a value in the first owned type. When there is another property having a value in the first owned entity the nested type is also loaded.

### Steps to reproduce
We created a little application to reproduce the problem.

SQL-Script to create table and some data:
```SQL
CREATE DATABASE EfCore_NestedOwnedTypes;
Use EfCore_NestedOwnedTypes;
CREATE TABLE Invoice
(
	InvoiceId INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ShippingAddress_Street NVARCHAR(50) NULL,
	ShippingAddress_Recipient_Name NVARCHAR(50) NOT NULL
)

INSERT INTO [dbo].[Invoice] (ShippingAddress_Recipient_Name) VALUES ('Bob');
```

C# Console application:
```c#
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;

namespace EfCore_NestedOwnedTypes
{
  public class Program
  {
    public static void Main(string[] args)
    {
      using (var context = new Context())
      {
        var invoice = context.Invoices.First();
        Console.WriteLine("Recipient name is: " + (invoice.ShippingAddress.Recipient.Name ?? "Null!"));
        Console.ReadLine();
      }
    }

    public class Context : DbContext
    {
      public virtual DbSet<Invoice> Invoices { get; set; }

      protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
      {
        if (!optionsBuilder.IsConfigured)
          optionsBuilder.UseSqlServer("data source=(local);initial catalog=EfCore_NestedOwnedTypes;integrated security=True;MultipleActiveResultSets=True;App=EntityFramework", options => options.EnableRetryOnFailure(3));
      }

      protected override void OnModelCreating(ModelBuilder modelBuilder)
      {
        modelBuilder.Entity<Invoice>(entity =>
        {
          entity.HasKey(e => e.InvoiceId);
          entity.Property(e => e.InvoiceId).HasColumnName("InvoiceId");
          entity.ToTable("Invoice");
          entity.OwnsOne(e => e.ShippingAddress, shippingAddress =>
          {
            shippingAddress.Property(e => e.Street).HasColumnName("ShippingAddress_Street");
            shippingAddress.OwnsOne(sa => sa.Recipient, recipient =>
            {
              recipient.Property(r => r.Name).HasColumnName("ShippingAddress_Recipient_Name");
            });
          });
        });
      }
    }

    public class Invoice
    {
      public Invoice() { ShippingAddress = new ShippingAddress(); }

      public int InvoiceId { get; set; }
      public ShippingAddress ShippingAddress { get; set; }
    }

    public class ShippingAddress
    {
      public ShippingAddress() { Recipient = new Recipient(); }

      public string Street { get; set; }
      public Recipient Recipient { get; set; }
    }

    public class Recipient
    {
      public string Name { get; set; }
    }
  }
}
```
Output: "Recipient name is: NULL!".
Note: when adding a value to ShippingAddress.Street everything works fine (Output: "Recipient name is: Bob").

### Further technical details
EF Core version: 3.0.0prev5
Operating system: Windows 10
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Materialize owned entities with all null properties if they are being referenced by other entities

Fixes #16032

### CODE REVIEW

File: src/EFCore/Query/ProjectionMember.cs [hunk 1]
```diff
@@ -19,32 +20,51 @@ public ProjectionMember()
             _memberChain = new List<MemberInfo>();
         }
 
+        public ProjectionMember(IEntityType root)
```
Comment (smitpatel) [inline src/EFCore/Query/ProjectionMember.cs]: This does not seem like good change design wise.

Comment (AndriySvyryd) [reply src/EFCore/Query/ProjectionMember.cs]: I agree. Any alternatives?

Comment (smitpatel) [reply src/EFCore/Query/ProjectionMember.cs]: We should generate joins to bind columns from additional entity types. Ideally join elimination would combine all of that up in single table. (That is how it is supposed to do for owned table sharing case also). If redundant joins are unwanted then either we need to implement join elimination or look into bigger change to accommodate multiple EntityType for entityprojection.

**Comment by AndriySvyryd** [comment]
Updated. Now with uglier SQL.

**Comment by AndriySvyryd** [comment]
FromSql will not work with table splitting unless the same query works without FromSql

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 2]
```diff
@@ -887,7 +887,6 @@ protected virtual Expression VisitNullConditional(NullConditionalExpression expr
         ///     any release. You should only use it directly in your code with extreme caution and knowing that
         ///     doing so can result in application failures when updating to a new Entity Framework Core release.
         /// </summary>
-        // TODO: DRY with NavigationExpansionHelpers
         protected virtual Expression CreateKeyAccessExpression(
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: I thought you were going to DRY this?

Also make this method private.

File: src/EFCore.Relational/Query/EntityProjectionExpression.cs [hunk 3]
```diff
@@ -16,8 +16,8 @@ public class EntityProjectionExpression : Expression
         private readonly IDictionary<INavigation, EntityShaperExpression> _navigationExpressionsCache
             = new Dictionary<INavigation, EntityShaperExpression>();
 
-        private readonly TableExpressionBase _innerTable;
         private readonly bool _nullable;
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/EntityProjectionExpression.cs]: Best change :trollface:

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs (hunk 2 above)
Comment (AndriySvyryd) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: For some reason tests started failing after DRYing...

Comment (smitpatel) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: Can you file an issue in backlog. I would like to investigate in future to better understand.

Comment (AndriySvyryd) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: I don't think it's worth it. I probably messed up a Convert or something.

**Comment by AndriySvyryd** [comment]
@smitpatel Ping

File: src/EFCore/Extensions/ConventionEntityTypeExtensions.cs [hunk 4]
```diff
@@ -27,7 +27,7 @@ public static class ConventionEntityTypeExtensions
         ///     The root base type. If the given entity type is not a derived type, then the same entity type is returned.
         /// </returns>
         public static IConventionEntityType RootType([NotNull] this IConventionEntityType entityType)
-            => (IConventionEntityType)((IEntityType)entityType).RootType();
+            => (IConventionEntityType)((IEntityType)entityType).GetRootType();
```
Comment (smitpatel) [inline src/EFCore/Extensions/ConventionEntityTypeExtensions.cs]: I wish this change was in separate PR, it would have been easier to review. :(

File: src/EFCore.Relational/Query/SqlExpressionFactory.cs [hunk 5]
```diff
@@ -435,47 +438,217 @@ public virtual SelectExpression Select(SqlExpression projection)
...
+        private void AddInnerJoin(
+            SelectExpression selectExpression, IForeignKey foreignKey, ICollection<IEntityType> sharingTypes, bool skipInnerJoins)
+        {
+            var joinPredicate = GenerateJoinPredicate(selectExpression, foreignKey, sharingTypes, skipInnerJoins, out var innerSelect);
+
+            var transparentIdentifierType = foreignKey.PrincipalEntityType.IsAssignableFrom(
+                GetMappedEntityProjectionExpression(selectExpression).EntityType)
+                ? TransparentIdentifierFactory.Create(foreignKey.PrincipalEntityType.ClrType, foreignKey.DeclaringEntityType.ClrType)
+                : TransparentIdentifierFactory.Create(foreignKey.DeclaringEntityType.ClrType, foreignKey.PrincipalEntityType.ClrType);
+            selectExpression.AddInnerJoin(innerSelect, joinPredicate, transparentIdentifierType);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionFactory.cs]: If these joins are just for generating conditions then just pass transparentIdentifierType as null. It will add join but will not re-map the projection as if after the join you are still selecting outer.

File: src/EFCore/Extensions/ConventionEntityTypeExtensions.cs (hunk 4 above)
Comment (AndriySvyryd) [reply src/EFCore/Extensions/ConventionEntityTypeExtensions.cs]: It was in a separate commit, but had to squash them

File: src/EFCore.Relational/Query/SqlExpressionFactory.cs [hunk 6]
```diff
@@ -435,47 +438,217 @@ public virtual SelectExpression Select(SqlExpression projection)
...
+            {
+                sharingTypes ??= new HashSet<IEntityType>(
+                        entityType.Model.GetEntityTypes()
+                            .Where(et => et.FindPrimaryKey() != null
+                                      && et.GetTableName() == entityType.GetTableName()
+                                      && et.GetSchema() == entityType.GetSchema()));
+
+                if (sharingTypes.Count > 0)
+                {
+                    predicate = GenerateDiscriminatorExpression(selectExpression, entityType);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionFactory.cs]: Bit awkward that this returns predicate but other methods applies it directly.

Comment (AndriySvyryd) [reply src/EFCore.Relational/Query/SqlExpressionFactory.cs]: It could apply it and return a bool instead

**Comment by ajcvickers** [comment]
@AndriySvyryd Why did you assign this to me?

**Comment by AndriySvyryd** [comment]
@ajcvickers You are the only one on our team who can merge into preview9

**Comment by ajcvickers** [comment]
@AndriySvyryd That should be fixed now.

**Comment by AndriySvyryd** [comment]
@ajcvickers Thanks. I thought it was by design.
