### PR TITLE
Fix to #18522 - Query: SqlFunctionExpression instance should be SqlExpression rather than Expression

### LINKED ISSUE #18522: Query: SqlFunctionExpression instance should be SqlExpression rather than Expression
Small typo/mistake but its a public surface so we can't change it without breaking.

### PR DESCRIPTION
**Pull request by maumar**
Resolves #18522

### CODE REVIEW

File: src/EFCore.Relational/Query/SqlExpressionVisitor.cs [hunk 1]
```diff
@@ -116,7 +116,7 @@ protected override Expression VisitExtension(Expression extensionExpression)
         protected abstract Expression VisitSqlFragment(SqlFragmentExpression sqlFragmentExpression);
         protected abstract Expression VisitSqlFunction(SqlFunctionExpression sqlFunctionExpression);
         protected abstract Expression VisitSqlParameter(SqlParameterExpression sqlParameterExpression);
-        protected abstract Expression VisitSqlUnary(SqlUnaryExpression sqlCastExpression);
+        protected abstract Expression VisitSqlUnary(SqlUnaryExpression sqlUnaryExpression);
         protected abstract Expression VisitSubSelect(ScalarSubqueryExpression scalarSubqueryExpression);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionVisitor.cs]: Break this too. VisitScalarSubquery.

File: src/EFCore.Relational/Query/SqlExpressionVisitor.cs [hunk 2]
```diff
@@ -82,7 +82,7 @@ protected override Expression VisitExtension(Expression extensionExpression)
                     return VisitSqlParameter(sqlParameterExpression);
 
                 case ScalarSubqueryExpression subSelectExpression:
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressionVisitor.cs]: update this too.
