### PR TITLE
Query: Fix an issue in SubqueryProjection creation which caused inval…

### LINKED ISSUE #10273: Rownumber paging with Skip() throws ArgumentNullException when projection contains static method call
When using row number paging support, when i try to run a query using Skip() which contains projection that includes static method call, an ArgumentNullException is thrown. Without Skip() it works. Without static method call it also works.

This only occurs when running against SQL Server <= 2008 database. Dont know why, but if I enable row number paging and run against SQL Server > 2008 this works (seems UseRowNumberPaging has no effect then).

```
Exception message: System.ArgumentNullException: 'Value cannot be null.'
Stack trace:
 	System.Private.CoreLib.dll!System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()	Unknown	No symbols loaded.
>	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore<System.Collections.Generic.IEnumerable<<>f__AnonymousType0<string>>>(System.Linq.Expressions.Expression query, Remotion.Linq.Parsing.Structure.INodeTypeProvider nodeTypeProvider, Microsoft.EntityFrameworkCore.Storage.IDatabase database, Microsoft.EntityFrameworkCore.Diagnostics.IDiagnosticsLogger<Microsoft.EntityFrameworkCore.DbLoggerCategory.Query> logger, System.Type contextType) Line 166	C#	Symbols loaded.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute.AnonymousMethod__0() Line 103	C#	Symbols loaded.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore<System.Collections.Generic.IEnumerable<<>f__AnonymousType0<string>>>(object cacheKey, System.Func<System.Func<Microsoft.EntityFrameworkCore.Query.QueryContext, System.Collections.Generic.IEnumerable<<>f__AnonymousType0<string>>>> compiler) Line 69	C#	Symbols loaded.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery<System.Collections.Generic.IEnumerable<<>f__AnonymousType0<string>>>(object cacheKey, System.Func<System.Func<Microsoft.EntityFrameworkCore.Query.QueryContext, System.Collections.Generic.IEnumerable<<>f__AnonymousType0<string>>>> compiler) Line 44	C#	Symbols loaded.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute<System.Collections.Generic.IEnumerable<<>f__AnonymousType0<string>>>(System.Linq.Expressions.Expression query) Line 99	C#	Symbols loaded.
 	Microsoft.EntityFrameworkCore.dll!Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute<System.Collections.Generic.IEnumerable<<>f__AnonymousType0<string>>>(System.Linq.Expressions.Expression expression) Line 62	C#	Symbols loaded.
 	Remotion.Linq.dll!Remotion.Linq.QueryableBase<<>f__AnonymousType0<string>>.GetEnumerator()	Unknown	No symbols loaded.
 	System.Private.CoreLib.dll!System.Collections.Generic.List<<>f__AnonymousType0<string>>.AddEnumerable(System.Collections.Generic.IEnumerable<<>f__AnonymousType0<string>> enumerable)	Unknown	No symbols loaded.
 	System.Linq.dll!System.Linq.Enumerable.ToList<<>f__AnonymousType0<string>>(System.Collections.Generic.IEnumerable<<>f__AnonymousType0<string>> source)	Unknown	No symbols loaded.
 	RowNumberPagingIssue.dll!RowNumberPagingIssue.Program.Main(string[] args) Line 33	C#	Symbols loaded.
```

### Steps to reproduce

Remember to run this against SQL Server <= 2008 !

```c#
    class TestEntity
    {
        public int Id { get; set; }
    }

    class TestDbContext : DbContext
    {
        public DbSet<TestEntity> Test => Set<TestEntity>();

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer(
                "some connection string",
                o => o.UseRowNumberForPaging());

            base.OnConfiguring(optionsBuilder);
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            var dbContext = new TestDbContext();
            dbContext.Database.EnsureCreated();
            
            var testModels =
                dbContext.Test
                    .Select(e => new { bug = String.Format("{0}", e.Id)})
                    .Skip(1)
                    .ToList();
        }
    }
```

### Further technical details
EF Core version: 2.0.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

### PR DESCRIPTION
**Pull request by smitpatel**
…id select expression

Issue: All projections in a subquery are required to be ColumnExpression/AliasExpression/ColumnReferenceExpression so that they can be lifted to outer select expression through LiftExpressionFromSubquery method.
In this particular case the expression had convert around it. Because its computed name was unique we did not change it causing invariant to break which later got converted to null projection.

Resolves #10273

### CODE REVIEW

File: src/EFCore.Relational/Extensions/RelationalExpressionExtensions.cs [hunk 1]
```diff
@@ -54,6 +55,7 @@ public static ColumnReferenceExpression LiftExpressionFromSubquery([NotNull] thi
                     return new ColumnReferenceExpression(columnReferenceExpression, table);
             }
 
+            Debug.Assert(true, "LiftExpressionFromSubquery was called on incorrect expression type.");
```
Comment (anpete) [inline src/EFCore.Relational/Extensions/RelationalExpressionExtensions.cs]: This should be false 😄 But better to use ```Debug.Fail```
