### PR TITLE
Always store original values for index properties

### LINKED ISSUE #18859: Index.IsUnique error with ChangingAndChangedNotifications TrackingStrategy
It seems that with the ChangingAndChangedNotifications tracking strategy when trying to delete an entity that has one of its property set as index.IsUnique, generate a tracking error
image

### Steps to reproduce
I reproduce the case in this console app.
https://github.com/Samoulou/indexUniqueTrackingError

When launching the console app, I just create the DB and delete the concerned entity, after 5 seconds the error should be throw.

NB: the problem occurs when updating the index property too

### Further technical details
EF Core version: not working with our project in 2.2.6 and with my console app in 3.0.0
Target framework: .NET Core 2.2.6, 3.0.0
Operating system: Windows 10
IDE: Visual Studio 2019 16.3.1

### PR DESCRIPTION
**Pull request by ajcvickers**
Since these are used by the update pipeline.

Fixes #18859

### CODE REVIEW

File: src/EFCore/Metadata/Internal/PropertyExtensions.cs [hunk 1]
```diff
@@ -141,7 +141,8 @@ public static bool RequiresOriginalValue([NotNull] this IProperty property)
             => property.DeclaringEntityType.GetChangeTrackingStrategy() != ChangeTrackingStrategy.ChangingAndChangedNotifications
                 || property.IsConcurrencyToken
                 || property.IsKey()
-                || property.IsForeignKey();
+                || property.IsForeignKey()
+                || property.IsIndex();
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/PropertyExtensions.cs]: We really only need the unique indexes

Comment (ajcvickers) [reply src/EFCore/Metadata/Internal/PropertyExtensions.cs]: @AndriySvyryd Updated to only do this for unique indexes.
