### PR TITLE
SQLite: Store char as TEXT by default

### LINKED ISSUE #8764: SQLite Migrations: HasComputedColumnSql is ignored
I am using examples from EntityFramework docs to use Sqlite and InMemoryDatabase for unit testing. Most tests work fine, but I am unable to test fluent API model changes that should take place during OnModelCreating.

For example,

```
// please excuse any typos in this example!

public class PersonContext : DbContext
{
    public PersonContext(DbContextOptions<PersonContext> options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Person>()
            .Property(p => p.DisplayName)
            .HasComputedColumnSql("[LastName] + ', ' + [FirstName]");
    }

    public DbSet<Person> Persons { get; set; }
}

public class Person
{
    public int PersonId { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }

    [Display(Name ="Full Name")]
    public string DisplayName { get; set; }
}
```
```
[Fact]
public void TestCreatePerson()
{
    var options = new DbContextOptionsBuilder<PersonContext>()
        .UseInMemoryDatabase(databaseName: "TestCreatePerson")
        .Options;

    using (var context = new PersonContext(options))
    {
        var person = new Person();
        person.FirstName = "Steven";
        person.LastName = "Ferrell";
        PersonsController controller = new PersonsController(context);
        controller.Create(person);
    }

    using (var context = new PersonContext(options))
    {
        Assert.Equal(1, context.Persons.Count());
        Assert.Equal("Steven", context.Persons.Single().FirstName);
//the following fails with the error that DisplayName is actually <null> instead of "Ferrell, Steven"
        Assert.Equal("Ferrell, Steven", context.Persons.Single().DisplayName);
    }
}
```

### LINKED ISSUE #15020: Microsoft.Data.Sqlite: Store char as TEXT
Again, like #15019, it's probably too late, but I wish we could store `char` values as TEXT. This would make databases way more compatible with external systems.

Today, we store the UTF-16 character code as an INTEGER.

### PR DESCRIPTION
**Pull request by bricelam**
This also fixes some bugs in the relational char type mapping:
- LINQ constants converted to int produced the wrong literal
- Apostrophe char values weren't escaped (fixes #8764)

Resolves #15020

**Providers**, the behavior of `CharTypeMapping` has changed in a way that may break derived types.

### CODE REVIEW

File: src/EFCore.Relational/Storage/CharTypeMapping.cs [hunk 1]
```diff
@@ -47,8 +49,22 @@ protected override RelationalTypeMapping Clone(RelationalTypeMappingParameters p
...
         /// </summary>
-        protected override string SqlLiteralFormatString => "'{0}'";
+        /// <param name="value">The literal value.</param>
+        /// <returns>
+        ///     The generated string.
+        /// </returns>
+        protected override string GenerateNonNullSqlLiteral(object value)
+        {
+            // NB: We can get Int32 values here too due to compiler-introduced convert nodes
+            var charValue = Convert.ToChar(Check.NotNull(value, nameof(value)));
```
Comment (smitpatel) [inline src/EFCore.Relational/Storage/CharTypeMapping.cs]: At least from Query funcletizer side it should preserve char constant.

Comment (bricelam) [reply src/EFCore.Relational/Storage/CharTypeMapping.cs]: Feel free to remove it as part of the query changes. (Or not since there's no harm in leaving it.) I effectively just moved code that was already in the SQLite provider.
