### PR TITLE
Handle case where cast between enum types is used in query

### LINKED ISSUE #11956: System.InvalidCastException when filtering projected query on EnumDto, with relational, worked before 2.1.0-preview2
_A full repro project is here: https://github.com/GeorgDangl/EFCoreProjectionInvalidCastRepro_

I noticed a regression that was introduced since `2.1.0-preview2`, it's also present in the current `2.1.0-rc1-final`. It was working with `2.1.0-preview1` and the 2.0 versions.

I am getting `System.InvalidCastExceptions` when I do a query, project it via LINQ `Select()` to a Dto class and then try to filter it with a variable representing an enum:

```csharp
// Throws System.InvalidCastException :
// Invalid cast from 'EFCoreProjectionInvalidCastRepro.EmailTemplateTypeDto'
// to 'EFCoreProjectionInvalidCastRepro.EmailTemplateType'.
[Fact]
public async Task CanFilterProjectionWithCapturedVariable()
{
    var templateType = EmailTemplateTypeDto.PasswordResetRequest;
    var template = await Context
        .EmailTemplates
        .Select(t => new EmailTemplateDto {Id = t.Id, TemplateType = (EmailTemplateTypeDto) t.TemplateType})
        .Where(t => t.TemplateType == templateType)
        .FirstOrDefaultAsync();
    Assert.NotNull(template);
}

// This works with an inline filter
[Fact]
public async Task CanFilterProjectionWithInlineVariable()
{
    var template = await Context
        .EmailTemplates
        .Select(t => new EmailTemplateDto {Id = t.Id, TemplateType = (EmailTemplateTypeDto) t.TemplateType})
        .Where(t => t.TemplateType == EmailTemplateTypeDto.PasswordResetRequest)
        .FirstOrDefaultAsync();
    Assert.NotNull(template);
}
```

The exception being thrown:

```
System.InvalidCastException: 'Invalid cast from 'EFCoreProjectionInvalidCastRepro.EmailTemplateTypeDto' to 'EFCoreProjectionInvalidCastRepro.EmailTemplateType'.'

at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.Sanitize[T](Object value)
at Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter`2.<>c__DisplayClass3_0`2.<SanitizeConverter>b__0(Object v)
at Microsoft.EntityFrameworkCore.Storage.RelationalTypeMapping.CreateParameter(DbCommand command, String name, Object value, Nullable`1 nullable)
at Microsoft.EntityFrameworkCore.Storage.Internal.TypeMappedRelationalParameter.AddDbParameter(DbCommand command, Object value)
at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalParameterBase.AddDbParameter(DbCommand command, IReadOnlyDictionary`2 parameterValues)
at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.CreateCommand(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteAsync(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.BufferlessMoveNext(DbContext _, Boolean buffer, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNext(CancellationToken cancellationToken)
at System.Linq.AsyncEnumerable.FirstOrDefault_[TSource](IAsyncEnumerable`1 source, CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.MoveNext(CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext(CancellationToken cancellationToken)
at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteSingletonAsyncQuery[TResult](QueryContext queryContext, Func`2 compiledQuery, IDiagnosticsLogger`1 logger, Type contextType)
at EFCoreProjectionInvalidCastRepro.ProjectionTests.CanFilterProjectionWithCapturedVariable() in D:\Visual Studio Projects\EFCoreProjectionInvalidCastRepro\EFCoreProjectionInvalidCastRepro\ProjectionTests.cs:line 37
```

### Other Observations
* It works with the InMemory provider
* It throws the same error for non-async calls
* It works on `2.1.0-preview1` and earlier
* It also happens when using AutoMappers queryable extension `ProjectTo<T>()`

### Further technical details
EF Core version: 2.1.0-rc1-final
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10 X64 and Windows Server 2012 R2
IDE: Visual Studio 2017 15.7 (happens also with `dotnet test`)

### Full Repro Code

```csharp
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace EFCoreProjectionInvalidCastRepro
{
    public class ProjectionTests
    {
        private AppDbContext Context => new AppDbContext();
        private static bool _isInitialized = false;

        public ProjectionTests()
        {
            if (!_isInitialized)
            {
                using (var context = new AppDbContext())
                {
                    context.Database.EnsureCreated();
                    context.EmailTemplates.Add(new EmailTemplate {Id = Guid.NewGuid(), TemplateType = EmailTemplateType.PasswordResetRequest});
                    context.SaveChanges();
                }

                _isInitialized = true;
            }
        }

        // Throws System.InvalidCastException :
        // Invalid cast from 'EFCoreProjectionInvalidCastRepro.EmailTemplateTypeDto'
        // to 'EFCoreProjectionInvalidCastRepro.EmailTemplateType'.
        [Fact]
        public async Task CanFilterProjectionWithCapturedVariable()
        {
            var templateType = EmailTemplateTypeDto.PasswordResetRequest;
            var template = await Context
                .EmailTemplates
                .Select(t => new EmailTemplateDto {Id = t.Id, TemplateType = (EmailTemplateTypeDto) t.TemplateType})
                .Where(t => t.TemplateType == templateType)
                .FirstOrDefaultAsync();
            Assert.NotNull(template);
        }

        // This one succeeds, the filter condition is inlined
        [Fact]
        public async Task CanFilterProjectionWithInlineVariable()
        {
            var template = await Context
                .EmailTemplates
                .Select(t => new EmailTemplateDto {Id = t.Id, TemplateType = (EmailTemplateTypeDto) t.TemplateType})
                .Where(t => t.TemplateType == EmailTemplateTypeDto.PasswordResetRequest)
                .FirstOrDefaultAsync();
            Assert.NotNull(template);
        }

        // The same error happends for non-async materialization
        [Fact]
        public void CanFilterProjectionWithCapturedVariableNonAsync()
        {
            var templateType = EmailTemplateTypeDto.PasswordResetRequest;
            var template = Context
                .EmailTemplates
                .Select(t => new EmailTemplateDto { Id = t.Id, TemplateType = (EmailTemplateTypeDto)t.TemplateType })
                .Where(t => t.TemplateType == templateType)
                .FirstOrDefault();
            Assert.NotNull(template);
        }
    }

    public class EmailTemplate
    {
        public Guid Id { get; set; }
        public EmailTemplateType TemplateType { get; set; }
    }

    public enum EmailTemplateType
    {
        PasswordResetRequest = 0,
        EmailConfirmation = 1
    }

    public class EmailTemplateDto
    {
        public Guid Id { get; set; }
        public EmailTemplateTypeDto TemplateType { get; set; }
    }

    public enum EmailTemplateTypeDto
    {
        PasswordResetRequest = 0,
        EmailConfirmation = 1
    }

    public class AppDbContext : DbContext
    {
        public DbSet<EmailTemplate> EmailTemplates { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            var sqliteInMemoryConnectionString = InMemorySqliteHelper.GetSqliteInMemoryConnectionString();
            optionsBuilder.UseSqlite(sqliteInMemoryConnectionString);
            base.OnConfiguring(optionsBuilder);
        }
    }

    public static class InMemorySqliteHelper
    {
        // This connection must be kept open for the lifetime of the process.
        // SQLite drops the database as soon as the last connection has been closed.
        private static SqliteConnection _connection;

        public static string GetSqliteInMemoryConnectionString()
        {
            var sqliteConnectionStringBuilder = new SqliteConnectionStringBuilder
            {
                DataSource = "in_memory_sqlite.db",
                Cache = SqliteCacheMode.Shared,
                Mode = SqliteOpenMode.Memory
            };
            var sqliteConnectionString = sqliteConnectionStringBuilder.ToString();
            if (_connection == null)
            {
                _connection = new SqliteConnection(sqliteConnectionString);
                _connection.Open();
            }

            return sqliteConnectionString;
        }
    }
}
```

By the way, I would _really_ like to know if there's some workaround, other than not using a Dto for the enum. I've been unsuccessfully tackling this since yesterday.

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #11956

This is a special case that used to work previous to 2.1 because all enums were erased. Adding some special-casing back to the converter to make it still work.

### CODE REVIEW

File: src/EFCore/Storage/ValueConversion/ValueConverter`.cs [hunk 1]
```diff
@@ -49,9 +49,23 @@ private static T Sanitize<T>(object value)
...
-                ? Convert.ChangeType(value, unwrappedType)
-                : value);
+            if (!unwrappedType.IsInstanceOfType(value))
+            {
+                if (unwrappedType.IsEnum)
+                {
+                    var valueType = value.GetType().UnwrapNullableType();
+                    if (valueType.IsEnum)
+                    {
+                        value = Convert.ChangeType(value, valueType.GetEnumUnderlyingType());
```
Comment (AndriySvyryd) [inline src/EFCore/Storage/ValueConversion/ValueConverter`.cs]: Don't we need to call `Convert.ChangeType(value, unwrappedType);` as well if `unwrappedType` is different from the underlying type (e.g. int enum mapped to a byte) ?

Also do we use `Convert.ChangeType` anywhere else in the code that might need the enum handling this as well? If so extract extension method

Comment (ajcvickers) [reply src/EFCore/Storage/ValueConversion/ValueConverter`.cs]: Will do some further investigation into what exactly is needed and if it is needed elsewhere.
