### PR TITLE
Query: Fix for Having clause missing in Grouping Subquery

### LINKED ISSUE #11646: Having clause missing in Grouping Subquery
While trying to find a workaround for #10012 that does not generate exceptions due to invalid sql, i've found this query that executes successful but delivers incorrect results as it forgets about the `HAVING` clause

### Steps to reproduce

```c#
class Program
{
    public static readonly LoggerFactory MyLoggerFactory = new LoggerFactory(new[] { new ConsoleLoggerProvider((_, __) => true, true) });

    static void Main(string[] args)
    {
        var context = new FileContext();
        context.Database.EnsureCreated();

        var duplicateSizes = context.FileEntries
            .GroupBy(x => x.Size)
            .Where(x => x.Count() > 1)
            .Select(x => x.Key);

        var fileEntries = context.FileEntries
            .Where(x => duplicateSizes.Contains(x.Size))
            .ToList();
    }
}

class FileContext : DbContext
{
    public DbSet<FileEntry> FileEntries { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        var builder = new SqliteConnectionStringBuilder();
        builder.DataSource = "db.sqlite";
        optionsBuilder
            .UseLoggerFactory(Program.MyLoggerFactory)
            .UseSqlite(builder.ToString());
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<FileEntry>()
            .HasIndex(x => x.Size);
    }
}

class FileEntry
{
    public long Id { get; set; }
    public long Size { get; set; }
    public string Path { get; set; }
}
```

### Produced SQL
```sql
SELECT "x"."Id", "x"."Path", "x"."Size"
FROM "FileEntries" AS "x"
WHERE "x"."Size" IN (
  SELECT "x0"."Size" AS "Key"
  FROM "FileEntries" AS "x0"
  GROUP BY "x0"."Size"
)
```

### Expected SQL
```sql
SELECT "x"."Id", "x"."Path", "x"."Size"
FROM "FileEntries" AS "x"
WHERE "x"."Size" IN (
  SELECT "x0"."Size" AS "Key"
  FROM "FileEntries" AS "x0"
  GROUP BY "x0"."Size"
  HAVING COUNT(*) > 1
)
```

### Further technical details
EF Core version: 2.1.0-preview2-final
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10 Pro
IDE: Visual Studio 2017 15.7 p3

### PR DESCRIPTION
**Pull request by smitpatel**
Issue: We missed Having clause because it wasn't being copied while cloning SelectExpression
Fix:
We added processing of Having & GroupBy both in following places now to be consistent with other SelectExpression metadata
- Clone
- PushDownSubquery
- Clear
- JoinElimination for tablesplitting
- VisitChildren

Further, added NullConditionalExpression for translation of grouping key which can arise from GroupJoin-DefaultIfEmpty pattern. This improved some of the query translation

Resolves #11646

### CODE REVIEW

File: src/EFCore.Relational/Query/Expressions/SelectExpression.cs [hunk 1]
```diff
@@ -85,7 +86,10 @@ public class SelectExpression : TableExpressionBase
         internal void DetachContext()
         {
             // TODO: Remove dependency on QCC. #11601
-            _queryCompilationContext = null;
+            if (!Debugger.IsAttached)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Expressions/SelectExpression.cs]: @maumar @anpete 🎉

File: src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs [hunk 2]
```diff
@@ -270,11 +270,11 @@ public virtual Expression VisitSelect(SelectExpression selectExpression)
 
                 _relationalCommandBuilder.Append("GROUP BY ");
                 GenerateList(selectExpression.GroupBy);
+            }
 
-                if (selectExpression.Having != null)
-                {
-                    GenerateHaving(selectExpression.Having);
-                }
+            if (selectExpression.Having != null)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs]: Without GroupBy there shouldn't be having clause. But I moved it out so that if we ever generate it incorrectly we would catch it instead of swallowing it.

File: src/EFCore.Relational/Query/Expressions/SelectExpression.cs [hunk 3]
```diff
@@ -1199,26 +1208,139 @@ protected override Expression Accept(ExpressionVisitor visitor)
...
+            for (var i = 0; i < GroupBy.Count; i++)
+            {
+                _groupBy[i] = visitor.Visit(GroupBy[i]);
+            }
+
+            Having = visitor.Visit(Having);
+
+            for (var i = 0; i < OrderBy.Count; i++)
+            {
+                _orderBy[i] = new Ordering(visitor.Visit(OrderBy[i].Expression), OrderBy[i].OrderingDirection);
```
Comment (anpete) [inline src/EFCore.Relational/Query/Expressions/SelectExpression.cs]: Don't alloc unless needed?
