### PR TITLE
Set operations: finalization

### LINKED ISSUE #13196: Include before Concat throws on nav rewrite
```C#
[ConditionalFact]
public virtual void Include_before_Concat()
{
    using(var context = CreateContext())
    {
        context.Customers.Include(c => c.Orders).Concat(context.Customers).ToList();
    }
}
```
> System.ArgumentException : The input sequence must have items of type 'Microsoft.EntityFrameworkCore.TestModels.Northwind.Customer', but it has items of type 'Microsoft.EntityFrameworkCore.Query.Internal.AnonymousObject'.
Parameter name: inputInfo
   at Remotion.Linq.Clauses.ResultOperatorBase.CheckSequenceItemType(StreamedSequenceInfo inputInfo, Type expectedItemType)
   at Remotion.Linq.Clauses.ResultOperators.ConcatResultOperator.GetOutputDataInfo(IStreamedDataInfo inputInfo)
   at System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   at Remotion.Linq.QueryModel.GetOutputDataInfo()
   at Remotion.Linq.Clauses.Expressions.SubQueryExpression..ctor(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.CollectionQueryModelRewritingExpressionVisitor.CreateJoinToParentQuery(QueryModel parentQueryModel, QuerySourceReferenceExpression parentQuerySourceReferenceExpression, Expression outerTargetExpression, IForeignKey foreignKey, QueryModel targetQueryModel, ICollection`1 subQueryProjection) in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\Internal\IncludeCompiler.CollectionQueryModelRewritingExpressionVisitor.cs:line 394
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.CollectionQueryModelRewritingExpressionVisitor.Rewrite(QueryModel collectionQueryModel, INavigation navigation) in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\Internal\IncludeCompiler.CollectionQueryModelRewritingExpressionVisitor.cs:line 149
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.CollectionQueryModelRewritingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\Internal\IncludeCompiler.CollectionQueryModelRewritingExpressionVisitor.cs:line 65
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitBlockExpressions(ExpressionVisitor visitor, BlockExpression block)
   at System.Linq.Expressions.ExpressionVisitor.VisitBlock(BlockExpression node)
   at System.Linq.Expressions.BlockExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.CollectionQueryModelRewritingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\Internal\IncludeCompiler.CollectionQueryModelRewritingExpressionVisitor.cs:line 83
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Remotion.Linq.Clauses.SelectClause.TransformExpressions(Func`2 transformation)
   at Remotion.Linq.QueryModel.TransformExpressions(Func`2 transformation)
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.RewriteCollectionQueries(QueryModel queryModel) in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\Internal\IncludeCompiler.cs:line 114
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.RewriteCollectionQueries() in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\Internal\IncludeCompiler.cs:line 101
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery) in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\EntityQueryModelVisitor.cs:line 349
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.OptimizeQueryModel(QueryModel queryModel, Boolean asyncQuery) in C:\enlistments\Universe\EntityFramework\src\EFCore.Relational\Query\RelationalQueryModelVisitor.cs:line 1345
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel) in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\EntityQueryModelVisitor.cs:line 170
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](QueryModel queryModel) in C:\enlistments\Universe\EntityFramework\src\EFCore\Storage\Database.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType) in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\Internal\QueryCompiler.cs:line 151
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0() in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\Internal\QueryCompiler.cs:line 91
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 67
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 44
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\Internal\QueryCompiler.cs:line 87
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) in C:\enlistments\Universe\EntityFramework\src\EFCore\Query\Internal\EntityQueryProvider.cs:line 62
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.SimpleQuerySqlServerTest.Include_before_Concat() in C:\enlistments\Universe\EntityFramework\test\EFCore.SqlServer.FunctionalTests\Query\SimpleQuerySqlServerTest.JoinGroupJoin.cs:line 555

### LINKED ISSUE #16065: Include() does not work if used after Union()
I have the following data context:

```C#
public class Foo
{
    public long Id { get; set; }
}

public class Bar
{
    public long Id { get; set; }
    public Foo Foo { get; set; }
}

public class DataContext : DbContext
{
    public DbSet<Foo> Foos { get; set; }
    public DbSet<Bar> Bars { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer(@"data source=(local);initial catalog=IncludeTest;Integrated Security=True");
    }
}
```

With this setup, I'm not able to use `Include` after I applied `Union`:

```C#
var list = ctx.Bars
    .Union(ctx.Bars)
    .Include(b => b.Foo)
    .ToList();

// items will have null Foo, even though the associated entity is present
```

This will work if `Include()` is used before `Union()`, but this workaround is less than ideal, when I want the queryable to be reusable and only care about fetching the association in specific cases.

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.9.3

### LINKED ISSUE #16165: Only 1 entity materalized although generated SQL returns more rows
While working on set operations, I ran into a situation where generated SQL properly fetches 7 customers, but only one gets materialized. This can be reproduce with test Union_Include from https://github.com/roji/EntityFrameworkCore/tree/StateOfTheUnion.

Related to #15611 which generally tracks materialization.

/cc @maumar who already did some investigation on this.

### PR DESCRIPTION
**Pull request by roji**
* Include/nav rewriting is now supported.
* We now push down to subquery when OrderBy, Take or Skip are applied to set operations, to avoid using the hack where ColumnExpression with no table alias was used. #16244 was opened to track for post-3.0.
* Added missing support for union over subselect projection mappings.
* Added Other type to SetOperationType so that providers can define extra set operations (e.g. PostgreSQL `INTERSECT ALL`, `EXCEPT ALL`).

Completes #6812
Fixes #13196
Fixes #16065
Fixes #16165

### CODE REVIEW

File: src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs [hunk 1]
```diff
@@ -394,98 +398,17 @@ public void ClearOrdering()
...
-                             {
-                                 throw new Exception("Non-entity shaper expression while handling set operation over siblings.");
-                             }
-
-                             shaperExpression = new EntityShaperExpression(
-                                 commonParentEntityType, entityShaperExpression.ValueBufferExpression, entityShaperExpression.Nullable);
-                         }
-
-                         continue;
+                        HandleEntityMapping(joinedMapping.Key, select1, entityProjection1, select2, entityProjection2);
```
Comment (roji) [inline src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs]: Just a refactor here to make the method smaller.

File: src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs [hunk 2]
```diff
@@ -504,7 +427,97 @@ public void ClearOrdering()
...
+                         select1, null,
+                         select2, null);
+                 }
+
+                 _projectionMapping[projectionMember] = new EntityProjectionExpression(commonParentEntityType, propertyExpressions);
+
+                 if (commonParentEntityType != projection1.EntityType)
+                 {
+                     // The first source has been up-cast by the set operation, so we also need to change the shaper expression.
+                     var entityShaperExpression =
```
Comment (roji) [inline src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs]: @smitpatel I know remove the cast only if it was casting to our common parent type, for which we're setting the new shaper anyway. This code doesn't handle all cases - it's possible there will be two cast nodes, in which case this will not work (but I've seen this pattern in other places in the code). I'm still not exactly sure what we expect to happen, but this may be enough for now. Let me know if you want us to do something else here.

File: src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs [hunk 3]
```diff
@@ -1304,7 +1332,12 @@ public enum SetOperationType
         /// <summary>
         /// Represents an SQL EXCEPT set operation.
         /// </summary>
-        Except    = 4
+        Except    = 4,
+
+        /// <summary>
+        /// Represents a custom, provider-specific set operation.
+        /// </summary>
+        Other     = 9999
```
Comment (roji) [inline src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs]: PostgreSQL has `INTERSECT ALL` and `EXCEPT ALL`, this would allow me to implement that.

File: src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs [hunk 4]
```diff
@@ -35,74 +35,84 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
                     : methodCallExpression.Update(methodCallExpression.Object, new[] { newSource, methodCallExpression.Arguments[1] });
             }
 
-            switch (methodCallExpression.Method.Name)
+            if (methodCallExpression.Method.DeclaringType == typeof(Queryable)
```
Comment (roji) [inline src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs]: I actually ran into an error because NetTopologySuite's Union was wrongly recognized here :)

Comment (maumar) [reply src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs]: I was thinking to eventually use actual methodinfos for matching, but this should be good, at least for now. There are actually some places e.g. in ProcessJoin that prevented functions with the same name from being matched. You can clean it up if u want, or I can do it later

Comment (smitpatel) [reply src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs]: Using actual methodInfos for method from Queryable/Enumerable has low value. If they add more things to those classes, there are pretty drastic reactions outside of the scope of EF Core. So I think it is safe to assume that if method defined on those classes, name matching is sufficient. (Even overloads won't be added). I know it is not 100% fail-safe code but it is YAGNI.

File: src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs [hunk 5]
```diff
@@ -853,6 +863,27 @@ private Expression ProcessSkipTake(MethodCallExpression methodCallExpression)
...
+            var preProcessResult1 = PreProcessTerminatingOperation(source1);
+
+            var source2 = VisitSourceExpression(methodCallExpression.Arguments[1]);
+            var preProcessResult2 = PreProcessTerminatingOperation(source2);
+
+            // If the siblings are different types, one is derived from the other the set operation returns the less derived type.
+            // Find that.
+            var clrType1 = preProcessResult1.state.CurrentParameter.Type;
+            var clrType2 = preProcessResult2.state.CurrentParameter.Type;
+            var parentState = clrType1.IsAssignableFrom(clrType2) ? preProcessResult1.state : preProcessResult2.state;
```
Comment (maumar) [inline src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs]: this way we only propagate include information applied on less derived type. e.g. 
customers.Include(c => c.Nav1).Concat(customers.OfType<VipCustomers>().Include(c => c.Nav2)), we would end up including only Nav1. We either need to merge include information (which is embedded in NavigationTreeNode on the NavigationExpansionState) or detect when the include paths on both sides are different and throw - can probably be done in a future PR as the scenario is somewhat contrived.

File: src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs (hunk 4 above)
Comment (maumar) [reply src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs]: agreed, the longer I see @roji 's solution the more I like it

File: src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs (hunk 5 above)
Comment (maumar) [reply src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs]: you can use IncludeHelpers.CopyIncludeInformation

File: test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs [hunk 6]
```diff
@@ -162,5 +161,45 @@ public virtual Task Select_Union_different_fields_in_anonymous_with_subquery(boo
...
+            => AssertQuery<Customer>(isAsync, cs => cs
+                .Where(c => c.City == "Berlin")
+                .Union(cs.Where(c => c.City == "London"))
+                .Include(c => c.Orders),
+                entryCount: 59);
+
+        [ConditionalTheory]
+        [MemberData(nameof(IsAsyncData))]
+        public virtual Task Include_Union(bool isAsync)
+            => AssertQuery<Customer>(isAsync, cs => cs
```
Comment (maumar) [inline test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs]: add test where we do union on reference projections, e.g. order.Select(o => o.Customer).Except(order.Where(o => o.CustomerID == "ALFKI).Select(o => o.Customer)

Comment (maumar) [reply test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs]: also case like weapons.Union(weapon.Select(w => w.SynergyWith)), in gears of war model - where the clr type is the same, but one has nav expansion, one doesnt

File: src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs [hunk 7]
```diff
@@ -370,11 +371,14 @@ public void ClearOrdering()
...
 
+            select1._identifyingProjection.AddRange(_identifyingProjection);
+            _identifyingProjection.Clear();
+
             var select2 = otherSelectExpression;
 
             if (_projection.Any())
             {
-                throw new NotImplementedException("Set operation on SelectExpression with populated _projection");
+                throw new NotSupportedException("Can't process set operations after client evaluation, consider moving the operation before the last Select() call (see issue #16243)");
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs]: Which exception type to use? @ajcvickers 
We had some recent discussion around this but I don't remember the outcome.

File: src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs [hunk 8]
```diff
@@ -504,7 +427,97 @@ public void ClearOrdering()
...
+                             shaperExpression is UnaryExpression unary
+                             && unary.NodeType == ExpressionType.Convert
+                             && unary.Type == commonParentEntityType.ClrType
+                                 ? unary.Operand as EntityShaperExpression : null);
+
+                     if (entityShaperExpression != null)
+                     {
+                         shaperExpression = new EntityShaperExpression(
+                             commonParentEntityType, entityShaperExpression.ValueBufferExpression, entityShaperExpression.Nullable);
+                     }
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs]: What is else result? Just ignore?

File: src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs [hunk 9]
```diff
@@ -680,11 +714,10 @@ public RelationalCollectionShaperExpression ApplyCollectionJoin(int collectionId
             var (outer, inner) = TryExtractJoinKey(innerSelectExpression);
             if (outer != null)
             {
-                if (IsDistinct
-                   || Limit != null
-                   || Offset != null)
+                if (IsDistinct || Limit != null || Offset != null || IsSetOperation)
                 {
-                    outer = new SqlRemappingVisitor(PushdownIntoSubquery()).Remap(outer);
+                    var pushdown = PushdownIntoSubquery();
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs]: Inline variable

File: src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs (hunk 3 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs]: Let's think about a different solution to represent set operation then. We are including multiple different patterns. Our common pattern so far has been custom expressions in tree rather than enum.

Comment (roji) [reply src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs]: This was one of the reasons that in the beginning I was thinking of a different type for set operations (instead of SelectExpression), but that's not compatible with our architecture.

Scoping this out to #16273 so we get this PR merged - will remove the Other enum member.

File: src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs (hunk 4 above)
Comment (roji) [reply src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs]: I agree using MethodInfos has low value, as the probability of change there is limited. However, we just had the incident where adding overloads to DbDataReader made us break entirely - I'm sure we had the same logic when we wrote that reflection code :) We're trying to push for LINQ/expression trees to start making progress again, so it's not totally inconceivable for overloads to be added.

There also isn't much cost to just using MethodInfos, plus we already have one centralized place where these are available (LinqMethodHelpers). We could do a pass (post-3.0) on the entire codebase at some point and simply switch to MethodInfos to future-proof the product. 

Unless you guys object I can open an issue to track.

File: src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs (hunk 5 above)
Comment (roji) [reply src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs]: Yeah, I thought about this a bit. I *think* that trying to do a set operation with differing includes should throw, since merging includes doesn't correspond to the presumed user expectation, which would be to only include each nav the set operand it's specified. This can't be done in SQL (i.e. unless we fetch the information and don't materialize it).

If users want merged includes, they can simply write the following themselves:

```sql
customers.Union(customers.OfType<...>())
    .Include(c => c.Nav1)
    .Include(c => c.Nav2)
```

We may want to discuss this in design (@divega @ajcvickers). For now I've implemented a NotSupportedException for this (@maumar hope you can take a look to make sure I did it right).

File: test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs (hunk 6 above)
Comment (roji) [reply test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs]: OK on the first.

For the second, the SQL produced seems good:

```c#
SELECT [w].[Id], [w].[AmmunitionType], [w].[IsAutomatic], [w].[Name], [w].[OwnerFullName], [w].[SynergyWithId]
FROM [Weapons] AS [w]
UNION
SELECT [w0].[Id], [w0].[AmmunitionType], [w0].[IsAutomatic], [w0].[Name], [w0].[OwnerFullName], [w0].[SynergyWithId]
FROM [Weapons] AS [w1]
LEFT JOIN [Weapons] AS [w0] ON [w1].[SynergyWithId] = [w0].[Id]
```

However, it's a left outer join and not an inner one (because SynergyWith is optional), so we get back rows with null IDs and materialization fails. I think that with a required relationship it would work fine, but SQL Server doesn't allow me to do that for testing (cycle).

We should maybe be handling this case, i.e. filter on non-null when doing projection via optional entity?

File: src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs (hunk 9 above)
Comment (roji) [reply src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs]: Sorry, debugging thing which slipped in.

File: src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs (hunk 8 above)
Comment (roji) [reply src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs]: OK, I went with a different approach - I now replace the EntityShaperExpression, and if it's wrapped by Convert nodes I recreate those exactly as they previously were. It's effectively as if the entity was originally queried as a less derived type as what it is.

Sorry this part is taking so many iterations, please let me know if it's still not the way you want - I still don't feel like I understand all the possibilities here 100%.

**Comment by roji** [comment]
Pushed a new commit with various fixes.

File: src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs (hunk 4 above)
Comment (smitpatel) [reply src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs]: I still consider it YAGNI.

File: test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs (hunk 6 above)
Comment (maumar) [reply test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs]: I don't think we should filter, when you just project the optional, i.e. weapons.Select(w => w.SynergyWith) we would materialize nulls rather than filter them. I'd expect similar effect for set ops.

Sql we produce for simple optional projection is:

```
SELECT [w].[Id], [w].[AmmunitionType], [w].[IsAutomatic], [w].[Name], [w].[OwnerFullName], [w].[SynergyWithId]
FROM [Weapons] AS [w0]
LEFT JOIN [Weapons] AS [w] ON [w0].[SynergyWithId] = [w].[Id]
```

and we also have null keys, but materialization doesn't fail. Something seems wrong in the set case.

Comment (roji) [reply test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs]: So it's expected to be fine to materialize entities with null keys? Wasn't aware of that...

Here's the test I was using:

```c#
[ConditionalFact]
public virtual void Union_with_self_projection()
{
    using (var ctx = CreateContext())
    {
        var query = ctx.Weapons.Union(ctx.Weapons.Select(w => w.SynergyWith));
        //var query = ctx.Weapons.Union(ctx.Weapons);
        var result = query.ToList();
    }
}
```

Comment (smitpatel) [reply test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs]: When key values are expected to be null in projection (generally appears from doing a left join and right side can be null, but there can be other cases), translation pipeline is supposed to mark entity Shaper as nullable. If entityShaper is nullable then when reading null key values, it will give null back rather than materializing object. (If entity shaper is not marked nullable then it will throw exception)

Comment (maumar) [reply test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs]: yup, it should work

Comment (roji) [reply test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs]: I see... that makes sense, was not aware - the exception was indeed an unexpected null in DbDataReader.

So this means we need to update the shaper for this when a set operation is performed? Any pointers to where/how I'd do that?

Comment (roji) [reply test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs]: I'll investigate some more - will try to find it.

File: src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs (hunk 7 above)
Comment (ajcvickers) [reply src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs]: @divega?

File: src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs [hunk 10]
```diff
@@ -853,6 +864,56 @@ private Expression ProcessSkipTake(MethodCallExpression methodCallExpression)
...
+            var preProcessResult1 = PreProcessTerminatingOperation(source1);
+
+            var source2 = VisitSourceExpression(methodCallExpression.Arguments[1]);
+            var preProcessResult2 = PreProcessTerminatingOperation(source2);
+
+            // Compare the include chains from each side to make sure they're identical. We don't allow set operations over
+            // operands with different include chains.
+            var current1 = preProcessResult1.state.PendingIncludeChain?.NavigationTreeNode;
+            var current2 = preProcessResult2.state.PendingIncludeChain?.NavigationTreeNode;
+            while (true)
```
Comment (maumar) [inline src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs]: rather than comparing from mappings you should compare navigations. You can re-use PendingIncludeFindingVisitor - run it on the pendingSelector of both preProcessResult.state. Those return PendingIncludes - mapping between navigationtreenode (from which you can extract the actual INavigation of the include) and the source mapping where it originated from. You can compare those structures for both sources and if they are the same, we are good, if they are different - throw. There could be multiple SourceMappings for each source (e.g. when we had a join before), so you need to figure out which SourceMapping from one source corresponds to which mapping from the other source, and then compare Navigations found by the visitor that are associated with them.

Also, the visitor currently short-circuits for collection includes, but you probably want to include them in the check, so you might want to add a flag to the visitor, and if the flag is set ignore this check:

```
            if (node.Navigation != null && node.Navigation.IsCollection())
            {
                return;
            }
```

**Comment by smitpatel** [comment]
If navigation part of set operation is going to take time then can we split out, push down for order by in separate PR and get it merged sooner?

**Comment by smitpatel** [comment]
Also set operations with fromsql.

File: src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs (hunk 7 above)
Comment (divega) [reply src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs]: I don't remember that discussion :smile: But I am leaning towards NotImplementedException and simplifying the message, but that is because I think #16243 is by design (of course I could be wrong and I may need someone to explain to me why it isn't).

Comment (divega) [reply src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs]: FYI, I created https://go.microsoft.com/fwlink/?linkid=2097910 for exceptions we throw when something would require client evaluation. We tweak what it points to in the future.

File: src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs (hunk 4 above)
Comment (divega) [reply src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs]: I agree with @roji. This kind of break has actually happened more than once and we already decided before to make sure when we obtain method infos we do it with a very targeted condition. AFAIR we already did a pass once (though on the old query pipeline) to improve what we had. Let's not overturn that unless there is a good reason.

**Comment by roji** [comment]
> If navigation part of set operation is going to take time then can we split out, push down for order by in separate PR and get it merged sooner?

I'm going to take a quick stab at it - I have to leave very soon anyway.

In any case I will look at it later tonight. @smitpatel, maybe comment on what you consider OK (e.g. there's still the convert nodes when replacing the EntityShaperExpression). If necessary I can split out the problematic parts.

Finally, even if the PR isn't perfect as-is, we can also decide to merge and I'll fix anything right afterwards (i.e. tomorrow during my day). Up to you.

**Comment by smitpatel** [comment]
```
private ColumnExpression(string name, TableExpressionBase table, Type type, RelationalTypeMapping typeMapping, bool nullable)
            : base(type, typeMapping)
        {
// Add this line
            Check.NotEmpty(Table.Alias);
            Name = name;
            Table = table;
            Nullable = nullable;
        }
```
Fix whatever fails with that, (disable/pushdown). (Apparently this PR does not update code about null check). Split out that part.

File: src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs (hunk 4 above)
Comment (roji) [reply src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs]: Opened #16300 to track.

File: test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs (hunk 6 above)
Comment (roji) [reply test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.SetOperations.cs]: Scoping out to #16301

File: src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs (hunk 10 above)
Comment (roji) [reply src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs]: Have done this as discussed, will push soon.

File: src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs (hunk 7 above)
Comment (roji) [reply src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs]: @divega I don't have the full picture, but @smitpatel seemed to indicate this should be possible by us moving the union before the client evaluation.

I'm leaning towards NotSupportedException (in the sense of not supported in this version), or to a less extent NotImplementedException (although that's usually used as a very temporary marker for a dev to remember they still have to do something). InvalidOperationException seems used more because an object is in a wrong state, which doesn't seem to be the case here.

However, I'm changing to InvalidOperationException for now we we really want this PR to get merged in time for preview7.

**Comment by roji** [comment]
@smitpatel, removed support entirely for set operations over operands of different entity types - scoped this out to #16298 (this is what the ColumnExpression was for). We can look at this later, hopefully (but not 100% necessarily for 3.0).

@maumar implemented the better way to compare includes on both sides, you can take a look.

Let's try to get it into preview7.

File: test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs [hunk 11]
```diff
@@ -22,21 +22,6 @@ namespace Microsoft.EntityFrameworkCore.Query
 {
     public abstract partial class SimpleQueryTestBase<TFixture>
     {
-        [ConditionalTheory(Skip = "Issue #6812. Cannot eval 'Union({from Customer c in value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Microsoft.EntityFrameworkCore.TestModels.Northwind.Customer]) where [c].CompanyName.StartsWith(\"B\") select [c]})'")]
```
Comment (AndriySvyryd) [inline test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs]: Please skip these and the new tests for Cosmos

Comment (roji) [reply test/EFCore.Specification.Tests/Query/SimpleQueryTestBase.ResultOperators.cs]: No problem, will skip all set operation tests for now.

File: src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs [hunk 12]
```diff
@@ -853,6 +864,57 @@ private Expression ProcessSkipTake(MethodCallExpression methodCallExpression)
...
+
+            var source1 = VisitSourceExpression(methodCallExpression.Arguments[0]);
+            var preProcessResult1 = PreProcessTerminatingOperation(source1);
+
+            var source2 = VisitSourceExpression(methodCallExpression.Arguments[1]);
+            var preProcessResult2 = PreProcessTerminatingOperation(source2);
+
+            // Extract the includes from each side and compare to make sure they're identical.
+            // We don't allow set operations over operands with different includes.
+            var pendingIncludeFindingVisitor = new PendingIncludeFindingVisitor(false);
```
Comment (maumar) [inline src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs]: nit - "skipCollectionNavigations:"

File: src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs [hunk 13]
```diff
@@ -853,6 +864,57 @@ private Expression ProcessSkipTake(MethodCallExpression methodCallExpression)
...
+            pendingIncludeFindingVisitor.Visit(preProcessResult1.state.PendingSelector.Body);
+            var pendingIncludes1 = pendingIncludeFindingVisitor.PendingIncludes;
+
+            pendingIncludeFindingVisitor = new PendingIncludeFindingVisitor(false);
```
Comment (maumar) [inline src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs]: same here

File: src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs [hunk 14]
```diff
@@ -853,6 +864,57 @@ private Expression ProcessSkipTake(MethodCallExpression methodCallExpression)
...
+
+                if (i1.NavTreeNode.Flatten()
+                    .Zip(i2.NavTreeNode.Flatten(), (n1, n2) => (First: n1, Second: n2))
+                    .Any(nodes => nodes.First.Navigation != nodes.Second.Navigation))
+                {
+                    throw new NotSupportedException(CoreStrings.SetOperationWithDifferentIncludesInOperands);
+                }
+            }
+
+            // If the siblings are different types, one is derived from the other the set operation returns the less derived type.
```
Comment (maumar) [inline src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs]: should we throw instead, because of #16298?

**Comment by maumar** [comment]
@roji nav rewrite changes look good!

File: src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs [hunk 15]
```diff
@@ -853,6 +864,57 @@ private Expression ProcessSkipTake(MethodCallExpression methodCallExpression)
...
+            }
+
+            foreach (var (i1, i2) in pendingIncludes1.Zip(pendingIncludes2, (i1, i2) => (i1, i2)))
+            {
+                if (i1.SourceMapping.RootEntityType != i2.SourceMapping.RootEntityType)
+                {
+                    throw new NotSupportedException(CoreStrings.SetOperationWithDifferentIncludesInOperands);
+                }
+
+                if (i1.NavTreeNode.Flatten()
```
Comment (maumar) [inline src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs]: actually it should be enough to compare Navigation on each NavTreeNode, no need to flatten and compare all of them - we are doing the same work multiple times

Comment (maumar) [reply src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs]: FindPendingReferenceIncludes already goes thru all the child nodes recursively, so we get an entry in PendingIncludes list for each navigation that is marked for include

File: src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs (hunk 7 above)
Comment (divega) [reply src/EFCore.Relational/Query/Pipeline/SqlExpressions/SelectExpression.cs]: Ah, I see. That is a good idea. I guess it would only about lifting the client eval part and not the actual projection, because lifting the projection over Union() would not be correct in all cases. I personally would love to do something when we can, but I suspect it is going to take some time for this to get to the top of the list. 

Re the exception type, I actually don't feel strongly about which one would be the most correct to throw, but what I heard from @ajcvickers and @smitpatel is that keeping the set of exception types customers should catch beats being absolutely correct.

File: src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs (hunk 14 above)
Comment (roji) [reply src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs]: We'd throw anyway from SelectExpression.ApplySetOperation(). I can really remove all trace of different siblings, but it doesn't seem really worth it (I hope we'll manage to fix it soon anyway) - let me know if you feel strongly.

File: src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs (hunk 15 above)
Comment (roji) [reply src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs]: OK, made the change - still don't have a good mental model of everything there. Thanks!

**Comment by roji** [comment]
Addressed @maumar's comments and rebased on latest master.

**Comment by smitpatel** [comment]
Can you split out PR in 2 parts?
- Fixing issue with Table without alias
- Nav expansion part of set operations

Since @maumar  is gone for vacation, it may take some time to understand nav expansion changes.

File: src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs (hunk 14 above)
Comment (maumar) [reply src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor_MethodCall.cs]: It’s fine as is, just a suggestion/observation

**Comment by roji** [comment]
Done, this PR now only fixes the ColumnExpression alias issue. Once it's merged I'll submit a separate one for nav/include support.
