### PR TITLE
Further improve model building performance

### LINKED ISSUE #9347: Large DbContext Startup Time and View Generation
Describe what is not working as expected.

Large DbContext (1000) tables takes about 40 seconds before the first query.  Any plans to add view generation at build time to EF Core, just like EF 6 has?
Thanks.

### Further technical details
EF Core version: 1.0.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Cache property and field infos
Memoize DisplayName() for Type
Call Attribute.IsDefined before GetCustomAttributes()
Use in parameters for TypeMappingInfo and RelationalTypeMappingInfo
Implement IEquatable<T> on TypeMappingInfo and RelationalTypeMappingInfo

Fixes #9347

### CODE REVIEW

File: src/EFCore/Metadata/Conventions/Internal/NavigationAttributeEntityTypeConvention.cs [hunk 1]
```diff
@@ -183,27 +177,25 @@ public virtual bool Apply(InternalEntityTypeBuilder entityTypeBuilder, EntityTyp
...
         {
             var navigationPropertyInfo =
-                entityTypeBuilder.Metadata.ClrType.GetRuntimeProperties().FirstOrDefault(p => p.Name == ignoredMemberName);
+                entityTypeBuilder.Metadata.GetRuntimeProperties()?.Find(ignoredMemberName);
             if (navigationPropertyInfo == null)
             {
                 return true;
             }
 
             var targetClrType = FindCandidateNavigationPropertyType(navigationPropertyInfo);
```
Comment (smitpatel) [inline src/EFCore/Metadata/Conventions/Internal/NavigationAttributeEntityTypeConvention.cs]: Could DRY this with if condition in a private function

File: src/EFCore/Metadata/Conventions/Internal/PropertyMappingValidationConvention.cs [hunk 2]
```diff
@@ -58,73 +58,80 @@ public virtual InternalModelBuilder Apply(InternalModelBuilder modelBuilder)
...
+
+                if (clrProperties.Count <= 0)
+                {
+                    continue;
+                }
 
-                    if (clrProperties.Count > 0)
+                foreach (var clrProperty in clrProperties)
+                {
+                    var actualProperty = entityType.GetRuntimeProperties().Find(clrProperty);
```
Comment (smitpatel) [inline src/EFCore/Metadata/Conventions/Internal/PropertyMappingValidationConvention.cs]: Do we need `Find` here since it was `First` earlier? Direct key access?
