### PR TITLE
SqlServer Spatial: Enable calling methods on parameterized values

### LINKED ISSUE #14595: SqlServer Spatial: Cannot call methods on varbinary
### Issue
SqlException when testing if a polygon contains a point.

I have a table in the database called Address with a Location column (of GEOGRAPHY data type). The goal is (ultimately) for a user to draw a boundary polygon on a map and the database query will return all records where the Location is within the polygon. However I'm seeing the following exception when executing the code.

```
Exception message:
   System.Data.SqlClient.SqlException: 'Cannot call methods on varbinary.'
Stack trace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EfCoreSpatialData.Program.Test01() in C:\Dev\Demos\EfCoreSpatialData\EfCoreSpatialData\Program.cs:line 52
   at EfCoreSpatialData.Program.Main(String[] args) in C:\Dev\Demos\EfCoreSpatialData\EfCoreSpatialData\Program.cs:line 17
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

Program.cs
```c#
using System;
using System.Collections.Generic;
using System.Linq;
using GeoAPI.Geometries;
using Microsoft.EntityFrameworkCore;
using NetTopologySuite.Geometries;

namespace EfCoreSpatialData
{
    class Program
    {
        private static SpatialDataContext dataContext;

        static void Main(string[] args)
        {
            SetDataContext();
            Test01();
            Console.WriteLine("Press ENTER to continue.");
            Console.ReadLine();
        }

        private static void Test01()
        {

            Point addressLocation = new Point(-4, 55)
            {
                SRID = 4326
            };

            List<Coordinate> searchCoordinates = new List<Coordinate>
            {
                new Coordinate(-5, 56),
                new Coordinate(-3, 56),
                new Coordinate(-3, 54),
                new Coordinate(-5, 54),
                new Coordinate(-5, 56)
            };

            Coordinate[] searchCoordinatesArray = searchCoordinates.ToArray();
            LinearRing searchLinearRing = new LinearRing(searchCoordinatesArray);
            Polygon searchPolygon = new Polygon(searchLinearRing)
            {
                SRID = 4326
            };

            IGeometry searchGeometry = searchPolygon.Normalized().Reverse();
            searchGeometry.SRID = 4326;

            bool locationIsInSearchPolygon = searchGeometry.Contains(addressLocation);
            Console.WriteLine(locationIsInSearchPolygon); // This is true.
            
            List<Address> addresses = dataContext.Addresses.Where(x => searchGeometry.Contains(x.Location)).ToList(); // This throws System.Data.SqlClient.SqlException: 'Cannot call methods on varbinary.'
            foreach (var address in addresses)
            {
                Console.WriteLine(address.Line1);
            }
        }

        private static void SetDataContext()
        {
            var optionsBuilder = new DbContextOptionsBuilder<SpatialDataContext>();
            var connectionString = "Server=.;Database=Spatial;Trusted_Connection=True;";
            optionsBuilder.UseSqlServer(connectionString, options => options.UseNetTopologySuite());
            dataContext = new SpatialDataContext(optionsBuilder.Options);
        }
    }
}
```

Address.cs
```c#
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using NetTopologySuite.Geometries;

namespace EfCoreSpatialData
{
    [Table(name: nameof(Address))]
    public class Address
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        public string Line1 { get; set; }

        public string Line2 { get; set; }

        public string Line3 { get; set; }

        public string Line4 { get; set; }

        public string Postcode { get; set; }

        public Point Location { get; set; }
    }
}

```
SpatialDataContext.cs
```c#
using Microsoft.EntityFrameworkCore;

namespace EfCoreSpatialData
{
    public class SpatialDataContext : DbContext
    {
        public SpatialDataContext(DbContextOptions<SpatialDataContext> options)
            : base(options)
        { }

        public DbSet<Address> Addresses { get; set; }
    }
}
```

```sql
USE [Spatial]
GO
/****** Object:  Table [dbo].[Address]    Script Date: 03/02/2019 23:29:46 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Address](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Line1] [nvarchar](50) NULL,
	[Line2] [nvarchar](50) NULL,
	[Line3] [nvarchar](50) NULL,
	[Line4] [nvarchar](50) NULL,
	[Postcode] [nvarchar](50) NULL,
	[Location] [geography] NULL,
 CONSTRAINT [PK_Address] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
```

Source solution also available at: https://gitlab.com/stuartwhiteford/efcorespatialdata

The SQL generated is as follows:

```sql
exec sp_executesql N'SELECT [x].[Id], [x].[Line1], [x].[Line2], [x].[Line3], [x].[Line4], [x].[Location], [x].[Postcode]
FROM [Address] AS [x]
WHERE @__searchGeometry_0.STContains([x].[Location]) = 1',N'@__searchGeometry_0 varbinary(112)',@__searchGeometry_0=0xE61000000104050000000000000000004B4000000000000014C00000000000004B4000000000000008C00000000000004C4000000000000008C00000000000004C4000000000000014C00000000000004B4000000000000014C001000000020000000001000000FFFFFFFF0000000003
```

but the following DOES work:

```sql
exec sp_executesql N'SELECT [x].[Id], [x].[Line1], [x].[Line2], [x].[Line3], [x].[Line4], [x].[Location], [x].[Postcode]
FROM [Address] AS [x]
WHERE @__searchGeometry_0.STContains([x].[Location]) = 1',N'@__searchGeometry_0 geography',@__searchGeometry_0=0xE61000000104050000000000000000004B4000000000000014C00000000000004B4000000000000008C00000000000004C4000000000000008C00000000000004C4000000000000014C00000000000004B4000000000000014C001000000020000000001000000FFFFFFFF0000000003
```

### Further technical details
EF Core version: 2.2.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer 2.2.1
Using: Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite 2.2.1
Operating system: Windows 10 Pro - Version 1803 - OS Build 17134.523
IDE: (e.g. Visual Studio 2017 15.9.6)

### PR DESCRIPTION
**Pull request by bricelam**
Fixes #14595

~~@divega Looks like dotnet/corefx#36678 isn't in Microsoft.Data.SqlClient. Tests pass after reverting 10e553acc21f495e1bbdb384b90ac0a6e334f5ff~~ (resolved)

### CODE REVIEW

File: test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs [hunk 1]
```diff
@@ -248,12 +248,23 @@ public override async Task Distance_on_converted_geometry_type(bool isAsync)
...
 
+        public override async Task Distance_on_converted_geometry_type_lhs(bool isAsync)
+        {
+            await base.Distance_on_converted_geometry_type_lhs(isAsync);
+
+            AssertSql(
+                @"@__point_0='0xE6100000010C000000000000F03F0000000000000000' (Nullable = false) (Size = 22) (DbType = Object)
+
+SELECT [g].[Id], @__point_0.STDistance([g].[Location]) AS [Distance]
+FROM [GeoPointEntity] AS [g]");
```
Comment (bricelam) [inline test/EFCore.SqlServer.FunctionalTests/Query/SpatialQuerySqlServerGeographyTest.cs]: 🎉 @Wraith2 you rock!

**Comment by bricelam** [comment]
Unblocked by #16527 🎉
