### PR TITLE
Query: Allow WithTag API on IQueryable of primitive types

### LINKED ISSUE #13326: WithTag and simple value projection
`WithTag` can't be used with simple type projection because of an compiler error.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: The Type "DateTime" must be a reference type to ba a genric TEntity-parameter used by "EntityFrameworkQueryableExtensions.WithTag<TEntity>(IQueryable<TEntity>, string)"
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
var dataQuery =
    from data in model.Datas
    where data.Timestamp >= begin
    && data.Timestamp < end
    select data.Timestamp;

var dataResult = dataQuery
     .WithTag("MyTag")
    .ToList();
```

### Further technical details
EF Core version: 2.2.0-preview2-35157
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 15.4

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #13326

### CODE REVIEW

File: src/EFCore/EntityFrameworkQueryableExtensions.cs [hunk 1]
```diff
@@ -2603,7 +2603,6 @@ IAsyncEnumerator<TEntity> IAsyncEnumerable<TEntity>.GetEnumerator()
         /// </returns>
         public static IQueryable<TEntity> WithTag<TEntity>(
             [NotNull] this IQueryable<TEntity> source, [NotNull] [NotParameterized] string tag)
```
Comment (ajcvickers) [inline src/EFCore/EntityFrameworkQueryableExtensions.cs]: The generic parameter should not be `TEntity` since it's not necessarily an entity. I would use just `T`. @divega?
