### PR TITLE
Query: Convert Enumerable methods to queryable specified after ToList…

### LINKED ISSUE #19059: Query: Allow AsEnumerable in subquery
According to #16314 Queryables/DbSet cannot be returned in anonymous projection due to type mismatch. Correct way to write it would be ToList/ToArray at the end of subquery. We could also allow AsEnumerable. (Internally we create list anyway)

### LINKED ISSUE #19060: Query: Translation of ToList().Count does not work in all cases
We have code to convert such member access to Count() query.
For case like #9751 adding ToList in projection and then doing Where with Count fails with client eval error.

### PR DESCRIPTION
**Pull request by smitpatel**
…/ToArray/AsEnumerable

- Convert all enumerable methods to queryable unless specified on query parameter (coming from closure)
- Convert ICollection<T>.Count to Queryable.Count<T>()
- Simplify (Queryable/CollectionNav/OwnedCollectionNav).(ToList/ToArray/AsEnumerable).AsQueryable to underlying queryable
- Remove MaterializeCollectionNavigation when ToList/ToArray is called on collection navigation.
- Convert Array.Length to Queryable.Count<T>()

Resolves #19059
Resolves #19060

### CODE REVIEW

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs [hunk 1]
```diff
@@ -543,6 +516,20 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
                 return methodCallExpression.Update(null, new[] { argument });
             }
 
+            if (typeof(IEnumerable).IsAssignableFrom(method.DeclaringType)
+                && string.Equals("ToArray", method.Name, StringComparison.Ordinal))
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs]: This is somewhat fuzzy match since many collection types define ToArray method on it which is not on any interface (like `ICollection<T>.Count`). It could match a `ToArray` method defined on a user defined collection type which may or may not be correct always. But doing this helps more scenarios than hurt one particular scenario.

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs [hunk 2]
```diff
@@ -150,24 +151,18 @@ protected override Expression VisitMember(MemberExpression memberExpression)
 
             var innerExpression = Visit(memberExpression.Expression);
 
-            // Convert CollectionNavigation.Count to subquery.Count()
-            if (innerExpression is MaterializeCollectionNavigationExpression materializeCollectionNavigation
-                && memberExpression.Member.Name == nameof(List<int>.Count))
+            // Convert ICollection<T>.Count to Count<T>()
+            if (memberExpression.Expression != null
```
Comment (maumar) [inline src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs]: consider DRYing along with core TypeExtensions.IsQueryableType

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs (hunk 1 above)
Comment (maumar) [reply src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs]: I'm not a fan of ducktyping in here - we could just handle well knows types, like ICollection, and throws for anything else. Thoughts? @roji @AndriySvyryd @ajcvickers

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs (hunk 2 above)
Comment (smitpatel) [reply src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs]: If this gets used before will do otherwise very marginal value.

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs (hunk 1 above)
Comment (smitpatel) [reply src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs]: Removed. I believe it provides enough value considering correct match would be much higher than incorrect match. And work-around if this does something which is not expected is easy enough.

But I don't care enough to fight it.
