### PR TITLE
[2.1] Metadata: Fix for calling OwnsOne on navigation which implements ICol…

### LINKED ISSUE #11688: Calling OwnsOne on navigation which implements ICollection throws NullRef
Using a complex type did work with `2.1.0-preview1-final` but broke with the latest preview.

Exception message:
`Object reference not set to an instance of an object.`
Stack trace:
```
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.FindRelationshipCandidates(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.DiscoverRelationships(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.Apply(EntityType entityType, MemberInfo navigationProperty)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.Apply(InternalEntityTypeBuilder sourceEntityTypeBuilder, InternalEntityTypeBuilder targetEntityTypeBuilder, String navigationName, MemberInfo propertyInfo)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnNavigationRemoved(InternalEntityTypeBuilder sourceEntityTypeBuilder, InternalEntityTypeBuilder targetEntityTypeBuilder, String navigationName, MemberInfo memberInfo)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.RunVisitor.VisitOnNavigationRemoved(OnNavigationRemovedNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.OnNavigationRemovedNode.Accept(ConventionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.Visit(ConventionNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(ConventionScope node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionScope.Accept(ConventionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.Visit(ConventionNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(ConventionScope node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionScope.Accept(ConventionVisitor visitor)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.Visit(ConventionNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(ConventionScope node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Dispose()
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.OwnsOneBuilder[TRelatedEntity](PropertyInfo navigation)
   at Microsoft.EntityFrameworkCore.Metadata.Builders.EntityTypeBuilder`1.OwnsOne[TRelatedEntity](Expression`1 navigationExpression)
   at NullReferenceAtFindRelationshipCandidates.DatabaseContext.<>c.<OnModelCreating>b__1_0(EntityTypeBuilder`1 e) in c:\users\alexander.herold.accenon\source\repos\NullReferenceAtFindRelationshipCandidates\NullReferenceAtFindRelationshipCandidates\DatabaseContext.cs:line 19
   at Microsoft.EntityFrameworkCore.ModelBuilder.Entity[TEntity](Action`1 buildAction)
   at NullReferenceAtFindRelationshipCandidates.DatabaseContext.OnModelCreating(ModelBuilder modelBuilder) in c:\users\alexander.herold.accenon\source\repos\NullReferenceAtFindRelationshipCandidates\NullReferenceAtFindRelationshipCandidates\DatabaseContext.cs:line 17
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelCustomizer.Customize(ModelBuilder modelBuilder, DbContext context)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.CreateModel(DbContext context, IConventionSetBuilder conventionSetBuilder, IModelValidator validator)
   at Microsoft.EntityFrameworkCore.Infrastructure.ModelSource.<>c__DisplayClass5_0.<GetModel>b__1()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
```

### Steps to reproduce
Clone https://github.com/Alexxtheonly/NullReferenceAtFindRelationshipCandidates
In `Test.cs` run test `ShouldThrowNullReference()`

### Further technical details
EF Core version: 2.1.0-preview2-final
Database Provider: InMemory, but doesn't matter
Operating system: Windows 10
IDE: Visual Studio 15.6.6

### PR DESCRIPTION
**Pull request by smitpatel**
Metadata: Fix for calling OwnsOne on navigation which implements ICollection throws NullRef

Issue: Conventions create one-to-many relationship when navigation of sequence type is found.
Later when OwnsOne is called, we would try to reuse the same navigation's FK to convert it to ownership.
This works fine for reference navigation. For navigation implementing ICollection, we would have FK with different target type. Since we cannot do such conversion, we encounter exception in pipeline.

Fix is to remove FK if the target type is different from target type of FK.

This also uncovered another issue in query. If the owned entity has non-shadow PK, it will be used as FK too.
This does not work well with SelectExpression.PushDownSubquery() because we consider 2 column with same name as same in SQL tree and hence not alias it but still add it. Which generates invalid SQL.
As for fix in query, we would de-dup the inner projections in the subquery, since that does not cause issue with valuebuffer indexes in shapers. At outer level they would still be repeated.

Resolves #11688

### CODE REVIEW

File: src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs [hunk 1]
```diff
@@ -2082,18 +2082,26 @@ private static InternalIndexBuilder DetachIndex(Index indexToDetach)
...
-                if (ownershipBuilder != null)
+                if (existingNavigation != null)
                 {
-                    ownershipBuilder = ownershipBuilder.RelatedEntityTypes(
-                        Metadata, ownershipBuilder.Metadata.FindNavigationsFromInHierarchy(Metadata).Single().GetTargetType(),
-                        configurationSource);
-                    ownershipBuilder = ownershipBuilder?.Navigations(inverse, navigation, configurationSource);
-                    ownershipBuilder = ownershipBuilder?.IsRequired(true, configurationSource);
-                    ownershipBuilder = ownershipBuilder?.IsOwnership(true, configurationSource);
+                    if (existingNavigation.ForeignKey.DeclaringEntityType.ClrType == targetEntityType.Type)
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/InternalEntityTypeBuilder.cs]: Perhaps existingNavigation.GetTarget().ClrType == targetEntityType.Type would work better for non-collection navigations.

**Comment by smitpatel** [comment]
Requesting additional feedback from @anpete for query bug fix.

Also bad thing is JoinElimination & RowNumberPaging is competing with each other to visit SelectExpression causing different SQLs based on which one runs first.

File: src/EFCore.Relational/Query/Expressions/SelectExpression.cs [hunk 2]
```diff
@@ -381,20 +381,25 @@ public virtual SelectExpression PushDownSubquery()
...
+                    {
+                        subquery._starProjection.Add(expressionToAdd);
+                    }
+                    else
+                    {
+                        subquery._projection.Add(expressionToAdd);
+                    }
                 }
 
                 var outerProjection = expressionToAdd.LiftExpressionFromSubquery(subquery);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Expressions/SelectExpression.cs]: Note to self: this should use the projection based on index.

File: test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs [hunk 3]
```diff
@@ -3080,20 +3080,33 @@ public void Row_number_paging_with_owned_type()
...
+                context.SaveChanges();
                 ClearLog();
+            }
 
+            using (var context = new MyContext10168(Fixture.TestSqlLoggerFactory))
+            {
                 var queryableObj = context.Note.Where(x => x.Text == "Foo Bar").AsQueryable();
 
-                queryableObj.Skip(0).Take(100).ToList();
+                var a = queryableObj.Skip(0).Take(100).ToList();
```
Comment (smitpatel) [inline test/EFCore.SqlServer.FunctionalTests/Query/QueryBugsTest.cs]: Add extra Asserts.

**Comment by ajcvickers** [comment]
@smitpatel Let's discuss whether the query part should be split into a different issue/PR.

File: test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs [hunk 4]
```diff
@@ -505,6 +505,13 @@ public virtual void Reconfiguring_entity_type_as_owned_throws()
 
                 Assert.Equal(2, modelBuilder.Model.GetEntityTypes(typeof(CustomerDetails)).Count);
             }
+
+            [Fact]
+            public virtual void OwnedType_can_derive_from_Collection()
+            {
+                var modelBuilder = CreateModelBuilder();
+                modelBuilder.Entity<PrincipalEntity>().OwnsOne(o => o.InverseNav);
```
Comment (anpete) [inline test/EFCore.Tests/ModelBuilding/OwnedTypesTestBase.cs]: Any verification?

**Comment by smitpatel** [comment]
Updated.

**Comment by ajcvickers** [comment]
@smitpatel Approved for 2.1 RC--can now be merged.
