### PR TITLE
Merge feature/2.0.1

### LINKED ISSUE #9627: Re-consider how default values are reverse engineered
Feedback on 2.0 (e.g. #9507 #9617) has made me think about what the real intent is behind having columns with default values. Specifically, I think it is likely wrong to assume that the EF model should have a store-generated property just because there is some default on the column. It may well be the cause the the application will always supply a value and so, when using EF, the default is never used. The default may instead be there because:
* It was needed when adding a new column (either by Migrations or manually)
* It is there for legacy reasons--old/non-EF app made use of it in hand-crafted SQL, but EF never will
* It's just part of the way all columns are created by the DBA or similar--the column gets a default regardless of whether it is needed or not

Going beyond the most general case, if the CLR default would generate the same value as the database default, then having EF do store generation is a no-op anyway. If an app was relying on this for bools in 1.1, and we now generate nullable bools, everything will still work, but the app needs to be updated to use nullable bools.

### PR DESCRIPTION
**Pull request by smitpatel**
This fixes #9627 in dev

### CODE REVIEW

File: test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs [hunk 1]
```diff
@@ -1108,6 +1108,36 @@ public void Default_and_computed_values_are_stored()
...
 
         [Fact]
+        public void Default_value_of_false_for_bit_is_not_stored()
+        {
+            Test(
+                @"
+CREATE TABLE DefaultBoolValues (
+    Id int,
+    BoolTrue bit DEFAULT (1),
+    BoolFalseType1 BIT DEFAULT 0,
```
Comment (smitpatel) [inline test/EFCore.SqlServer.FunctionalTests/Scaffolding/SqlServerDatabaseModelFactoryTest.cs]: @bricelam - Added variation of `bit` too. all of them comes out as bit only.
