### PR TITLE
Throw better exception for incorrect ownership configuration.

### LINKED ISSUE #13912: Configuring non-ownership navigation to the owner throws
First off I am terrible at wording and I am not 100% sure how to describe this issue. I searched around a bit but I couldn't find an existing issue that fully captured this so I decided to make a new one. 

To summarise: When using an `OwnedAttribute` property with a one-to-many FK on the type that the FK references the FK and Column are being ignored but it works as expected for every other type and it works as expected if I cut + paste the columns from the `OwnedAttribute` type directly onto the original type. 

I am trying to use `OwnedAttribute` in a Code First project to add some common columns to many tables.

```C#
public class Entity
{
    public Guid Id { get; set; }
}
[Owned]
public class ExtraData
{
    public Guid CreatorId { get; set; }
    public Entity Creator { get; set; }
}
```

This works as expected when added to a type, 

```C#
public class SomeType
{
    public Guid Id { get; set; }
    public ExtraData ExtraData { get; set; }
}
```

which results in a migration of 

```C#
migrationBuilder.CreateTable(
    name: "SomeTypes",
    columns: table => new
    {
        Id = table.Column<Guid>(nullable: false),
        ExtraData_CreatorId = table.Column<Guid>(nullable: false)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_SomeTypes", x => x.Id);
        table.ForeignKey(
            name: "FK_SomeTypes_Entities_ExtraData_CreatorId",
            column: x => x.ExtraData_CreatorId,
            principalTable: "Entities",
            principalColumn: "Id",
            onDelete: ReferentialAction.Cascade);
    });
```
My issue is that when I add this property to the type that it references,

```C#
public class Entity
{
    public Guid Id { get; set; }
    public ExtraData ExtraData { get; set; }
}
```

The FK and its column are completely ignored

```C#
migrationBuilder.CreateTable(
    name: "Entities",
    columns: table => new
    {
        Id = table.Column<Guid>(nullable: false)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_Entities", x => x.Id);
    });
```

If, instead, I add these columns directly to `Entity` everything works as expected.

```C#
public class Entity
{
    public Guid Id { get; set; }
    public Guid CreatorId { get; set; }
    public Entity Creator { get; set; }
}
```

```
migrationBuilder.CreateTable(
    name: "Entities",
    columns: table => new
    {
        Id = table.Column<Guid>(nullable: false),
        CreatorId = table.Column<Guid>(nullable: false)
    },
    constraints: table =>
    {
        table.PrimaryKey("PK_Entities", x => x.Id);
        table.ForeignKey(
            name: "FK_Entities_Entities_CreatorId",
            column: x => x.CreatorId,
            principalTable: "Entities",
            principalColumn: "Id",
            onDelete: ReferentialAction.Cascade);
    });
```

Also vaguely related, I commented on another issue with this but trying to rename the FK column on the `OwnedAttribute` type to strip the prefix (`ExtraData_`) I receive the following error (even if I explicitly set the PKey and FKey.)

>The keys {'CreatorId'} on 'ExtraData' and {'Id'} on 'Entity' are both mapped to 'Entities.PK_Entities' but with different columns ({'CreatorId'} and {'Id'}).

### Further technical details
EF Core version: 2.1.4.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Enterprise
IDE: Visual Studio Professional 2017 15.7.6

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Fixes #13912

### CODE REVIEW

File: src/EFCore/Metadata/Conventions/InversePropertyAttributeConvention.cs [hunk 1]
```diff
@@ -186,12 +186,12 @@ public InversePropertyAttributeConvention([NotNull] ProviderConventionSetBuilder
             var ownership = entityType.FindOwnership();
             if (ownership != null
                 && ownership.PrincipalEntityType == targetEntityTypeBuilder.Metadata
-                && ownership.PrincipalToDependent.GetIdentifyingMemberInfo() != inverseNavigationPropertyInfo)
+                && ownership.PrincipalToDependent?.GetIdentifyingMemberInfo() != inverseNavigationPropertyInfo)
```
Comment (smitpatel) [inline src/EFCore/Metadata/Conventions/InversePropertyAttributeConvention.cs]: Do we allow ownership.PrincipalToDependent to be null? If yes, then there are potentially a lot more NullRefs than this.

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/InversePropertyAttributeConvention.cs]: We don't. But we don't want to fail with a NRE, instead it will fail on model validation.

Comment (smitpatel) [reply src/EFCore/Metadata/Conventions/InversePropertyAttributeConvention.cs]: So query will never have to worry about this?

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Conventions/InversePropertyAttributeConvention.cs]: Correct
