### PR TITLE
Fix #11004 - Attempting to access entity on group throws 'disposed ob…

### LINKED ISSUE #11004: Attempting to access entity on group throws "disposed object...." error
```c#    
    class Program
	{
		public const string ConnectionString = "Data Source=.\\SQLEXPRESS;Initial Catalog=Staging;Integrated Security=True;MultipleActiveResultSets=True;";

		static void Main(string[] args)
		{
			try
			{
				new Program().Run();
			}
			catch (Exception ex)
			{
				string y = ex.Message;
				// Cannot access a disposed object. 
				// A common cause of this error is disposing a context that was resolved from dependency injection 
				// and then later trying to use the same context instance elsewhere in your application. This may occur 
				// if you are calling Dispose() on the context, or wrapping the context in a using statement. 
				// If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
				// Object name: 'Db'.
			}
		}

		public void Run()
		{
			var junk = GetSeries(0, 100000).Result;
			var moreJunk = junk.First().First().ID; // throws here
		}

		public virtual async Task<List<IGrouping<string, DTOSeries>>> GetSeries(int skip, int take)
		{
			List<IGrouping<string, DTOSeries>> series = null;

			using (Db db = new Db(new DbContextOptionsBuilder<Db>().UseSqlServer(Program.ConnectionString).Options))
			{
				series = await db.DTOSeries
					.GroupBy(x => x.Symbol)
					.OrderBy(x => x.Key)
					.Skip(skip).Take(take).ToListAsync();
			}
			return series;
		}
	}

	

	public class Db : DbContext
	{
		public DbSet<DTOSeries> DTOSeries { get; set; }

		public Db(DbContextOptions<Db> options)
			: base(options)
		{

		}
	}


	public partial class DTOSeries
	{
		[XmlIgnore]
		public int ID { get; set; }

		[XmlIgnore]
		public int CategoryID { get; set; }

		[XmlAttribute("id")]
		public string Symbol { get; set; }

		[XmlAttribute("title")]
		public string Title { get; set; }

		[XmlAttribute("frequency")]
		public string Frequency { get; set; }

		[XmlAttribute("units")]
		public string Units { get; set; }

		[XmlAttribute("seasonal_adjustment_short")]
		public string SeasonalAdj { get; set; }

		[XmlAttribute("last_updated")]
		public String LastUpdated { get; set; }

		[XmlAttribute("popularity")]
		public int Popularity { get; set; }

		[XmlAttribute("realtime_start")]
		public DateTime RTStart { get; set; }

		[XmlAttribute("notes")]
		public string Notes { get; set; }
	}
```

### PR DESCRIPTION
**Pull request by anpete**
…ject....' error

Change to tracking "outside" the groups. Each time a group is pulled from the outer sequence we track the elements in the group before yielding it.

### CODE REVIEW

File: src/EFCore/Query/ExpressionVisitors/Internal/CorrelatedCollectionFindingExpressionVisitor.cs [hunk 1]
```diff
@@ -100,7 +101,7 @@ private void TryMarkSubQuery(SubQueryExpression expression)
                 _validator = new CorrelatedSubqueryOptimizationValidator();
             }
 
-            if (_validator.CanTryOptimizeCorrelatedSubquery(subQueryModel))
```
Comment (smitpatel) [inline src/EFCore/Query/ExpressionVisitors/Internal/CorrelatedCollectionFindingExpressionVisitor.cs]: Remove _validator field. Unused.

**Comment by anpete** [comment]
Ping @smitpatel

**Comment by smitpatel** [comment]
Also add test for async code path.
