### PR TITLE
Fix temporary value snapshot

### LINKED ISSUE #17997: Changes to entities ignored while looping through change tracker entries
I have some code that I run just before SaveChanges is called. This code loops through the entries currently in the change tracker and changes a few values of the underlying entities.

During upgrade to `3.0.0-rc1.19456.14` I noticed that these changes are now ignored. I've also verified this in `3.0.0-rc2.19463.9` where this still happens. Edit: Also still happens on 3.0.0. (Congratulations on the release, btw! 😄)

This happens with the SqlServer provider, and it doesn't happen with the InMemory provider.

### Steps to reproduce

The following code ran in 2.2.x, because the foreign key was set to `null` while looping the entries. Now, because this change is ignored, it throws because an entity with the foreign key `999` doesn't exist.
``` c#
public class Tests
{
    [Fact]
    public ShouldNotThrow()
    {
        var dbContext = new MyContext();
        dbContext.Database.EnsureDeleted();
        dbContext.Database.EnsureCreated();
        dbContext.Set<Entity>().Add(new Entity() { SubEntityId = 999 });

        foreach (var entry in dbContext.ChangeTracker.Entries())
        {
            if (entry.Entity is Entity entity)
            {
                entity.SubEntityId = null;
            }
        }

        dbContext.SaveChanges();
    }
}

public class MyContext : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.UseSqlServer("Data Source=localhost;Database=Test;Integrated Security=False;User ID=sa;Password={my-pass}");
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Entity>();
        modelBuilder.Entity<SubEntity>();
    }
}

public class Entity
{
    public int Id { get; set; }
        
    public int? SubEntityId { get; set; }
    public SubEntity SubEntity { get; set; }
}

public class SubEntity
{
    public int Id { get; set; }
}
```

### Further technical details

EF Core version: `3.0.0-rc1.19456.14` / `3.0.0-rc2.19463.9` / `3.0.0`
Database provider: `SqlServer`
Target framework: `netcoreapp3.0`
Operating system: `Win 10 1903`
IDE: `Visual Studio 2019 16.3.0`

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #17997

The problem here was that the temporary values snapshot was copying current values rather than starting with empty values. This then meant that when the current value was set to null, the temp value took over, which was then incorrect. Related to this, when setting a current value to null, the temp value (if it exists) must also be set to null otherwise it will start being used.

### CODE REVIEW

File: src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs [hunk 1]
```diff
@@ -911,7 +911,7 @@ public virtual void EnsureTemporaryValues()
         {
             if (_temporaryValues.IsEmpty)
             {
-                _temporaryValues = new SidecarValues(this);
```
Comment (AndriySvyryd) [inline src/EFCore/ChangeTracking/Internal/InternalEntityEntry.cs]: Use a direct cast, it's likely to be on the hot path.
