### PR TITLE
[2.0.1] Query: Fix for Access to context bound variable can be optimized out

### LINKED ISSUE #9825: Access to context bound variable can be optimized out
Found investigating #9809. This should work:

```C#
modelBuilder
    .Entity<Report>()
    .HasQueryFilter(x => !x.IsDeleted && (IsModerated == null || IsModerated == x.IsModerated));
```
but the IsModerated == null part is optimized away.

### PR DESCRIPTION
**Pull request by smitpatel**
**Take 3**

Issue:
We adopted short-circuiting logic in logical expression due to possible exceptions (which compiler would never throw in memory). This works correctly for general cases because the expression tree would have current value of closure variable hence evaluating to correct thing.
When it comes to QueryFilter, the filter has closure member access on context instance which was used during OnModelCreating which may have stale value of context closure variables. We parametrize such closure variables and insert their values through parameters when running query. But if such closure variable is used in complex expression which can short-circuit then we would be using wrong value for short-circuit (by this point we haven't inserted correct value from current context instance) hence generating incorrect query model. The other cause for it is QueryCache has only 1 entry for all the possible values of context bound variables in filter.

Solution:
Since evaluating filter with context bound variables with different value may not always generate a re-usable query model for all values of variables, whenever we get an expression to evaluate during funcletizing query filter, we replace context, with context parameter (which would be injected later) and return this expression without evaluating anything in-memory. Any exception to be thrown from evaluation of context bound variables will be thrown when actual parameter value will be calculated while running query.

Resolves #9825

### CODE REVIEW

**Comment by smitpatel** [comment]
Quirking is pending. If the implementation is acceptable I will add quirks.

File: src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs [hunk 1]
```diff
@@ -416,6 +417,23 @@ public virtual object Evaluate([CanBeNull] Expression expression, [CanBeNull] ou
...
 
+            if (_generateContextAccessors)
+            {
+                var contextParameterReplacingExpressionVisitor = new ContextParameterReplacingExpressionVisitor();
+                var updatedExpression = contextParameterReplacingExpressionVisitor.Visit(expression);
+
+                if (contextParameterReplacingExpressionVisitor.ContextParameterExpression != null)
+                {
+                    parameterName = updatedExpression is MemberExpression memberExpression
+                        ? memberExpression.Member.Name
```
Comment (anpete) [inline src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs]: How is this name used? Can it collide when there are multiple filters?

**Comment by natemcmaster** [comment]
Can you retarget this to the rel/2.0.1 branch before merging?

File: src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs (hunk 1 above)
Comment (smitpatel) [reply src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs]: #9850

**Comment by smitpatel** [comment]
Updated with quirks.

File: src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs [hunk 2]
```diff
@@ -32,6 +32,8 @@ public class ParameterExtractingExpressionVisitor : ExpressionVisitor
 
         private bool _inLambda;
 
+        private static bool QuirkEnabled => AppContext.TryGetSwitch("Microsoft.EntityFrameworkCore.Issue9825", out var enabled) && enabled;
```
Comment (anpete) [inline src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs]: private fields start with '_' - You can update R# naming settings.

Comment (anpete) [inline src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs]: Field?

File: src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs [hunk 3]
```diff
@@ -48,6 +51,11 @@ public class ParameterExtractingExpressionVisitor : ExpressionVisitor
             _logger = logger;
             _parameterize = parameterize;
             _generateContextAccessors = generateContextAccessors;
+
+            if (_generateContextAccessors)
+            {
```
Comment (anpete) [inline src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs]: && field is null

File: src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs [hunk 4]
```diff
@@ -403,6 +429,22 @@ var compilerPrefixIndex
             return Expression.Parameter(expression.Type, parameterName);
         }
 
+        private class ContextParameterReplacingExpressionVisitor : ExpressionVisitor
```
Comment (anpete) [inline src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs]: sealed

File: src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs [hunk 5]
```diff
@@ -403,6 +429,22 @@ var compilerPrefixIndex
...
+        {
+            public ParameterExpression ContextParameterExpression;
+
+            protected override Expression VisitConstant(ConstantExpression node)
```
Comment (anpete) [inline src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs]: node => constantExpression :trollface:

File: src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs [hunk 6]
```diff
@@ -403,6 +429,22 @@ var compilerPrefixIndex
...
+            {
+                if (typeof(DbContext).GetTypeInfo()
+                    .IsAssignableFrom(node.Type.GetTypeInfo()))
+                {
+                    return ContextParameterExpression ?? (ContextParameterExpression = Expression.Parameter(node.Type, "context"));
+                }
+
+                return base.VisitConstant(node);
```
Comment (anpete) [inline src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs]: nit: can just return node.

File: src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs [hunk 7]
```diff
@@ -416,6 +458,25 @@ public virtual object Evaluate([CanBeNull] Expression expression, [CanBeNull] ou
                 return null;
             }
 
+            if (!QuirkEnabled)
+            {
+                if (_generateContextAccessors)
+                {
+                    var updatedExpression = _contextParameterReplacingExpressionVisitor.Visit(expression);
```
Comment (anpete) [inline src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs]: nit: we usually call this 'newExpression'

File: src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs (hunk 2 above)
Comment (smitpatel) [reply src/EFCore/Query/ExpressionVisitors/Internal/ParameterExtractingExpressionVisitor.cs]: the use of out variable blocks it.

**Comment by divega** [comment]
> We adopted short-circuiting logic in logical expression due to possible exceptions (which compiler would never throw in memory)

@smitpatel Do we handle query filters with patterns that would require short-circuiting after the fix?

**Comment by divega** [comment]
I guess `MyContext9825` covers that. Thanks.

**Comment by smitpatel** [comment]
@divega - It actually may not short-circuit but that behavior is somewhat hard to define because of having only 1 entry in query cache for all values of filters. We don't have ability to generate different select expression based on values. It would short circuit in generated SQL but it needs to be translatable and values could be computable.

**Comment by rainerllera** [comment]
When will this be available?
