### PR TITLE
Column Ordering: Sort PK properties first

### LINKED ISSUE #13069: Mismatch between properties mapping to same column in database for owned entities could cause incorrect column configuration
When adding a migration part of the configuration seems to be skipped.
```c#
builder.Property(x => x.ProviderKey).HasMaxLength(50).IsUnicode(false); 
```
DOES NOT EQUAL 
```c#
ProviderKey = table.Column<string>(nullable: false)
```
Relevant Code:
```c#
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.ApplyConfiguration(new CustomerConfig());
    }
```

```c#
public class CustomerConfig : IEntityTypeConfiguration<Domain.Customer>
{
    public void Configure(EntityTypeBuilder<Domain.Customer> builder)
    {
        builder.ToTable(nameof(Domain.Customer));
        builder.OwnsOne(
            o => o.Created,
            sa =>
            {
                sa.Property(p => p.Reason).HasMaxLength(255).IsUnicode(false);
            }
        );
builder.Property(x => x.TenantId).IsRequired();
        builder.Property(x => x.RowVersion).IsRowVersion();
builder.HasKey(x => new { x.TenantId, x.ProviderId, x.ProviderKey });
        builder.Property(x => x.ProviderKey).HasMaxLength(50).IsUnicode(false);
builder.Property(x => x.DisplayName).HasMaxLength(255).IsUnicode(false);
    }
}
```

Is generating:
```c#
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.CreateTable(
            name: "Customer",
            columns: table => new
            {
                TenantId = table.Column<Guid>(nullable: false),
                RowVersion = table.Column<byte[]>(rowVersion: true, nullable: true),
                Created_SessionId = table.Column<Guid>(nullable: true),
                Created_At = table.Column<DateTimeOffset>(nullable: true),
                Created_Reason = table.Column<string>(unicode: false, maxLength: 255, nullable: true),
                ProviderId = table.Column<Guid>(nullable: false),
                ProviderKey = table.Column<string>(nullable: false),
                DisplayName = table.Column<string>(unicode: false, maxLength: 255, nullable: true)
            },
            constraints: table =>
            {
                table.PrimaryKey("PK_Customer", x => new { x.TenantId, x.ProviderId, x.ProviderKey });
            });
    }
```
The Domain.Customer.ProviderKey configuration does not seem to be applied in the migration.
Full project can be found https://github.com/CodeThumper/EFCoreMigrationSample

### Steps to reproduce
Full project can be found https://github.com/CodeThumper/EFCoreMigrationSample

### Further technical details
EF Core version: 2.1.1
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 Pro Version 1803 build 17134.228
IDE:  Visual Studio 2017 15.7.4

### LINKED ISSUE #13678: Column Ordering: Put primary key properties first
According to @bricelam 
```C#
        public abstract class Base
        {
            public int? RealFkNavigationId { get; set; }
            public Principal ShadowFkNavigation { get; set; }
            public Principal RealFkNavigation { get; set; }
            public int Id3 { get; set; }
        }

        public class Dependent : Base
        {
            public int Id2 { get; set; }
            public int Id1 { get; set; }
            public string Value { get; set; }
        }
```
And PK definition,
```C#
                    target.Entity<Dependent>(b =>
                    {
                        b.Property<int>("ShadowPk");
                        b.Property<int>("AnotherShadowProperty");
                        b.HasKey("Id1", "Id2", "Id3", "ShadowPk");
                    });
```

Column order will be
 - Id3
 - Id2
 - Id1
 - ShadowPk
 - RealFkNavigationId
 - ShadowFkNavigationId
 - Value
 - AnotherShadowProperty

Primary key properties before any other properties.
Inside PK properties,
- Properties from base type first
- In same type, follow reflection order,
- Shadow properties at last

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #13678

Now we sort PK properties first.
Inside PK properties, we sort by CLR hierarchy, then by reflection order, then by CLR vs shadow property

Resolves #13069
Issue: User specified facets were stored on property from owner which is part of PK. This property is shared with owned types PK.
Since column ordering expanded owned type into navigation and PK property appeared after navigation in reflection order, we sorted owned PK property before owner PK property.
While doing distinct, we selected owned PK property which did not have facets copied over from owner PK which caused migration to lose user configuration.
Fix: Sorting PK properties first in migration solves issue that owned property is used for table definition

### CODE REVIEW

File: src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs [hunk 1]
```diff
@@ -721,7 +734,13 @@ private static IEnumerable<IProperty> GetSortedProperties(IEntityType entityType
                 }
             }
 
-            return graph.TopologicalSort().SelectMany(t => types[t].Values).SelectMany(p => groups[p])
+            var sortedPropertyInfos = graph.TopologicalSort().SelectMany(e => types[e].Values).ToList();
+
+            return sortedPropertyInfos
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs]: There's probably a way of making the graph do all the ordering, but it might be less readable.

Comment (smitpatel) [reply src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs]: I think for RTM, localized would be safer fix.
The logic is quite complex here. @bricelam to determine if we want to change this as you suggest above.

Comment (AndriySvyryd) [reply src/EFCore.Relational/Migrations/Internal/MigrationsModelDiffer.cs]: I don't think we should change it at this point
