### PR TITLE
[2.1.3] Handle properties with same name from multiple explicit interface implementations.

### LINKED ISSUE #12203: 2.1.0 can't do Value Conversions on complex IEnumerable types like JObject (newtonsoft)
It seems any complex property type still goes through all the discover relationships machinery even though you explicitly call the new 2.1 value converter api `HasConversion(converter)`.

For example try to set up a value conversion for Newtonsofts `JObject` as this one implements many IEnumerable derived interfaces that will trigger this `DiscoverRelationships` codepath.

Leading to beautifully vague stacktraces and completely blocking us from using this new api

```
 System.Reflection.AmbiguousMatchException : Ambiguous match found.
Stack Trace:
   at System.RuntimeType.GetPropertyImpl(String name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetProperty(String name, BindingFlags bindingAttr)
   at System.SharedTypeExtensions.GetPropertiesInHierarchy(Type type, String name)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Reflection.PropertyInfoExtensions.FindSetterProperty(PropertyInfo propertyInfo)
   at System.Reflection.PropertyInfoExtensions.IsCandidateProperty(PropertyInfo propertyInfo, Boolean needsWrite, Boolean publicOnly)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyDiscoveryConvention.IsCandidatePrimitiveProperty(PropertyInfo propertyInfo)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.PropertyDiscoveryConvention.Apply(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnEntityTypeAdded(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.RunVisitor.VisitOnEntityTypeAdded(OnEntityTypeAddedNode node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(ConventionScope node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionVisitor.VisitConventionScope(ConventionScope node)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ConventionBatch.Run()
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.RelationshipDiscoveryConvention.DiscoverRelationships(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Conventions.Internal.ConventionDispatcher.ImmediateConventionScope.OnEntityTypeAdded(InternalEntityTypeBuilder entityTypeBuilder)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Model.AddEntityType(EntityType entityType)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.InternalModelBuilder.Entity(TypeIdentity& type, ConfigurationSource configurationSource, Boolean throwOnQuery)
```

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Fixes #12203

### CODE REVIEW

File: src/Shared/SharedTypeExtensions.cs [hunk 1]
```diff
@@ -190,12 +190,15 @@ public static IEnumerable<PropertyInfo> GetPropertiesInHierarchy(this Type type,
             do
             {
                 var typeInfo = type.GetTypeInfo();
-                var propertyInfo = typeInfo.GetDeclaredProperty(name);
-                if (propertyInfo != null
-                    && !(propertyInfo.GetMethod ?? propertyInfo.SetMethod).IsStatic)
+                foreach (var propertyInfo in typeInfo.DeclaredProperties)
                 {
-                    yield return propertyInfo;
+                    if (propertyInfo.Name.Equals(name, StringComparison.Ordinal)
```
Comment (smitpatel) [inline src/Shared/SharedTypeExtensions.cs]: Could linq-ify

**Comment by smitpatel** [comment]
@dotnet-bot test windows release x64 build

**Comment by smitpatel** [comment]
Build failure in windows.
