### PR TITLE
Close connection even if ambient transaction hasn't completed

### LINKED ISSUE #14218: With TransactionScope, after DbContext is disposed, DbConnection is still open.
This issue happens with TransactionScope. After DbContext is disposed, DbConnection is still open.

### Expected
In EF, after DbContext is disposed, its DbConnection is closed:
```cs
new ExecutionStrategy().Execute(() =>
{
    using (TransactionScope transactionScope = new TransactionScope())
    {
        DbConnection connection;
        using (AdventureWorks adventureWorks = new AdventureWorks())
        {
            connection = adventureWorks.Database.Connection;
            // Some operations.
            ProductCategory category = new ProductCategory() { Name = nameof(ProductCategory) };
            adventureWorks.ProductCategories.Add(category);
            adventureWorks.SaveChanges();
        }
        Trace.WriteLine(connection.State); // Closed, expected.
    }
});
```
The above ExecutionStrategy class is from [here](https://github.com/Dixin/CodeSnippets/blob/master/FunctionalProgramming%2BLINQ/Tutorial.Shared/LinqToEntities/Database.cs).

### Not expected
In EF Core, the same workflow, after DbContext is disposed, its DbConnection is **NOT** closed:
```cs
dbCon.Database.CreateExecutionStrategy().Execute(() =>
{
    using (TransactionScope transactionScope = new TransactionScope())
    {
        DbConnection connection;
        using (AdventureWorks adventureWorks = new AdventureWorks())
        {
            connection = adventureWorks.Database.GetDbConnection();
            // Some operations.
            ProductCategory category = new ProductCategory() {Name = nameof(ProductCategory)};
            adventureWorks.ProductCategories.Add(category);
            adventureWorks.SaveChanges();
        }
        Trace.WriteLine(connection.State); // Open, NOT expected.
    }
});
```

### Problem
This causes issues, for example:
```cs
dbContext.Database.CreateExecutionStrategy().Execute(() =>
{
    using (TransactionScope transactionScope = new TransactionScope())
    {
        using (AdventureWorks adventureWorks = new AdventureWorks())
        {
            // Some operations.
            adventureWorks.Products.ToArray();
        }

        // DbConnection is still open!!!

        using (DbConnection connection = new SqlConnection("ConnectionString"))
        using (DbCommand command = connection.CreateCommand())
        {
            connection.Open(); // PlatformNotSupportedException
            // Some operations.
        }
    }
});
```
The above workflow works in EF, and throws exception in EF Core:
> System.PlatformNotSupportedException
>   HResult=0x80131539
>   Message=This platform does not support distributed transactions.
>   Source=System.Transactions.Local
>   StackTrace:
>    at System.Transactions.Distributed.DistributedTransactionManager.GetDistributedTransactionFromTransmitterPropagationToken(Byte[] propagationToken)
>    at System.Transactions.TransactionInterop.GetDistributedTransactionFromTransmitterPropagationToken(Byte[] propagationToken)
>    at System.Transactions.TransactionStatePSPEOperation.PSPEPromote(InternalTransaction tx)
>    at System.Transactions.TransactionStateDelegatedBase.EnterState(InternalTransaction tx)
>    at System.Transactions.EnlistableStates.Promote(InternalTransaction tx)
>    at System.Transactions.Transaction.Promote()
>    at System.Transactions.TransactionInterop.ConvertToDistributedTransaction(Transaction transaction)
>    at System.Transactions.TransactionInterop.GetExportCookie(Transaction transaction, Byte[] whereabouts)
>    at System.Data.SqlClient.SqlInternalConnection.GetTransactionCookie(Transaction transaction, Byte[] whereAbouts)
>    at System.Data.SqlClient.SqlInternalConnection.EnlistNonNull(Transaction tx)
>    at System.Data.ProviderBase.DbConnectionPool.PrepareConnection(DbConnection owningObject, DbConnectionInternal obj, Transaction transaction)
>    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
>    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource\`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
>    at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource\`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
>    at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource\`1 retry, DbConnectionOptions userOptions)
>    at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource\`1 retry)
>    at System.Data.SqlClient.SqlConnection.Open()
>    at Tutorial.LinqToEntities.Transactions.<>c.<TransactionScope>b__6_0() in D:\User\GitHub\Tutorial\Tutorial.Shared\LinqToEntities\Transactions.cs:line 162
>    at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c.<Execute>b__0_0(Action operationScoped)
>    at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation[TState,TResult](Func\`3 operation, Func\`3 verifySucceeded, TState state)

### Workaround
The workaround apparently is to manually close the DbConnection:
```cs
adventureWorks22.Database.CreateExecutionStrategy().Execute(() =>
{
    using (TransactionScope transactionScope = new TransactionScope())
    {
        using (AdventureWorks adventureWorks = new AdventureWorks())
        {
            // Some operations.
            adventureWorks.Products.ToArray();
            adventureWorks.Database.CloseConnection(); // Manually close DbConnection.
        }

        // DbConnection is closed.

        using (DbConnection connection = new SqlConnection(ConnectionStrings.AdventureWorks))
        using (DbCommand command = connection.CreateCommand())
        {
            connection.Open(); // Works.
            // Some operations.
        }
    }
});
```

### Further technical details
EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 1809 x64
IDE: Visual Studio 2017 15.9.4

### PR DESCRIPTION
**Pull request by AndriySvyryd**
On SQL Server if a connection was enlisted in a transaction, closed, then enlisted in a different transaction before the first one was completed results in a deadlock. We maintained the connection opened to allow the database to throw in this case, but this was unexpected behavior.

Now we close the database connection, but keep the reference to the original transaction to perform the above check explicitly.

This change also allowed to remove the semaphore as the opened count shouldn't be mutated on different threads anymore.

Fixes #14218

### CODE REVIEW

**Comment by divega** [comment]
@roji you may want to consider this for Npgsql, given you mentioned in #14218 that it implements the same optimization as SqlClient to avoid unnecessary transaction promotion.

**Comment by roji** [comment]
@divega this seems to be a RelationalConnection-only change, do you think there's anything that needs to be done in providers?

**Comment by divega** [comment]
@roji good point. I was expecting the behavior to become provider-specific based on the discussion in #1418. Would need to look deeper to understand what is in here. Maybe @AndriySvyryd can explain.

**Comment by divega** [comment]
I haven’t looked at the code in detail yet, but a guess based on the description of the PR is that this will close the connection regardless of pending Sys.Tx transactions, hence causing transaction promotion (and failure since .NET Core does not implement 2-phase commit) for database providers that do not implement the optimization. The user will then have the option to open the connection manually once inside the transaction to avoid this. Hence the breaking change classification. @AndriySvyryd, have I guessed well?

**Comment by AndriySvyryd** [comment]
The breaking change is more for users that rely on the connection being open after the context has been disposed.
Providers that don't support reenlisting the connection in the same transaction can override this behavior.

**Comment by divega** [comment]
> On SQL Server if a connection was enlisted in a transaction, closed, then enlisted in a different transaction before the first one was completed results in a deadlock. We maintained the connection opened to allow the database to throw in this case, but this was unexpected behavior.
Let me know if I a missing something. 

>The breaking change is more for users that rely on the connection being open after the context has been disposed.

But my understanding is that we didn't do it just because of this negative scenario. We actually also did it to prevent transaction promotion with most database providers in a common scenario in which a single DbContext issues multiple operations in the same Sys.Tx transaction, which in .NET Core throws PlatformNotSupportedException. Correct?

I am not pushing back, but just trying to understand the extent of the breaking change. Here are a few things that IMO could make the break acceptable:

1. Two of the most used providers (SqlServer and Npgsql) work better with this behavior
2. Customers can hopefully workaround by opening the connection explicitly in application code
3. It will be relatively easy to connect the exception in the context of using EF Core with the workaround
4. It simplifies the implementation and how we can describe the behavior of EF Core to customers

> Providers that don't support reenlisting the connection in the same transaction can override this behavior.

Perhaps, but I am no longer sure if we should recommend providers to do this if we take the breaking change. It may just make things harder to predict if you know if your provider overrides it or not, and the workaround of opening the connection explicitly to make that scenario work should have very few downsides.

**Comment by AndriySvyryd** [comment]
> But my understanding is that we didn't do it just because of this negative scenario. We actually also did it to prevent transaction promotion with most database providers in a common scenario in which a single DbContext issues multiple operations in the same Sys.Tx transaction, which in .NET Core throws PlatformNotSupportedException. Correct?

Yes, I'm just saying that this is more likely to be the break.

>Perhaps, but I am no longer sure if we should recommend providers to do this if we take the breaking change. 

Agree, having the user implement the workaround is more reliable and will result in the same behavior across providers.

**Comment by roji** [comment]
I don't have the history/context on this, but promise to give this a deep look tomorrow.

**Comment by AndriySvyryd** [comment]
@roji Note that if you are on the reviewers list it doesn't mean you have to review, just that you are at least somewhat familiar with the area and your review would be enough to merge this.

**Comment by divega** [comment]
> Agree, having the user implement the workaround is more reliable and will result in the same behavior across providers.

Also, time may be better spent implementing the same optimization at the ADO.NET later that SqlClient and Npgsql have.

File: src/EFCore.Relational/Storage/RelationalConnection.cs [hunk 1]
```diff
@@ -507,53 +506,40 @@ private void HandleAmbientTransactions()
...
+                throw new InvalidOperationException(RelationalStrings.PendingAmbientTransaction);
+            }
+
             if (current != null)
             {
                 Dependencies.TransactionLogger.AmbientTransactionEnlisted(this, current);
             }
 
             DbConnection.EnlistTransaction(current);
-            try
```
Comment (ajcvickers) [inline src/EFCore.Relational/Storage/RelationalConnection.cs]: 💐

**Comment by ctrl-alt-d** [comment]
Hi people, @ajcvickers , @AndriySvyryd ,

Sorry about to comment on closed issue, just a little question:

How to deal with nested transactions? I just tested following code and runs fine, it closes connection on transaction and also is able to commit or rollback both transactions.

Are you so kind to confirm I can code in this way? Thanks.

```

   ...
   await OuterTxMethod( myDbContextInstance );
   ...

private async Task OuterTxMethod(Ctx ctx)
{
    using (var tx = new TransactionScope(TransactionScopeOption.Required,
                                            new TransactionOptions { IsolationLevel = IsolationLevel.Serializable },
                                            TransactionScopeAsyncFlowOption.Enabled))
    {
        var parent = await InnerTxMethod(ctx);
        var m = new MyModel
        {
            MyParentId = parent.Id,
            MyProperty = 2
        };
        ctx.MyModels.Add(m);
        await ctx.SaveChangesAsync();
        // tx.Complete();  <-- uncomment for commit
        ctx.Database.CloseConnection();
    }
}

private async Task<MyModel> InnerTxMethod(Ctx ctx)
{
    var m = new MyModel
    {
        MyParentId = null,
        MyProperty = 1
    };
    using (var tx = new TransactionScope(TransactionScopeOption.Required,
                                            new TransactionOptions { IsolationLevel = IsolationLevel.Serializable },
                                            TransactionScopeAsyncFlowOption.Enabled))
    {
        ctx.MyModels.Add(m);
        await ctx.SaveChangesAsync();
        tx.Complete();
        ctx.Database.CloseConnection();
    }
    return m;
}
```

**Comment by AndriySvyryd** [comment]
@ctrl-alt-d This approach is fine with the current version. But the `CloseConnection` call won't be necessary and might cause exceptions in EF Core 3.0
