### PR TITLE
Fixing named query cache misses by adding support for collections in …

### LINKED ISSUE #37112: Compiled query is never cached when named query filters is used
### Bug description

Hello,

I tried the new *named global query filter* feature, but it seems to have a problem with query caching when using its corresponding overload of `IgnoreQueryFilters`:

```csharp
IgnoreQueryFilters(this IQueryable source, [NotParameterized] IReadOnlyCollection filterKeys)
```

CompiledQueryCacheKeyGenerator.GenerateCacheKey appears to always generate a new key, which leads to cache misses and query recompilation on each call.

This issue does not occur when using the previous overload:
```csharp
IgnoreQueryFilters(this IQueryable source)
```

### Your code

```csharp
I have a minimal reproduction scenario available [here](https://github.com/WiseGus/ef10_named_filters_cache)  using Microsoft.EntityFrameworkCore.Sqlite

Note: It can be reproduced to both Microsoft.EntityFrameworkCore.Sqlite and Microsoft.EntityFrameworkCore.SqlServer.
```

### Stack traces

```text

```

### Verbose output

```text

```

### EF Core version

10.0.0-rc.2.25502.107

### Database provider

Microsoft.EntityFrameworkCore.Sqlite

### Target framework

.NET 10.0

### Operating system

Windows 11

### IDE

Visual Studio 2026 Insiders 11201.2

### PR DESCRIPTION
**Pull request by bittola**
Fixing named query cache misses by adding support for collections inconstant expression comparer

fixes #37112

- [x] I've read the guidelines for [contributing](CONTRIBUTING.md) and seen the [walkthrough](https://youtu.be/9OMxy1wal1s?t=1869)
- [x] The code builds and tests pass locally (also verified by our automated build checks)
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Code follows the same patterns and style as existing code in this repo

### CODE REVIEW

File: src/EFCore/Query/ExpressionEqualityComparer.cs [hunk 1]
```diff
@@ -76,6 +76,13 @@ public int GetHashCode(Expression obj)
                             hash.Add(structuralEquatable.GetHashCode(StructuralComparisons.StructuralEqualityComparer));
                             break;
 
+                        case IEnumerable enumerable when constantExpression.Value is not string:
```
Comment (bittola) [inline src/EFCore/Query/ExpressionEqualityComparer.cs]: There are some limitations with this approach. At this point we don't have any information about the intent. In some cases we don't care about the order of elements in the collection, nor we care about the type of the collection. We just care that the elements are the same in no particular order.
 
With the implementation above we get the cache hit only when the type of the collection and order of the elements is the same.
For example:
```csharp
var result = context.Entities
    .IgnoreQueryFilters(["ActiveFilter", "NameFilter"])
    .ToList();
_ = context.Entities
    .IgnoreQueryFilters(["ActiveFilter", "NameFilter"])
    .ToList();
```

However, the following won't work:
```csharp
var result = context.Entities
    .IgnoreQueryFilters(["ActiveFilter", "NameFilter"])
    .ToList();
_ = context.Entities
    .IgnoreQueryFilters(["NameFilter", "ActiveFilter"])
    .ToList();
```

it will work with sorted collection for example
```csharp
var result = context.Entities
    .IgnoreQueryFilters(new SortedSet<string> { "ActiveFilter", "NameFilter" })
    .ToList();
_ = context.Entities
    .IgnoreQueryFilters(new SortedSet<string> { "NameFilter", "ActiveFilter" })
    .ToList();
```

The question is how to pass that information to the comparer that we care or not about the order. We only have a type information. If we are OK with this limitation, then fine

Comment (bittola) [reply src/EFCore/Query/ExpressionEqualityComparer.cs]: Another thing we may need to consider is to limit this to more specific interface like ICollection or so

File: src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs [hunk 2]
```diff
@@ -2710,7 +2710,8 @@ public static IQueryable<TEntity> IgnoreQueryFilters<TEntity>(
                 Expression.Call(
                     instance: null,
                     method: IgnoreNamedQueryFiltersMethodInfo.MakeGenericMethod(typeof(TEntity)),
-                    arguments: [source.Expression, Expression.Constant(filterKeys)]))
+                    // converting the collection to a sorted set to ensure cache is hit even when order of keys differs
+                    arguments: [source.Expression, Expression.Constant(new SortedSet<string>(filterKeys))]))
```
Comment (cincuranet) [inline src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs]: This is a nice approach. But for 10 servicing we want to keep the changes to a minimum to prevent any unforeseen problems. Change this to an array (and check whether it is not already an array to prevent double work) here and that should be it.

File: src/EFCore/Query/ExpressionEqualityComparer.cs (hunk 1 above)
Comment (cincuranet) [inline src/EFCore/Query/ExpressionEqualityComparer.cs]: As I wrote above, especially for 10 servicing, we want to keep the changes to a minimum. So changing in `EntityFrameworkQueryableExtensions` to an array and keeping `ExpressionEqualityComparer` is absolutely fine. For bigger work here I opened #37212.

The fact that `["ActiveFilter", "NameFilter"]` and `["NameFilter", "ActiveFilter"]` will be considered different is fine.

File: test/EFCore.Specification.Tests/Query/AdHocQueryFiltersQueryTestBase.cs [hunk 3]
```diff
@@ -34,6 +34,28 @@ public virtual async Task Named_query_filters_ignore_some()
...
+        _ = context.Entities
+            .IgnoreQueryFilters(["ActiveFilter", "NameFilter"])
+            .ToList();
+        _ = context.Entities
+            .IgnoreQueryFilters(["ActiveFilter", "NameFilter"])
+            .ToList();
+        _ = context.Entities
+            .IgnoreQueryFilters(["NameFilter", "ActiveFilter"])
+            .ToList();
+        Assert.Equal(1, cacheLog.Count);
```
Comment (cincuranet) [inline test/EFCore.Specification.Tests/Query/AdHocQueryFiltersQueryTestBase.cs]: This will be `2` then. And we can consider it expected. You can add comment and mention #37212.

File: test/EFCore.Tests/Query/ExpressionEqualityComparerTest.cs [hunk 4]
```diff
@@ -107,6 +107,42 @@ public void Array_constant_expressions_are_compared_correctly()
...
+        var e2 = Constant(new SortedSet<string> { "value1", "value3", "value2" });
+        var e3 = Constant(new SortedSet<string> { "value1", "value2", "value4" });
+
+        Assert.True(expressionComparer.Equals(e1, e2));
+        Assert.False(expressionComparer.Equals(e1, e3));
+
+        Assert.Equal(expressionComparer.GetHashCode(e1), expressionComparer.GetHashCode(e2));
+        Assert.NotEqual(expressionComparer.GetHashCode(e1), expressionComparer.GetHashCode(e3));
+    }
+
```
Comment (cincuranet) [inline test/EFCore.Tests/Query/ExpressionEqualityComparerTest.cs]: This can be removed then.

**Review by cincuranet — CHANGES_REQUESTED** [review]
This is good. I posted some small requests corrections and we'll be good to go. I'll then make sure to backport it to 10.0 for servicing.

File: src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs [hunk 5]
```diff
@@ -2710,7 +2710,8 @@ public static IQueryable<TEntity> IgnoreQueryFilters<TEntity>(
                 Expression.Call(
                     instance: null,
                     method: IgnoreNamedQueryFiltersMethodInfo.MakeGenericMethod(typeof(TEntity)),
-                    arguments: [source.Expression, Expression.Constant(filterKeys)]))
+                    // converting the collection to an array if it isn't already one to ensure consistent caching
```
Comment (roji) [inline src/EFCore/Extensions/EntityFrameworkQueryableExtensions.cs]: Can we reference #37112 in the comment for context, and reference #37212 as a possible future solution?
