### PR TITLE
Fix to #17339 - Test: Re-enable Union_over_different_projection_types

### LINKED ISSUE #17339: Test: Re-enable Union_over_different_projection_types

### PR DESCRIPTION
**Pull request by maumar**
Resolves #17339

### CODE REVIEW

File: test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs [hunk 1]
```diff
@@ -387,6 +387,28 @@ public override async Task Union_over_different_projection_types(bool isAsync, s
...
+                "Binary" => leftSql.Replace("{Alias}", " AS [c]"),
+                "Column" => leftSql.Replace("{Alias}", ""),
+                "Constant" => leftSql.Replace("{Alias}", " AS [c]"),
+                "Function" => leftSql.Replace("{Alias}", " AS [c]"),
+                "ScalarSubquery" => leftSql.Replace("{Alias}", " AS [c]"),
+                "Unary" => leftSql.Replace("{Alias}", " AS [c]"),
+                _ => throw new ArgumentException("Unexpected type: " + leftType),
+            };
+
+            rightSql = rightType switch
```
Comment (smitpatel) [inline test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs]: non-switch expression.

File: test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs [hunk 2]
```diff
@@ -387,6 +387,28 @@ public override async Task Union_over_different_projection_types(bool isAsync, s
...
+            {
+                "Binary" => leftType == "Column" ? rightSql.Replace("{Alias}", " AS [OrderID]") : rightSql.Replace("{Alias}", " AS [c]"),
```
Comment (smitpatel) [inline test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs]: could possibly use ternary inside Replace method call.

File: test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs (hunk 1 above)
Comment (maumar) [reply test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs]: @smitpatel @roji did we not agree that it was OK to use them? I see a bunch of switch expressions in our codebase

Comment (smitpatel) [reply test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs]: Based on read-ability. left is method call so ok but methodcall and ternary is becoming complex.

Comment (roji) [reply test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs]: I personally find this within the acceptable usage range...

File: test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs [hunk 3]
```diff
@@ -387,6 +387,41 @@ public override async Task Union_over_different_projection_types(bool isAsync, s
...
+                case "Binary":
+                case "Constant":
+                case "Function":
+                case "ScalarSubquery":
+                case "Unary":
+                    leftSql = leftSql.Replace("{Alias}", " AS [c]");
+                    break;
+
+                default:
+                    throw new ArgumentException("Unexpected type: " + rightType);
```
Comment (smitpatel) [inline test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs]: leftType

File: test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs [hunk 4]
```diff
@@ -399,26 +434,26 @@ static string GenerateSql(string expressionType)
...
 FROM [Orders] AS [o]";
                     case "ScalarSubquery":
                         return @"SELECT (
     SELECT COUNT(*)
     FROM [Order Details] AS [o]
-    WHERE [o0].[OrderID] = [o].[OrderID])
+    WHERE [o0].[OrderID] = [o].[OrderID]){Alias}
 FROM [Orders] AS [o0]";
                     default:
                         throw new InvalidOperationException();
```
Comment (smitpatel) [inline test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs]: may be add error msg here also

File: test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs [hunk 5]
```diff
@@ -387,6 +387,41 @@ public override async Task Union_over_different_projection_types(bool isAsync, s
             var leftSql = GenerateSql(leftType);
             var rightSql = GenerateSql(rightType);
 
+            switch (leftType)
```
Comment (smitpatel) [inline test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs]: Looking at this switch block, it can be written using ternary directly. Only Column generates different. May be have switch block could help if it changes in future or it may be just YAGNI. I don't have any preference. Upto you.

File: test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs (hunk 1 above)
Comment (maumar) [reply test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs]: @roji I agree, this seems quite readable still. However, there is a lot of repetition so in this particular case old-school switch looks better.

File: test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs (hunk 3 above)
Comment (maumar) [reply test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.SetOperations.cs]: oops :)
