### PR TITLE
Use AssemblyQualifiedName to distinguish db functions.  Fix issue #18425

### LINKED ISSUE #18425: DbFunction translation considers two classes the same if they have the same name
Consider two different classes which are both called "Inner" and both have a method called "Min".
```C#
public static class OuterA {
	public static class Inner {
		public static decimal? Min(decimal? a, decimal? b) {
			throw new Exception();
		}
	}
}
public static class OuterB {
	public static class Inner {
		public static decimal? Min(decimal? a, decimal? b) {
			throw new Exception();
		}
	}
}
```
```C#
var methodA = typeof(OuterA.Inner).GetMethod(nameof(OuterA.Inner.Min));
var methodB = typeof(OuterB.Inner).GetMethod(nameof(OuterB.Inner.Min));
modelBuilder.HasDbFunction(methodA).HasTranslation(parameters => new SqlFunctionExpression("TestA", methodA.ReturnType, parameters));
modelBuilder.HasDbFunction(methodB).HasTranslation(parameters => new SqlFunctionExpression("TestB", methodB.ReturnType, parameters));
```
```C#
ctx.TestTable.Select(z => OuterA.Inner.Min(1, 2)).First();
ctx.TestTable.Select(z => OuterB.Inner.Min(1, 2)).First();
```
Both of the above queries translate to
```SQL
SELECT "TestB"(1.0, 2.0)
FROM "TEST_TABLE" "z"
FETCH FIRST 1 ROWS ONLY
```
If I rename one of the Inner classes, then the first query correctly calls TestA instead of TestB.

EF Core version: 2.2
Database provider: Microsoft.EntityFrameworkCore.Oracle
Target framework: .NET Framework 4.7
Operating system: Windows 10
IDE: Visual Studio 2017 15.8.6

### PR DESCRIPTION
**Pull request by pmiddleton**
Update dbfunctions to use the AssemblyQualifiedName in their annotation name.  This will prevent nested, and cross assembly, class functions from having name collisions.  

Fixes #18425

### CODE REVIEW

File: src/EFCore.Relational/Metadata/Internal/DbFunction.cs [hunk 1]
```diff
@@ -121,7 +121,8 @@ public static IEnumerable<DbFunction> GetDbFunctions([NotNull] Model model)
         private static string BuildAnnotationName(MethodBase methodBase)
             =>
                 // ReSharper disable once AssignNullToNotNullAttribute
-                $"{RelationalAnnotationNames.DbFunction}{methodBase.DeclaringType.ShortDisplayName()}{methodBase.Name}({string.Join(",", methodBase.GetParameters().Select(p => p.ParameterType.Name))})";
+                // ReSharper disable once PossibleNullReferenceException
+                $"{RelationalAnnotationNames.DbFunction}{methodBase.DeclaringType.AssemblyQualifiedName}{methodBase.Name}({string.Join(",", methodBase.GetParameters().Select(p => p.ParameterType.Name))})";
```
Comment (smitpatel) [inline src/EFCore.Relational/Metadata/Internal/DbFunction.cs]: Use namespace qualified name.

Comment (pmiddleton) [reply src/EFCore.Relational/Metadata/Internal/DbFunction.cs]: ParameterType.Name will only return Nullable`1 without the generic parameter for nullable fields  so I switched to Fullname to prevent collisions there as well.

File: src/EFCore.Relational/Metadata/Internal/DbFunction.cs [hunk 2]
```diff
@@ -121,7 +121,8 @@ public static IEnumerable<DbFunction> GetDbFunctions([NotNull] Model model)
         private static string BuildAnnotationName(MethodBase methodBase)
             =>
                 // ReSharper disable once AssignNullToNotNullAttribute
-                $"{RelationalAnnotationNames.DbFunction}{methodBase.DeclaringType.ShortDisplayName()}{methodBase.Name}({string.Join(",", methodBase.GetParameters().Select(p => p.ParameterType.Name))})";
+                // ReSharper disable once PossibleNullReferenceException
+                $"{RelationalAnnotationNames.DbFunction}{methodBase.DeclaringType.FullName}{methodBase.Name}({string.Join(",", methodBase.GetParameters().Select(p => p.ParameterType.FullName))})";
```
Comment (smitpatel) [inline src/EFCore.Relational/Metadata/Internal/DbFunction.cs]: Can we just use parameter's name rather than typeName? If user runs into clash they can always rename parameter name. It is pretty edge case anyway.
cc: @aspnet/efteam

Comment (pmiddleton) [reply src/EFCore.Relational/Metadata/Internal/DbFunction.cs]: We can go with the parameter name, but you do run the risk of collisions.  Any reason you don't want to use the fullName?

Comment (smitpatel) [reply src/EFCore.Relational/Metadata/Internal/DbFunction.cs]: @AndriySvyryd - Make a decision 😉

Comment (AndriySvyryd) [reply src/EFCore.Relational/Metadata/Internal/DbFunction.cs]: @pmiddleton The main reason is readability (even though only someone debugging will see it). Collisions can be avoided by renaming the parameters. But I don't feel strongly about this.
@ajcvickers Opinions?

Comment (bricelam) [reply src/EFCore.Relational/Metadata/Internal/DbFunction.cs]: I vote for namespace-qualified parameter type names (as it is here)

Comment (AndriySvyryd) [reply src/EFCore.Relational/Metadata/Internal/DbFunction.cs]: Parameter types it is then.

Comment (pmiddleton) [reply src/EFCore.Relational/Metadata/Internal/DbFunction.cs]: Ok - I will switch it back to FullName tonight.  I had changed to Name last night :)

Comment (pmiddleton) [reply src/EFCore.Relational/Metadata/Internal/DbFunction.cs]: Ok fixed.

**Comment by smitpatel** [comment]
Can we also update the commit message.
Windows build timed out on CI. I am looking into it.

**Comment by smitpatel** [comment]
cc: @Pilchie

**Comment by smitpatel** [comment]
@pmiddleton - Thanks 😄
