### PR TITLE
Make parameter binding API public

### LINKED ISSUE #14554: Custom proxy generation for entities
I would like to generate my own proxies for the entities returned by EF. 

The particular feature I would like to be able to implement, is similar to the LazyLoading proxies. But instead of lazy loading, I want to throw exceptions when un-loaded navigational properties are accessed.

And example navigational path could be Blog => Post => Comment.

A method that takes a Post as an argument might not know if the Comments list was loaded by the query. So if the Comments property is accessed, I would want my proxy to throw an exception, if there was no `Include` for that relation in the query.

Currently, the issue is that the property would just be null, which could be interpreted wrongly be the runtime code.

I looked at the LazyLoading implementation, but it seems most of the code required to do this is marked as "Internal, do not use", so I would suggest there was a supported way of doing this. (If there is, I could not find it, but would love to know)

### PR DESCRIPTION
**Pull request by ajcvickers**
This allows others to build proxies without using internal code.

Fixes #14554 #15252

Internal code is still being used for conventions.

### CODE REVIEW

File: src/EFCore/Metadata/EntityTypeParameterBinding.cs [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+namespace Microsoft.EntityFrameworkCore.Metadata
+{
+    /// <summary>
+    ///     Describes the binding of a <see cref="IEntityType" />, which may or may not also have and associated
+    ///     <see cref="IServiceProperty" />, to a parameter in a constructor, factory method, or similar.
+    /// </summary>
+    public class EntityTypeParameterBinding : ServiceParameterBinding
+    {
+        /// <summary>
+        ///     Creates a new <see cref="ServiceParameterBinding" /> instance for the given service type.
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/EntityTypeParameterBinding.cs]: Wrong type reference

File: src/EFCore/Metadata/FactoryMethodConstructorBinding.cs [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+            [NotNull] Type runtimeType)
+            : this(factoryMethod, parameterBindings, runtimeType)
+        {
+            Check.NotNull(factoryInstance, nameof(factoryInstance));
+
+            _factoryInstance = factoryInstance;
+        }
+
+        /// <summary>
+        ///     Creates a <see cref="MethodCallExpression" /> (possible wrapped to convert) using the given
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/FactoryMethodConstructorBinding.cs]: Fix grammar in parenthesis or remove them.

File: src/EFCore/Metadata/IConventionServiceProperty.cs [hunk 3]
```diff
@@ -32,5 +33,18 @@ public interface IConventionServiceProperty : IServiceProperty, IConventionPrope
         /// </summary>
         /// <returns> The configuration source. </returns>
         ConfigurationSource GetConfigurationSource();
+
+        /// <summary>
+        ///     Sets the <see cref="ServiceParameterBinding"/> for this property.
+        /// </summary>
+        /// <param name="parameterBinding"> The parameter binding. </param>
+        /// <param name="configurationSource"> The configuration source that is setting this facet. </param>
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/IConventionServiceProperty.cs]: This parameter should be `bool fromDataAnnotation = false`
