### PR TITLE
Cosmos: Properly handle nested owned types on owned collections

### LINKED ISSUE #18265: Cosmos: querying an entity with a nested owned collection throws
I have an item object that is an entity in an EF Core 3 DbContext that is pointing to a Cosmos Db. When I try to retrieve the record from the DbContext, I get the following exception:
An exception of type 'System.InvalidOperationException' occurred in System.Linq.Expressions.dll but was not handled in user code: 'When called from 'VisitLambda', rewriting a node of type 'System.Linq.Expressions.ParameterExpression' must return a non-null value of the same type. Alternatively, override 'VisitLambda' and change it to not visit children of this type.'

This error is only thrown when the Item's object owns many ItemImages and ItemImages Owns many ImageAttributes. The AddAsync command thows no error when this information is added to a CosmosDb store but it will error every time on retrieval.

Any attempt to do a FirstOrDefaultAsync or FindAsync results in the error.

### Steps to reproduce

I have attached sample code in a repository using VS code and the Cosmos Emulator.
https://github.com/TeaBaerd/CosmosEfCoreOwnsManyOwnsMany

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Consolidate Enumerable methods info
Print the declaring type name for static method calls

Fixes #18265

### CODE REVIEW

File: src/EFCore/Query/EnumerableMethods.cs [hunk 1]
```diff
@@ -0,0 +1,344 @@
...
+// Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.
+
+using System;
+using System.Collections.Generic;
+using System.Linq;
+using System.Reflection;
+
+namespace Microsoft.EntityFrameworkCore.Query
+{
+    public static class EnumerableMethods
```
Comment (smitpatel) [inline src/EFCore/Query/EnumerableMethods.cs]: No, we don't want to expose this. 😢

Comment (AndriySvyryd) [reply src/EFCore/Query/EnumerableMethods.cs]: So are we ok with exposing `QueryableMethods`?

Comment (smitpatel) [reply src/EFCore/Query/EnumerableMethods.cs]: QueryableMethods is what we translate in our pipeline. EnumerableMethods (apart from InMemory) is part of implementation detail for particular provider rather than required functionality. Let's discuss in person.

File: src/EFCore.Cosmos/Query/Internal/ContainsTranslator.cs [hunk 2]
```diff
@@ -5,6 +5,7 @@
 using System.Collections.Generic;
 using System.Linq;
 using System.Reflection;
+using Microsoft.EntityFrameworkCore.Query.Internal;
```
Comment (smitpatel) [inline src/EFCore.Cosmos/Query/Internal/ContainsTranslator.cs]: Internal code usage in providers?

Comment (AndriySvyryd) [reply src/EFCore.Cosmos/Query/Internal/ContainsTranslator.cs]: Because EnumerableMethods is Internal now. I'll move it to shared and make it real `internal`.

File: src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs [hunk 3]
```diff
@@ -162,12 +162,9 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
         {
             if (methodCallExpression.TryGetEFPropertyArguments(out var source, out var propertyName))
             {
-                if (!TryBindMember(Visit(source), MemberIdentity.Create(propertyName), out var result))
-                {
-                    throw new InvalidOperationException($"Property {propertyName} not found on {source}");
-                }
-
-                return result;
+                return TryBindMember(Visit(source), MemberIdentity.Create(propertyName), out var result)
```
Comment (smitpatel) [inline src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs]: Why return null? EF.Property cannot be used on non-ef-property.

Comment (AndriySvyryd) [reply src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs]: We'll throw a better exception if null is returned here.

Comment (AndriySvyryd) [reply src/EFCore.Cosmos/Query/Internal/CosmosSqlTranslatingExpressionVisitor.cs]: Also for include on collections we call EF.Property in a lambda, where we don't have the actual type

File: src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs [hunk 4]
```diff
@@ -109,12 +117,17 @@ public override Expression Visit(Expression expression)
...
+
                         return Expression.Call(
                             _getParameterValueMethodInfo.MakeGenericMethod(parameterExpression.Type),
                             QueryCompilationContext.QueryContextParameter,
                             Expression.Constant(parameterExpression.Name));
 
-                    case MaterializeCollectionNavigationExpression materializeCollectionNavigationExpression:
+                    case MaterializeCollectionNavigationExpression _:
                         return base.Visit(expression);
                     //return _selectExpression.AddCollectionProjection(
```
Comment (smitpatel) [inline src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs]: Remove this perhaps?

Comment (AndriySvyryd) [reply src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs]: But we'll need it when implementing non-owned include 😄

**Comment by smitpatel** [comment]
>                     shaperExpression = unaryExpression.Operand as EntityShaperExpression;

This should also check NodeType of UnaryExpression. (Assuming only convert is allowed)


---
Refers to: src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs:193 in 4d082f8. [](commit_id = 4d082f8aa11a90944b3d65d46b2d389bc52a7932, deletion_comment = False)

**Comment by smitpatel** [comment]
>                 case ProjectionBindingExpression innerProjectionBindingExpression:

This assumes that projectionBinding is always mapped by Index. Is that always true? Can it not be projection mapping?

---
Refers to: src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs:195 in 4d082f8. [](commit_id = 4d082f8aa11a90944b3d65d46b2d389bc52a7932, deletion_comment = True)

**Comment by smitpatel** [comment]
>                     innerEntityProjection = (EntityProjectionExpression)((UnaryExpression)unaryExpression.Operand).Operand;

Should there be type safety check? Or we have invariant in pipeline for this?

---
Refers to: src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs:201 in 4d082f8. [](commit_id = 4d082f8aa11a90944b3d65d46b2d389bc52a7932, deletion_comment = True)

File: src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs [hunk 5]
```diff
@@ -269,6 +282,15 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
 
                         break;
 
+                    case ParameterExpression parameterExpression:
```
Comment (smitpatel) [inline src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs]: Do we need similar processing for Member case?

File: src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs [hunk 6]
```diff
@@ -326,6 +360,49 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
+                        case nameof(Queryable.AsQueryable)
+                        when genericMethod == QueryableMethods.AsQueryable:
+                            // Unwrap AsQueryable
+                            return visitedSource;
+
+                        case nameof(Queryable.Select)
+                        when genericMethod == QueryableMethods.Select:
+                            var shaper = visitedSource as CollectionShaperExpression;
+
+                            LambdaExpression lambda = null;
```
Comment (smitpatel) [inline src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs]: UnwrapLambdaFromQuote

File: src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs [hunk 7]
```diff
@@ -326,6 +360,49 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
+                    switch (method.Name)
+                    {
+                        case nameof(Queryable.AsQueryable)
+                        when genericMethod == QueryableMethods.AsQueryable:
+                            // Unwrap AsQueryable
+                            return visitedSource;
+
+                        case nameof(Queryable.Select)
+                        when genericMethod == QueryableMethods.Select:
+                            var shaper = visitedSource as CollectionShaperExpression;
```
Comment (smitpatel) [inline src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs]: What happens if shaper becomes null?

File: src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs [hunk 8]
```diff
@@ -326,6 +360,49 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
+                                case UnaryExpression unaryExpression:
+                                    lambda = unaryExpression.Operand as LambdaExpression;
+                                    break;
+                            }
+
+                            _collectionShaperMapping.Add(lambda.Parameters.Single(), shaper);
+
+                            var genericArguments = method.GetGenericArguments();
+                            return Expression.Call(
+                                EnumerableMethods.Select.MakeGenericMethod(
```
Comment (smitpatel) [inline src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs]: Can you pass the array directly?

File: src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs [hunk 9]
```diff
@@ -326,6 +360,49 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
+                                    genericArguments[0],
+                                    genericArguments[1]),
+                                shaper,
+                                Visit(lambda));
```
Comment (smitpatel) [inline src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs]: Just visit body and reconstruct lambda. Visiting Lambda can have unintended side-effects.

**Comment by smitpatel** [comment]
>                             else if (projectionExpression is UnaryExpression convertExpression)

Also check nodeType?


---
Refers to: src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitor.cs:101 in 4d082f8. [](commit_id = 4d082f8aa11a90944b3d65d46b2d389bc52a7932, deletion_comment = True)

**Comment by smitpatel** [comment]
>                             var projectionExpression = ((UnaryExpression)binaryExpression.Right).Operand;

Another invariant?

---
Refers to: src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitor.cs:91 in 4d082f8. [](commit_id = 4d082f8aa11a90944b3d65d46b2d389bc52a7932, deletion_comment = False)

File: src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs (hunk 5 above)
Comment (AndriySvyryd) [reply src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs]: You mean checking the unary type? I'll add it

File: src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitor.cs [hunk 10]
```diff
@@ -200,6 +198,42 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
                     return CreateGetValueExpression(innerExpression, property, methodCallExpression.Type);
                 }
 
+                if (method.DeclaringType == typeof(Enumerable)
+                    || method.DeclaringType == typeof(EnumerableExtensions))
+                {
+                    var genericMethod = method.IsGenericMethod ? method.GetGenericMethodDefinition() : null;
```
Comment (smitpatel) [inline src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitor.cs]: Can hoist it outside to use in previous if too.

File: src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitor.cs [hunk 11]
```diff
@@ -200,6 +198,42 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
+
+                    if (method.Name == nameof(Enumerable.Select)
+                        && genericMethod == EnumerableMethods.Select)
+                    {
+                        LambdaExpression lambda = null;
```
Comment (smitpatel) [inline src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitor.cs]: UnwrapLambda, Also if you are here then you should not have quote around lambda for enumerable methods. Probably you need to unwrap during translation.

File: src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs (hunk 7 above)
Comment (AndriySvyryd) [reply src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs]: Nothing good. I'll add return null.

File: src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs (hunk 5 above)
Comment (smitpatel) [reply src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs]: VisitMethodCall you are checking for collectionShaperMapping. Do we need to do similar to VisitMember? Probably it is here because we generated nested include. Perhaps it could allow us to support nested selects on owned collection. Low priority. Saw VisitMethodCall being different from VisitMember so commented.

**Comment by AndriySvyryd** [comment]
>                 case ProjectionBindingExpression innerProjectionBindingExpression:

For now Member would only be called in an Index projectionBinding, I think we would only need projection mapping if we allow querying unmapped properties unless you can think of a different case off top of your head.

---
In reply to: [545169128](https://github.com/aspnet/EntityFrameworkCore/pull/18461#issuecomment-545169128) [](ancestors = 545169128)

---
Refers to: src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs:195 in 4d082f8. [](commit_id = 4d082f8aa11a90944b3d65d46b2d389bc52a7932, deletion_comment = True)

**Comment by AndriySvyryd** [comment]
>                     innerEntityProjection = (EntityProjectionExpression)((UnaryExpression)unaryExpression.Operand).Operand;

This is an invariant - we always need to cast the projection to ValueBuffer and we only support Member on entity projection. I guess we could throw a better exception message if it's not, but I would need to think to come up with a test case.

---
In reply to: [545171073](https://github.com/aspnet/EntityFrameworkCore/pull/18461#issuecomment-545171073) [](ancestors = 545171073)

---
Refers to: src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs:201 in 4d082f8. [](commit_id = 4d082f8aa11a90944b3d65d46b2d389bc52a7932, deletion_comment = True)

File: src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs (hunk 5 above)
Comment (AndriySvyryd) [reply src/EFCore.Cosmos/Query/Internal/CosmosProjectionBindingExpressionVisitor.cs]: I see, yes we would need it for nested selects on owned collection, but it wouldn't be enough to make them work. I guess it would fall under #17957

---
In reply to: [337776476](https://github.com/aspnet/EntityFrameworkCore/pull/18461#discussion_r337776476) [](ancestors = 337776476)

File: src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitor.cs [hunk 12]
```diff
@@ -200,6 +202,30 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
                     return CreateGetValueExpression(innerExpression, property, methodCallExpression.Type);
                 }
 
+                if (method.DeclaringType == typeof(Enumerable)
+                    || method.DeclaringType == typeof(EnumerableExtensions))
+                {
+                    if (method.Name == nameof(Enumerable.Select)
```
Comment (smitpatel) [inline src/EFCore.Cosmos/Query/Internal/CosmosShapedQueryCompilingExpressionVisitor.CosmosProjectionBindingRemovingExpressionVisitor.cs]: Merge Ifs.
Remove EnumerableExtensions
