### PR TITLE
[2.1] Query: Fix for GroupByAggregate with join on grouping key produces incorrect sql

### LINKED ISSUE #11814: Query: GroupByAggregate with join on grouping key produces incorrect sql
Repro:

```cs
from c in cs
join a in os.GroupBy(o => o.CustomerID)
			.Where(g => g.Count() > 5)
			.Select(g => new { g.Key, LastOrderID = g.Max(o => o.OrderID) })
	on c.CustomerID equals a.Key
select new { c, a.LastOrderID }
```

produces the following sql:

```sql
SELECT [c].[CustomerID], [c].[Address], [c].[City], [c].[CompanyName], [c].[ContactName], [c].[ContactTitle], [c].[Country], [c].[Fax], [c].[Phone], [c].[PostalCode], [c].[Region], [t].[Key], [t].[LastOrderID]
FROM [Customers] AS [c]
INNER JOIN (
    SELECT [o].[CustomerID] AS [Key], MAX([o].[OrderID]) AS [LastOrderID]
    FROM [Orders] AS [o]
    GROUP BY [o].[CustomerID]
    HAVING COUNT(*) > 5
) AS [t] ON [c].[CustomerID] = [o].[CustomerID] AS [Key]
```

we shouldn't be adding AS Key alias at the end

### PR DESCRIPTION
**Pull request by smitpatel**
Issue: We save `Key` memberInfo to translation mapping in SelectExpression so we can bind `Key` later.
In this query, we also had anonymous projection in aggregate which projected out `Key` which would be essentially same projection but different `MemberInfo`
This causes us to have multiple `MemberInfo`s with same projection.
During `PushDownSubquery()`, we always lifted first `MemberInfo` matching current projection. This caused us to have stale entry in mapping.
In this particular scenario it got used and generated wrong query. (In other cases, we were corrupting mapping but never used it).

Fix:
Correct fix is to remove the stale mapping since the older memberInfo cannot be referenced further. So during the set method, we remove if there is existing mapping to same projection.
This has minor issue in case when GroupBy is done on anonymous object since it causes the inner select to be pushed down inside the elementSelector which requires the older mapping to map correctly. Fix is to update new mapping from key translation only after we have visited elementSelector too.

Resolves #11814

### CODE REVIEW

File: src/EFCore.Relational/Query/Expressions/SelectExpression.cs [hunk 1]
```diff
@@ -938,6 +938,15 @@ public virtual void SetProjectionForMemberInfo([NotNull] MemberInfo memberInfo,
             Check.NotNull(memberInfo, nameof(memberInfo));
             Check.NotNull(projection, nameof(projection));
 
+            var existingMemberInfo = _memberInfoProjectionMapping.FirstOrDefault(
+                        kvp => ExpressionEqualityComparer.Instance.Equals(kvp.Value, projection))
```
Comment (ilmax) [inline src/EFCore.Relational/Query/Expressions/SelectExpression.cs]: FirstOrDefault could return null, so I think we should probably access `Key` with the elvis operator

File: src/EFCore.Specification.Tests/Query/AsyncGroupByQueryTestBase.cs [hunk 2]
```diff
@@ -1253,6 +1253,21 @@ private bool Equals(CompositeDto other)
                 entryCount: 133);
         }
 
+        [ConditionalFact]
+        public virtual async Task Join_GroupBy_Aggregate_on_key()
+        {
+            await AssertQuery<Order, Customer>(
```
[the remark this answers is not in the document]
Comment (smitpatel) [reply src/EFCore.Specification.Tests/Query/AsyncGroupByQueryTestBase.cs]: They are needed for compilation.
Either we await AssertQuery or we return the task. But every task returned by AssertQuery is different type so we cannot use Task without generic parameters.

File: src/EFCore.Relational/Query/Expressions/SelectExpression.cs (hunk 1 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/Expressions/SelectExpression.cs]: It is actually neither required nor compile-able for dictionary.
FirstOrDefault for a dict always returns a KeyValuePair. If it is not found then it returns KVP with default values of key & value in it. So we don't need null safety here but the key could be null if not found.

Comment (ilmax) [reply src/EFCore.Relational/Query/Expressions/SelectExpression.cs]: That's true, my bad... I didn't notice it was a dictionary :|
