### PR TITLE
Fix reload when nullable complex property is null

### LINKED ISSUE #37559: EF 10: EntityEntry.ReloadAsync throws when nullable complex property is null
### Bug description

Calling EntityEntry.ReloadAsync() on an entity with a nullable complex property throws an InvalidOperationException when the complex property is null.
In the repro below, Product.Price is configured as optional, but reloading the entity fails because EF attempts to materialize required members (Amount, CurrencyId) of the complex type even though the complex property itself is null.

### Your code

```csharp
#:package Npgsql.EntityFrameworkCore.PostgreSQL@10.0.0
#:package Microsoft.EntityFrameworkCore.Relational@10.0.2
#:property PublishAot=false

using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

await using var context = new ProductContext();
await context.Database.EnsureDeletedAsync();
await context.Database.EnsureCreatedAsync();

context.Products.Add(new());
await context.SaveChangesAsync();

await context.ChangeTracker.Entries().First().ReloadAsync();
;

public sealed class ProductContext : DbContext
{
    public DbSet<Product> Products { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder
            .UseNpgsql("Host=localhost;Username=postgres;Password=postgres;Database=Test")
            .LogTo(Console.WriteLine, LogLevel.Information)
            .EnableSensitiveDataLogging();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
        => modelBuilder.Entity<Product>().ComplexProperty(x => x.Price, x =>
        {
            x.IsRequired(false);
        });
}

public sealed class Product
{
    public int Id { get; private set; }
    public Price? Price { get; set; }
}

public sealed class Price
{
    public required decimal Amount { get; init; }
    public required int CurrencyId { get; init; }
}
```

### Stack traces

```text
An exception of type 'System.InvalidOperationException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'The property 'Amount' contains null on entity 'Product' with the key value '{Amount: 0}', but the property is marked as required.'
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.HandleConceptualNulls(Boolean sensitiveLoggingEnabled, Boolean force, Boolean isCascadeDelete)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntryBase.HandleNullForeignKey(IProperty property, Boolean setModified, Boolean isCascadeDelete)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntryBase.SetProperty(IPropertyBase propertyBase, Object value, Boolean isMaterialization, Boolean setModified, Boolean isCascadeDelete, CurrentValueType valueType)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntryBase.SetProperty(IPropertyBase propertyBase, Object value, Boolean isMaterialization, Boolean setModified, Boolean isCascadeDelete)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntryBase.set_Item(IPropertyBase propertyBase, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.CurrentPropertyValues.SetValueInternal(IInternalEntry entry, IPropertyBase property, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntryPropertyValues.SetValues(PropertyValues propertyValues)
   at Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry.Reload(PropertyValues storeValues)
   at Microsoft.EntityFrameworkCore.ChangeTracking.EntityEntry.<ReloadAsync>d__54.MoveNext()
```

### Verbose output

```text

```

### EF Core version

10.0.2

### Database provider

Npgsql.EntityFrameworkCore.PostgreSQL

### Target framework

.NET 10.0.2

### Operating system

Windows 11

### IDE

VSCode

### PR DESCRIPTION
**Pull request by thromel**
## Summary
Reloading an entity with a nullable complex property set to null in the store could throw a conceptual-null error when the complex contained required members. The store value projection was reading non-nullable value types, losing nulls and causing the complex to be treated as non-null.

## Fix
- Preserve nulls for value-type members inside nullable complex properties when projecting store values.
- Compute nullable-complex null flags from store values and pass them into `ArrayPropertyValues` so reload skips nested required members when the complex is null.
- Add regression coverage for reload on optional complex properties.

## Closes issue when merged
- Fixes #37559

## Test Plan
- [x] Sqlite: reload optional complex property with null store values (PropertyValuesSqliteTest / Reloading_optional_complex_property_with_null_does_not_throw)
- [x] InMemory: reload optional complex property with null store values (PropertyValuesInMemoryTest / Reloading_optional_complex_property_with_null_does_not_throw)
- [x] SqlServer: reload optional complex property with null store values (PropertyValuesSqlServerTest / Reloading_optional_complex_property_with_null_does_not_throw)

## ORCID
- https://orcid.org/0009-0009-2432-8960

### CODE REVIEW

File: src/EFCore/ChangeTracking/EntityEntry.cs [hunk 1]
```diff
@@ -633,8 +634,65 @@ public virtual PropertyValues OriginalValues
     public virtual async Task<PropertyValues?> GetDatabaseValuesAsync(CancellationToken cancellationToken = default)
     {
         var values = await Finder.GetDatabaseValuesAsync(InternalEntry, cancellationToken).ConfigureAwait(false);
+        var nullComplexPropertyFlags = values == null ? null : CreateNullComplexPropertyFlags(InternalEntry, values);
 
-        return values == null ? null : new ArrayPropertyValues(InternalEntry, values, null);
+        return values == null ? null : new ArrayPropertyValues(InternalEntry, values, nullComplexPropertyFlags);
+    }
+
+    private static bool[]? CreateNullComplexPropertyFlags(InternalEntityEntry entry, object?[] values)
```
Comment (AndriySvyryd) [inline src/EFCore/ChangeTracking/EntityEntry.cs]: Add a constructor to `ArrayPropertyValues` that doesn't take `nullComplexPropertyFlags` and put the logic below in it. It will have access to `PropertyValues.NullableComplexProperties` so it can be simplified

File: test/EFCore.Specification.Tests/PropertyValuesTestBase.cs [hunk 2]
```diff
@@ -3195,6 +3195,21 @@ public virtual void Nullable_complex_property_with_null_value_returns_null_when_
...
     }
 
+    [ConditionalFact]
+    public virtual async Task Reloading_optional_complex_property_with_null_does_not_throw()
+    {
+        using var context = CreateContext();
+        var building = Building.Create(Guid.NewGuid(), "Building Null", 123m);
+        building.OptionalMilk = null;
+        context.Add(building);
+        await context.SaveChangesAsync();
```
Comment (AndriySvyryd) [inline test/EFCore.Specification.Tests/PropertyValuesTestBase.cs]: Don't call `SaveChangesAsync`, instead modify SeedAsync to make `OptionalMilk` null on "Building Two"

File: src/EFCore/Internal/EntityFinder.cs [hunk 3]
```diff
@@ -863,11 +863,14 @@ private static Expression<Func<object, object[]>> BuildProjection(IEntityType en
                 path.Add(complexType.ComplexProperty);
             }
```
Comment (AndriySvyryd) [inline src/EFCore/Internal/EntityFinder.cs:871]: Instead of calculating nullability in `IsInNullableComplexProperty` you can do it in this loop and inline `GetReadType`

**Comment by AndriySvyryd** [comment]
Thanks for your contribution!
