### PR TITLE
ExpressionPrinter fixes/cleanup

### LINKED ISSUE #18413: Query: clean-up expression printer when we can do breaking changes
We can make expression printer internal, since we expose Print method on `ExpressionExtensions`

Also, currently we repurposed 'generateUniqueParameterIds' to mean general optimized vs debug output. We should rename it to something more appropriate.

### LINKED ISSUE #18709: Query: expression printer should still print type argument for Cast and OfType
Currently just prints out Method name, like for all other Enumerable/Queryable methods

### PR DESCRIPTION
**Pull request by maumar**
Fix to #18709 - Query: expression printer should still print type argument for Cast and OfType
Fix to #18413 - Query: clean-up expression printer when we can do breaking changes

Resolves #18709
Resolves #18413

### CODE REVIEW

File: src/EFCore/Query/ExpressionPrinter.cs [hunk 1]
```diff
@@ -53,8 +53,7 @@ public ExpressionPrinter()
         }
 
         private int? CharacterLimit { get; set; }
-
-        private bool GenerateUniqueParameterIds { get; set; }
+        private bool Verbose { get; set; }
```
Comment (smitpatel) [inline src/EFCore/Query/ExpressionPrinter.cs]: Is there any specific reason these are private properties rather than fields?
