### PR TITLE
Query: Removing Queryable conversion for sources which are not queryable

### LINKED ISSUE #17374: Latest builds incompatible with some PostgreSQL array scenarios
When syncing EFCore.PG to latest preview9, some array scenarios are now breaking.

Exception:
```c#
Processing of the LINQ expression 'AsQueryable<int>(NavigationTreeExpression
    Value: EntityReferenceSomeArrayEntity
    Expression: (Unhandled parameter: s).SomeArray)' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in /home/roji/projects/EFCore/src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs:line 573
```

Query:
```c#
var count = ctx.SomeEntities.Count(e => e.SomeArray.Any());
```

Expression tree before NavigationExpandingExpressionVisitor:
```
value(Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1[Npgsql.EntityFrameworkCore.PostgreSQL.Query.ArrayQueryTest+SomeArrayEntity]).Count(e => e.SomeArray.AsQueryable().Any())
```

Basically NavigationExpandingExpressionVisitor freaks out when it sees a queryable method (AsQueryable) on an array.

/cc @smitpatel

### PR DESCRIPTION
**Pull request by smitpatel**
Our EnumerableToQueryable converter works on all the methods. But during nav expansion, we actually inject query sources.
If item is not a query source (like postgre arrays or collection property mapped as scalar via value conversion), then we convert it to enumerable again to be handled by provider.

Resolves #17374

### CODE REVIEW

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs [hunk 1]
```diff
@@ -618,6 +633,128 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
             return ProcessUnknownMethod(methodCallExpression);
         }
 
+        private MethodCallExpression ConvertToEnumerable(MethodInfo queryableMethod, List<Expression> arguments)
+        {
+            var genericTypeArguments = queryableMethod.IsGenericMethod
+                ? queryableMethod.GetGenericArguments()
+                : null;
+            var enumerableArguments = arguments.Select(
+                arg => arg is UnaryExpression unaryExpression
```
Comment (maumar) [inline src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs]: use unwrap lambda helper

Comment (smitpatel) [reply src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.cs]: I tried using it but test failed. Not all arguments are LambdaExpression.
