### PR TITLE
Fix to #15720 - Query: Subquery Member pushdown

### LINKED ISSUE #15363: Consecutive calls to FirstOrDefault() in a projection not translatable
We got a model that's set up as a 1:n and 1:n
- `Foo` has many `Intermediate`s - `Intermediate` has exactly one `Foo`
- `Intermediate` has many `Bar`s - `Bar` has exactly one `Intermediate`

The use case is to select the first `Bar` from the first `Intermediate` from every `Foo`. Sounds weird, but the query should be self-explanatory:
```Foos.Select(foo => foo.Intermediates.FirstOrDefault().Bars.FirstOrDefault())```

This query won't get translated:
```
Exception message: Error generated for warning 'Microsoft.EntityFrameworkCore.Query.QueryClientEvaluationWarning: The LINQ expression 'FirstOrDefault()' could not be translated and will be evaluated locally.'. This exception can be suppressed or logged by passing event ID 'RelationalEventId.QueryClientEvaluationWarning' to the 'ConfigureWarnings' method in 'DbContext.OnConfiguring' or 'AddDbContext'.
Stack trace:    at Microsoft.EntityFrameworkCore.Diagnostics.EventDefinition`1.Log[TLoggerCategory](IDiagnosticsLogger`1 logger, WarningBehavior warningBehavior, TParam arg, Exception exception)
   at Microsoft.EntityFrameworkCore.Internal.RelationalLoggerExtensions.QueryClientEvaluationWarning(IDiagnosticsLogger`1 diagnostics, QueryModel queryModel, Object queryModelElement)
   at Remotion.Linq.QueryModelVisitorBase.VisitResultOperators(ObservableCollection`1 resultOperators, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.ProjectionExpressionVisitor.VisitSubQuery(SubQueryExpression expression)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitSelectClause(SelectClause selectClause, QueryModel queryModel)
   at Remotion.Linq.QueryModelVisitorBase.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryModelVisitor.VisitQueryModel(QueryModel queryModel)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.CreateQueryExecutor[TResult](QueryModel queryModel)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](Expression query, IQueryModelGenerator queryModelGenerator, IDatabase database, IDiagnosticsLogger`1 logger, Type contextType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass13_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Remotion.Linq.QueryableBase`1.GetEnumerator()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at EFCoreBug.Program.Main() in C:\Users\Path\to\Project\EFCoreBug\Program.cs:line 17
```

### Steps to reproduce
The following domain-model was used to reproduce the issue.
```c#
public class Foo
{
    [Key]
    public Guid Id { get; set; }

    public ISet<Intermediate> Intermediates { get; } = new HashSet<Intermediate>();
}

public class Intermediate
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    public Foo Foo { get; set; }
    
    public ISet<Bar> Bars { get; } = new HashSet<Bar>();
}

public class Bar
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    public Intermediate Intermediate { get; set; }
}
```
The context was set up as shown below
```c#
public class MyContext : DbContext
{
    public DbSet<Foo> Foos { get; set; }

    private const string ConnectionString = @"Data Source=(LocalDB)\MSSQLLocalDB;Initial Catalog=efbug-integration;Integrated Security=true;";

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        optionsBuilder.ConfigureWarnings(warnings =>
        {
            warnings.Throw(RelationalEventId.QueryClientEvaluationWarning);
        });

        optionsBuilder.UseSqlServer(ConnectionString);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Foo>();
    }
}
```
And a test program
```c#
public class Program
{
    public static void Main()
    {
        using (var ctx = new MyContext())
        {
            ctx.Database.EnsureCreated();

            //Ok
            var query1 = ctx.Foos.Select(foo => foo.Intermediates.FirstOrDefault()).ToList();

            //Ok
            var query2 = ctx.Foos.Select(foo => foo.Intermediates.FirstOrDefault().Bars).ToList();

            //Not translatable - exception see above
            var query3 = ctx.Foos.Select(foo => foo.Intermediates.FirstOrDefault().Bars.FirstOrDefault()).ToList();
        }

    }
}
```

### Further technical details
EF Core version: 2.2.4
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2017 and 2019

cc @axelheer

### PR DESCRIPTION
**Pull request by maumar**
Problem was we were not handling a scenario with nested FirstOrDefault, e.g. customers.Select(c => orders.Select(orderDetails.FirstOrDefault()).FirstOrDefault().DetailName)
In this case we need to recursively pushdown the property until we don't encounter cardinality reducing operator.

Also resolves #15363 - Consecutive calls to FirstOrDefault() in a projection not translatable
This was already working but adding a test.

### CODE REVIEW

File: src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor.cs [hunk 1]
```diff
@@ -58,6 +58,30 @@ protected override Expression VisitExtension(Expression extensionExpression)
             string propertyName,
             Type resultType)
         {
+            // in case of nested FirstOrDefaults, we need to dig into the inner most - that's where the member finally gets pushed down to
+            if (navigationExpansionExpression.State.PendingSelector.Body is NavigationExpansionExpression navigationExpansionPendingSelector
+                && navigationExpansionPendingSelector.State.PendingCardinalityReducingOperator != null)
+            {
+                var newPendingSelector = (NavigationExpansionExpression)ProcessMemberPushdown(source, navigationExpansionPendingSelector, efProperty, memberInfo, propertyName, resultType);
+
+                var newStateNested = new NavigationExpansionExpressionState(
```
Comment (smitpatel) [inline src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor.cs]: There should be function to change each element given most of the state are the same

Comment (maumar) [reply src/EFCore/Query/NavigationExpansion/Visitors/NavigationExpandingVisitor.cs]: good idea, but will do it later, when I clean up the code

File: test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs [hunk 2]
```diff
@@ -615,17 +615,13 @@ public override void Select_Where_Subquery_Deep_First()
...
                 @"@__p_0='2'
 
-SELECT TOP(@__p_0) [od].[OrderID], [od].[ProductID], [od].[Discount], [od].[Quantity], [od].[UnitPrice]
-FROM [Order Details] AS [od]
-WHERE (
-    SELECT TOP(1) (
-        SELECT TOP(1) [c].[City]
+SELECT TOP(@__p_0) [o].[OrderID], [o].[ProductID], [o].[Discount], [o].[Quantity], [o].[UnitPrice]
+FROM [Order Details] AS [o]
+WHERE (SELECT TOP(1) (SELECT TOP(1) [c].[City]
```
Comment (smitpatel) [inline test/EFCore.SqlServer.FunctionalTests/Query/SimpleQuerySqlServerTest.cs]: Add line break as it was in previous
