### PR TITLE
SqlServer: Generate Bool literal correctly

### LINKED ISSUE #14956: SqlServer should have own bool type mapping
Currently SqlServer uses `BoolTypeMapping` from relational. Which prints literal as `1 / 0`. In SqlServer those literals are always interpreted as int (numeric). While it would all work in comparison etc since data type precedence would kick in. It fails miserably in projection since we are trying to read back bool and SqlServer returns an int. SqlServer should have own type mapping which generate `1 / 0` casted to bit.

We already do that for float maps to real & double maps to float and floating point constant are considered float rather than real so we have to do casting when generating float.
https://github.com/aspnet/EntityFrameworkCore/blob/9be0341cfc60a852b7c30da444b460702e0a055d/src/EFCore.SqlServer/Storage/Internal/SqlServerFloatTypeMapping.cs#L49-L50

### PR DESCRIPTION
**Pull request by smitpatel**
This also removes hacky code to generate cast in projection.

Resolves #14956

### CODE REVIEW

File: src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs [hunk 1]
```diff
@@ -2078,6 +2058,14 @@ private static Expression BuildCompareToExpression(Expression expression, bool c
                     expression,
                     Expression.Constant(compareTo, expression.Type));
 
+                // If False is converted to False == True, replace it with 0 == 1
```
Comment (maumar) [inline src/EFCore.Relational/Query/Sql/DefaultQuerySqlGenerator.cs]: fix for compareTo == false

File: test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs [hunk 2]
```diff
@@ -345,7 +345,7 @@ public override void From_sql_queryable_simple_projection_composed()
 FROM (
     SELECT *
     FROM ""Products""
-    WHERE ""Discontinued"" <> 1
+    WHERE ""Discontinued"" <> CAST(1 AS bit)
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs]: Isn't this a degradation in terms of the SQL being produced, assuming that in this context a simple `1` worked well?

Comment (smitpatel) [reply test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs]: It is degradation but regressions are facts of life. :trollface: 

On serious note,
The issue is, SqlServer cannot read bool value out of non-bool column in results. So we always need to make sure that we don't end up with something non-bool.
The case where simple `1` worked, it did implicit type conversion to convert both sides to int and that worked. Now if you do this on top level projection then you are stuck again because you would be reading an int value. We had specific work-around in the place for `CAST(COALESCE(t.NullableBoolColumn, 1) AS BIT)` so that we read back bool values. Also we have `TypeTrueLiteral` so that we generate 1/0 in case block as bit in order to read back bool value which was another hack for SqlServer only.

Now the challenges 
- In projection, you need to print out bool literal
  - Typemapping needs to understand the context for literal generation which makes it worse for all providers & types just for SqlServer & bool.
  - Query translation can have different types mapping in different parts so we can print out 1 as int but that can cause issue in type system + SqlTranslator does not know where the expression would be placed in SQL + TypeMapping does not provide info on how to combine 2 different TypeMappings.
  - We can do cast on top level like coalesce case but then you would have to traverse whole projection expression to identify if there is any literal & of bool type & result is bool type then put cast around it. Which is kind of do-able but complex.

All in all, while SQL worsened here, it feels like the literal we generated is of correct type rather than trying to simpler SQL and then working around bugs in other ways.

Comment (roji) [reply test/EFCore.SqlServer.FunctionalTests/Query/FromSqlQuerySqlServerTest.cs]: Yuck... I understand (some of) the complexity. In any case it's great that at least now it's restricted to SQL Server and doesn't affect others. Thanks for the explanation!
