### PR TITLE
Query: Enable throwing behavior for Single/SingleOrDefault on top level

### LINKED ISSUE #15866: Query: Identity query failures
With the new pipeline, queries of the following form are failing:
```C#
await UserClaims.Where(uc => uc.UserId.Equals(user.Id)).Select(c => c.ToClaim()).ToListAsync(cancellationToken);
```

Issues of the following form may also be failing, but this may be a red herring:
```C#
Users.SingleOrDefaultAsync(u => u.NormalizedEmail == normalizedEmail, cancellationToken);
```

### PR DESCRIPTION
**Pull request by smitpatel**
In future we need to detect cases when it is used inside subquery to not throw but currently all such tests are disabled because it was doing client eval in previous pipeline

Part of #15559
Resolves #15866

### CODE REVIEW

File: src/EFCore.Relational/Query/Pipeline/RelationalQueryableMethodTranslatingExpressionVisitor.cs [hunk 1]
```diff
@@ -728,7 +728,7 @@ protected override ShapedQueryExpression TranslateSingleOrDefault(ShapedQueryExp
             }
 
             var selectExpression = (SelectExpression)source.QueryExpression;
-            selectExpression.ApplyLimit(TranslateExpression(Expression.Constant(1)));
+            selectExpression.ApplyLimit(TranslateExpression(Expression.Constant(2)));
```
Comment (maumar) [inline src/EFCore.Relational/Query/Pipeline/RelationalQueryableMethodTranslatingExpressionVisitor.cs]: we need to fix this in case of subqueries eventually.

Comment (smitpatel) [reply src/EFCore.Relational/Query/Pipeline/RelationalQueryableMethodTranslatingExpressionVisitor.cs]: #15559 is still open for that. I will add notes from our discussion there.
