### PR TITLE
Fix to #17531 - Query: incorrect results for queries with optional navigation followed by collection navigation with skip/take/distinct

### LINKED ISSUE #17531: Query: incorrect results for queries with optional navigation followed by collection navigation with skip/take/distinct
query:

```cs
from l1 in ctx.LevelOnes
select l1.OneToOne_Optional_FK1.OneToMany_Optional2.Take(50)
```

generated sql:

```sql
SELECT l.Id, t.Id, t.Level2_Optional_Id, t.Level2_Required_Id, t.Name, t.OneToMany_Optional_Inverse3Id, t.OneToMany_Optional_Self_Inverse3Id, t.OneToMany_Required_Inverse3Id, t.OneToMany_Required_Self_Inverse3Id, t.OneToOne_Optional_PK_Inverse3Id, t.OneToOne_Optional_Self3Id
    FROM LevelOne AS l
    LEFT JOIN LevelTwo AS l1 ON l.Id == l1.Level1_Optional_Id
    OUTER APPLY 
    (
        SELECT TOP(50) l0.Id, l0.Level2_Optional_Id, l0.Level2_Required_Id, l0.Name, l0.OneToMany_Optional_Inverse3Id, l0.OneToMany_Optional_Self_Inverse3Id, l0.OneToMany_Required_Inverse3Id, l0.OneToMany_Required_Self_Inverse3Id, l0.OneToOne_Optional_PK_Inverse3Id, l0.OneToOne_Optional_Self3Id
        FROM LevelThree AS l0
        WHERE ((l1.Id == l0.OneToMany_Optional_Inverse3Id) && ( l1.Id IS NOT NULL && l0.OneToMany_Optional_Inverse3Id IS NOT NULL)) || (l1.Id IS NULL &&  l0.OneToMany_Optional_Inverse3Id IS NULL)
    ) AS t
    ORDER BY l.Id ASC, t.Id ASC
```

Problem is that initially in nav rewrite for collection navigation we introduce correlation predicate in form of equality. In simple case (i.e. without Skip/Take/Distinct) that gets converted into join, and the correlation predicate gets converted to join condition.

However here, we can't do that, so the collection remains as a subquery and the correlation predicate remains equality. Then, null semantics gets applied and if both sides of the correlation predicate are null, the result is a match - which is incorrect in case of correlating navigations.

We should add condition to the correlation predicate that would filter out cases where outer key is null. We should do it in nav rewrite and then compensate accordingly in relational for the new shape of the correlation predicate

### PR DESCRIPTION
**Pull request by maumar**
Problem was that when expanding collection navigations we convert them into subqueries with a correlation predicate being outerKey == innerKey. For relational, most of those queries would later be converted into joins, however for some complex cases e.g. with Skip/Take (and also on InMemory) the query would stay in the form of subquery with correlation predicate. Then, null semantics kicks in and converts the correlation predicate to a form that returns true when both keys are null. This is incorrect in the context of chaining navigations - if the parent entity is null then it should never return any children.

Fix is to add null check to the correlation predicate during nav rewrite, like so: outerKey != null && outerKey == innerKey
Additionally, when trying to convert those subqueries into joins we need to account for a new pattern and remove the null check, since its irrelevant when it comes to join key comparison on relational

Fixes #17531

### CODE REVIEW

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 1]
```diff
@@ -959,6 +959,18 @@ static SqlExpression combineNonNullExpressions(SqlExpression left, SqlExpression
 
                     return combineNonNullExpressions(leftJoinKey, rightJoinKey);
                 }
+
+                // ignore null check
+                if (sqlBinaryExpression.OperatorType == ExpressionType.NotEqual
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs]: Not right. It needs to identify whole pattern.
If you are generating `a.Prop != null && a.Prop == b.Prop` then that is what you have to match in Sql tree also.

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs [hunk 2]
```diff
@@ -179,11 +179,11 @@ private Expression TryExpandNavigation(Expression root, MemberIdentity memberIde
                 {
                     // This is FirstOrDefault ending so we need to push down properties.
                     var temporaryParameter = Expression.Parameter(root.Type);
-                    var temporaryKey = CreateKeyAccessExpression(
-                        temporaryParameter,
+                    var temporaryKey = temporaryParameter.CreateKeyAccessExpression(
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs]: Thy makeNullable added here?

File: test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs [hunk 3]
```diff
@@ -18,5 +18,11 @@ public override Task SelectMany_with_navigation_filter_paging_and_explicit_Defau
         {
             return Task.CompletedTask;
         }
+
+        [ConditionalTheory(Skip = "Issue #17230")]
+        public override Task Project_collection_navigation_nested_with_take(bool isAsync)
+        {
+            return Task.CompletedTask;
```
Comment (smitpatel) [inline test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs]: Call base rather than Task.CompletedTask.
Task.CompletedTask should only be called if the test is not skipped but is invalid for the provider and always should show as passed.
FYI @aspnet/efteam

File: src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs (hunk 2 above)
Comment (maumar) [reply src/EFCore/Query/Internal/NavigationExpandingExpressionVisitor.ExpressionVisitors.cs]: removed duplicated method. the method that was removed worked exactly like the extension that is used currently when makeNullable == true

File: test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs (hunk 3 above)
Comment (maumar) [reply test/EFCore.Sqlite.FunctionalTests/Query/ComplexNavigationsQuerySqliteTest.cs]: agreed, only used task to be consistent with the case above, will change both

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 4]
```diff
@@ -921,6 +921,11 @@ private SqlExpression TryExtractJoinKey(SelectExpression selectExpression)
                 && selectExpression.Predicate != null)
             {
                 var joinPredicate = TryExtractJoinKey(selectExpression, selectExpression.Predicate, out var predicate);
+                if (predicate != null)
+                {
+                    predicate = RemoveNullChecks(predicate);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs]: The idea is to flow null checks which are part of correlated predicate to join predicate and remove null checks from join predicate only when appropriate. Inverse of logic of first property.

**Comment by maumar** [comment]
new version up @smitpatel

File: src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs [hunk 5]
```diff
@@ -992,22 +997,73 @@ private SqlBinaryExpression ValidateKeyComparison(SelectExpression inner, SqlBin
...
                     {
+                        columnExpressions.Add(leftColumn);
+
                         return sqlBinaryExpression;
                     }
 
                     if (ContainsTableReference(rightColumn.Table)
                         && inner.ContainsTableReference(leftColumn.Table))
                     {
+                        columnExpressions.Add(leftColumn);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/SqlExpressions/SelectExpression.cs]:
```suggestion
                        columnExpressions.Add(rightColumn);
```
