### PR TITLE
Fix nullability in entity equality

### LINKED ISSUE #16564: EntityEquality generates type mismatch
Test: Contains_over_entityType_with_null_should_rewrite_to_identity_equality
```
                var query
                    = context.Orders.Where(o => o.CustomerID == "VINET")
                        .Contains(null);
```
```
bool Contains(
|__ source: IQueryable<Order> Where(
|   |__ source: DbSet<Order>, 
|   |__ predicate: (Order o) => o.CustomerID == "VINET"), 
|__ item: (Unhandled parameter: __p_0))

// Gets rewritten into

bool Contains(
|__ source: IQueryable<int> Select(
|   |__ source: IQueryable<Order> Where(
|   |   |__ source: DbSet<Order>, 
|   |   |__ predicate: (Order Param_0) => Param_0.CustomerID == "VINET"), 
|   |__ selector: (Order Param_0) => Property(Param_0, "OrderID")), 
|__ item: (Unhandled parameter: __entity_equality_p_0_OrderID))
```
here p0 is null so runtime generated parameter is also null. But value is being cast to int which is NRE. When rewriting key access on potentially null expression, it should convert the types to nullable.

### PR DESCRIPTION
**Pull request by roji**
Fixes #16564

### CODE REVIEW

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 1]
```diff
@@ -898,7 +900,8 @@ private static object ParameterValueExtractor(QueryContext context, string baseP
         /// Extracts the list parameter with name <paramref name="baseParameterName"/> from <paramref name="context"/> and returns a
         /// projection to its elements' <paramref name="property"/> values.
         /// </summary>
-        private static object ParameterListValueExtractor<TEntity, TProperty>(QueryContext context, string baseParameterName, IProperty property)
+        private static List<TProperty> ParameterListRefTypeExtractor<TEntity, TProperty>(QueryContext context, string baseParameterName, IProperty property)
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: Generic on TProperty, you can pass nullable TProperty here rather than having 2 functions.

Comment (roji) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: Of course, silly me.

**Comment by kccsf** [comment]
Thanks @roji :-)
