### PR TITLE
Query: GroupBy after Skip/Take should push down subquery

### LINKED ISSUE #9581: Query: GroupBy after Skip/Take produces incorrect results
```C#
        [ConditionalFact]
        public virtual void OrderBy_Skip_GroupBy()
        {
            AssertQuery<Order>(
                os => os.OrderBy(o => o.OrderDate).Skip(50).GroupBy(o => o.CustomerID).OrderBy(g => g.Key),
                assertOrder: true);
        }
```
Produces 
```SQL
  SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[OrderDate]
  FROM [Orders] AS [o]
  ORDER BY [o].[CustomerID], [o].[OrderDate]
  OFFSET @__p_0 ROWS
```
Which is incorrect SQL and gives wrong results.

### PR DESCRIPTION
**Pull request by smitpatel**
Also lift GroupBy subquery when possible
This allows us to access the SelectExpression corresponding to GroupBy Result operator in ParentQMV

Resolves #9581

### CODE REVIEW

File: src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs [hunk 1]
```diff
@@ -785,6 +785,16 @@ var subQueryModelVisitor
 
             subQueryModelVisitor.VisitSubQueryModel(subQueryModel);
 
+            if ((subQueryModelVisitor.Expression as MethodCallExpression)?.Method.GetGenericMethodDefinition()
+                .Equals(QueryCompilationContext.QueryMethodProvider.GroupByMethod) == true
```
Comment (anpete) [inline src/EFCore.Relational/Query/RelationalQueryModelVisitor.cs]: Use MethodIsClosedFormOf
