### PR TITLE
Query: Clean up in ExpressionEqualityComparer

### LINKED ISSUE #10529: Query: GetHashCode(Expression obj) of ExpressionEqualityComparer does not support ExpressionType.Assign
Hi there,

I have a homemade mapping/projection library that I use to map/project between DB models and DTOs. In the expression tree that this library builds, there are a few assignments (i.e. Expression.Assign) being made in the logic to support mapping/projection of abstract classes to derived types (i.e. I have the abstract `Field`, and the concrete `BooleanField` entities and the abstract `FieldDto`, and the concret `BooleanFieldDto` DTOs).

Here is the relevant part in the resulting expression tree:

```c#
.If (
	$field .Is Application.Domain.Models.BooleanField
) {
	.Block(Application.Domain.Models.BooleanField $booleanfield) {
		$booleanfield = (Application.Domain.Models.BooleanField)$field;
		$x = (Web.Models.Schemas.FieldDto).New Web.Models.Schemas.BooleanFieldDto(){
			Properties = .New Web.Models.Schemas.BooleanFieldPropertiesDto(){
				DefaultValue = ($booleanfield.Properties).DefaultValue,
				Label = ($booleanfield.Properties).Label,
				Hint = ($booleanfield.Properties).Hint,
				Placeholder = ($booleanfield.Properties).Placeholder,
				IsRequired = ($booleanfield.Properties).IsRequired
			},
			Name = $booleanfield.Name,
			FieldTypeName = $booleanfield.FieldTypeName
		}
	}
} .Else {
	.Default(System.Void)
};
```

Mapping an existing entity model to its DTO counterpart works as expected, however doing a projection fails with the following exception:

```c#
An unhandled exception occurred while processing the request.

NotImplementedException: The method or operation is not implemented.

Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.GetHashCode(Expression obj)
Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.GetHashCode(Expression obj)
Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.GetHashCode<T>(IList<T> expressions)
Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.GetHashCode(Expression obj)
Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.GetHashCode<T>(IList<T> expressions)
Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.GetHashCode(Expression obj)
Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.GetHashCode(Expression obj)
Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.GetHashCode(Expression obj)
Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.GetHashCode(Expression obj)
Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.GetHashCode<T>(IList<T> expressions)
Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.GetHashCode(Expression obj)
Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.GetHashCode<T>(IList<T> expressions)
Microsoft.EntityFrameworkCore.Query.Internal.ExpressionEqualityComparer.GetHashCode(Expression obj)
Microsoft.EntityFrameworkCore.Query.CompiledQueryCacheKeyGenerator+CompiledQueryCacheKey.GetHashCode()
Microsoft.EntityFrameworkCore.Query.RelationalCompiledQueryCacheKeyGenerator+RelationalCompiledQueryCacheKey.GetHashCode()
System.Collections.Generic.ObjectEqualityComparer.GetHashCode(T obj)
System.Collections.Concurrent.ConcurrentDictionary.TryGetValue(TKey key, out TValue value)
Microsoft.Extensions.Caching.Memory.MemoryCache.TryGetValue(object key, out object result)
Microsoft.Extensions.Caching.Memory.CacheExtensions.TryGetValue<TItem>(IMemoryCache cache, object key, out TItem value)
Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore<TFunc>(object cacheKey, Func<Func<QueryContext, TFunc>> compiler)
Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddAsyncQuery<TResult>(object cacheKey, Func<Func<QueryContext, IAsyncEnumerable<TResult>>> compiler)
Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileAsyncQuery<TResult>(Expression query)
Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync<TResult>(Expression query, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync<TResult>(Expression expression, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync<TSource, TResult>(MethodInfo operatorMethodInfo, IQueryable<TSource> source, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.SingleOrDefaultAsync<TSource>(IQueryable<TSource> source, CancellationToken cancellationToken)
HedgeSoft.Web.Controllers.SchemasController+<Get>d__5.MoveNext() in SchemasController.cs
var schema = await _mapper.Project<SchemaDetailedDto>(
```
I noticed in the code of `ExpressionEqualityComparer.GetHashCode(Expression obj)`, there is no case for `ExpressionType.Assign`, hence the `NotImplementedException` thrown above. 

Is this something that is not supported, or will be supported by EF?

As a workaround, I am fetching the entity normally, then doing a map to a DTO. However I would prefer support for projection for performance reasons.

Thanks in advance!

### Further technical details
EF Core version: 2.0.0
Database Provider: NpgSql
Operating system: Windows 10 Pro
IDE: Visual Studio 2017 15.5.1

### LINKED ISSUE #17959: Compute Hash for MemberMemberBinding in ExpressionEqualityComparer
https://github.com/aspnet/EntityFrameworkCore/blob/03503351c9dd3daf05a1ff66520c00aba3e372eb/src/EFCore/Query/Internal/ExpressionEqualityComparer.cs#L238

I think that this line is supposed to be
``` C#
throw new NotImplementedException($"Unhandled binding type: {memberBinding.BindingType}");
```

However, textual representation of the binding (that is output currently) will be helpful too, especially because only one binding type is not supported currently.

### LINKED ISSUE #18685: ExpressionEqualityComparer cleanup
Use switch on Type rather than NodeType.
Add hashcode computation for missing nodes
- BlockExpression
- AssignExpression

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #18685
Resolves #10529
Resolves #17959

### CODE REVIEW

File: src/EFCore/Query/Internal/ExpressionEqualityComparer.cs [hunk 1]
```diff
@@ -644,56 +638,99 @@ private bool CompareBinding(MemberBinding a, MemberBinding b)
...
+                    || b == null
+                    || a.Count != b.Count)
+                {
+                    return false;
+                }
 
-            private bool CompareMemberMemberBinding(MemberMemberBinding a, MemberMemberBinding b)
-                => Equals(a.Member, b.Member)
-                    && CompareBindingList(a.Bindings, b.Bindings);
+                for (int i = 0, n = a.Count; i < n; i++)
```
Comment (maumar) [inline src/EFCore/Query/Internal/ExpressionEqualityComparer.cs]: nitL var ;P

Comment (smitpatel) [reply src/EFCore/Query/Internal/ExpressionEqualityComparer.cs]: Cannot use var.
