### PR TITLE
Try match FK properties with the exact name as principal key if they are a proper subset of the dependent PK and don't contain the Id property.

### LINKED ISSUE #15250: Match a subset of the PK as FK properties
We've noticed a regression in EF Core's FK property discovery convention when upgrading from 2.1.8 to 2.2.0. We're using composite keys across our entities.

I've put together a reduced testcase here: https://gist.github.com/deadalusai/b49ecb2fe55a72fe2b42ff34e1caa817

### Steps to reproduce
1. Clone the above gist (just a .csproj and Program.cs)
2. `dotnet restore`
3. `dotnet run`
4. See the FK relationships printed out for `EntityType: Subscription`

Under EF Core 2.2.0 EF unnecessarily generates a shadow property when building the FK for the `Subscription -> Product` relationship. EF Core 2.1.8 uses the existing key properties.

Under 2.2.0 (broken):
```
EntityType: Subscription
  Foreign keys:
    Subscription {'TenantId'} -> Tenant {'TenantId'} ToPrincipal: Tenant
    Subscription {'ProductTenantId', 'ProductId1'} -> Product {'TenantId', 'ProductId'} ToDependent: Subscriptions ToPrincipal: Product
    Subscription {'TenantId', 'SubscriberId'} -> Subscriber {'TenantId', 'SubscriberId'} ToDependent: Subscriptions ToPrincipal: Subscriber
```

Under 2.1.8 (working):
```
EntityType: Subscription
  Foreign keys:
    Subscription {'TenantId'} -> Tenant {'TenantId'} ToPrincipal: Tenant
    Subscription {'TenantId', 'ProductId'} -> Product {'TenantId', 'ProductId'} ToDependent: Subscriptions ToPrincipal: Product
    Subscription {'TenantId', 'SubscriberId'} -> Subscriber {'TenantId', 'SubscriberId'} ToDependent: Subscriptions ToPrincipal: Subscriber
```

### Further technical details
EF Core version: 2.2.0
Database Provider: Microsoft.EntityFrameworkCore.SqlServer

From my testing it looks like the bug was introduced in https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/2.2.0-preview3-35497 (last good working version was 2.2.0-preview2-35157).

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Fixes #15250

### CODE REVIEW

File: src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs [hunk 1]
```diff
@@ -16,14 +16,19 @@ namespace Microsoft.EntityFrameworkCore.Metadata.Conventions
...
+    ///             * [navigation property name][principal key property name]
     ///             * [navigation property name]Id
-    ///             * [principal entity name][primary key property name]
+    ///             * [principal entity name][principal key property name]
     ///             * [principal entity name]Id
     ///     </para>
     ///     <para>
-    ///         If no matching properties were found, the relationship is one-to-one, doesn't represent an ownership,
-    ///         the dependent side is not ambiguous and not derived then the primary key properties are used.
+    ///         If no matching properties were found, doesn't represent an ownership,
```
Comment (smitpatel) [inline src/EFCore/Metadata/Conventions/ForeignKeyPropertyDiscoveryConvention.cs]: what doesn't represent an ownership?
