### PR TITLE
Pack of entity equality fixes

### LINKED ISSUE #17076: EntityEquality failed to identify navigation chain correctly
```C#
        [ConditionalFact]
        public virtual void Comparing_two_collection_navigations_inheritance()
        {
            using (var ctx = CreateContext())
            {
                var query = from f in ctx.Factions
                            from o in ctx.Gears.OfType<Officer>()
                            where f is LocustHorde && o.HasSoulPatch
                            // ReSharper disable once PossibleUnintendedReferenceComparison
                            where ((LocustHorde)f).Commander.DefeatedBy.Weapons == o.Weapons
                            select new
                            {
                                f.Name,
                                o.Nickname
                            };

                var result = query.ToList();
                Assert.Equal(1, result.Count);
                Assert.Equal("Locust", result[0].Name);
                Assert.Equal("Marcus", result[0].Nickname);
            }
        }
```
While debugging found inside EE that leftNavigation turns out to be null (for this chain ((LocustHorde)f).Commander.DefeatedBy.Weapons)

### LINKED ISSUE #17109: EntityEquality: OrderBy entity fails in some cases
```C#
        [ConditionalTheory]
        [MemberData(nameof(IsAsyncData))]
        public virtual Task Order_by_entity_qsre(bool isAsync)
        {
            return AssertQuery<Gear>(
                isAsync,
                gs => gs.OrderBy(g => g.AssignedCity).ThenByDescending(g => g.Nickname).Select(f => f.FullName),
                gs => gs.OrderBy(g => Maybe(g.AssignedCity, () => g.AssignedCity.Name)).ThenByDescending(g => g.Nickname)
                    .Select(f => f.FullName),
                assertOrder: true);
        }
```
```
 Message: 
    System.ArgumentException : Property 'Microsoft.EntityFrameworkCore.TestModels.GearsOfWarModel.City AssignedCity' is not defined for type 'Microsoft.EntityFrameworkCore.TestModels.GearsOfWarModel.City' (Parameter 'property')
  Stack Trace: 
    Expression.Property(Expression expression, PropertyInfo property)
    Expression.MakeMemberAccess(Expression expression, MemberInfo member)
    MemberExpression.Update(Expression expression)
    ReplacingExpressionVisitor.VisitMember(MemberExpression memberExpression) line 65
    MemberExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    ReplacingExpressionVisitor.Visit(Expression expression) line 39
    ReplacingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) line 72
    MethodCallExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    ReplacingExpressionVisitor.Visit(Expression expression) line 39
    ReplacingExpressionVisitor.Replace(Expression original, Expression replacement, Expression tree) line 18
    EntityEqualityRewritingExpressionVisitor.VisitOrderingMethodCall(MethodCallExpression methodCallExpression) line 473
    EntityEqualityRewritingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) line 237
    MethodCallExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    EntityEqualityRewritingExpressionVisitor.VisitOrderingMethodCall(MethodCallExpression methodCallExpression) line 436
    EntityEqualityRewritingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) line 237
    MethodCallExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    EntityEqualityRewritingExpressionVisitor.VisitSelectMethodCall(MethodCallExpression methodCallExpression) line 509
    EntityEqualityRewritingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) line 245
    MethodCallExpression.Accept(ExpressionVisitor visitor)
    ExpressionVisitor.Visit(Expression node)
    EntityEqualityRewritingExpressionVisitor.Rewrite(Expression expression) line 53
    QueryOptimizer.Visit(Expression query) line 32
    QueryCompilationContext.CreateQueryExecutor[TResult](Expression query) line 66
    Database.CompileQuery[TResult](Expression query, Boolean async) line 71
    QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) line 106
    <>c__DisplayClass9_0`1.<Execute>b__0() line 96
    CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) line 84
    CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) line 59
    QueryCompiler.Execute[TResult](Expression query) line 92
    EntityQueryProvider.Execute[TResult](Expression expression) line 79
    EntityQueryable`1.GetEnumerator() line 94
    LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
    EnumerableHelpers.ToArray[T](IEnumerable`1 source)
    Enumerable.ToArray[TSource](IEnumerable`1 source)
    QueryAsserter`1.AssertQuery[TItem1](Func`2 actualQuery, Func`2 expectedQuery, Func`2 elementSorter, Action`2 elementAsserter, Boolean assertOrder, Int32 entryCount, Boolean isAsync, String testMethodName) line 349
    GearsOfWarQuerySqlServerTest.Order_by_entity_qsre(Boolean isAsync) line 5789
    --- End of stack trace from previous location where exception was thrown ---
```
ReplacingVisitor is replacing it with parameter of different type.

cc:@roji

### PR DESCRIPTION
**Pull request by roji**
Fixes #17109
Fixes #17076

### CODE REVIEW

File: test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs [hunk 1]
```diff
@@ -3886,20 +3886,28 @@ public override void Comparing_two_collection_navigations_inheritance()
             base.Comparing_two_collection_navigations_inheritance();
 
             AssertSql(
-                @"SELECT [f].[Name], [o].[Nickname]
-FROM [ConditionalFactions] AS [f]
-CROSS JOIN [Gears] AS [o]
+                @"SELECT [t].[Name], [t0].[Nickname]
```
Comment (roji) [inline test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs]: @smitpatel can you make sure this SQL makes sense? It became much bigger from the previous one.

File: test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs [hunk 2]
```diff
@@ -3886,20 +3886,28 @@ public override void Comparing_two_collection_navigations_inheritance()
...
 LEFT JOIN (
-    SELECT [join.Commander.DefeatedBy].*
-    FROM [Gears] AS [join.Commander.DefeatedBy]
-    WHERE [join.Commander.DefeatedBy].[Discriminator] IN (N'Officer', N'Gear')
-) AS [t0] ON ([t].[DefeatedByNickname] = [t0].[Nickname]) AND ([t].[DefeatedBySquadId] = [t0].[SquadId])
-WHERE (([f].[Discriminator] = N'LocustHorde') AND (([f].[Discriminator] = N'LocustHorde') AND ([o].[HasSoulPatch] = CAST(1 AS bit)))) AND (([t0].[Nickname] = [o].[Nickname]) AND ([t0].[SquadId] = [o].[SquadId]))");
+    SELECT [g0].[Nickname], [g0].[SquadId], [g0].[AssignedCityName], [g0].[CityOrBirthName], [g0].[Discriminator], [g0].[FullName], [g0].[HasSoulPatch], [g0].[LeaderNickname], [g0].[LeaderSquadId], [g0].[Rank]
+    FROM [Gears] AS [g0]
+    WHERE [g0].[Discriminator] IN (N'Gear', N'Officer')
+) AS [t2] ON (([t1].[DefeatedByNickname] = [t2].[Nickname]) AND [t1].[DefeatedByNickname] IS NOT NULL) AND (([t1].[DefeatedBySquadId] = [t2].[SquadId]) AND [t1].[DefeatedBySquadId] IS NOT NULL)
```
Comment (smitpatel) [inline test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs]: Need to investigate why null semantics got applied on a left join predicate.
cc: @maumar

File: test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs (hunk 1 above)
Comment (smitpatel) [reply test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs]: The way cross join happened changed so SQL is fine from that POV. One slight issue, I commented. @maumar  can look into it or you can investigate if you want.

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 3]
```diff
@@ -643,6 +662,27 @@ protected virtual Expression VisitJoinMethodCall(MethodCallExpression methodCall
                 : (Expression)newMethodCall;
         }
 
+        protected virtual Expression VisitOfType(MethodCallExpression methodCallExpression)
+        {
+            var newSource = Visit(methodCallExpression.Arguments[0]);
+            var updatedMethodCall = methodCallExpression.Update(null, new[] { Unwrap(newSource) });
+
+            if (!(newSource is EntityReferenceExpression sourceWrapper)
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: Possibly DRY. Seeing this repeated few times in this class.

Comment (roji) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: Agreed, in general the EE visitor has evolved and could be cleaned up at some point...

File: test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs (hunk 1 above)
Comment (roji) [reply test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs]: Will let @maumar take a look :)

Comment (maumar) [reply test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs]: filed a tracking item - #17132 - will take a look once I'm done with defining query (hopefully very soon)

Comment (maumar) [reply test/EFCore.SqlServer.FunctionalTests/Query/GearsOfWarQuerySqlServerTest.cs]: the null semantics happens because its composite key - for non-composite keys we perform relational null semantics for joins, but for composite keys we perform c# null semantics to match the actual linq join behavior
