### PR TITLE
Fix to #17236 - Improve readability of expressions in client evaluation exception

### LINKED ISSUE #17236: Improve readability of expressions in client evaluation exception
Scrub the places where the exception is thrown and ensure:
* The most appropriate expression to print is being used
* The result of printing the expression can be correlated with the code that was written

### PR DESCRIPTION
**Pull request by maumar**
Adding a new switch to ExpressionPrinter that creates simplified output for Print and verbose (i.e. what we had before this change) for PrintDebug.
Simplified output means:
- displaying Enumerable/Queryable methods (e.g. Where, Select, Join) as extension methods
- simplifying display of Navigation object

Also fixed minor display bugs in expression printer.

Also some changes in testing:
- added unit tests for ExpressionPrinter,
- DRY the "translation failed" tests,
- "translation failed" tests no longer verify expression in the exception message and instead just make sure that right exception is thrown.

Resolves #17236

### CODE REVIEW

**Comment by maumar** [comment]
ping

File: src/EFCore/Query/ExpressionPrinter.cs [hunk 1]
```diff
@@ -534,34 +553,53 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
             }
 
-            _stringBuilder.Append(methodCallExpression.Method.Name);
-            if (methodCallExpression.Method.IsGenericMethod)
+            var methodArguments = methodCallExpression.Arguments.ToList();
+
+            var simplifiedMethod = StreamlineOutput
+                && (methodCallExpression.Method.DeclaringType == typeof(Enumerable)
+                    || methodCallExpression.Method.DeclaringType == typeof(Queryable)
+                    || methodCallExpression.Method.DeclaringType == typeof(QueryableExtensions))
```
Comment (AndriySvyryd) [inline src/EFCore/Query/ExpressionPrinter.cs]: Just do it for all extension methods, see https://stackoverflow.com/a/299526/1171992

File: src/EFCore/Query/MaterializeCollectionNavigationExpression.cs [hunk 2]
```diff
@@ -31,9 +31,17 @@ public virtual MaterializeCollectionNavigationExpression Update(Expression subqu
 
         public virtual void Print(ExpressionPrinter expressionPrinter)
         {
-            expressionPrinter.Append($"MaterializeCollectionNavigation({Navigation}, ");
-            expressionPrinter.Visit(Subquery);
-            expressionPrinter.Append(")");
+            var navigation = expressionPrinter.StreamlineOutput
+                ? $"Navigation: { Navigation.DeclaringEntityType.DisplayName()}.{ Navigation.Name}"
```
Comment (AndriySvyryd) [inline src/EFCore/Query/MaterializeCollectionNavigationExpression.cs]: Add a parameter to `NavigationExtensions.ToDebugString` instead

File: src/EFCore/Query/ExpressionPrinter.cs [hunk 3]
```diff
@@ -55,6 +55,8 @@ public ExpressionPrinter()
 
         private bool GenerateUniqueParameterIds { get; set; }
 
+        public virtual bool StreamlineOutput { get; private set; }
```
Comment (smitpatel) [inline src/EFCore/Query/ExpressionPrinter.cs]: What is this for?

File: src/EFCore/Query/ExpressionPrinter.cs [hunk 4]
```diff
@@ -428,7 +438,10 @@ protected override Expression VisitLabel(LabelExpression labelExpression)
 
         protected override Expression VisitLambda<T>(Expression<T> lambdaExpression)
         {
-            _stringBuilder.Append("(");
+            if (lambdaExpression.Parameters.Count > 1)
```
Comment (AndriySvyryd) [inline src/EFCore/Query/ExpressionPrinter.cs]: Should still add the parenthesis if there are no parameters

File: src/EFCore/Query/ExpressionPrinter.cs (hunk 3 above)
Comment (AndriySvyryd) [reply src/EFCore/Query/ExpressionPrinter.cs]: I think we can just assume it will always be `true` and remove it.

File: test/EFCore.Tests/Query/ExpressionPrinterTest.cs [hunk 5]
```diff
@@ -0,0 +1,184 @@
...
+            Assert.Equal("True && True", _expressionPrinter.Print(expr7));
+            Assert.Equal("True || True", _expressionPrinter.Print(expr8));
+            Assert.Equal("7 & 42", _expressionPrinter.Print(expr9));
+            Assert.Equal("7 | 42", _expressionPrinter.Print(expr10));
+            Assert.Equal("7 ^ 42", _expressionPrinter.Print(expr11));
+            Assert.Equal("7 + 42", _expressionPrinter.Print(expr12));
+            Assert.Equal("7 - 42", _expressionPrinter.Print(expr13));
+            Assert.Equal("7 * 42", _expressionPrinter.Print(expr14));
+            Assert.Equal("7 / 42", _expressionPrinter.Print(expr15));
+            Assert.Equal("7 % 42", _expressionPrinter.Print(expr16));
```
Comment (AndriySvyryd) [inline test/EFCore.Tests/Query/ExpressionPrinterTest.cs]: Inline the expressions

File: src/EFCore/Query/ExpressionPrinter.cs (hunk 3 above)
Comment (maumar) [reply src/EFCore/Query/ExpressionPrinter.cs]: its supposed to capture difference between Print and PrintDebug, i.e. what is customer curated output vs verbose debug output. For now its just about how we display methods (i.e. with type arguments or without), but all future optimizations would be switched on/off here as well

Comment (smitpatel) [reply src/EFCore/Query/ExpressionPrinter.cs]: YAGNI for now. We can add when we need it.

**Comment by maumar** [comment]
@AndriySvyryd @smitpatel new version up

File: src/EFCore/Query/MaterializeCollectionNavigationExpression.cs [hunk 6]
```diff
@@ -31,9 +31,13 @@ public virtual MaterializeCollectionNavigationExpression Update(Expression subqu
 
         public virtual void Print(ExpressionPrinter expressionPrinter)
         {
-            expressionPrinter.Append($"MaterializeCollectionNavigation({Navigation}, ");
-            expressionPrinter.Visit(Subquery);
-            expressionPrinter.Append(")");
+            expressionPrinter.AppendLine("MaterializeCollectionNavigation(");
+            using (expressionPrinter.Indent())
+            {
+                expressionPrinter.AppendLine($"navigation: {Navigation.ToString()},");
```
Comment (smitpatel) [inline src/EFCore/Query/MaterializeCollectionNavigationExpression.cs]: Doesn't interpolated string calls ToString method already?

File: test/EFCore.Tests/Query/ExpressionPrinterTest.cs [hunk 7]
```diff
@@ -0,0 +1,167 @@
...
+namespace Microsoft.EntityFrameworkCore.Query
+{
+    public class ExpressionPrinterTest
+    {
+        private readonly ExpressionPrinter _expressionPrinter = new ExpressionPrinter();
+
+        [ConditionalFact]
+        public void UnaryExpression_printed_correctly()
+        {
+            var expr1 = Expression.Convert(Expression.Constant(42), typeof(decimal));
```
Comment (smitpatel) [inline test/EFCore.Tests/Query/ExpressionPrinterTest.cs]: Why did we not inline expressions here? :trollface:

File: test/EFCore.Tests/Query/ExpressionPrinterTest.cs [hunk 8]
```diff
@@ -0,0 +1,167 @@
...
+        }
+
+        private class DerivedClass : BaseClass
+        {
+        }
+
+        [ConditionalFact]
+        public void BinaryExpression_printed_correctly()
+        {
+            Assert.Equal("7 == 42", _expressionPrinter.Print(Expression.MakeBinary(ExpressionType.Equal, Expression.Constant(7), Expression.Constant(42))));
```
Comment (smitpatel) [inline test/EFCore.Tests/Query/ExpressionPrinterTest.cs]: May be.
`new ExpressionPrinter().Print(((Expression<Func<int, bool>>)(e => e > 42)).Body)`

File: src/EFCore/Metadata/Internal/NavigationExtensions.cs [hunk 9]
```diff
@@ -31,44 +30,7 @@ public static class NavigationExtensions
...
-            if (navigation.FindInverse() != null)
-            {
-                builder.Append(" Inverse: ").Append(navigation.FindInverse().Name);
-            }
-
-            if (navigation.GetPropertyAccessMode() != PropertyAccessMode.PreferField)
-            {
-                builder.Append(" PropertyAccessMode.").Append(navigation.GetPropertyAccessMode());
-            }
+            builder.Append($"{indent}Navigation: {navigation.DeclaringEntityType.DisplayName()}.{navigation.Name}");
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/NavigationExtensions.cs]: I meant that it's ok to always use the short version of the navigation in expression printing. Elsewhere it should still add all the aspects to the string.

File: src/EFCore/Query/MaterializeCollectionNavigationExpression.cs (hunk 6 above)
Comment (AndriySvyryd) [reply src/EFCore/Query/MaterializeCollectionNavigationExpression.cs]: Call `Navigation.ToDebugString(detailed: false)`

File: src/EFCore/Metadata/Internal/NavigationExtensions.cs [hunk 10]
```diff
@@ -23,66 +23,78 @@ public static class NavigationExtensions
         ///     any release. You should only use it directly in your code with extreme caution and knowing that
         ///     doing so can result in application failures when updating to a new Entity Framework Core release.
         /// </summary>
+        public static string ToDebugString(
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/NavigationExtensions.cs]: Also mark this as Obsolete so we remember to remove it. And add XML docs to the method below

File: src/EFCore/Metadata/Internal/NavigationExtensions.cs [hunk 11]
```diff
@@ -23,66 +23,78 @@ public static class NavigationExtensions
...
-            [NotNull] string indent = "")
+            [NotNull] string indent = "",
+            bool detailed = true)
         {
             var builder = new StringBuilder();
 
             builder.Append(indent);
 
-            if (singleLine)
+            if (detailed)
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/NavigationExtensions.cs]: Invert condition and return early to avoid extra indentation and code repetition.

File: src/EFCore/Metadata/Internal/NavigationExtensions.cs [hunk 12]
```diff
@@ -27,12 +42,20 @@ public static class NavigationExtensions
...
+            [NotNull] string indent = "",
+            bool detailed = true)
         {
             var builder = new StringBuilder();
 
             builder.Append(indent);
 
+            if (!detailed)
+            {
+                builder.Append($"Navigation: {navigation.DeclaringEntityType.DisplayName()}.{navigation.Name}");
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/NavigationExtensions.cs]: This is the same as the code below, just move the check after `builder.Append(navigation.Name);` and avoid code duplication.

File: src/EFCore/Metadata/Internal/NavigationExtensions.cs [hunk 13]
```diff
@@ -80,10 +101,7 @@ public static class NavigationExtensions
                 builder.Append(" ").Append(indexes.StoreGenerationIndex);
             }
 
-            if (!singleLine)
-            {
-                builder.Append(navigation.AnnotationsToDebugString(indent + "  "));
-            }
+            builder.Append(navigation.AnnotationsToDebugString(indent + "  "));
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/NavigationExtensions.cs]: Why did this change?

File: src/EFCore/Metadata/Internal/NavigationExtensions.cs (hunk 10 above)
Comment (smitpatel) [reply src/EFCore/Metadata/Internal/NavigationExtensions.cs]: If this is an internal API. also put EntityFrameworkInternal attribute.

File: src/EFCore/Query/ExpressionPrinter.cs [hunk 14]
```diff
@@ -534,34 +544,61 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
...
+
+            if (simplifiedMethod)
             {
-                _stringBuilder.Append("<");
-                var first = true;
-                foreach (var genericArgument in methodCallExpression.Method.GetGenericArguments())
+                Visit(methodArguments[0]);
+
+                var methodDeclaringType = methodCallExpression.Method.DeclaringType;
+                if (methodDeclaringType == typeof(Queryable)
```
Comment (smitpatel) [inline src/EFCore/Query/ExpressionPrinter.cs]: I thought checking for extension method was sufficient to remove this specific type checks.

Comment (smitpatel) [reply src/EFCore/Query/ExpressionPrinter.cs]: Also this increments the indent but check below to decrement the indent check only for simplified method.

Comment (maumar) [reply src/EFCore/Query/ExpressionPrinter.cs]: this special cases Enumerable/Queryable to be printed as:
```
souce
    .Method(arguments)
```

rather than single line

File: src/EFCore/Query/MaterializeCollectionNavigationExpression.cs [hunk 15]
```diff
@@ -31,9 +32,13 @@ public virtual MaterializeCollectionNavigationExpression Update(Expression subqu
 
         public virtual void Print(ExpressionPrinter expressionPrinter)
         {
-            expressionPrinter.Append($"MaterializeCollectionNavigation({Navigation}, ");
-            expressionPrinter.Visit(Subquery);
-            expressionPrinter.Append(")");
+            expressionPrinter.AppendLine("MaterializeCollectionNavigation(");
```
Comment (smitpatel) [inline src/EFCore/Query/MaterializeCollectionNavigationExpression.cs]: Remove `(` after the expression type. Use nameof syntax.

File: src/EFCore/Query/ExpressionPrinter.cs (hunk 14 above)
Comment (smitpatel) [reply src/EFCore/Query/ExpressionPrinter.cs]: Add regression test too :trollface:

File: src/EFCore/Metadata/Internal/NavigationExtensions.cs (hunk 10 above)
Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/NavigationExtensions.cs]: We only need to use that on classes not in the Internal namespace
