### PR TITLE
[release/10.0] Fix performance degradation for primitive collections for multiple parameters translation and deep trees with closure over same variable

### LINKED ISSUE #37152: EF Core 10 queries much slower than EF Core 9 with a larger number of parameters
### Bug description

A workaround is to go back to the old OPENJSON method of querying:
optionsBuilder.UseParameterizedCollectionMode(ParameterTranslationMode.Parameter);

### Your code

```csharp
// Fill a Test table with ~100k entries.

List<int> items = [];

for (int i = 0; i < 4000; i++)
{
    items.Add(i);

    _ = await context.Test.Where(x => items.Contains(x.Id)).Select(x => x.Id).ToListAsync();
}
```

### Stack traces

```text

```

### Verbose output

```text

```

### EF Core version

10.0.0

### Database provider

SqlServer

### Target framework

.NET 1.0

### Operating system

_No response_

### IDE

_No response_

### PR DESCRIPTION
**Pull request by cincuranet**
Fixes #37152.

### 🔢

| Method   | Job     | Arguments           | Count | Mean        | Error     | StdDev    | Ratio  | RatioSD | Gen0      | Gen1     | Gen2    | Allocated   | Alloc Ratio |
|--------- |-------- |-------------------- |------ |------------:|----------:|----------:|-------:|--------:|----------:|---------:|--------:|------------:|------------:|
| Manual   | 10.0.0  | /p:EFVersion=10.0.0 | 1000  | 17,873.4 us | 135.77 us | 127.00 us |  11.21 |    0.25 | 3500.0000 | 187.5000 | 31.2500 | 28701.33 KB |       18.00 |
| Manual   | 9.0.11  | /p:EFVersion=9.0.11 | 1000  |  1,595.5 us |  31.07 us |  33.24 us |   1.00 |    0.03 |  187.5000 | 109.3750 | 31.2500 |  1594.15 KB |        1.00 |
| Manual   | current | Default             | 1000  |  1,620.6 us |  28.11 us |  32.37 us |   1.02 |    0.03 |  218.7500 | 125.0000 | 31.2500 |  1893.34 KB |        1.19 |
|          |         |                     |       |             |           |           |        |         |           |          |         |             |             |
| Contains | 10.0.0  | /p:EFVersion=10.0.0 | 1000  | 21,901.9 us | 263.62 us | 246.59 us | 202.41 |    4.23 | 8781.2500 |  31.2500 |       - |  71871.2 KB |      448.59 |
| Contains | 9.0.11  | /p:EFVersion=9.0.11 | 1000  |    108.2 us |   2.16 us |   2.02 us |   1.00 |    0.03 |   19.5313 |   2.4414 |       - |   160.22 KB |        1.00 |
| Contains | current | Default             | 1000  |    563.7 us |  10.96 us |  18.00 us |   5.21 |    0.19 |  195.3125 |        - |       - |  1635.02 KB |       10.21 |

### 💭

The _Manual_ benchmark is now very close to what it used to be in 9. The 2% difference in speed (some runs showed 5%, the Error/StdDev here is pretty high) is the "price" for now much more nicer parameter names.

The _Contains_ benchmark is not comparing 🍎 and 🍎. In 9, the query was translated to `OPENJSON`, while in 10 this is translated to multiple parameters. Before the fix the translation was very slow (~188x) and created a lot of allocations (~448x). Now the numbers are ~5x and ~10x. Again, this is comparing 1 parameter vs 1000 parameters - 🍎 vs 🍊. 

Fair to say, I know about a decent room for improvement in allocations (hence theoretically in speed as well, at least in benchmarks). But it is too risky for servicing. I might do it for 11.

It is also important to know that this benchmark measures _only_ the translation. Once the query hits the database, the translation to multiple parameters should show its real benefits.

### Description

EF 10 changed the default translation for parameterized collections from single parameter and JSON function to multiple parameters. We missed O(n^2) performance degradation in code path where we generate unique parameter names resulting in subpar performance.

### Customer impact

Query translation takes significant time compared to other types of translation. Excessive allocations.

### How found

Customer reported on 10.0.

### Regression

Yes.

### Testing

The change in the PR is covered by existing tests. We don't have specific benchmarks for translations.

### Risk

Low. Added fast path optimization. Quirk added.

### CODE REVIEW

File: src/EFCore.Relational/Query/SqlNullabilityProcessor.cs [hunk 1]
```diff
@@ -2241,7 +2244,9 @@ private static void ExpandParameterIfNeeded(
     {
         if (expandedParameters.Count <= index)
         {
-            var parameterName = Uniquifier.Uniquify(valuesParameterName, parameters, int.MaxValue);
+            var parameterName = UseOldBehavior37152
+                ? Uniquifier.Uniquify(valuesParameterName, parameters, int.MaxValue)
+                : Uniquifier.Uniquify(valuesParameterName, parameters, 512, index + 1);
```
Comment (roji) [inline src/EFCore.Relational/Query/SqlNullabilityProcessor.cs]: nit: I always add parameter names for non-obvious literals (when reviewing your PR I had no idea what either `512` or `index + 1` meant):

```suggestion
                : Uniquifier.Uniquify(valuesParameterName, parameters, maxLength: 512, uniquifier: index + 1);
```

File: src/EFCore/Infrastructure/Uniquifier.cs [hunk 2]
```diff
@@ -21,12 +21,14 @@ public static class Uniquifier
...
     /// <param name="maxLength">The maximum length of the identifier.</param>
+    /// <param name="uniquifier">An optional starting number for the uniquifier.</param>
     /// <returns>A unique identifier.</returns>
     public static string Uniquify<T>(
         string currentIdentifier,
         IReadOnlyDictionary<string, T> otherIdentifiers,
-        int maxLength)
-        => Uniquify(currentIdentifier, otherIdentifiers, s => s, maxLength);
+        int maxLength,
+        int uniquifier = 1)
```
Comment (roji) [inline src/EFCore/Infrastructure/Uniquifier.cs]: Careful, adding a parameter is a binary break (and moreover this is a fully public API). That means that if any provider is compiled against 10.0.0 and uses Uniquify, it will be broken by this patch.

At least for the patch, just add a new, separate API. For the 11.0 fix we can do the binary break.

File: src/EFCore.Relational/Query/SqlNullabilityProcessor.cs (hunk 1 above)
Comment (roji) [inline src/EFCore.Relational/Query/SqlNullabilityProcessor.cs]: If I understand correctly, you're using 512 as a magic threshold for using Span-based truncation instead of StringBuilder (haven't fully gone into it).

AFAIK maxLength is currently used for actually limiting the total number of characters for the end identifier, for cases where there's a (low) limit on the character length, e.g. table/column numbers, where we also need to truncate (we add ~1, ~2 instead). I don't think that's relevant here, and it looks like you're reusing that mechanism for something a bit different (Span vs. StringBuilder).

If we want to optimize and use Span, doesn't it make sense to do that based on the actual size of the identifier, rather than based on the maxLength that the user passed? In other words, even if the user passed maxLength 1000 (because the identifier really may be 1000 chars long), but the actual identifier happened to be super short, shouldn't we be using Span?

File: src/EFCore/Infrastructure/Uniquifier.cs [hunk 3]
```diff
@@ -132,6 +155,53 @@ public static string Truncate(string identifier, int maxLength, int? uniquifier
     /// <param name="uniquifier">An optional number that will be appended to the identifier.</param>
     /// <returns>The shortened identifier.</returns>
     public static string Truncate(string identifier, int maxLength, string? suffix, int? uniquifier = null)
+        => maxLength <= 512
```
Comment (roji) [inline src/EFCore/Infrastructure/Uniquifier.cs]: As above, rather than looking at maxLength, shouldn't we just be looking at `identifier.Length`?

Also, is the extra Span optimization really worth it for the patch? Unless it brings significant additional perf, maybe better to leave it out to keep the patch minimal (the below is quite a lot of extra code with potential bugs etc.).

In fact, if we're looking to improve perf here, I'd consider going a bit further: Truncate gets repeatedly called from Uniquify - continuously producing strings from the Spans used internally; a better implementation would have uniquify working on a single Span internally and only converting to a string once a unique, final identifier has been found. Of course, that's not something we should do in the patch - I'd leave the whole Span thing out unless it's significant.

File: src/EFCore/Query/Internal/ExpressionTreeFuncletizer.cs [hunk 4]
```diff
@@ -2091,11 +2094,18 @@ bool PreserveConvertNode(Expression expression)
...
+                var originalParameterName = parameterName;
+                for (var i = 0; _parameterNames.Contains(parameterName); i++)
+                {
+                    parameterName = originalParameterName + i;
+                }
+            }
+            else
             {
-                parameterName = originalParameterName + i;
+                parameterName = Uniquifier.Uniquify(parameterName, _parameterNames, 512, _parameterNames.Count);
```
Comment (roji) [inline src/EFCore/Query/Internal/ExpressionTreeFuncletizer.cs]: This uses `_parameterNames.Count` as the uniquifier, instead of tracking per prefix; that's the cause for all the parameter numbering "holes" that you see in the test SQLs. Instead, `_parameterNames` could simply be converted to a dictionary that maps prefixes to their highest-so-far-used number (and that would be the uniquifier). That would ensure that for each prefix, we get simply, incrementing numbers without holes.

I'm not going to pretend that this is super important, but it also seems pretty simple/risk-free to do. Any reason you think we shouldn't?

Comment (cincuranet) [reply src/EFCore/Query/Internal/ExpressionTreeFuncletizer.cs]: > I'm not going to pretend that this is super important, but it also seems pretty simple/risk-free to do. Any reason you think we shouldn't?

Original idea was to revert to original behavior that was using running count. This is basically doing that (while using the rest of the introduced changes).

Adding extra dictionary and lookup seemed wasteful to me. I personally don't expect perfectly numbered parameters. Also it would require `Uniquifier` to return last used number - not a huge deal, but I would say too much for servicing...

File: src/EFCore/Infrastructure/Uniquifier.cs (hunk 3 above)
Comment (cincuranet) [reply src/EFCore/Infrastructure/Uniquifier.cs]: > Also, is the extra Span optimization really worth it for the patch? Unless it brings significant additional perf, maybe better to leave it out to keep the patch minimal (the below is quite a lot of extra code with potential bugs etc.).

Without the Span version the allocation ratio goes from 1.06x to 1.19x. Time goes from 1.04x to 1.05x. Seems worth it. But if you see that too risky, I have no problem removing it.

> In fact, if we're looking to improve perf here, I'd consider going a bit further: Truncate gets repeatedly called from Uniquify - continuously producing strings from the Spans used internally; a better implementation would have uniquify working on a single Span internally and only converting to a string once a unique, final identifier has been found. Of course, that's not something we should do in the patch - I'd leave the whole Span thing out unless it's significant.

Yes, we discussed that. Remember. But ultimately decided it would be too risky for patch (it would also require switching to alternate lookup for `Dictionary<K, V>`, sadly nothing like that on interface or sets).

File: src/EFCore.Relational/Query/SqlNullabilityProcessor.cs (hunk 1 above)
Comment (cincuranet) [reply src/EFCore.Relational/Query/SqlNullabilityProcessor.cs]: Right. I forgot that the `uniquifier` parameter in `Truncate` is fixed and hence we know in advance the total length. I'll try changing it and see whether it works.

File: src/EFCore/Infrastructure/Uniquifier.cs (hunk 2 above)
Comment (cincuranet) [reply src/EFCore/Infrastructure/Uniquifier.cs]: Right. Completely missed this is not internal.

File: src/EFCore/Infrastructure/Uniquifier.cs (hunk 3 above)
Comment (roji) [reply src/EFCore/Infrastructure/Uniquifier.cs]: OK. The perf diff from 1.04x to 1.05x doesn't seem to justify it for me - for the patch specifically; we can always do whatever we want for 11 of course. So I'd say let's keep the patch super simple and low-risk and remove it.

File: src/EFCore/Infrastructure/Uniquifier.cs (hunk 2 above)
Comment (roji) [reply src/EFCore/Infrastructure/Uniquifier.cs]: FWIW for patches I'd even try avoiding it for pubternal, just in case (unless it becomes difficult).

File: src/EFCore/Query/Internal/ExpressionTreeFuncletizer.cs (hunk 4 above)
Comment (roji) [reply src/EFCore/Query/Internal/ExpressionTreeFuncletizer.cs]: Definitely agree for servicing, no need to do anything beyond the minimum. The below is only for 11.

> Adding extra dictionary and lookup seemed wasteful to me.

The thing is that we already have the `_parameterNames` HashSet, which we already look up on, etc. So unless I'm mistaken, this wouldn't add any additional overhead compared to what we're already doing today (haven't thought it through).

Otherwise I agree that it's not very important, though the idea behind the change in 10 was to really make parameter names nice and logical - the holes slightly go against it. But no really strong feelings.

Comment (cincuranet) [reply src/EFCore/Query/Internal/ExpressionTreeFuncletizer.cs]: OK. I'll keep that in mind.

File: src/EFCore/Infrastructure/Uniquifier.cs [hunk 5]
```diff
@@ -26,7 +26,23 @@ public static string Uniquify<T>(
...
+    /// <summary>
+    ///     Creates a unique identifier by appending a number to the given string.
+    /// </summary>
+    /// <typeparam name="T">The type of the object the identifier maps to.</typeparam>
+    /// <param name="currentIdentifier">The base identifier.</param>
+    /// <param name="otherIdentifiers">A dictionary where the identifier will be used as a key.</param>
+    /// <param name="maxLength">The maximum length of the identifier.</param>
+    /// <param name="uniquifier">An optional starting number for the uniquifier.</param>
+    /// <returns>A unique identifier.</returns>
+    public static string Uniquify<T>(
```
Comment (roji) [inline src/EFCore/Infrastructure/Uniquifier.cs:41]: Assuming we intend to clean these up for 11/later and e.g. make maxLength optional, it may be prudent to put `[EntityFrameworkInternal]` on the new overloads you're introducing here.

Comment (cincuranet) [reply src/EFCore/Infrastructure/Uniquifier.cs:41]: Sir, yes sir.

File: src/EFCore/Infrastructure/Uniquifier.cs [hunk 6]
```diff
@@ -78,9 +163,30 @@ public static string Uniquify<TKey, TValue>(
...
+    /// <typeparam name="TValue">The type of the object the identifier maps to.</typeparam>
+    /// <param name="currentIdentifier">The base identifier.</param>
+    /// <param name="otherIdentifiers">A dictionary where the identifier will be used as part of the key.</param>
+    /// <param name="suffix">An optional suffix to add after the uniquifier.</param>
+    /// <param name="keySelector">Creates the key object from an identifier.</param>
+    /// <param name="maxLength">The maximum length of the identifier.</param>
+    /// <param name="uniquifier">An optional starting number for the uniquifier.</param>
+    /// <returns>A unique identifier.</returns>
+    [EntityFrameworkInternal]
+    public static string Uniquify<TKey, TValue>(
```
Comment (roji) [inline src/EFCore/Infrastructure/Uniquifier.cs:129]: Maybe it's worth leaving out all the other new overloads which call into this one, introducing the pubternal overloads that we actually need in this servicing PR. Not critical, but would make the patch minimal (we can always refactor later in main).

Comment (roji) [reply src/EFCore/Infrastructure/Uniquifier.cs:129]: Are all the new overloads of Uniquify that this introduced actually being called? Am suggesting to reduce the patch size by removing anything that isn't necessary, is all.

Comment (cincuranet) [reply src/EFCore/Infrastructure/Uniquifier.cs:129]: OK

**Comment by cincuranet** [comment]
cc @artl93 
56 files looks big, but the changes are mostly test in files. The actual code is small.
For 11.0 there's more performance available and I'll do it. But for servicing we kept it small.

**Comment by cincuranet** [comment]
Approved via email.
