### PR TITLE
Take backing field into account when deciding what kind of collection to create

### LINKED ISSUE #15506: Use backing field when determining collection navigation type to create
Looks like right now we are only looking at the property CLR type. See #10800.

Repro:
```C#
public class Blog
{
    private List<Post> _posts;
    
    public int Id { get; set; }

    public IEnumerable<Post> Posts
    {
        get => _posts;
        set => _posts = (List<Post>) value;
    }
}

public class Post
{
    public int Id { get; set; }
    public Blog Blog { get; set; }
}

public class BloggingContext : DbContext
{
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Blog>();
    }
    
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder) 
        => optionsBuilder
            .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=Test;ConnectRetryCount=0");
}

public class Program
{
    public static void Main()
    {
        using (var context = new BloggingContext())
        {
            context.Database.EnsureDeleted();
            context.Database.EnsureCreated();

            context.Add(new Blog
            {
                Posts = new List<Post>
                {
                    new Post(),
                    new Post(),
                    new Post()
                }
            });
            
            context.SaveChanges();
        }
        
        using (var context = new BloggingContext())
        {
            var blogs = context.Set<Blog>().Include(e => e.Posts).ToList();
        }
    }
}
```
Throws:
```
Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.HashSet`1[Post]' to type 'System.Collections.Generic.List`1[Post]'.
   at Blog.set_Posts(IEnumerable`1 value) in C:\Stuff\TwoTwo\TwoTwo\Program.cs:line 20
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrCollectionAccessorFactory.CreateAndSetHashSet[TEntity,TCollection,TElement](TEntity entity, Action`2 setterDelegate)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.GetOrCreateCollection(Object instance)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.IncludeCollection[TEntity,TRelated,TElement](Int32 includeId, INavigation navigation, INavigation inverseNavigation, IEntityType targetEntityType, IClrCollectionAccessor clrCollectionAccessor, IClrPropertySetter inverseClrPropertySetter, Boolean tracking, TEntity entity, Func`1 relate
dEntitiesFactory, Func`3 joinPredicate)
   at lambda_method(Closure , QueryContext , Blog , Object[] )
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler._Include[TEntity](QueryContext queryContext, TEntity entity, Object[] included, Action`3 fixup)
   at lambda_method(Closure , Blog )
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider._TrackEntities[TOut,TIn](IEnumerable`1 results, QueryContext queryContext, IList`1 entityTrackingInfos, IList`1 entityAccessors)+MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.Main() in C:\Stuff\TwoTwo\TwoTwo\Program.cs:line 70
```

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #15506

### CODE REVIEW

File: src/EFCore/Metadata/Internal/ClrCollectionAccessorFactory.cs [hunk 1]
```diff
@@ -53,14 +53,28 @@ public class ClrCollectionAccessorFactory
             bool forConstruction = false,
             bool forSet = false)
         {
+            MemberInfo GetMostDerivedMemberInfo()
```
Comment (smitpatel) [inline src/EFCore/Metadata/Internal/ClrCollectionAccessorFactory.cs]: get*
