### PR TITLE
Query: Cast result of IndexOf appropriately for SqlServer

### LINKED ISSUE #18772: Query: sql exception (cant cast from bigint to int) when trying to project result of IndexOf
query:

```cs
ctx.Entities1.Select(e => e.NullableStringA.IndexOf("F") }).ToList()
```

exception:
```

Unable to cast object of type 'System.Int64' to type 'System.Int32'.

Microsoft.Data.SqlClient.SqlBuffer.Int32.get()
	Microsoft.Data.SqlClient.SqlDataReader.GetInt32(int)
    Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.ReadInt(System.Data.Common.DbDataReader, int, Microsoft.EntityFrameworkCore.Storage.ReaderColumn) in BufferedDataReader.cs
    Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.ReadRow() in BufferedDataReader.cs
    Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.BufferedDataRecord.Initialize(System.Data.Common.DbDataReader, System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Storage.ReaderColumn>) in BufferedDataReader.cs
    Microsoft.EntityFrameworkCore.Query.Internal.BufferedDataReader.Initialize(System.Collections.Generic.IReadOnlyList<Microsoft.EntityFrameworkCore.Storage.ReaderColumn>) in BufferedDataReader.cs
    Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(Microsoft.EntityFrameworkCore.Storage.RelationalCommandParameterObject) in RelationalCommand.cs
    Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable<T>.Enumerator.InitializeReader(Microsoft.EntityFrameworkCore.DbContext, bool) in QueryingEnumerable.cs
    Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementation<TState, TResult>(System.Func<Microsoft.EntityFrameworkCore.DbContext, TState, TResult>, System.Func<Microsoft.EntityFrameworkCore.DbContext, TState, Microsoft.EntityFrameworkCore.Storage.ExecutionResult<TResult>>, TState) in ExecutionStrategy.cs
    Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.Execute<TState, TResult>(TState, System.Func<Microsoft.EntityFrameworkCore.DbContext, TState, TResult>, System.Func<Microsoft.EntityFrameworkCore.DbContext, TState, Microsoft.EntityFrameworkCore.Storage.ExecutionResult<TResult>>) in ExecutionStrategy.cs
```

Problem is that on SqlServer function CHARINDEX returns bigint if the argument is nvarchar(max)

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #18772

### CODE REVIEW

File: src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs [hunk 1]
```diff
@@ -82,12 +82,27 @@ public virtual SqlExpression Translate(SqlExpression instance, MethodInfo method
                 var stringTypeMapping = ExpressionExtensions.InferTypeMapping(instance, argument);
                 argument = _sqlExpressionFactory.ApplyTypeMapping(argument, stringTypeMapping);
 
-                var charIndexExpression = _sqlExpressionFactory.Subtract(
-                    _sqlExpressionFactory.Function(
+                SqlExpression charIndexExpression;
+                var storeType = stringTypeMapping.StoreType;
+                if (string.Equals(storeType, "nvarchar(max)", StringComparison.OrdinalIgnoreCase)
+                    || string.Equals(storeType, "varchar(max)", StringComparison.OrdinalIgnoreCase))
```
Comment (AndriySvyryd) [inline src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs]: We probably should delegate some of this to the type mapping to make this more robust. Perhaps part of https://github.com/aspnet/EntityFrameworkCore/issues/10434

Comment (smitpatel) [reply src/EFCore.SqlServer/Query/Internal/SqlServerStringMethodTranslator.cs]: Delegating if it is max type? I would prefer to keep the logic of adding convert node in query only. A translation pipeline should know that when translating to a function, you may get back different types based on typeMapping of arguments.
