### PR TITLE
Entity equality support for non-extension Contains

### LINKED ISSUE #15554: QueryRewrite: support contains on collection navigation
query:

```cs
customers.Select(c => c.Orders.Contains(someOrder))
```

currently Enumerable.Contains is translated to `IN`, which is incorrect for the case above

### PR DESCRIPTION
**Pull request by roji**
EE handled the extension version of {IQueryable,IEnumerable}.Contains,
but not instance methods such as List.Contains.

Fixes #15554, continues work from #16134.

There's a slight complication with the translation of `orders.Where(o => customers.Any(c => c.Orders.Contains(o)))` (test Where_contains_on_navigation).

As this wasn't handled by EE, nav expansion rewrote this to:

```sql
SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[OrderDate]
FROM [Orders] AS [o]
WHERE EXISTS (
    SELECT 1
    FROM [Customers] AS [c]
    WHERE EXISTS (
        SELECT 1
        FROM [Orders] AS [o0]
        WHERE (([c].[CustomerID] = [o0].[CustomerID]) AND [o0].[CustomerID] IS NOT NULL) AND ([o0].[OrderID] = [o].[OrderID])))
```

With this PR, the translation becomes:

```sql
SELECT [o].[OrderID], [o].[CustomerID], [o].[EmployeeID], [o].[OrderDate]
FROM [Orders] AS [o]
WHERE EXISTS (
    SELECT 1
    FROM [Customers] AS [c]
    WHERE [o].[OrderID] IN (
        SELECT [o0].[OrderID]
        FROM [Orders] AS [o0]
        WHERE ([c].[CustomerID] = [o0].[CustomerID]) AND [o0].[CustomerID] IS NOT NULL
    )
)
```

Which seems fine. However, EE can't handle composite keys, so that case is specifically left for nav expansion to handle (usually EE throws an informative exception instead). See test Where_contains_on_navigation_with_composite_keys.

### CODE REVIEW

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 1]
```diff
@@ -258,16 +267,17 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
 
         protected virtual Expression VisitContainsMethodCall(MethodCallExpression methodCallExpression)
         {
-            var arguments = methodCallExpression.Arguments;
-            var newSource = Visit(arguments[0]);
-            var newItem = Visit(arguments[1]);
+            // We handle both Contains the extension method and the instance method
+            var (newSource, newItem) = methodCallExpression.Arguments.Count == 2
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: Either split out 2 variable assignment into multiple statements or do assignment and call visit separately.

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 2]
```diff
@@ -280,15 +290,22 @@ protected virtual Expression VisitContainsMethodCall(MethodCallExpression method
             var entityType = sourceEntityType ?? itemEntityType;
 
             var keyProperties = entityType.FindPrimaryKey().Properties;
-            var keyProperty = keyProperties.Count == 1
-                ? keyProperties.Single()
-                : throw new NotSupportedException(CoreStrings.EntityEqualityContainsWithCompositeKeyNotSupported(entityType.DisplayName()));
+            if (keyProperties.Count > 1)
+            {
+                // We usually throw on composite keys, but here specifically we don't in order to allow Any(Contains()) to be translated
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: It is not task for navigation expansion. Comment is incorrect.

**Comment by roji** [comment]
> Navigation expansion does not care about keys. It is not expansion of navigation. EE should rewrite to whatever appropriate query if any.

Sure - the point is only that currently nav expansion also currently rewrites Any(Contains) without needing to care about keys or translate to them (with SQL EXISTS). The translation is different but both seem equally valid (see the SQL samples I posted above from test Where_contains_on_navigation). And the one advantage the current nav expansion mapping has, is that it works on composite keys.

> Hold off on this change for now. It is correct fix but if we are taking care of Queryable.Contains already then my changes in new nav expansion should fix it as it includes changes to make all translatable methods to Queryable ones. So c.Orders.Contains(o) would be re-written to c.Orders.AsQueryable().Contains(o)

No problem, that would certainly simplify things in EE. Keep in mind also the (somewhat contrived) scenario where the Contains list isn't an entity type:

`customers.Where(c => new List<Customer> { new Customer { CustomerID = "XXX" } }.Contains(c))`

Are we planning for the constant list here to also have AsQueryable()? If so then otherwise, otherwise we'd still need some special handling in EE.

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs (hunk 2 above)
Comment (roji) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: See my comment below - it's an alternate translation of the same specific construct that does not care need to care about keys.

**Comment by smitpatel** [comment]
>  the point is only that currently nav expansion also currently rewrites Any(Contains) without needing to care about keys or translate to them (with SQL EXISTS).

Is it actually task for expanding a navigation though? If it is not expanding navigation then it does not belong to nav expansion. Could be different visitor if not EE. (EE seem to deal with converting entities to key access where suitable)

List contains - true. Add some tests

**Comment by smitpatel** [comment]
I missed a bit on list example. You would need to add another runtime parameter or a new constant which evaluates the `List.Select`. Enumerable methods are not task for translation pipeline.

**Comment by roji** [comment]
>> the point is only that currently nav expansion also currently rewrites Any(Contains) without needing to care about keys or translate to them (with SQL EXISTS).
>
> Is it actually task for expanding a navigation though? If it is not expanding navigation then it does not belong to nav expansion. Could be different visitor if not EE. (EE seem to deal with converting entities to key access where suitable)

True, definitely could make sense to split it out to a different visitor. And also true that it doesn't feel like it belongs in entity equality - strictly speaking there is no actual equality comparison.

Concretely, how do you want to deal with this? Is your new implementation of nav rewrite going to drop the Any(Contains) rewriting? If so, do you want me to write it in a separate visitor?

> List contains - true. Add some tests

Will do

> I missed a bit on list example. You would need to add another runtime parameter or a new constant which evaluates the List.Select. Enumerable methods are not task for translation pipeline.

Can you explain/give example? I didn't understand this bit...

**Comment by smitpatel** [comment]
If you just do blind rewrite on this 
`customers.Where(c => new List<Customer> { new Customer { CustomerID = "XXX" } }.Contains(c))`
to 
`customers.Where(c => new List<Customer> { new Customer { CustomerID = "XXX" } }.Select(c => c.Id).Contains(c.Id))`

Then we don't know how to translate `constant.Select(c => c.Id)` It is enumerable select which does not work on any data source associated with server. If you write the second query yourself outside of EF then The Enumerable select will be processed by ParameterExtractor already. So if you are doing rewrite in compilation phase you have to do the same.

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs (hunk 2 above)
Comment (smitpatel) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: Nav expansion bit is misleading.

**Comment by roji** [comment]
Of course, makes sense. But for the constant example we could just evaluate (like we already do for other constant key rewriting in EE), right? The problem would be with a parameterized list, where we'd need to do what you say...

**Comment by smitpatel** [comment]
Yes.
Constant -> Evaluate
Parameter -> add runtime parameter.
Same thing we do when accessing key when one side was parameter/constant.

**Comment by roji** [comment]
Makes sense. So just to confirm, this PR still needs to recognize and rewrite List.Contains() - it will not be normalized to IQueryable.Contains()? That means it largely keeps its current form, with the additions discussed.

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs (hunk 2 above)
Comment (roji) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: Modified the comment.

**Comment by roji** [comment]
@smitpatel have implemented constant and parameter handling for the source list.

**Comment by roji** [comment]
@smitpatel rebased this after your changes to nav expansion etc.

Should we have EnumerableMethodProvider just like we have QueryableMethodProvider? The EE Contains logic, for example, needs to wrap non-queryable Lists of keys with Contains, Select, etc. If so I can do that as part of #16300. Otherwise wrapping these with AsQueryable fails in NavigationExpandingEV.VisitMethodCall (NonNavSource), which seems like the way we want it, right?

**Comment by smitpatel** [comment]
EF Core query pipeline is about translating Methods to server. Only queryble methods can be translated. While certain enumerable method may appear due to collection navigations, we convert them to Queryable methods as once they are expanded it, it would be queryable anyway. So EnumerableMethodProvider does not belong to EF Core. Yes, certain visitor may require to process Enumerable method because of operators working on client side collection. Those visitor should resolve particular methods they need.

Creating generalized class for Enumerable methods passes a wrong message in terms of what we translate. And as @ajcvickers mentioned elsewhere, people would use our library for entirely wrong reason just to get those method resolutions. Hence it is not a surface we want to add. If there many different visitors using many of such methods, we can add pubternal class later.

**Comment by smitpatel** [comment]
You should not put AsQueryable around something which is not EntityQueryable eventually.
Enumerable.Contains is handled here https://github.com/aspnet/EntityFrameworkCore/blob/release/3.0/src/EFCore.Relational/Query/Internal/ContainsTranslator.cs

**Comment by roji** [comment]
Thanks for the explanation @smitpatel, all makes sense.

The idea wasn't to add a *public* EnumerableMethodProvider, just an internal one, to avoid having to look up enumerable LINQ methods in various places, similar to #16504. Searching for `typeof(Enumerable)` shows quite a few cases where enumerable methods are being looked. Let me know what you think.

In any case, the PR as it is does its own lookup, so it can be reviewed and merged regardless of this question.

**Comment by smitpatel** [comment]
I did not find enough look ups for enumerable methods which warrants additional class. Only handful of places with very little scope of making it DRY. Also remember `.Internal` cannot cross assembly boundaries.

File: src/EFCore/Extensions/Internal/ExpressionExtensions.cs [hunk 3]
```diff
@@ -170,5 +170,15 @@ public static LambdaExpression UnwrapLambdaFromQuote(this Expression expression)
...
             ? unary.Operand
             : expression);
+
+        /// <summary>
+        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
+        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
+        ///     any release. You should only use it directly in your code with extreme caution and knowing that
+        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
+        /// </summary>
+        public static bool IsQueryParam(this ParameterExpression parameterExpression)
```
Comment (smitpatel) [inline src/EFCore/Extensions/Internal/ExpressionExtensions.cs]: IsQueryParameter

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 4]
```diff
@@ -36,6 +36,13 @@ public class EntityEqualityRewritingExpressionVisitor : ExpressionVisitor
         private static readonly MethodInfo _objectEqualsMethodInfo
             = typeof(object).GetRuntimeMethod(nameof(object.Equals), new[] { typeof(object), typeof(object) });
 
+        // TODO: Clean up as part of #16300
+        private static MethodInfo _enumerableContainsMethodInfo =
+            typeof(Enumerable).GetMethods().First(m => m.Name == nameof(Enumerable.Contains) && m.GetParameters().Length == 2);
+        private static MethodInfo _enumerableSelectMethodInfo =
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: We take slightly different pattern.
```
        private static readonly MethodInfo _containsMethodInfo = typeof(Enumerable).GetTypeInfo()
            .GetDeclaredMethods(nameof(Enumerable.Contains))
            .Single(mi => mi.GetParameters().Length == 2);
```

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 5]
```diff
@@ -241,6 +248,15 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
                 }
             }
 
+            // We handled the Contains extension method above, but there's also List.Contains and potentially others on ICollection
+            if (methodCallExpression.Method.Name == "Contains"
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: Check ContainsTranslator to recognize the methods. It may exclude somethings but if we cannot translate we can defer not doing EE on it fully for now

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 6]
```diff
@@ -334,27 +352,74 @@ protected virtual Expression VisitContainsMethodCall(MethodCallExpression method
...
-                QueryableMethodProvider.SelectMethodInfo.MakeGenericMethod(entityType.ClrType, keyProperty.ClrType),
-                Unwrap(newSource),
-                keySelector);
-
-            var rewrittenItem = newItem.IsNullConstantExpression()
+            if (keyProperties.Count > 1)
+            {
+                // We usually throw on composite keys, but here specifically we don't, since the construct Any(Contains()) can be translated
+                // without any key rewriting (see test Where_contains_on_navigation_with_composite_keys).
+                // This is currently done by nav expansion so we let the expression through.
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: It is not longer done by nav expansion.
Rather throw

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 7]
```diff
@@ -334,27 +352,74 @@ protected virtual Expression VisitContainsMethodCall(MethodCallExpression method
             var entityType = sourceEntityType ?? itemEntityType;
 
             var keyProperties = entityType.FindPrimaryKey().Properties;
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: Did not notice before but make sure that PK exists and we are not doing entityEquality rewrite on keyless entities

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 8]
```diff
@@ -334,27 +352,74 @@ protected virtual Expression VisitContainsMethodCall(MethodCallExpression method
...
+            }
+            else
+            {
+                // The source list is neither a constant nor a parameter. Wrap it with a projection to its primary key.
+                var param = Expression.Parameter(entityType.ClrType, "v");
+                var keySelector = Expression.Lambda(CreatePropertyAccessExpression(param, keyProperty), param);
+                rewrittenSource = Expression.Call(
+                    (Unwrap(newSource).Type.IsQueryableType()
+                        ? QueryableMethodProvider.SelectMethodInfo
+                        : _enumerableSelectMethodInfo).MakeGenericMethod(entityType.ClrType, keyProperty.ClrType),
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: No enumerable select. We cannot translate it. If the source is not queryable then just throw

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 9]
```diff
@@ -786,8 +851,7 @@ private Expression CreatePropertyAccessExpression(Expression target, IProperty p
 
             // If the target is a query parameter, we can't simply add a property access over it, but must instead cause a new
             // parameter to be added at runtime, with the value of the property on the base parameter.
-            if (target is ParameterExpression baseParameterExpression
-                && baseParameterExpression.Name.StartsWith(CompiledQueryCache.CompiledQueryParameterPrefix, StringComparison.Ordinal))
+            if (target is ParameterExpression baseParameterExpression && baseParameterExpression.IsQueryParam())
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: If this is not used outside of this class then make it private method

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 10]
```diff
@@ -820,6 +884,31 @@ private static object ParameterValueExtractor(QueryContext context, string baseP
...
+        /// projection to its elements' <paramref name="property"/> values.
+        /// </summary>
+        private static object ParameterListValueExtractor(QueryContext context, string baseParameterName, IProperty property)
+        {
+            var baseListParameter = (IEnumerable)context.ParameterValues[baseParameterName];
+            if (baseListParameter == null)
+            {
+                return null;
+            }
+            var keyListType = typeof(List<>).MakeGenericType(property.ClrType);
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: Is `param.Select(e => property.GetGetter().GetClrValue(e)).ToList()` possible?

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 11]
```diff
@@ -820,6 +884,31 @@ private static object ParameterValueExtractor(QueryContext context, string baseP
...
+            var keyList = (IList)Activator.CreateInstance(keyListType);
+            foreach (var listItem in baseListParameter)
+            {
+                keyList.Add(property.GetGetter().GetClrValue(listItem));
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: cache GetGetter() result

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs (hunk 7 above)
Comment (roji) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: Makes sense, will check other places too. Will throw an informative exception.

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs (hunk 9 above)
Comment (roji) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: Seemed like a good functionality to extract out, will revert.

Comment (smitpatel) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: It's good that code is DRY but we don't need to put it outside till anyone actually need it.

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs (hunk 10 above)
Comment (roji) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: Unfortunately not (at least that I'm aware of), because `keyList` is a non-generic IList... I also hate this.

Comment (smitpatel) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: Do we not know the type of keyList?

Comment (roji) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: You're right, will do.

Comment (roji) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: In the end I left the constant implementation as-is, since it seemed like overkill to generate an extractor and invoke it. For parameter it is now generic.

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 12]
```diff
@@ -179,20 +187,19 @@ protected override Expression VisitConditional(ConditionalExpression conditional
...
         {
+            var method = methodCallExpression.Method;
             var arguments = methodCallExpression.Arguments;
             Expression newSource;
 
             // Check if this is this Equals()
-            if (methodCallExpression.Method.Name == nameof(object.Equals)
-                && methodCallExpression.Object != null
-                && methodCallExpression.Arguments.Count == 1)
+            if (method.Name == nameof(object.Equals) && methodCallExpression.Object != null && methodCallExpression.Arguments.Count == 1)
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: nit: break long lines. :trollface:

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 13]
```diff
@@ -334,27 +348,72 @@ protected virtual Expression VisitContainsMethodCall(MethodCallExpression method
...
-            // Wrap the source with a projection to its primary key, and the item with a primary key access expression
-            var param = Expression.Parameter(entityType.ClrType, "v");
-            var keySelector = Expression.Lambda(CreatePropertyAccessExpression(param, keyProperty), param);
-            var keyProjection = Expression.Call(
-                QueryableMethodProvider.SelectMethodInfo.MakeGenericMethod(entityType.ClrType, keyProperty.ClrType),
-                Unwrap(newSource),
-                keySelector);
-
-            var rewrittenItem = newItem.IsNullConstantExpression()
+            var keyProperty = keyProperties.Count switch
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: For keyless entities, FindPrimaryKey will return null so .Properties would NRE.
Also add a test to verify exception.

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 14]
```diff
@@ -334,27 +348,72 @@ protected virtual Expression VisitContainsMethodCall(MethodCallExpression method
...
+            {
+                0 => throw new NotSupportedException(CoreStrings.EntityEqualityOnKeylessEntityNotSupported(entityType.DisplayName())),
+                1 => keyProperties[0],
+                _ => throw new NotSupportedException(CoreStrings.EntityEqualityContainsWithCompositeKeyNotSupported(entityType.DisplayName()))
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: InvalidOperationExceptions

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 15]
```diff
@@ -334,27 +348,72 @@ protected virtual Expression VisitContainsMethodCall(MethodCallExpression method
...
+
+            if (newSource is ConstantExpression listConstant)
+            {
+                // The source list is a constant, evaluate and replace with a list of the keys
+                var listValue = (IEnumerable)listConstant.Value;
+                var keyListType = typeof(List<>).MakeGenericType(keyProperty.ClrType);
+                var keyList = (IList)Activator.CreateInstance(keyListType);
+                foreach (var listItem in listValue)
+                {
+                    keyList.Add(keyProperty.GetGetter().GetClrValue(listItem));
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: nit: could cache getter here easily

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 16]
```diff
@@ -334,27 +348,72 @@ protected virtual Expression VisitContainsMethodCall(MethodCallExpression method
...
+                }
+                rewrittenSource = Expression.Constant(keyList, keyListType);
+            }
+            else if (newSource is ParameterExpression listParam
+                     && listParam.Name.StartsWith(CompiledQueryCache.CompiledQueryParameterPrefix, StringComparison.Ordinal))
+            {
+                // The source list is a parameter. Add a runtime parameter that will contain a list of the extracted keys for each execution.
+                var parameterKeyExtractor = _parameterListValueExtractor.MakeGenericMethod(entityType.ClrType, keyProperty.ClrType);
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: nit:parameterKeyExtractMethod

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 17]
```diff
@@ -334,27 +348,72 @@ protected virtual Expression VisitContainsMethodCall(MethodCallExpression method
...
+                    Expression.Call(
+                        parameterKeyExtractor,
+                        QueryCompilationContext.QueryContextParameter,
+                        Expression.Constant(listParam.Name, typeof(string)),
+                        Expression.Constant(keyProperty, typeof(IProperty))),
+                    QueryCompilationContext.QueryContextParameter
+                );
+
+                var newParameterName = $"{RuntimeParameterPrefix}{listParam.Name.Substring(CompiledQueryCache.CompiledQueryParameterPrefix.Length)}_{keyProperty.Name}";
+                _queryCompilationContext.RegisterRuntimeParameter(newParameterName, lambda);
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: Should RegisterRuntimeParameter return parameterExpression?
It knows the type of parameter and name of parameter to create it. And anyone registering a parameter needs to construct it

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 18]
```diff
@@ -334,27 +348,72 @@ protected virtual Expression VisitContainsMethodCall(MethodCallExpression method
...
+            }
+            else
+            {
+                // The source list is neither a constant nor a parameter. Wrap it with a projection to its primary key.
+                var param = Expression.Parameter(entityType.ClrType, "v");
+                var keySelector = Expression.Lambda(CreatePropertyAccessExpression(param, keyProperty), param);
+                rewrittenSource = Expression.Call(
+                    QueryableMethodProvider.SelectMethodInfo.MakeGenericMethod(entityType.ClrType, keyProperty.ClrType),
+                    Unwrap(newSource),
+                    keySelector);
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: Wrap it in Expression.Quote

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 19]
```diff
@@ -334,27 +348,72 @@ protected virtual Expression VisitContainsMethodCall(MethodCallExpression method
...
+            }
+
+            // Rewrite the item with a key expression as needed (constant, parameter and other are handled within)
+            rewrittenItem = newItem.IsNullConstantExpression()
                 ? Expression.Constant(null)
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: If possible specify the type of null constant.

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs [hunk 20]
```diff
@@ -385,6 +444,11 @@ protected virtual Expression VisitOrderingMethodCall(MethodCallExpression method
                 || genericMethodDefinition == QueryableMethodProvider.ThenByMethodInfo;
 
             var keyProperties = entityType.FindPrimaryKey().Properties;
+            if (keyProperties.Count == 0)
```
Comment (smitpatel) [inline src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: All these checks need to check for FindPrimaryKey == null

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs (hunk 12 above)
Comment (roji) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: How long are long lines :)

Will do.

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs (hunk 14 above)
Comment (roji) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: Changed here and everywhere else.

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs (hunk 17 above)
Comment (roji) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: It's a nice idea, but RegisterRuntimeParameter doesn't really know the type - the lambda it receives currently returns object. I could change the lambda to return the actual type but that creates some complications of its own (and values get boxed anyway so generics doesn't help). I'll pass in the type to RegisterRuntimeParameter, but let me know if I've missed something easier.

Comment (roji) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: Actually I'll go ahead and do this.

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs (hunk 18 above)
Comment (roji) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: Did elsewhere as well.

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs (hunk 19 above)
Comment (roji) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: Just took the entity type's clrType, right?

File: src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs (hunk 12 above)
Comment (smitpatel) [reply src/EFCore/Query/Internal/EntityEqualityRewritingExpressionVisitor.cs]: 120 characters.
Generally for conditions we put them on new line when applying && or ||.
@AndriySvyryd changes them when doing code cleanup.

**Comment by smitpatel** [comment]
Make sure build passes. I don't know why everything is red.

**Comment by roji** [comment]
There were some typing/nullability issues related to https://github.com/aspnet/EntityFrameworkCore/pull/16841#discussion_r310325713 - I ended up going back to a simpler version where the parameter version is explicitly passed into RegisterRuntimeParameter (instead of simply inferring it from the lambda's return type). I'll revisit as part of #16564.
