### PR TITLE
Be more resilient when using the model from the model snapshot

### LINKED ISSUE #17145: InvalidOperationException when creating a migration and using HasData in OnModelCreating
I'm hitting an exception when creating a new migration on a DbContext which overrides OnModelCreating and includes HasData. I experienced this in an existing project which has been updated from 2,2 although I was able to reproduce the flow of events using a newly created ASP.NET Core 3.0 project.

### Steps to reproduce

1. Start with a default ASP.NET Core project which uses Identity
2. Add a simple DbSet, I used...

```
public class ApplicationDbContext : IdentityDbContext
{
	public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
		: base(options)
	{
	}

	public DbSet<Thing> Things { get; set; }      

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Thing>()
			.HasData(new Thing { Id = 1, Name = "A thing" });

		base.OnModelCreating(modelBuilder);
	}
}

public class Thing
{
	public int Id { get; set; }
	public string Name { get; set; }
}
```

3. Create a migration which should succeed
4. Add another DbSet...

```
public class ApplicationDbContext : IdentityDbContext
{
	public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
		: base(options)
	{
	}

	public DbSet<Thing> Things { get; set; }
	public DbSet<AnotherThing> AnotherThings { get; set; }

	protected override void OnModelCreating(ModelBuilder modelBuilder)
	{
		modelBuilder.Entity<Thing>()
			.HasData(new Thing { Id = 1, Name = "A thing" });

		base.OnModelCreating(modelBuilder);
	}
}

public class Thing
{
	public int Id { get; set; }
	public string Name { get; set; }
}

public class AnotherThing
{
	public int Id { get; set; }
	public string Name { get; set; }
}
```

5. Try to create a migration

The expected result is that a new migration is generated.
The actual result is an exception...

```
C:\Users\steve.gordon\source\repos\WebApplication3\WebApplication3>dotnet ef migrations add step3
info: Microsoft.EntityFrameworkCore.Infrastructure[10403]
      Entity Framework Core 3.0.0-preview8.19405.11 initialized 'ApplicationDbContext' using provider 'Microsoft.EntityFrameworkCore.SqlServer' with options: None
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.InvalidOperationException: The model must be finalized before 'GetTypeMapping' can be used. Ensure that either 'OnModelCreating' has completed or, if using a stand-alone 'ModelBuilder', that 'FinalizeModel' has been called.
   at Microsoft.EntityFrameworkCore.PropertyExtensions.GetTypeMapping(IProperty property)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.SimplePrincipalKeyValueFactory`1..ctor(IProperty property)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.KeyValueFactoryFactory.CreateSimpleFactory[TKey](IKey key)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.KeyValueFactoryFactory.Create[TKey](IKey key)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Key.<>c__19`1.<GetPrincipalKeyValueFactory>b__19_0(Key k)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Key.GetPrincipalKeyValueFactory[TKey]()
   at Microsoft.EntityFrameworkCore.Metadata.Internal.KeyExtensions.GetPrincipalKeyValueFactory[TKey](IKey key)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMapFactoryFactory.CreateFactory[TKey](IKey key)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMapFactoryFactory.Create(IKey key)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Key.<>c.<get_IdentityMapFactory>b__18_0(Key k)
   at Microsoft.EntityFrameworkCore.Internal.NonCapturingLazyInitializer.EnsureInitialized[TParam,TValue](TValue& target, TParam param, Func`2 valueFactory)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.Key.get_IdentityMapFactory()
   at Microsoft.EntityFrameworkCore.Metadata.Internal.KeyExtensions.GetIdentityMapFactory(IKey key)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetOrCreateIdentityMap(IKey key)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.Microsoft.EntityFrameworkCore.Update.IUpdateEntry.set_EntityState(EntityState value)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.TrackData(IModel source, IModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.Diff(IModel source, IModel target, DiffContext diffContext)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationsModelDiffer.GetDifferences(IModel source, IModel target)
   at Microsoft.EntityFrameworkCore.Migrations.Design.MigrationsScaffolder.ScaffoldMigration(String migrationName, String rootNamespace, String subNamespace, String language)
   at Microsoft.EntityFrameworkCore.Design.Internal.MigrationsOperations.AddMigration(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigrationImpl(String name, String outputDir, String contextType)
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.AddMigration.<>c__DisplayClass0_0.<.ctor>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.<>c__DisplayClass3_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Design.OperationExecutor.OperationBase.Execute(Action action)
Exception has been thrown by the target of an invocation.
```

### Further technical details
EF Core version: 3.0.0-preview8.19405.7 (although also tried with a nightly build of preview 9)
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 16.3 Preview 2.0

### PR DESCRIPTION
**Pull request by ajcvickers**
Fixes #17145 but see also #17205

The fix here allows the state manager to work, which is required when the model snapshot has model data in it.

### CODE REVIEW

File: src/EFCore/Metadata/Internal/Model.cs [hunk 1]
```diff
@@ -83,6 +86,16 @@ public Model([NotNull] ConventionSet conventions)
         /// </summary>
         public virtual ConventionDispatcher ConventionDispatcher { [DebuggerStepThrough] get; private set; }
 
+        /// <summary>
+        ///     This is an internal API that supports the Entity Framework Core infrastructure and not subject to
+        ///     the same compatibility standards as public APIs. It may be changed or removed without notice in
+        ///     any release. You should only use it directly in your code with extreme caution and knowing that
+        ///     doing so can result in application failures when updating to a new Entity Framework Core release.
+        /// </summary>
+        public virtual bool IsConventionBasedMutableModel
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/Model.cs]: Why not call FinalizeModel on the snapshot and rename this to `IsReadOnly`?

Comment (ajcvickers) [reply src/EFCore/Metadata/Internal/Model.cs]: Because what does it mean to finalize the model when there are no conventions? It's still not "ready to use" with things like type mappings available. I tried some time back to add just the conventions that would make this work, but that got really messy.

Hence #17205

Comment (ajcvickers) [reply src/EFCore/Metadata/Internal/Model.cs]: But I could try doing this if you think it's cleaner--but it still needs revisiting either way, and it's internal API.

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/Model.cs]: Finalize means that it won't be modified anymore. I think it will align better with what we have planned

Comment (ajcvickers) [reply src/EFCore/Metadata/Internal/Model.cs]: Okay, will do.

Comment (ajcvickers) [reply src/EFCore/Metadata/Internal/Model.cs]: @AndriySvyryd Updated.

File: src/EFCore/Metadata/Internal/Model.cs [hunk 2]
```diff
@@ -823,7 +832,7 @@ public virtual void SetPropertyAccessMode(PropertyAccessMode? propertyAccessMode
         /// </summary>
         public virtual IModel FinalizeModel()
         {
-            var finalModel = (Model)ConventionDispatcher.OnModelFinalized(Builder)?.Metadata;
+            var finalModel = (Model)ConventionDispatcher?.OnModelFinalized(Builder)?.Metadata;
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/Model.cs]: Why this changed? Is `FinalizeModel` getting called twice on the same model?

File: src/EFCore.Relational/Infrastructure/ModelSnapshot.cs [hunk 3]
```diff
@@ -16,10 +17,14 @@ public abstract class ModelSnapshot
...
-            var modelBuilder = new ModelBuilder(new ConventionSet());
+            var model = new Model();
+            var modelBuilder = new ModelBuilder(model);
+
             BuildModel(modelBuilder);
 
-            return modelBuilder.Model;
+            model.FinalizeModel();
+
+            return model;
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Infrastructure/ModelSnapshot.cs]:
```suggestion
            return model.FinalizeModel();
```

File: src/EFCore/Metadata/Internal/Model.cs [hunk 4]
```diff
@@ -823,7 +832,7 @@ public virtual void SetPropertyAccessMode(PropertyAccessMode? propertyAccessMode
...
             return finalModel?.MakeReadonly();
```
Comment (AndriySvyryd) [inline src/EFCore/Metadata/Internal/Model.cs]:
```suggestion
            return finalModel?.MakeReadonly() ?? this;
```

File: src/EFCore/Metadata/Internal/Model.cs (hunk 2 above)
Comment (ajcvickers) [reply src/EFCore/Metadata/Internal/Model.cs]: Removed the other place that the model is sometimes finalized. However, see #17205 since this is wrong too.

File: src/Shared/Check.cs [hunk 5]
```diff
@@ -93,5 +93,14 @@ public static IReadOnlyList<T> HasNoNulls<T>(IReadOnlyList<T> value, [InvokerPar
 
             return value;
         }
+
+        [Conditional("DEBUG")]
+        public static void DebugAssert([System.Diagnostics.CodeAnalysis.DoesNotReturnIf(false)] bool condition, string message)
```
Comment (AndriySvyryd) [inline src/Shared/Check.cs]: We should replace all Asserts with this

Comment (ajcvickers) [reply src/Shared/Check.cs]: Filed #17204 yesterday.
