### PR TITLE
Preserve annotations when detaching entity types and navigations.

### LINKED ISSUE #10612: Rebuilding relationships causes annotations on navigations to be lost
Cannot include a private collection in an entity
```
System.NotSupportedException : Collection is read-only.
   at System.ThrowHelper.ThrowNotSupportedException(ExceptionResource resource)
   at Microsoft.EntityFrameworkCore.Metadata.Internal.ClrICollectionAccessor`3.Add(Object instance, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.AddToCollection(InternalEntityEntry entry, INavigation navigation, IClrCollectionAccessor collectionAccessor, Object value)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.ToDependentFixup(InternalEntityEntry dependentEntry, InternalEntityEntry principalEntry, IForeignKey foreignKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.InitialFixup(InternalEntityEntry entry, ISet`1 handledForeignKeys, Boolean fromQuery)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.NavigationFixer.TrackedFromQuery(InternalEntityEntry entry, ISet`1 handledForeignKeys)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntryNotifier.TrackedFromQuery(InternalEntityEntry entry, ISet`1 handledForeignKeys)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.MarkUnchangedFromQuery(ISet`1 handledForeignKeys)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTrackingFromQuery(IEntityType baseEntityType, Object entity, ValueBuffer valueBuffer, ISet`1 handledForeignKeys)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.StartTracking(Object entity, IEntityType entityType)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.<IncludeCollectionAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.IncludeCompiler.<_IncludeAsync>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.ExpressionVisitors.Internal.TaskLiftingExpressionVisitor.<_ExecuteAsync>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.EntityQueryModelVisitor.AsyncSelectEnumerable`2.AsyncSelectEnumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.<SingleOrDefault_>d__381`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.TaskResultAsyncEnumerable`1.Enumerator.<MoveNext>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.AsyncIterator`1.<MoveNext>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<ExecuteSingletonAsyncQuery>d__23`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at booking.student.infrastructure.Repositories.StudentRepository.<FindAsync>d__6.MoveNext() in /Users/Jose8789/oculos/college/services/booking.student/infrastructure/booking.student.infrastructure/Repositories/StudentRepository.cs:line 36
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at booking.student.tests.StudentManagementTest.<ChangeProgressStatus>d__3.MoveNext() in /Users/Jose8789/oculos/college/services/booking.student/tests/booking.student.tests/StudentManagementTest.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

### Steps to reproduce

```c#
public class Student 
    {
        private List<StudentProgress> _progresses;
        protected Student()
        {
            _progresses = new List<StudentProgress>();
        }
        public IEnumerable<StudentProgress> Progresses => _progresses.AsReadOnly();
    }

public void Configure(EntityTypeBuilder<Student> studentConfiguration)
        {
            studentConfiguration.HasKey(x => x.Id);
            studentConfiguration.Ignore(x => x.DomainEvents);

            studentConfiguration.Metadata.FindNavigation(nameof(Student.Progresses))
                .SetPropertyAccessMode(PropertyAccessMode.Field);
        }
public class StudentProgress : Entity
    {
        public int ProgressStatusId { get; private set; }
        public int Year { get; private set; }
        public Grade Grade { get; private set; }
        public int CourseId { get; private set; }

        public StudentProgress(Grade grade, int year, int courseId, ProgressStatus progress)
        {
            ProgressStatusId = progress.Id;
            Year = year;
            Grade = grade;
            CourseId = courseId;
        }
    }

this is where I'm getting the error:
public async Task<Student> FindAsync(int identity)
        {
            var student = await _context.Set<Student>()
                .Include(x=>x.Progresses) // this line is generating the error
                .Where(b => b.Id == identity)
                .SingleOrDefaultAsync();

            return student;
        }
```

### LINKED ISSUE #10911: Annotations on the first owned entity type reference are lost
I discovered an odd regression that has occurred between build 28148 and 300047. I will have to spend some time tracking down when it occurred, I will try to do that tomorrow.

The issue is that my model has sub-owned types and suddenly the migration would stop generating correctly. I have tracked it down to two issues in the ModelSnapshot code, below is a Gist of a sample snapshot.

https://gist.github.com/mrswain/f975e4a2538eaea8d9b06d26d961cecc

The end result of the model should be 4 entities and 7 owned entities, and all entities should be mapped to 4 schema.table pairs.

What happens is I now get 6 entities (two owned ones become unowned) and some of the owned entities lose their table relational attributes.

I dropped the test back to build 28148 and it gives the correct output so some change has caused this.

NOTE:
My test program is a simple
```C#
using System;

namespace EFTest
{
    class Program
    {
        static void Main(string[] args)
        {
            var snapshot = new SnapshotTest();

            var model = snapshot.Model;

        }
    }
}
```
I have a breakpoint on the model assignment so I can view the results.

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Fixes #10612
Fixes #10911

### CODE REVIEW

File: src/EFCore/Metadata/Internal/EntityTypeSnapshot.cs [hunk 1]
```diff
@@ -20,15 +20,13 @@ public class EntityTypeSnapshot
         ///     directly from your code. This API may change or be removed in future releases.
         /// </summary>
         public EntityTypeSnapshot(
-            [CanBeNull] List<Tuple<string, ConfigurationSource>> ignoredMembers,
-            [CanBeNull] IReadOnlyCollection<object> seedData,
+            [CanBeNull] EntityType entityType,
             [CanBeNull] PropertiesSnapshot properties,
-            [CanBeNull] List<Tuple<InternalIndexBuilder, ConfigurationSource>> indexes,
```
Comment (ajcvickers) [inline src/EFCore/Metadata/Internal/EntityTypeSnapshot.cs]: Why Tuple not ()?

Comment (AndriySvyryd) [reply src/EFCore/Metadata/Internal/EntityTypeSnapshot.cs]: Will change
