### PR TITLE
[2.1.5] Query: Make `MethodInfoBasedNodeTypeRegistryFactory` best possible singleton service

### LINKED ISSUE #12682: Singleton DefaultMethodInfoBasedNodeTypeRegistryFactory is not thread-safe
`DefaultMethodInfoBasedNodeTypeRegistryFactory` is a registered as singleton instance (However we are really only concerned about its base class). The base class `MethodInfoBasedNodeTypeRegistryFactory`, accepts a ReLinq `MethodInfoBasedNodeTypeRegistry` instance which from a quick glance at the source is pretty clearly not thread safe is mutating members are used.

The factory singeton gets injected into every scoped lifetime `QueryModelGenerator` which immediately calls `Create()` on it. `MethodInfoBasedNodeTypeRegistry.Create()` in turn calls `.Register()` on the stored MethodInfoBasedNodeTypeRegistry field which is a mutating member.

It looks like a `QueryModelGenerator` is an indirect constructor injected dependency of `DbContext` via `QueryModelGenetator` -> `QueryCompiler` -> `EntityQueryProvider`-> `DbContextDependencies` -> `DbContext`.

So it looks to me like every time a new `DbContext` is created in a fresh scope (plausibly in a different thread), we end up mutating an effectively static object that is not thread safe if mutated! 

It is possible that I overlooking something that would make this safe, but I don't immediately see it. 

I came across this when investigating an `System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.` error that appeared to stem from a `MethodInfoBasedNodeTypeRegistry` being used by EFCore.

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #12682 

This uses lock to make sure that we are not mutating service once we start calling Create method on it.
It includes all the changes on related objects to clean up. Some may be kept as is due to this being a patch fix.

### CODE REVIEW

File: src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs [hunk 1]
```diff
@@ -43,7 +54,14 @@ public virtual void RegisterMethods(IEnumerable<MethodInfo> methods, Type nodeTy
...
             Check.NotNull(nodeType, nameof(nodeType));
 
-            _methodInfoBasedNodeTypeRegistry.Register(methods, nodeType);
+            if (!_finalized)
+            {
+                _methodInfoBasedNodeTypeRegistry.Register(methods, nodeType);
+            }
+            else
+            {
+                // throw?
```
Comment (AndriySvyryd) [inline src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs]: We should throw if we don't want to make this work.

Comment (smitpatel) [reply src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs]: Do you have any idea how to make it work? It is trying to modify a singleton service once its initialized. I am leaning toward just throwing in this case. (Bad provider code?) cc: @divega @ajcvickers 

If we throw then what should be exception msg/type?

Comment (AndriySvyryd) [reply src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs]: To make it _work_ we could add a lock here and clear out `_nodeTypeProviders`. But we would only do this to avoid introducing any breaking changes, though from my understanding it's unlikely that someone could actually get this exception, correct?

File: src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs [hunk 2]
```diff
@@ -18,8 +18,12 @@ namespace Microsoft.EntityFrameworkCore.Query.Internal
     /// </summary>
     public class MethodInfoBasedNodeTypeRegistryFactory : INodeTypeProviderFactory
     {
+        private static readonly object _syncLock = new object();
         private readonly MethodInfoBasedNodeTypeRegistry _methodInfoBasedNodeTypeRegistry;
 
+        private bool _finalized;
```
Comment (AndriySvyryd) [inline src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs]: This isn't needed, you can just check `_nodeTypeProviders` for null

File: src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs [hunk 3]
```diff
@@ -52,29 +68,22 @@ public virtual void RegisterMethods(IEnumerable<MethodInfo> methods, Type nodeTy
...
-
-            _methodInfoBasedNodeTypeRegistry
-                .Register(StringIncludeExpressionNode.SupportedMethods, typeof(StringIncludeExpressionNode));
-
-            _methodInfoBasedNodeTypeRegistry
-                .Register(ThenIncludeExpressionNode.SupportedMethods, typeof(ThenIncludeExpressionNode));
-
-            var innerProviders
-                = new INodeTypeProvider[]
+            if (_nodeTypeProviders == null)
```
Comment (ajcvickers) [inline src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs]: This is double-check locking. Is this safe on .NET Core for all architectures? Last I heard it wasn't safe on ARM.

File: src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs [hunk 4]
```diff
@@ -43,7 +52,14 @@ public virtual void RegisterMethods(IEnumerable<MethodInfo> methods, Type nodeTy
...
             Check.NotNull(nodeType, nameof(nodeType));
 
-            _methodInfoBasedNodeTypeRegistry.Register(methods, nodeType);
+            if (_nodeTypeProviders == null)
+            {
+                _methodInfoBasedNodeTypeRegistry.Register(methods, nodeType);
+            }
+            else
+            {
+                throw new InvalidOperationException();
```
Comment (ajcvickers) [inline src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs]: So we will hit this if a provider (or other code) calls this outside of the constructor--is that correct?

Comment (ajcvickers) [reply src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs]: Could we instead in this case log a warning and do what we were doing before, but in a thread-safe way? That is, using the lock?

File: src/EFCore.Relational/Query/Internal/RelationalMethodInfoBasedNodeRegistryFactory.cs [hunk 5]
```diff
@@ -0,0 +1,24 @@
...
+
+using Microsoft.EntityFrameworkCore.Query.ResultOperators.Internal;
+
+namespace Microsoft.EntityFrameworkCore.Query.Internal
+{
+    /// <summary>
+    ///     This API supports the Entity Framework Core infrastructure and is not intended to be used
+    ///     directly from your code. This API may change or be removed in future releases.
+    /// </summary>
+    public class RelationalMethodInfoBasedNodeRegistryFactory : DefaultMethodInfoBasedNodeTypeRegistryFactory
```
Comment (ajcvickers) [inline src/EFCore.Relational/Query/Internal/RelationalMethodInfoBasedNodeRegistryFactory.cs]: Is there a reason this needs to be pubternal in the patch? If not we should make it real internal for the patch and make it pubternal when going from the patch branch to 2.2. (I know a strong case can be made that this is not necessary, but it will make it easier going through shiproom where any new public API is heavily frowned upon.)

Comment (smitpatel) [reply src/EFCore.Relational/Query/Internal/RelationalMethodInfoBasedNodeRegistryFactory.cs]: It can certainly made internal but this class registers FromSql. So if providers are going to react to this then they would need to derive from this class or copy code from this.

File: src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs (hunk 3 above)
Comment (smitpatel) [reply src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs]: As per discussion this is safe as memory barrier is automatically introduced.

File: src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs (hunk 4 above)
Comment (smitpatel) [reply src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs]: Removed the exception. In the absense of else part, it will behave same as how it did before this fix.

File: src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs (hunk 3 above)
Comment (AndriySvyryd) [reply src/EFCore/Query/Internal/MethodInfoBasedNodeTypeRegistryFactory.cs]: Make `_nodeTypeProviders` volatile just to be sure

**Comment by smitpatel** [comment]
Updated.

**Comment by KevinCathcart** [comment]
One consideration here: The locks only protect the writes to dictionary. It serializes writes, so the dictionary cannot end up in a corrupted state. However the reads lack any lock. Officially Dictionary does not support a single writer with concurrent readers. 

If an insert were to cause a resize then a concurrent reader could see the value not being present in the dictionary.

**Comment by smitpatel** [comment]
@KevinCathcart - Thanks for suggestion. There are few consideration for that here. The underlying relinq object can be mutating (like resizing) but there is no way to avoid it unless we make the whole use of the underlying object locked through the stack. This object is being used in each query compilation so effectively that would be a huge bottleneck. We are creating object inside the lock, we are just returning it as is outside of it.

**Comment by ajcvickers** [comment]
@smitpatel @AndriySvyryd Assuming quirk mode is not set, do we ever mutate the structure that Relinq is using? If so, is it possible to instead create a new structure combining what is currently in it with what needs to be added and then tell Relinq to start using that structure?

**Comment by smitpatel** [comment]
The only time we mutate the structure ReLinq is using is because of the order services are initialized. We are initializing `QueryModelGenerator` while initializing `DbContextDependencies` which creates above object. But at that point, other query specific services (`RelationalQueryCompilationContext`) has not initialized. Those are initialized when actual query is being compiled. Which causes to register extra methods. Though we also generate a new `QueryModelGenerator` for each query compilation. Hence the only time this service is called with `Create` is before actually running any query in unused init. We don't mutate the structure once we are past that phase.

**Comment by KevinCathcart** [comment]
Right this patch does in practice avoid basically all issues.

Technically I think it could happen then a modification occurs while a query is running if there are multiple contexts, one relational and one not. In that case, the non relational could be created, and be executing a query, while meanwhile another request comes in that needs the relational context. 

The only way I can see to completely close this hole with even remotely acceptable performance is to have later calls create a new empty `MethodNameBasedNodeTypeRegistry` instance (via the default constructor), and create a new array that is the same as the old one except with the new instance prepended. 

Since the `CompoundNodeTypeProvider` simply asks each provider it is provided in order, this would have the same net effect. At least in the code in this repository, only singletons even register types, and always on creation, so there is no real risk of the array growing to indefinate size. 

Of course in the overwhelming majority of all cases all types will be registered before the array is even created, so they can just modify the main instance in-place.

**Comment by smitpatel** [comment]
@KevinCathcart - What you are saying is true and this patch does not fix all issues in theory. We also considered recreating whole object (but that causes higher overhead and complexity of storing data with possibility of bottlenecking again.

> Technically I think it could happen then a modification occurs while a query is running if there are multiple contexts, one relational and one not.
Precisely, this statement while true in theory, not possible in practice at current stage. The only way to have that done is to have multiple database providers registering services. Even with that, currently all the providers are relational only. While people use same DbContext with different database providers (especially with testing), most of them don't share service containers across database providers. Adding complexity provides very low value compared to risk of regression it can bring in the patch.
