### PR TITLE
RevEng: Swap out type alias with actual store type in DatabaseModelFactory

### LINKED ISSUE #12633: RevEng: Use underlying types (not aliases) in the resulting model
I'm using a database where there are a lot of user defined data-types. There are also like 60 tables or more so I used the `dotnet ef dbcontext scaffold` command to generate the models. 

In the project file I included

```xml
   <DotNetCliToolReference Include="Microsoft.EntityFrameworkCore.Tools.DotNet" Version="2.1.0-preview1-final" />
```
and generated it with the following command:

```ps1
$connectionString = "Data Source=(local);Initial catalog=TestDb;Persist Security Info=True;Integrated Security=True;"
$outputDir = "Entities\TestDb"
$context = "TestContext"

dotnet ef dbcontext scaffold "$connectionString" Microsoft.EntityFrameworkCore.SqlServer --output-dir "$outputDir" --force --context "$context" --schema dbo --use-database-names
```
the resulting context is

```cs
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<UserDefinedDataTypeBug>(entity =>
            {
                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.Status).HasColumnType("Enumeration");
            });
        }
```

When I now try to query this model with

```cs
            using (var context = new TestContext())
            {
                var results =
                    context
                        .UserDefinedDataTypeBug
                        .Where(x => x.Status == 1)
                        .ToList();
            }
```

it throws a `SqlException` that reads

```
Class         16  byte
LineNumber    1   int
Message       "Type Enumeration is not a defined system type."    string
Number        243 int
Procedure     ""  string
Server        "..."   string
Source        ".Net SqlClient Data Provider"  string
State         2   byte
```

with the stack-trace

```
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at UserDefinedDataTypeBug.Program.Main(String[] args) in C:\...\UserDefinedDataTypeBug\Program.cs:line 13
```

I've read (e.g. [here](https://www.learnentityframeworkcore.com/configuration/fluent-api/hascolumntype-method)) that this should work but it doesn't. I have to manually comment the `HasColumnType` line out in order for the query to work.

### Steps to reproduce

I have created a small console application that reproduces this issue. You can find it in [here](https://github.com/he-dev/UserDefinedDataTypeBug) in my repository.

### Further technical details
EF Core version: (2.1.1)
Database Provider: (Microsoft.EntityFrameworkCore.SqlServer) SqlServer 2014
Operating system: Window 10 Pro
IDE: (Visual Studio 2017 15.7.4)

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #12633

Filed #13292 for cleanup of infra as breaking change

### CODE REVIEW

File: src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs [hunk 1]
```diff
@@ -622,20 +621,18 @@ private static string EscapeLiteral(string s)
...
 #pragma warning restore IDE0034 // Simplify 'default' expression
                             };
 
-                            if ((underlyingStoreType ?? storeType) == "rowversion")
+                            if (storeType == "rowversion")
                             {
                                 column[ScaffoldingAnnotationNames.ConcurrencyToken] = true;
                             }
 
-                            column.SetUnderlyingStoreType(underlyingStoreType);
```
Comment (bricelam) [inline src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs]: Obsolete this and the attribute name

Comment (bricelam) [reply src/EFCore.SqlServer/Scaffolding/Internal/SqlServerDatabaseModelFactory.cs]: GetUnderlyingStoreType too
