### PR TITLE
Fix handling of Contains on IReadOnlySet and custom IReadOnlyCollection.

### LINKED ISSUE #36262: IReadOnlyCollection cannot be used with Contains Query
### Bug description

Hi,

When class implements IReadOnlyCollection, it cannot be used for Containsd queries.

Fails with exception.
```
System.InvalidOperationException: 'The LINQ expression 'DbSet<tstRawDbEntity>()
    .Where(t => __c1_0.Contains(t.Id))' could not be translated. Additional information: Translation of method 'EF8Perf904.IdsContainerAndReadOnlyCollection.Contains' failed. If this method can be mapped to your custom function, see https://go.microsoft.com/fwlink/?linkid=2132413 for more information. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.'
```

Thanks,
Regards,
Evgeny.

### Your code

```csharp
Here is a sample IReadOnlyCollection implementation

    class IdsContainerAndReadOnlyCollection : IEnumerable<Guid>, IReadOnlyCollection<Guid>
    {
        HashSet<Guid> _ids = new HashSet<Guid>();

        public int Count => _ids.Count;

        public bool IsReadOnly => true;

        public void Add(Guid id)
        {
            _ids.Add(id);
        }

        public void Clear() => _ids.Clear();

        public bool Contains(Guid item) => _ids.Contains(item);

        public void CopyTo(Guid[] array, int arrayIndex) => _ids.CopyTo(array, arrayIndex);

        public bool Remove(Guid item) => _ids.Remove(item);

        public IEnumerator<Guid> GetEnumerator() => _ids.GetEnumerator();

        IEnumerator IEnumerable.GetEnumerator() => _ids.GetEnumerator();
    }


Test scenario

        [TestMethod]
        public void ReadOnlyCollectionQuery()
        {
            using (var ctx = Context)
            {
                var c1 = new IdsContainerAndReadOnlyCollection() { Guid.NewGuid() };
                var items1 = ctx.Raws.Where(r => c1.Contains(r.Id)).ToList();
            }
        }
```

### Stack traces

```text

```

### Verbose output

```text

```

### EF Core version

9.0.6

### Database provider

_No response_

### Target framework

_No response_

### Operating system

_No response_

### IDE

_No response_

### LINKED ISSUE #37081: IReadOnlySet<T>.Contains not translated into parameterized query
### Bug description

Related to #36262 and #32365

I expect `IReadOnlySet<T>.Contains` to be properly converted to a parameterized OPENJSON query when looking up an entity by a list of IDs. It's common to pass collections around using interfaces. We shouldn't need to convert to a concrete type before using the collection inside EF.

I'm on .net 9 while using Microsoft.EntityFrameworkCore.SqlServer Version="9.0.10"

example:
```csharp
await using var db = await dbContextFactory.CreateDbContextAsync(args.CancellationToken);

IReadOnlySet<long> list = new long[] { 1,2 }.ToFrozenSet();  //does not work
IReadOnlySet<long> list = new HashSet<long> { 1, 2 }; //does not work
HashSet<long> list = new HashSet<long>() { 1, 2 }; //works properly

var results = db.APInvoiceLines.Where(l => list.Contains(l.ApinvoiceId));
var q = results.ToQueryString(); //validate sql
```

Expected:
```sql
DECLARE @__list_0 nvarchar(4000) = N'[1,2]';

SELECT ...
FROM [dbo].[APInvoiceLines] AS [a]
WHERE [a].[APInvoiceId] IN (
    SELECT [l].[value]
    FROM OPENJSON(@__list_0) WITH ([value] bigint '$') AS [l]
)
```
Actual:
```sql 
SELECT ...
FROM [dbo].[APInvoiceLines] AS [a]
WHERE [a].[APInvoiceId] IN (CAST(1 AS bigint), CAST(2 AS bigint))
```

### Your code

```csharp
see above, it's very easy to replicate with any given table.
```

### Stack traces

```text

```

### Verbose output

```text

```

### EF Core version

9.0.10

### Database provider

Microsoft.EntityFrameworkCore.SqlServer

### Target framework

.NET 9.0

### Operating system

Windows 11

### IDE

Visual Studio 2022 17.16.18

### PR DESCRIPTION
**Pull request by cincuranet**
Fixes #37081.
Fixes #36262.

### CODE REVIEW

File: src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs [hunk 1]
```diff
@@ -171,43 +171,49 @@ protected override Expression VisitMethodCall(MethodCallExpression methodCallExp
         }
 
         if (method.DeclaringType is { IsGenericType: true }
-            && method.DeclaringType.TryGetElementType(typeof(ICollection<>)) is not null
-            && method.Name == nameof(ICollection<>.Contains))
+            && method.Name == nameof(ICollection<>.Contains)
```
Comment (roji) [inline src/EFCore/Query/Internal/QueryableMethodNormalizingExpressionVisitor.cs]: Tiny nit: can move the Name check even another line up, before generic DeclaringType check (the Name check is the most specifiy theck here).
