### PR TITLE
Additional perf improvements around null semantics scenarios

### LINKED ISSUE #17543: Queries really slow due to null checks
I'm getting a lot of slowdowns on the EF Core 3 preview. Here's an example.

```c#
var firstResult = await Db.Results.FirstOrDefaultAsync(o => o.TestId == 1);
```

This generates the following SQL, which runs really slowly on my SQL Azure database (>3 seconds):

```sql
exec sp_executesql N'SELECT TOP(1) [r].[Id]
FROM [Results] AS [r]
WHERE (([r].[TestId] = @__testId_0) AND ([r].[TestId] IS NOT NULL AND @__testId_0 IS NOT NULL))
OR ([r].[TestId] IS NULL AND @__testId_0 IS NULL)',N'@__testId_0 int',@__testId_0=1
```

The SQL I would expect is (<0.1 seconds):
```sql
exec sp_executesql N'SELECT TOP(1) [r].[Id]
FROM [Results] AS [r]
WHERE ([r].[TestId] = @__testId_0)',N'@__testId_0 int',@__testId_0=1
```

### Further technical details
EF Core version: 3.0.0-preview8.19405.11
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10
IDE: Visual Studio 2019 Version 16.3 Preview 2

### LINKED ISSUE #18525: Query: optimize binary expression AndAlso and OrElse where left and right are the same
Sometimes after running optimizations we end up with expressions like:

```sql
(c.Property IS NULL AND c.Property IS NULL) OR (c.Property2 IS NOT NULL AND c.Property2 IS NOT NULL)
```

this can be optimized to: 

```sql
c.Property IS NULL OR c.Property2 IS NOT NULL
```

moreover, case like:

```sql
c.Property IS NULL OR c.Property IS NOT NULL
```

is tautology, which we can also recognize (similarly for AND, resolving to always being false

### LINKED ISSUE #18547: DbFunctions compared to NULL are ignored and break the query builder
DbFunctions that are comparing to NULL are ignored in the query and even break other (valid) conditions.

For example:
```csharp
    public class DataContext : DbContext
    {
        private static readonly LoggerFactory LoggerFactory =
            new LoggerFactory(new[]
            {
                new DebugLoggerProvider()
            });

        public DbSet<Course> Courses { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Data Source=.;Initial Catalog=Test;Integrated Security=True;MultipleActiveResultSets=True;");
            optionsBuilder.UseLoggerFactory(LoggerFactory);
            optionsBuilder.EnableDetailedErrors();
            optionsBuilder.EnableSensitiveDataLogging();
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.HasDbFunction(typeof(DataContext).GetMethod(nameof(JsonValue)))
                        .HasTranslation(args =>
                        {
                            var arguments = args.ToList();
                            var a = (String) ((SqlConstantExpression) arguments[0]).Value;
                            arguments[0] = new SqlConstantExpression(Expression.Constant(a), RelationalTypeMapping.NullMapping);

                            return SqlFunctionExpression.Create("JSON_VALUE", arguments, typeof(String), null);
                        });
        }

        public static String JsonValue(String column, String path)
        {
            throw new NotSupportedException();
        }
    }

    public class Course
    {
        [Key]
        public Guid CourseId { get; set; }

        public String CourseName { get; set; }
        public String MetaData { get; set; }
    }

    public class MetaData
    {
        public String TestParam { get; set; }
    }
```

When I run:
```context.Courses.FirstOrDefault(m => DataContext.JsonValue("MetaData", "$.TestParam") == "Test 123");```
Works as expected, but when I run:
```context.Courses.FirstOrDefault(m => DataContext.JsonValue("MetaData", "$.TestParam") == null);```
it doesn't work, the generated query is odd as well:
```sql
SELECT TOP(1) [c].[CourseId], [c].[CourseName], [c].[MetaData]
FROM [Courses] AS [c]
WHERE CAST(0 AS bit) = CAST(1 AS bit)
```
When chaining multiple conditions, like this:
```context.Courses.FirstOrDefault(m => m.CourseName == "Test 1" && DataContext.JsonValue("MetaData", "$.TestParam") == null);```
It gives the same result.

Here is a demo repo:
[test-repo.zip](https://github.com/aspnet/EntityFrameworkCore/files/3764393/test-repo.zip)

### PR DESCRIPTION
**Pull request by maumar**
Resolves #17543 - Queries really slow due to null checks
Resolves #18525 - Query: optimize binary expression AndAlso and OrElse where left and right are the same
Resolves #18547 - DbFunctions compared to NULL are ignored and break the query builder

#17543

Before when rewriting null comparisons we would always remove possibility of nulls in the resulting expression. This is not always needed, specifically in predicates, where it doesn't really matter if expression returns false or null - the result is the same.
Now we detect those cases and apply "simplified" null expansion which should lead to better performance.

#18525

Null semantics initially expands expressions to a verbose form which then gets simplified in query optimizer. One of the optimizations added is when we do AND/OR where both sides are the same. Other small improvements have been added in this change also.

#18547

Previously we assumed that function can only be null if at least one of its arguments is null. This is the case for most built-in functions, but not all. This also goes for user defined functions which can return arbitrary results.
Fix is to treat all functions as potentially nullable. This leads to worse queries is some cases, but is also mitigated by other improvements added along side.
In the future we will provide metadata to better determine given function's nullability.

Also fixed a few small bug found along the way - incorrect Equals comparison for SqlExpression, for cases when TypeMapping was null.

### CODE REVIEW

**Comment by maumar** [comment]
cc: @ajcvickers @Pilchie

File: test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQuerySqlServerTest.cs [hunk 1]
```diff
@@ -275,7 +275,7 @@ public override async Task String_starts_with_on_argument_with_wildcard_column_n
                 @"SELECT [f].[FirstName] AS [fn], [f0].[LastName] AS [ln]
 FROM [FunkyCustomers] AS [f]
 CROSS JOIN [FunkyCustomers] AS [f0]
-WHERE (([f0].[LastName] <> N'') OR [f0].[LastName] IS NULL) AND ([f].[FirstName] IS NOT NULL AND ([f0].[LastName] IS NOT NULL AND (LEFT([f].[FirstName], LEN([f0].[LastName])) <> [f0].[LastName])))");
+WHERE (([f0].[LastName] <> N'') OR [f0].[LastName] IS NULL) AND ([f].[FirstName] IS NOT NULL AND ([f0].[LastName] IS NOT NULL AND ((LEFT([f].[FirstName], LEN([f0].[LastName])) <> [f0].[LastName]) OR LEFT([f].[FirstName], LEN([f0].[LastName])) IS NULL)))");
```
Comment (maumar) [inline test/EFCore.SqlServer.FunctionalTests/Query/FunkyDataQuerySqlServerTest.cs]: sql is worse due to #18547, we have issue tracking improvement for those here: #18555

**Comment by smitpatel** [comment]
Commit message has wrong issue reference.

File: src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs [hunk 2]
```diff
@@ -20,7 +20,6 @@ public override Expression Process(Expression query)
         {
             query = base.Process(query);
             query = new SearchConditionConvertingExpressionVisitor(SqlExpressionFactory).Visit(query);
-            query = OptimizeSqlExpression(query);
```
Comment (smitpatel) [inline src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs]: Why don't we need to call this again?

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs [hunk 3]
```diff
@@ -44,64 +46,236 @@ protected override Expression VisitExtension(Expression extensionExpression)
...
+
+            return newExpression;
+        }
+
         protected virtual Expression VisitSqlUnaryExpression(SqlUnaryExpression sqlUnaryExpression)
         {
-            switch (sqlUnaryExpression.OperatorType)
+            var newOperand = (SqlExpression)Visit(sqlUnaryExpression.Operand);
+
+            return SimplifyUnaryExpression(
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: Just call visit base regenerate the SqlUnaryExpression and pass it to the method. You are passing components anyway.

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs [hunk 4]
```diff
@@ -44,64 +46,236 @@ protected override Expression VisitExtension(Expression extensionExpression)
...
+            switch (operatorType)
             {
                 case ExpressionType.Not:
-                    return VisitNot(sqlUnaryExpression);
+                    switch (operand)
+                    {
+                        // !(true) -> false
+                        // !(false) -> true
+                        case SqlConstantExpression constantOperand
+                        when constantOperand.Value is bool value:
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: when case is indented? @andriySvyryd

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs [hunk 5]
```diff
@@ -44,64 +46,236 @@ protected override Expression VisitExtension(Expression extensionExpression)
...
+                                return SimplifyLogicalSqlBinaryExpression(
+                                    binaryOperand.OperatorType == ExpressionType.AndAlso
+                                        ? ExpressionType.OrElse
+                                        : ExpressionType.AndAlso,
+                                    newLeft,
+                                    newRight,
+                                    binaryOperand.TypeMapping);
+                            }
+
+                            // those optimizations are only valid in 2-value logic
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: relevance of comment?

File: src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs (hunk 2 above)
Comment (maumar) [reply src/EFCore.SqlServer/Query/Internal/SqlServerQueryTranslationPostprocessor.cs]: ParameterValueBasedSelectExpressionOptimizer is now a sql optimizer

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs [hunk 6]
```diff
@@ -44,64 +46,236 @@ protected override Expression VisitExtension(Expression extensionExpression)
...
+                        // !(false) -> true
+                        case SqlConstantExpression constantOperand
+                        when constantOperand.Value is bool value:
+                            return SqlExpressionFactory.Constant(!value, typeMapping);
+
+                        case InExpression inOperand:
+                            return inOperand.Negate();
+
+                        case SqlUnaryExpression unaryOperand:
+                            switch (unaryOperand.OperatorType)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: 3 levels of nested switches :trollface:

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs [hunk 7]
```diff
@@ -44,64 +46,236 @@ protected override Expression VisitExtension(Expression extensionExpression)
...
                         case ColumnExpression columnOperand
                             when !columnOperand.IsNullable:
-                            return SqlExpressionFactory.Constant(false, sqlUnaryExpression.TypeMapping);
+                            return SqlExpressionFactory.Constant(false, typeMapping);
 
-                        case SqlUnaryExpression sqlUnaryOperand
-                            when sqlUnaryOperand.OperatorType == ExpressionType.Convert
+                        case SqlUnaryExpression sqlUnaryOperand:
+                            if (sqlUnaryOperand.OperatorType == ExpressionType.Convert
                             || sqlUnaryOperand.OperatorType == ExpressionType.Not
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: nit:indent

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs [hunk 8]
```diff
@@ -44,64 +46,236 @@ protected override Expression VisitExtension(Expression extensionExpression)
...
-                            || sqlUnaryOperand.OperatorType == ExpressionType.Negate:
-                            return (SqlExpression)Visit(SqlExpressionFactory.IsNull(sqlUnaryOperand.Operand));
-
+                            || sqlUnaryOperand.OperatorType == ExpressionType.Negate)
+                            {
+                                // op(a) is null -> a is null
+                                return SimplifyNullNotNullExpression(ExpressionType.Equal, sqlUnaryOperand.Operand, type, typeMapping);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: can use operatorType

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs [hunk 9]
```diff
@@ -44,64 +46,236 @@ protected override Expression VisitExtension(Expression extensionExpression)
...
+
+                            if (sqlUnaryOperand.OperatorType == ExpressionType.Equal
+                                || sqlUnaryOperand.OperatorType == ExpressionType.NotEqual)
+                            {
+                                // (a is null) is null -> false
+                                // (a is not null) is null -> false
+                                return SqlExpressionFactory.Constant(false, typeMapping);
+                            }
+                            break;
                         case SqlBinaryExpression sqlBinaryOperand:
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: Linebreak

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs (hunk 5 above)
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: its still correct - we dont do optimized rewrite for expressions wrapped around NOT. This code only works for operands of NOT, so as long as null semantics rewrite runs at all (i.e. useRelationalNulls = false), the optimization can be applied

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs [hunk 10]
```diff
@@ -112,169 +286,222 @@ protected virtual Expression VisitSqlUnaryExpression(SqlUnaryExpression sqlUnary
...
-            if (sqlUnaryExpression.Operand is SqlConstantExpression innerConstantBool
-                && innerConstantBool.Value is bool value)
+            if (operatorType == ExpressionType.AndAlso
+                || operatorType == ExpressionType.OrElse)
             {
-                return SqlExpressionFactory.Constant(!value, sqlUnaryExpression.TypeMapping);
-            }
+                var leftUnary = left as SqlUnaryExpression;
+                var rightUnary = right as SqlUnaryExpression;
+                if (leftUnary != null
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: Little comment

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs [hunk 11]
```diff
@@ -112,169 +286,222 @@ protected virtual Expression VisitSqlUnaryExpression(SqlUnaryExpression sqlUnary
...
+            ExpressionType operatorType,
+            SqlExpression left,
+            SqlExpression right,
+            RelationalTypeMapping typeMapping)
         {
-            // !(true) -> false
-            // !(false) -> true
-            if (sqlUnaryExpression.Operand is SqlConstantExpression innerConstantBool
-                && innerConstantBool.Value is bool value)
+            if (operatorType == ExpressionType.AndAlso
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: Use switch case to follow the pattern ?

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs [hunk 12]
```diff
@@ -112,169 +286,222 @@ protected virtual Expression VisitSqlUnaryExpression(SqlUnaryExpression sqlUnary
...
+                        operatorType,
+                        left,
+                        right,
+                        leftNullConstant,
+                        rightNullConstant,
+                        typeMapping);
                 }
 
-                if (innerUnary.OperatorType == ExpressionType.Equal)
+                var leftBoolConstant = left.Type == typeof(bool) ? left as SqlConstantExpression : null;
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: You already cast it to constant above, try to DRY

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs [hunk 13]
```diff
@@ -112,169 +286,222 @@ protected virtual Expression VisitSqlUnaryExpression(SqlUnaryExpression sqlUnary
...
+                        rightBoolConstant,
+                        typeMapping);
                 }
 
-                //!(a IS NOT NULL) -> a IS NULL
-                if (innerUnary.OperatorType == ExpressionType.NotEqual)
+                // only works when a is not nullable
+                // a == a -> true
+                // a != a -> false
+                if ((left is LikeExpression
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: is LikeExpression only one which cannot be nullable?

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs [hunk 14]
```diff
@@ -112,169 +286,222 @@ protected virtual Expression VisitSqlUnaryExpression(SqlUnaryExpression sqlUnary
...
+                    return SqlExpressionFactory.Constant(operatorType == ExpressionType.Equal, typeMapping);
                 }
 
-                // those optimizations are only valid in 2-value logic
-                // they are safe to do here because null semantics removes possibility of nulls in the tree
-                // however if we decide to do "partial" null semantics (that doesn't distinguish between NULL and FALSE, e.g. for predicates)
-                // we need to be extra careful here
-                if (!_useRelationalNulls
-                    && TryNegate(innerBinary.OperatorType, out var negated))
+                if (leftNull)
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: Use ternary

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs [hunk 15]
```diff
@@ -112,169 +286,222 @@ protected virtual Expression VisitSqlUnaryExpression(SqlUnaryExpression sqlUnary
...
+            RelationalTypeMapping typeMapping)
         {
-            var newLeft = (SqlExpression)Visit(sqlBinaryExpression.Left);
-            var newRight = (SqlExpression)Visit(sqlBinaryExpression.Right);
+            if (leftBoolConstant != null && rightBoolConstant != null)
+            {
+                // potential optimization:
+                // we can't do it on SqlServer because it reverts search conditions back to values
+                // and we run this visitor after search condition visitor
+                //return operatorType == ExpressionType.Equal
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: That should be fine, no? SqlServer will revert optimization but other providers can still use

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs (hunk 13 above)
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: there are probably more, we can add them in the future

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs [hunk 16]
```diff
@@ -112,169 +286,222 @@ protected virtual Expression VisitSqlUnaryExpression(SqlUnaryExpression sqlUnary
...
 
-            return sqlBinaryExpression.Update(newLeft, newRight);
+            return SqlExpressionFactory.MakeBinary(operatorType, left, right, typeMapping);
+
+            static bool CanOptimize(SqlExpression operand)
+                => operand is LikeExpression
+                || (operand is SqlUnaryExpression sqlUnary
+                    && (sqlUnary.OperatorType == ExpressionType.Equal
+                        || sqlUnary.OperatorType == ExpressionType.NotEqual
+                        || sqlUnary.OperatorType == ExpressionType.Not));
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: SqlUnary with Not can never be null? What if Not(NullableBoolColumn)?

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs (hunk 15 above)
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: problem is that ParameterValueBasedSelectExpressionOptimizer runs after search condition so it will re-apply this - will add this optimization once ParameterValueBasedSelectExpressionOptimizer runs search condition visitor as well

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 17]
```diff
@@ -8,122 +8,157 @@
...
+            _canOptimize = false;
+            var newOperand = (SqlExpression)Visit(caseExpression.Operand);
+            var newWhenClauses = new List<CaseWhenClause>();
+            foreach (var whenClause in caseExpression.WhenClauses)
+            {
+                _canOptimize = testIsCondition;
+                var newTest = (SqlExpression)Visit(whenClause.Test);
+                _canOptimize = false;
+                var newResult = (SqlExpression)Visit(whenClause.Result);
+                isNullable |= _isNullable;
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: You may also need to reset _isNullable before visiting as if Test is nullable & result is not-nullable

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 18]
```diff
@@ -8,122 +8,157 @@
...
             _isNullable |= isNullable;
+            _canOptimize = canOptimize;
 
             return likeExpression.Update(newMatch, newPattern, newEscapeChar);
         }
 
-        private InnerJoinExpression VisitInnerJoinExpression(InnerJoinExpression innerJoinExpression)
+        protected override Expression VisitInnerJoin(InnerJoinExpression innerJoinExpression)
         {
             var newTable = (TableExpressionBase)Visit(innerJoinExpression.Table);
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: Don't you need to reset CanOptimize here like CrossJoin?

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs (hunk 14 above)
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: ok, will also DRY equal and notequal

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs (hunk 3 above)
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: In several places this method is used to build unary expression from scratch (e.g. when pushing not into the arguments of binary expression. I could create the unary expression and pass it to the method instead, but the current way allows me tho streamline the code bit better - see SimplifyBoolConstantComparisonExpression, or SimplifyUnaryExpression method itself (handling of Not -> Binary)

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs (hunk 4 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: Yes, but you don't need to always to it, code cleanup will be performed eventually. The important part is to not undo what code cleanup does.

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 19]
```diff
@@ -331,10 +512,93 @@ private SqlBinaryExpression VisitSqlBinaryExpression(SqlBinaryExpression sqlBina
...
+            }
+
+            _canOptimize = canOptimize;
+
+            return sqlCastExpression.Update(newOperand);
+        }
+
+        protected override Expression VisitSubSelect(ScalarSubqueryExpression scalarSubqueryExpression)
+        {
+            var canOptimize = _canOptimize;
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: No resetting to false?

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs (hunk 12 above)
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: i was thinking about it, but opted not to - one is null constant (of any type), one is bool constant. We could just check if the expression is any constant, but we would be doing it for all operators - we only need the info for equal/notequal/orelse/andalso

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 20]
```diff
@@ -331,10 +512,93 @@ private SqlBinaryExpression VisitSqlBinaryExpression(SqlBinaryExpression sqlBina
...
+            var subquery = (SelectExpression)Visit(scalarSubqueryExpression.Subquery);
+            _canOptimize = canOptimize;
```
Comment (smitpatel) [inline src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: No nullable? SubSelect can be null since subquery can return 0 rows. Also file an issue to update the method name to match expression type

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs (hunk 3 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: Saw it later. No need to change.

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs (hunk 16 above)
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: good catch, on sql server its safe b/c they get converted to CASE, but other providers can result in null

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs (hunk 12 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: Do a soft cast and integrate check to null value or bool type in if conditions??

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs (hunk 13 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: If we plan to add more in future, can you put that in private method?

File: src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs (hunk 16 above)
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/SqlExpressionOptimizingExpressionVisitor.cs]: added note in #18689

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs (hunk 19 above)
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: selectExpression handles it, but we can add it, just in case

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs (hunk 20 above)
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: select handles that

**Comment by maumar** [comment]
@smitpatel new version up

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 21]
```diff
@@ -8,190 +8,322 @@
...
-            _isNullable = false;
-            // if there is no 'else' there is a possibility of null, when none of the conditions are met
-            // otherwise the result is nullable if any of the WhenClause results OR ElseResult is nullable
-            var isNullable = caseExpression.ElseResult == null;
+            var expression = (SqlExpression)Visit(orderingExpression.Expression);
 
-            var newOperand = (SqlExpression)Visit(caseExpression.Operand);
-            var newWhenClauses = new List<CaseWhenClause>();
-            foreach (var whenClause in caseExpression.WhenClauses)
+            return orderingExpression.Update(expression);
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: Isn't this override redundant?

Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: will remove

Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: method is abstract in base

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs [hunk 22]
```diff
@@ -8,190 +8,322 @@
...
+            var canOptimize = _canOptimize;
+            var testIsCondition = caseExpression.Operand == null;
+            _canOptimize = false;
+            var newOperand = (SqlExpression)Visit(caseExpression.Operand);
+            var newWhenClauses = new List<CaseWhenClause>();
+            foreach (var whenClause in caseExpression.WhenClauses)
+            {
+                _canOptimize = testIsCondition;
+                var newTest = (SqlExpression)Visit(whenClause.Test);
+                _canOptimize = false;
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: There's no need to keep setting it to false. There's no code that could set it to true

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs (hunk 21 above)
Comment (AndriySvyryd) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: Perhaps we should add a non-abstract base class.

---
In reply to: [341784207](https://github.com/aspnet/EntityFrameworkCore/pull/18694#discussion_r341784207) [](ancestors = 341784207)

Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: filed #18714

File: src/EFCore.Relational/Query/SqlExpressions/SqlExpression.cs [hunk 23]
```diff
@@ -32,7 +32,8 @@ public override bool Equals(object obj)
 
         private bool Equals(SqlExpression sqlExpression)
             => Type == sqlExpression.Type
-                && TypeMapping?.Equals(sqlExpression.TypeMapping) == true;
+               && ((TypeMapping == null && sqlExpression.TypeMapping == null)
+                || TypeMapping?.Equals(sqlExpression.TypeMapping) == true);
```
Comment (AndriySvyryd) [inline src/EFCore.Relational/Query/SqlExpressions/SqlExpression.cs]: Equals(TypeMapping, sqlExpression.TypeMapping)

File: src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs (hunk 21 above)
Comment (maumar) [reply src/EFCore.Relational/Query/Internal/NullSemanticsRewritingExpressionVisitor.cs]: filed #18714
