### PR TITLE
Change nullability of explicitly configured shadow FKs to match the requiredness.

### LINKED ISSUE #12862: ReadStoreGeneratedValue throws ArgumentException when a private field FK is used
EntityFrameworkCore version: 2.1.1
Application type: netcoreapp2.1 console application in VS2017
Exception message: 

> ArgumentException: Expression of type 'System.Int32' cannot be used for parameter of type 'System.Nullable`1[System.Int32]' of method 'System.Nullable`1[System.Int32] ReadStoreGeneratedValue[Nullable`1](System.Nullable`1[System.Int32], Int32)'

Code:
```C#
    class Author
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    class Book
    {
        public Book() { }
        public Book(string name, int authorId)
        {
            this.Name = name;
            _authorId = authorId;
        }

        public int Id { get; set; }
        public string Name { get; set; }
        //public int AuthorId { get; set; }
        private int _authorId;
        public Author Author { get; set; }
    }

    class BookContext : DbContext
    {
        public DbSet<Book> Books { get; set; }
        public DbSet<Author> Authors { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=Books;Trusted_Connection=True;MultipleActiveResultSets=true");
        }

        protected override void OnModelCreating(ModelBuilder builder)
        {
            var author = builder.Entity<Author>();
            author.HasKey(e => e.Id);
            author.Property(e => e.Id).ValueGeneratedOnAdd();
            author.Property(e => e.Name);

            var book = builder.Entity<Book>();
            book.HasKey(e => e.Id);
            book.Property(e => e.Id).ValueGeneratedOnAdd();
            book.HasOne(e => e.Author).WithMany().HasForeignKey("AuthorId").IsRequired();
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var context = new BookContext())
            {
                context.Database.EnsureDeleted();
                context.Database.EnsureCreated();
                context.Authors.Add(new Author { Name = "author1" });
                context.SaveChanges();
            }
        }
    }
```

If I use public property `AuthorId` instead of private field (or use int? instead of int for the field), it's working fine.

### PR DESCRIPTION
**Pull request by AndriySvyryd**
Fixes #12862

### CODE REVIEW

File: src/EFCore.Relational/Storage/RelationalTypeMapping.cs [hunk 1]
```diff
@@ -482,7 +482,7 @@ public virtual RelationalTypeMapping Clone(in RelationalTypeMappingInfo mappingI
         /// </summary>
         public virtual bool IsFixedLength => Parameters.FixedLength;
 
-        private bool PrecisionAndScaleOverriden { get; }
+        private readonly bool _precisionAndScaleOverriden;
```
Comment (smitpatel) [inline src/EFCore.Relational/Storage/RelationalTypeMapping.cs]: Move to top?
