### PR TITLE
Fix to #18808 - Query: incorrect results for query with Join where key selector is anonymous type with a single property

### LINKED ISSUE #18808: Query: incorrect results for query with Join where key selector is anonymous type with a single property
e.g.: 

```cs
from l1 in ss.Set<Level1>()
                    join l2 in ss.Set<Level2>()
                        on new { A = EF.Property<int?>(l1, "OneToMany_Optional_Self_Inverse1Id") }
                        equals new { A = EF.Property<int?>(l2, "Level1_Optional_Id") }
                    select l1
```

we produce:

```sql
SELECT [l].[Id], [l].[Date], [l].[Name], [l].[OneToMany_Optional_Self_Inverse1Id], [l].[OneToMany_Required_Self_Inverse1Id], [l].[OneToOne_Optional_Self1Id]
FROM [LevelOne] AS [l]
INNER JOIN [LevelTwo] AS [l0] ON [l].[OneToMany_Optional_Self_Inverse1Id] = [l0].[Level1_Optional_Id]
```

We should be applying null semantics here instead to be consistent with c# (we do that if anonymous type has more properties)

### PR DESCRIPTION
**Pull request by maumar**
Problem was that on c# join predicate behaves differently when it's a regular property (null and null yield false), and where its anonymous type with just a single property (new { A = null } and new { A = null } yields true).
However, we lose that distinction during initial Join predicate translation.

Fix is to add a sentinel true == true condition, if the anonymous type only has one element. This condition can be later optimized out.

Resolves #18808

### CODE REVIEW

File: test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs [hunk 1]
```diff
@@ -2876,9 +2876,9 @@ public override async Task Join_condition_optimizations_applied_correctly_when_a
             await base.Join_condition_optimizations_applied_correctly_when_anonymous_type_with_single_property(isAsync);
 
             AssertSql(
-                @"SELECT [l1].[Id], [l1].[Date], [l1].[Name], [l1].[OneToMany_Optional_Self_Inverse1Id], [l1].[OneToMany_Required_Self_Inverse1Id], [l1].[OneToOne_Optional_Self1Id]
-FROM [LevelOne] AS [l1]
-INNER JOIN [LevelTwo] AS [l2] ON ([l1].[OneToMany_Optional_Self_Inverse1Id] = [l2].[Level1_Optional_Id]) OR ([l1].[OneToMany_Optional_Self_Inverse1Id] IS NULL AND [l2].[Level1_Optional_Id] IS NULL)");
+                @"SELECT [l].[Id], [l].[Date], [l].[Name], [l].[OneToMany_Optional_Self_Inverse1Id], [l].[OneToMany_Required_Self_Inverse1Id], [l].[OneToOne_Optional_Self1Id]
+FROM [LevelOne] AS [l]
+INNER JOIN [LevelTwo] AS [l0] ON (([l].[OneToMany_Optional_Self_Inverse1Id] = [l0].[Level1_Optional_Id]) OR ([l].[OneToMany_Optional_Self_Inverse1Id] IS NULL AND [l0].[Level1_Optional_Id] IS NULL)) AND (CAST(1 AS bit) = CAST(1 AS bit))");
```
Comment (maumar) [inline test/EFCore.SqlServer.FunctionalTests/Query/ComplexNavigationsQuerySqlServerTest.cs]: extra condition can be pruned, when/if we fix #18492
