### PR TITLE
Query: Allow property access on derived type by using type casting

### LINKED ISSUE #15807: Query: Casting in EF.Property
```C#
        [Fact]
        public virtual void Discriminator_with_cast_in_shadow_property()
        {
            using (var context = CreateContext())
            {
                var preditors
                    = context.Set<Animal>()
                        .Where(b => "Kiwi" == EF.Property<string>(b, "Discriminator"))
                        .Select(
                            k => new
                            {
                                Preditor = EF.Property<string>((Bird)k, "EagleId")
                            })
                        .ToArray();

                Assert.Equal(1, preditors.Length);
            }
        }
```

### LINKED ISSUE #15848: Query: translation error when projecting with a cast
query:

```cs
ctx.Factions.Select(f => (LocustHorde)f);
```

exception:

```
'Unable to cast object of type 'Microsoft.EntityFrameworkCore.Query.Pipeline.EntityShaperExpression' to type 'Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.SqlExpressions.SqlExpression'.'

   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalSqlTranslatingExpressionVisitor.VisitUnary(UnaryExpression unaryExpression) in D:\git\EntityFrameworkCore\src\EFCore.Relational\Query\PipeLine\RelationalSqlTranslatingExpressionVisitor.cs:line 335
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalSqlTranslatingExpressionVisitor.Translate(Expression expression) in D:\git\EntityFrameworkCore\src\EFCore.Relational\Query\PipeLine\RelationalSqlTranslatingExpressionVisitor.cs:line 45
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalProjectionBindingExpressionVisitor.Visit(Expression expression) in D:\git\EntityFrameworkCore\src\EFCore.Relational\Query\PipeLine\RelationalProjectionBindingExpressionVisitor.cs:line 106
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalProjectionBindingExpressionVisitor.Translate(SelectExpression selectExpression, Expression expression) in D:\git\EntityFrameworkCore\src\EFCore.Relational\Query\PipeLine\RelationalProjectionBindingExpressionVisitor.cs:line 41
   at Microsoft.EntityFrameworkCore.Relational.Query.Pipeline.RelationalQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector) in D:\git\EntityFrameworkCore\src\EFCore.Relational\Query\PipeLine\RelationalQueryableMethodTranslatingExpressionVisitor.cs:line 601
   at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression) in D:\git\EntityFrameworkCore\src\EFCore\Query\Pipeline\QueryableMethodTranslatingExpressionVisitor.cs:line 331
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.Pipeline.QueryCompilationContext2.CreateQueryExecutor[TResult](Expression query) in D:\git\EntityFrameworkCore\src\EFCore\Query\Pipeline\QueryCompilationContext2.cs:line 61
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery2[TResult](Expression query, Boolean async) in D:\git\EntityFrameworkCore\src\EFCore\Storage\Database.cs:line 97
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async) in D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs:line 118
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0() in D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs:line 107
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler) in D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 84
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler) in D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\CompiledQueryCache.cs:line 59
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query) in D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\QueryCompiler.cs:line 103
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression) in D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\EntityQueryProvider.cs:line 80
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetEnumerator() in D:\git\EntityFrameworkCore\src\EFCore\Query\Internal\EntityQueryable`.cs:line 93
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.GearsOfWarQueryTestBase`1.Nav_rewrite_Distinct_with_convert() in D:\git\EntityFrameworkCore\test\EFCore.Specification.Tests\Query\GearsOfWarQueryTestBase.cs:line 7441
   at Microsoft.EntityFrameworkCore.Query.GearsOfWarQuerySqlServerTest.Nav_rewrite_Distinct_with_convert() in D:\git\EntityFrameworkCore\test\EFCore.SqlServer.FunctionalTests\Query\GearsOfWarQuerySqlServerTest.cs:line 8365

```

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #15807
Resolves #15848 (Since client eval for projection is already added)

### CODE REVIEW

File: src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs [hunk 1]
```diff
@@ -79,17 +79,49 @@ protected override Expression VisitExtension(Expression node)
 
         protected override Expression VisitMember(MemberExpression memberExpression)
         {
-            var innerExpression = Visit(memberExpression.Expression);
-            if (innerExpression is EntityShaperExpression entityShaper)
+            if (memberExpression.Expression is EntityShaperExpression
+                || (memberExpression.Expression is UnaryExpression innerUnaryExpression
+                    && innerUnaryExpression.NodeType == ExpressionType.Convert
```
Comment (maumar) [inline src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs]: what about nested convert?

File: src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs [hunk 2]
```diff
@@ -79,17 +79,49 @@ protected override Expression VisitExtension(Expression node)
...
+            if (source is EntityShaperExpression entityShaper)
+            {
+                var entityType = entityShaper.EntityType;
+                if (convertedType != null)
+                {
+                    entityType = entityType.RootType().GetDerivedTypesInclusive()
+                        .FirstOrDefault(et => et.ClrType == convertedType);
+                }
+
+                return BindProperty(entityShaper, entityType.FindProperty(propertyName));
```
Comment (maumar) [inline src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs]: entityType can't be null at this point?

File: src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs (hunk 1 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs]: Not supported. Multiple cast is anyway redundant because all EntityTypes are in same hierarchy. If we see customer asking for it, we will look into it.

File: src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs (hunk 2 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs]: It actually can be. Let me update.

Comment (smitpatel) [reply src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs]: EntityShaper would never give null entityType but the converted type could be unmapped and hence entityType could be null.

Comment (smitpatel) [reply src/EFCore.Relational/Query/Pipeline/RelationalSqlTranslatingExpressionVisitor.cs]: Updated. Changed it to client eval.
