### PR TITLE
Query: Anonymous object group by causes invalid SQL

### LINKED ISSUE #11636: 'MIN' is not a recognized built-in function name - 2.1.0-preview2-final
Since i update EF 2.0.2 Final to 2.1.0-preview2-final I get this error message on my LINQ query using group by with LINQ Min() method.

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: 'MIN' is not a recognized built-in function name.
Stack trace: 
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.<ExecuteAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<BufferlessMoveNext>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.<ExecuteAsync>d__7`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncQueryingEnumerable`1.AsyncEnumerator.<MoveNext>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.EntityFrameworkCore.Query.Internal.AsyncLinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.<MoveNext>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Linq.AsyncEnumerable.<Aggregate_>d__6`3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ReporterConsole.DAOs.BatchAuditRepo.<GetTaskList>d__4.MoveNext() in C:\Users\Roni.axelrad\Source\Repos\ReporterConsole\ReporterConsole\DAOs\BatchAuditRepo.cs:line 117
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ReporterConsole.Utils.QueryManager.<GetQueriesResultList>d__0.MoveNext() in C:\Users\Roni.axelrad\Source\Repos\ReporterConsole\ReporterConsole\Utils\QueryManager.cs:line 43
```

### Steps to reproduce
I use a LINQ Query with join and group by aggregation of the min datetime.
Including my query. the issue is coming out from that line 'StartTime = taskBatchGroup.Min(grp => grp.EntryTime)' although in version 2.0.2 it is working perfectly fine.

```c#
var gbaJoinTasksAndBatches = from gbajoin in _db.GBatchAudit
                                     join task1 in _db.TTask on gbajoin.TaskId equals task1.TaskId
                                     join batch1 in _db.TBatch on gbajoin.BatchId equals batch1.BatchId
                                     where gbajoin.EntryTime >= ReporterArgs.FromDate &&
                                           gbajoin.EntryTime <= ReporterArgs.ToDate &&
                                           gbajoin.EntryType == 1
                                     orderby gbajoin.EntryTime
                                     select new
                                     {
                                         gbajoin.EntryTime,
                                         gbajoin.BatchRunNum,
                                         task1.TaskId,
                                         task1.TaskName,
                                         batch1.BatchId,
                                         batch1.BatchName
                                     };

        var gbaGroupedByErrorMessage = from gbaJoin in gbaJoinTasksAndBatches
                                       group gbaJoin by new
                                       {
                                           gbaJoin.BatchRunNum,
                                           Task = gbaJoin.TaskName,
                                           TaskId = gbaJoin.TaskId,
                                           Batch = gbaJoin.BatchName,
                                           BatchId = gbaJoin.BatchId,
                                       } into taskBatchGroup

                                       select new TaskListDto
                                       {
                                           BatchName = taskBatchGroup.Key.Batch,
                                           BatchId = taskBatchGroup.Key.BatchId,
                                           TaskName = taskBatchGroup.Key.Task,
                                           TaskId = taskBatchGroup.Key.TaskId,
                                           BatchRunNumber = taskBatchGroup.Key.BatchRunNum,
                                           StartTime = taskBatchGroup.Min(grp => grp.EntryTime)
                                       };

        return await gbaGroupedByErrorMessage.OrderBy(t => t.StartTime).ToListAsync();
```

### Further technical details
EF Core version: 2.1.0-preview2-final
Database Provider: Microsoft.EntityFrameworkCore.SqlServer
Operating system: Windows 10 64-bit
IDE: (e.g. Visual Studio 2017 15.6.6)

### PR DESCRIPTION
**Pull request by smitpatel**
Issue: Due to anonymous object we aliased projections. When wrapping the expression insider aggregate function, this generates invalid sql.
The same could happen with aggregate operation without group by too. Due to relinq optimizations, unable to write such a test.

Resolves #11636

Also added fixed issue with doing multiple select with first being on anonymous type.

### CODE REVIEW

File: src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs [hunk 1]
```diff
@@ -935,7 +945,8 @@ private static Expression HandleSum(HandlerContext handlerContext)
                     var inputType = handlerContext.QueryModel.SelectClause.Selector.Type;
 
                     expression = (expression as ExplicitCastExpression)?.Operand ?? expression;
-                    Expression sumExpression = new SqlFunctionExpression("SUM", inputType, new[] { expression });
+                    Expression sumExpression = new SqlFunctionExpression(
+                        "SUM", inputType, new[] { UnwrapAliasExpression(expression) });
```
Comment (maumar) [inline src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs]: add newline after

Comment (smitpatel) [reply src/EFCore.Relational/Query/Internal/RelationalResultOperatorHandler.cs]: Will cover in future PR.
