### PR TITLE
[rc2] Stop using JSON_VALUE() RETURNING for uniqueidentifier on SQL Server 2025

### LINKED ISSUE #36627: SQL Server: new JSON_VALUE() RETURNING clause is incompatible with uniqueidentifier, geometry/geography
> Incorrect syntax near 'uniqueidentifier'

```SQL
SELECT JSON_VALUE([j].[Reference], '$.TestDefaultString') AS [TestDefaultString], JSON_VALUE([j].[Reference], '$.TestMaxLengthString') AS [TestMaxLengthString], CAST(JSON_VALUE([j].[Reference], '$.TestBoolean') AS bit) AS [TestBoolean], CAST(JSON_VALUE([j].[Reference], '$.TestByte') AS tinyint) AS [TestByte], JSON_VALUE([j].[Reference], '$.TestCharacter') AS [TestCharacter], CAST(JSON_VALUE([j].[Reference], '$.TestDateTime') AS datetime2) AS [TestDateTime], CAST(JSON_VALUE([j].[Reference], '$.TestDateTimeOffset') AS datetimeoffset) AS [TestDateTimeOffset], CAST(JSON_VALUE([j].[Reference], '$.TestDecimal') AS decimal(18,3)) AS [TestDecimal], CAST(JSON_VALUE([j].[Reference], '$.TestDouble') AS float) AS [TestDouble], CAST(JSON_VALUE([j].[Reference], '$.TestGuid') AS uniqueidentifier) AS [TestGuid], CAST(JSON_VALUE([j].[Reference], '$.TestInt16') AS smallint) AS [TestInt16], CAST(JSON_VALUE([j].[Reference], '$.TestInt32') AS int) AS [TestInt32], CAST(JSON_VALUE([j].[Reference], '$.TestInt64') AS bigint) AS [TestInt64], CAST(JSON_VALUE([j].[Reference], '$.TestSignedByte') AS smallint) AS [TestSignedByte], CAST(JSON_VALUE([j].[Reference], '$.TestSingle') AS real) AS [TestSingle], CAST(JSON_VALUE([j].[Reference], '$.TestTimeSpan') AS time) AS [TestTimeSpan], CAST(JSON_VALUE([j].[Reference], '$.TestDateOnly') AS date) AS [TestDateOnly], CAST(JSON_VALUE([j].[Reference], '$.TestTimeOnly') AS time) AS [TestTimeOnly], CAST(JSON_VALUE([j].[Reference], '$.TestUnsignedInt16') AS int) AS [TestUnsignedInt16], CAST(JSON_VALUE([j].[Reference], '$.TestUnsignedInt32') AS bigint) AS [TestUnsignedInt32], CAST(JSON_VALUE([j].[Reference], '$.TestUnsignedInt64') AS decimal(20,0)) AS [TestUnsignedInt64], CAST(JSON_VALUE([j].[Reference], '$.TestEnum') AS int) AS [TestEnum], CAST(JSON_VALUE([j].[Reference], '$.TestEnumWithIntConverter') AS int) AS [TestEnumWithIntConverter], CAST(JSON_VALUE([j].[Reference], '$.TestNullableEnum') AS int) AS [TestNullableEnum], CAST(JSON_VALUE([j].[Reference], '$.TestNullableEnumWithIntConverter') AS int) AS [TestNullableEnumWithIntConverter], JSON_VALUE([j].[Reference], '$.TestNullableEnumWithConverterThatHandlesNulls') AS [TestNullableEnumWithConverterThatHandlesNulls]
FROM [JsonEntitiesAllTypes] AS [j]
```

### PR DESCRIPTION
**Pull request by roji**
**NOTE: This PR is based on top of #36730, review last commit only**

Fixes #36627

**Description**
We added support for SQL Server 2025's JSON data type, which enhances the JSON_VALUE() support to include a RETURNING clause which types the data being extracted out of JSON documents. Unfortunately, the GUID data type specifically (uniqueidentifier) is not supported by SQL Server with the new RETURNING clause, so this PR falls back to the older typing mechanism via a CAST.

**Customer impact**
Without this PR, some queries involving a GUID value stored within JSON complex types fail when targeting SQL Server 2025 with the new JSON data type (mainline 10 scenario).

**How found**
Testing

**Regression**
No

**Testing**
Added, extended type tests to cover this.

**Risk**
Very low, trivial one-line change in new codepath.

### CODE REVIEW

**Comment by artl93** [comment]
Can we have a reviewer other than me?

File: src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs [hunk 1]
```diff
@@ -629,6 +629,9 @@ protected override Expression VisitJsonScalar(JsonScalarExpression jsonScalarExp
         // Note that we don't need to check the compatibility level - if the json type is being used, then RETURNING is supported.
         var useJsonValueReturningClause = !jsonQuery
             && jsonScalarExpression.Json.TypeMapping?.StoreType is "json"
+            // The following types aren't supported by the JSON_VALUE() RETURNING clause (#36627).
+            // Note that for varbinary we already transform the JSON_VALUE() into OPENJSON() earlier, in SqlServerJsonPostprocessor.
+            && jsonScalarExpression.TypeMapping?.StoreType is not "uniqueidentifier" and not "geometry" and not "geography"
```
Comment (AndriySvyryd) [inline src/EFCore.SqlServer/Query/Internal/SqlServerQuerySqlGenerator.cs]: Make this case-insensitive

File: test/EFCore.SqlServer.FunctionalTests/Query/JsonQueryJsonTypeSqlServerTest.cs [hunk 2]
```diff
@@ -2290,9 +2289,8 @@ public override async Task Json_boolean_predicate(bool async)
...
 FROM [JsonEntitiesAllTypes] AS [j]
-WHERE JSON_VALUE([j].[Reference], '$.TestBoolean' RETURNING bit) = CAST(1 AS bit)
 """);
```
Comment (AndriySvyryd) [inline test/EFCore.SqlServer.FunctionalTests/Query/JsonQueryJsonTypeSqlServerTest.cs]: Also unskip `Json_predicate_on_guid`
