### PR TITLE
Metadata: Run SqlServerIndexConvention when changing base type

### LINKED ISSUE #10659: Metadata: Unique Index on derived type does not exclude nulls
Creating a one to one relationship on a derived type doesn't work if the table name starts with a capital 'S'. The index that is created for the foreign key is usually a conditional index with the filter: "[RssImageRefId] IS NOT NULL");. However, if the table name starts with a capital S, the filter does not get applied. It may be easier to understand by trying the simple program below. 
```
SqlException: Cannot insert duplicate key row in object 'dbo.SBlogs' with unique index 'IX_SBlogs_RssImageRefId'. The duplicate key value is (<NULL>).
The statement has been terminated.
```

### Steps to reproduce
Uncommenting the commented line below fixes the problem. 

```c#
using Microsoft.EntityFrameworkCore;
using System;

namespace UniqueIndexTest
{
	class Program
	{
		static void Main(string[] args)
		{
			using (var myContext = new MyContext())
			{
				var rssBlog = new RssBlog();
				var rssImage = new RssImage();
				rssImage.RssBlogCurrent = rssBlog;
				myContext.Add(rssBlog);
				myContext.Add(rssImage);
				myContext.SaveChanges();
				myContext.Add(new Blog());
				myContext.Add(new Blog());
				myContext.SaveChanges();
			}
			Console.ReadLine();
		}
	}

	public class MyContext : DbContext
	{
		public DbSet<RssImage> RssImages { get; set; }
		// the line below works if you change it to: 
		//public DbSet<Blog> Blogs { get; set; }
		public DbSet<Blog> SBlogs { get; set; }
		public DbSet<RssBlog> RssBlogs { get; set; }

		protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
		{
			optionsBuilder.UseSqlServer(@"Data Source=" + System.Environment.MachineName +
				";Initial Catalog=uniqueIndexTest;" + "Integrated Security=True" +
				";Connect Timeout=15;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False");
			optionsBuilder.EnableSensitiveDataLogging();
			optionsBuilder.ConfigureWarnings(w => w.Log(
				Microsoft.EntityFrameworkCore.Diagnostics.CoreEventId.SensitiveDataLoggingEnabledWarning));
		}
	}

	public class Blog
	{
		public int Id { get; set; }
	}

	public class RssBlog : Blog
	{
		public RssImage RssImageRef { get; set; }
		public int RssImageRefId { get; set; }
	}

	public class RssImage 
	{
		public int Id { get; set; }
		public RssBlog RssBlogCurrent { get; set; }
	}
}
```

### Further technical details
EF Core version: 2.0.1
Database Provider:  Microsoft.EntityFrameworkCore.SqlServer 2.0.1
Operating system: Windows 10
IDE: Visual Studio 2017 15.5.2

### PR DESCRIPTION
**Pull request by smitpatel**
SqlServerIndexConvention sets filter on unique index based on column null-ability.
When changing base type, the column null-ability in derived type changes so we need to update the filter.
Fix is to trigger convention for BaseTypeChanged

Resolves #10659

### CODE REVIEW

File: src/EFCore.SqlServer/Metadata/Conventions/Internal/SqlServerIndexConvention.cs [hunk 1]
```diff
@@ -32,6 +33,20 @@ public SqlServerIndexConvention([NotNull] ISqlGenerationHelper sqlGenerationHelp
             _sqlGenerationHelper = sqlGenerationHelper;
         }
 
+        /// <summary>
+        ///     This API supports the Entity Framework Core infrastructure and is not intended to be used
+        ///     directly from your code. This API may change or be removed in future releases.
+        /// </summary>
+        public virtual bool Apply(InternalEntityTypeBuilder entityTypeBuilder, EntityType oldBaseType)
+        {
+            foreach (var index in entityTypeBuilder.Metadata.GetDeclaredIndexes())
```
Comment (AndriySvyryd) [inline src/EFCore.SqlServer/Metadata/Conventions/Internal/SqlServerIndexConvention.cs]: Only need to do this if current or old base type is null
