### PR TITLE
Metadata: Keep track of referencing FKs defined on QueryTypes

### LINKED ISSUE #13382: ModelBuilder: Discovering QueryType before referenced EntityType introduces unnecessary TempId
When I introduce an Entity Type object as "Principal entity" in QueryType Model I am getting an exception that.

EntityType is mapped to a table and QueryType is mapped to a View..

```
SqlException: Invalid column name 'TempId'.
 Invalid column name 'TempId'.
System.Data.SqlClient.SqlConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, bool breakConnection, Action<Action> wrapCloseInAction)
System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, bool callerHasConnectionLock, bool asyncClose)
System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, out bool dataReady)
System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
System.Data.SqlClient.SqlDataReader.get_MetaData()
System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, string resetOptionsString)
System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, bool returnStream, bool async, int timeout, out Task task, bool asyncWrite, SqlDataReader ds)
System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, bool returnStream, TaskCompletionSource<object> completion, int timeout, out Task task, bool asyncWrite, string method)
System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary<string, object> parameterValues)
Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary<string, object> parameterValues)
Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable<T>+Enumerator.BufferlessMoveNext(DbContext _, bool buffer)
Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.Execute<TState, TResult>(TState state, Func<DbContext, TState, TResult> operation, Func<DbContext, TState, ExecutionResult<TResult>> verifySucceeded)
Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable<T>+Enumerator.MoveNext()
System.Linq.Enumerable+SelectEnumerableIterator<TSource, TResult>.MoveNext()
System.Linq.Enumerable.TryGetFirst<TSource>(IEnumerable<TSource> source, out bool found)
lambda_method(Closure )
Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider+ResultEnumerable<T>.GetEnumerator()
Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider+ExceptionInterceptor<T>+EnumeratorExceptionInterceptor.MoveNext()
System.Linq.Enumerable.TryGetFirst<TSource>(IEnumerable<TSource> source, out bool found)
System.Linq.Enumerable.First<TSource>(IEnumerable<TSource> source)
Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler+<>c__DisplayClass15_1<TResult>.<CompileQueryCore>b__0(QueryContext qc)
System.Linq.Queryable.FirstOrDefault<TSource>(IQueryable<TSource> source, Expression<Func<TSource, bool>> predicate)
Atlas.Cases.Api.Controllers.CaseController.Get(int caseId) in CaseController.cs
+
            var caseConsultant = _caseContext.CaseConsultants
lambda_method(Closure , object , object[] )
Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(object target, object[] parameters)
Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor+SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)```

```
### Steps to reproduce
1. Create a view and 1 table in sql  server in different schemas..
2. Configure View as QueryType and Table as Entity in the db Context..
3. When Querying a QueryType include the object in the query..

```c#
    
    [Table("Person", Schema ="dbo")]
    public class Person
    {
        [Key]
        public int PID { get; set; }
        [ForeignKey("Address")]
        public int AddrID { get; set; }
        public virtual Address Address { get; set; }

    }

    public class CaseConsultant
    {
        [ForeignKey("Person")]
        public int PersonId { get; set; }
        [ForeignKey("MailingAddress")]
        public int AddressId { get; set; }
        public int CaseId { get; set; }
        public virtual PersonPerson { get; set; }
        public virtual Address MailingAddress { get; set; }
    }

    public class CaseConsultantConfiguration : IQueryTypeConfiguration<CaseConsultant>
    {
        public void Configure(QueryTypeBuilder<CaseConsultant> builder)
        {
            builder.ToView("CaseConsultant", "dbo");

            builder.Property(o => o.CaseId);
            builder.Property(o => o.PersonId);

            builder.HasOne(o => o.Person); ;

            builder.HasOne(o => o.MailingAddress);
        }
    }

   public class CaseContext : DbContext
    {
        public CaseContext()
        {

        }

        public CaseContext(DbContextOptions<CaseContext> options) : base(options)
        {
           
        }

        public DbQuery<CaseConsultant> CaseConsultants { get; set; }
        public DbSet<Person> Persons { get; set; }


        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {

        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.ApplyConfiguration(new CaseConsultantConfiguration());
        }
    }

    [Route("api/[controller]")]
    [ApiController]
    public class CaseController : ControllerBase
    {
        private CaseContext _caseContext;

        public CaseController(CaseContext caseContext)
        {
            _caseContext = caseContext;
        }

        [Route("{caseId}")]
        public CaseResponse Get(int caseId)
        {



            var person = _caseContext.Persons.Where(a => a.PID == 1);


            var caseConsultant = _caseContext.CaseConsultants
            .Include("Person")
            .FirstOrDefault(c => c.CaseId == caseId);


            return null;
        }



    }

```

### Further technical details
EF Core version: (2.1.3)
Database Provider: ( Microsoft.EntityFrameworkCore.SqlServer)
Operating system: Windows
IDE: (Visual Studio 2017 15.8.3)

### PR DESCRIPTION
**Pull request by smitpatel**
Issue: We did not keep track of referencing FKs on QueryTypes. This causes issue when query type is discovered first making FK to TempId.
Since when PK is discovered on EntityType, we cannot find referencing FK to replace on QueryType.

Resolves #13382

### CODE REVIEW

File: src/EFCore/ChangeTracking/Internal/NavigationFixer.cs [hunk 1]
```diff
@@ -580,7 +580,8 @@ private void DeleteFixup(InternalEntityEntry entry)
                         conflictingPrincipalForeignKey.PrincipalEntityType.DisplayName()));
             }
 
-            foreach (var foreignKey in entityType.GetReferencingForeignKeys())
+            foreach (var foreignKey in entityType.GetReferencingForeignKeys()
+                                        .Where(fk => !fk.DeclaringEntityType.IsQueryType))
```
Comment (AndriySvyryd) [inline src/EFCore/ChangeTracking/Internal/NavigationFixer.cs]: Use 'if' for better perf
