### PR TITLE
Query: Improvements to Relational GroupBy translation for composition

### LINKED ISSUE #9969: Query: Translate GroupBy constant value followed by aggregate as table aggregate
Based on https://github.com/aspnet/EntityFrameworkCore/issues/2341#issuecomment-326918994 & https://github.com/aspnet/EntityFrameworkCore/issues/2341#issuecomment-334268880

```C#
var query = context.Orders.Where(o => (o.OrderId > 0))
.GroupBy(Param_0 => 0)
.Select(Param_1 => new {
P0 = Param_1.Key,
P1 = Param_1.Count(),
P2 = Param_1.Sum(elem => elem.Freight),
P3 = Param_1.Max(elem => elem.ShipName),
P4 = Param_1.Min(elem => elem.ShipAddress)
});
```

Queries like above cannot be translated to relational group by since group by constant is invalid SQL
```SQL
select CustomerID, count(*) from orders
group by 0;
```
throws
```
Msg 164, Level 15, State 1, Line 2
Each GROUP BY expression must contain at least one column that is not an outer reference.
```

Since the purpose of such queries is just to get full aggregate of whole table rather than group-wise, we can perhaps rewrite QueryModel to simplify the task beforehand so our translation pipeline can work seamlessly. 

As indicated by @bricelam , some of the frameworks are generating such queries (he can fill in more details), hence we should separately prioritize that work, hence filing this issue.

### LINKED ISSUE #10870: Query: GroupBy with Where produces invalid SQL
Using GroupBy with Where produces invalid SQL

```
Exception message:
   Microsoft.Data.Sqlite.SqliteException: 'SQLite Error 1: 'misuse of aggregate function COUNT()'.'
Stack trace:
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.<PrepareAndEnumerateStatements>d__62.MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader()
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(DbContext _, Boolean buffer)
   at Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider.<_GroupBy>d__19`3.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MegaDedup.Program.Main(String[] args) in Program.cs:line 24
```

### Steps to reproduce

```c#
class Program
{
    public static readonly LoggerFactory MyLoggerFactory = new LoggerFactory(new[] { new ConsoleLoggerProvider((_, __) => true, true) });

    static void Main(string[] args)
    {
        var context = new FileContext();
        context.Database.EnsureCreated();

        context.FileEntries
            .GroupBy(x => x.Size)
            .Where(x => x.Count() > 1)
            .Select(x => x.Key)
            .ToList();
    }
}

class FileContext : DbContext
{
    public DbSet<FileEntry> FileEntries { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        var builder = new SqliteConnectionStringBuilder();
        builder.DataSource = "db.sqlite";
        optionsBuilder
            .UseLoggerFactory(Program.MyLoggerFactory)
            .UseSqlite(builder.ToString());
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<FileEntry>()
            .HasIndex(x => x.Size);
    }
}

class FileEntry
{
    public long Id { get; set; }
    public long Size { get; set; }
    public string Path { get; set; }
}
```

### Produced SQL
```sql
SELECT "x"."Id", "x"."Path", "x"."Size"
FROM "FileEntries" AS "x"
WHERE COUNT(*) > 1
ORDER BY "x"."Size"
```

### Expected SQL
```sql
SELECT "x"."Size"
FROM "FileEntries" AS "x"
GROUP BY "x"."Size"
HAVING COUNT(*) > 1
```

### Further technical details
EF Core version: 2.1.0-preview1-28226
Database Provider: Microsoft.EntityFrameworkCore.Sqlite
Operating system: Windows 10 Pro
IDE: Visual Studio 2017 15.6 p3

### LINKED ISSUE #11157: Query: Incorrect warning about group by client eval
Repro code:
```C#
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace EFSampleApp
{
    public class Program
    {
        public static void Main(string[] args)
        {
            using (var db = new MyContext())
            {
                // Recreate database
                db.Database.EnsureDeleted();
                db.Database.EnsureCreated();

                // Seed database


                db.SaveChanges();
            }

            using (var db = new MyContext())
            {
                // Run queries
                var groupedOrders = db.Order
                    .Where(x => x.CompletedOrderId != null)
                    .Where(x => x.OrderDateDt > DateTime.Now.AddDays(-30))
                    .GroupBy(x => new { x.OrderDateDt })
                    .Select(x => new
                    {
                        Date = x.Key.OrderDateDt,
                        Count = x.Count()
                    })
                    .ToList();

            }

            Console.WriteLine("Program finished.");
        }
    }


    public class MyContext : DbContext
    {
        private static ILoggerFactory LoggerFactory => new LoggerFactory().AddConsole(LogLevel.Trace);

        // Declare DBSets
        public DbSet<Order> Order { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            // Select 1 provider
            optionsBuilder
                .UseSqlServer(@"Server=(localdb)\mssqllocaldb;Database=_ModelApp;Trusted_Connection=True;Connect Timeout=5;ConnectRetryCount=0")
                //.UseSqlite("filename=_modelApp.db")
                //.UseInMemoryDatabase(databaseName: "_modelApp")
                .EnableSensitiveDataLogging()
                .UseLoggerFactory(LoggerFactory);
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            // Configure model
        }
    }

    public class Order
    {
        public int Id { get; set; }
        public int? CompletedOrderId { get; set; }
        public DateTime OrderDateDt { get; set; }
    }
}
```
```
dbug: Microsoft.EntityFrameworkCore.Query[10104]
      Optimized query model:
      'from IGrouping<<>f__AnonymousType0<DateTime>, Order> x in
          (from Order x in DbSet<Order>
          where [x].CompletedOrderId != null
          where [x].OrderDateDt > DateTime DateTime.Now.AddDays(-30)
          select [x]).GroupBy(new <>f__AnonymousType0`1(OrderDateDt = [x].OrderDateDt), [x])
      select new <>f__AnonymousType1<DateTime, int>(
          [x].Key.OrderDateDt,

              (from Order <generated>_1 in [x]
              select [<generated>_1]).Count()
      )'
warn: Microsoft.EntityFrameworkCore.Query[20500]
      The LINQ expression 'GroupBy(new <>f__AnonymousType0`1(OrderDateDt = [x].OrderDateDt), [x])' could not be translated and will be evaluated locally.
dbug: Microsoft.EntityFrameworkCore.Query[10107]
      (QueryContext queryContext) => IEnumerable<<>f__AnonymousType1<DateTime, int>> _InterceptExceptions(
          source: IEnumerable<<>f__AnonymousType1<DateTime, int>> _ShapedQuery(
              queryContext: queryContext,
              shaperCommandContext: SelectExpression:
                  SELECT [x].[OrderDateDt], COUNT(*)
                  FROM [Order] AS [x]
                  WHERE [x].[CompletedOrderId] IS NOT NULL AND ([x].[OrderDateDt] > DATEADD(day, -30E0, GETDATE()))
                  GROUP BY [x].[OrderDateDt],
              shaper: TypedProjectionShaper<ValueBufferShaper, ValueBuffer, <>f__AnonymousType1<DateTime, int>>),
          contextType: EFSampleApp.MyContext,
          logger: DiagnosticsLogger<Query>,
          queryContext: queryContext)
```

### LINKED ISSUE #11176: Query: groupby doesn't get translated if the result is projected into DTO
This translates correctly:

```cs
                var query = ctx.Children
                    .Select(c => c.Group)
                    .GroupBy(g => g)
                    .Select(g => new
                    {
                        Group = g.Key,
                        GroupCount = g.Count()
                    }).ToList();
```

into:

```
SELECT [c].[Group], COUNT(*)
            FROM [Children] AS [c]
            GROUP BY [c].[Group]
```

but this:

```
                var query = ctx.Children
                    .Select(c => c.Group)
                    .GroupBy(g => g)
                    .Select(g => new BarVm
                    {
                        Group = g.Key,
                        GroupCount = g.Count()
                    }).ToList();
```

produces the following query plan:

```
(QueryContext queryContext) => IEnumerable<BarVm> _InterceptExceptions(
    source: IEnumerable<BarVm> _Select(
        source: IEnumerable<IGrouping<int, int>> _GroupBy(
            source: IEnumerable<ValueBuffer> _ShapedQuery(
                queryContext: queryContext, 
                shaperCommandContext: SelectExpression: 
                    SELECT [c].[Group]
                    FROM [Children] AS [c]
                    ORDER BY [c].[Group], 
                shaper: ValueBufferShaper), 
            keySelector: (ValueBuffer c) => int TryReadValue(c, 0, Child.Group), 
            elementSelector: (ValueBuffer c) => int TryReadValue(c, 0, Child.Group)), 
        selector: (IGrouping<int, int> g) => new BarVm{ 
            Group = g.Key, 
            GroupCount = int Count(g) 
        }
    ), 
    contextType: Repro10472.MyContext, 
    logger: DiagnosticsLogger<Query>, 
    queryContext: queryContext)
```

### LINKED ISSUE #11218: 'AS' in group by statement when an 'AS' is present in the select statement
```
Emploi
{
    public int EmployeurId {get; set;}
    public Employeur Employeur {get;set;}
...
}

Employeur
{
    public int Id {get; set;}
    public string NomCourt {get;set;}
... 
}
```

EF uses Emploi.EmployeurId instead of Emploi.Employeur.Id which is ok.  It renames it in the query with 'AS' statement.  The problem is that the statement get copied in the group by clause with the 'AS' in it.
```
emploiQuery
.GroupBy(e => new { e.Employeur.Id, e.Employeur.NomCourt })
.Select(grp => new { Value = grp.Key.Id, Label = grp.Key.NomCourt, Count = grp.Count() })
```

This generates the following query:
```
SELECT [e].[EmployeurId] AS [Id], [e.Employeur].[NomCourt], COUNT(*)
FROM [Emploi] AS [e]
INNER JOIN [Employeur] AS [e.Employeur] ON [e].[EmployeurId] = [e.Employeur].[Id]
GROUP BY [e].[EmployeurId] AS [Id], [e.Employeur].[NomCourt]
```

### PR DESCRIPTION
**Pull request by smitpatel**
Query: Improvements to Relational GroupBy translation for composition

- Add support for translating OrderBy after GroupBy operator
- Add support for `HAVING` clause in SQL which would be generated when translating predicate after GroupByAggregate Resolves #10870
- Make sure client eval warning is not issued when translating GroupByAggregate Resolves #11157
- GroupBy Aggregate works when element/result selector is DTO instead of anonymous type Resolves #11176 (KeySelector has to be client evaluated)
- Make sure that SQL added to GROUP BY clause is not aliased Resolves #11218
- Translate GroupBy Constant/Parameter with aggregates Resolves #9969

Part of #10012 
Part of #2341

### CODE REVIEW

**Comment by smitpatel** [comment]
Ping!

File: src/EFCore.Relational/Query/Expressions/SelectExpression.cs [hunk 1]
```diff
@@ -93,6 +93,14 @@ public class SelectExpression : TableExpressionBase
         /// </value>
         public virtual Expression Predicate { get; [param: CanBeNull] set; }
 
+        /// <summary>
+        ///     Gets or sets the predicate corresponding to the HAVING part of the SELECT expression.
+        /// </summary>
+        /// <value>
+        ///     The predicate.
+        /// </value>
+        public virtual Expression HavingExpression { get; [param: CanBeNull] set; }
```
Comment (anpete) [inline src/EFCore.Relational/Query/Expressions/SelectExpression.cs]: Having

**Comment by smitpatel** [comment]
Updated to translate group by constant/parameter. Ready for review.

File: test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs [hunk 2]
```diff
@@ -756,20 +881,123 @@ public override void Self_join_GroupBy_Aggregate()
...
+
+        public override void GroupBy_filter_count()
+        {
+            base.GroupBy_filter_count();
+
+            AssertSql(
+                @"SELECT [o].[CustomerID] AS [Key], COUNT(*) AS [Count]
+FROM [Orders] AS [o]
+GROUP BY [o].[CustomerID]
+HAVING COUNT(*) > 4");
```
Comment (bricelam) [inline test/EFCore.SqlServer.FunctionalTests/Query/GroupByQuerySqlServerTest.cs]: 🎉

File: src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs [hunk 3]
```diff
@@ -202,10 +193,47 @@ public override Expression Visit(Expression expression)
...
+                        }
+
+                        _isGroupAggregate = false;
+                        var translatedKey = Visit(groupResultOperator.KeySelector);
+                        _isGroupAggregate = true;
+
+                        return translatedKey;
+                    }
+
+                    goto default;
```
Comment (anpete) [inline src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs]: Can the default block be moved after the switch?

File: src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs [hunk 4]
```diff
@@ -721,11 +711,35 @@ var newMemberExpression
 
         private Expression TryBindQuerySourcePropertyExpression(MemberExpression memberExpression)
         {
-            if (memberExpression.Expression is QuerySourceReferenceExpression qsre)
+            if (!(memberExpression.Expression is QuerySourceReferenceExpression qsre))
```
Comment (anpete) [inline src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs]: Flip condition?

Comment (smitpatel) [reply src/EFCore.Relational/Query/ExpressionVisitors/SqlTranslatingExpressionVisitor.cs]: Flipping condition wouldn't avoid nesting. First if block retrieves the QSRE in multiple cases. Second if block uses QSRE to find the translation.

File: src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs (hunk 3 above)
Comment (smitpatel) [reply src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs]: Yes. Would it matter though?

Comment (anpete) [reply src/EFCore.Relational/Query/ExpressionVisitors/RelationalProjectionExpressionVisitor.cs]: Code would be more standard. n-dev problem :trollface:
