### PR TITLE
Correctly identify owned entity materialization without owner

### LINKED ISSUE #18024: Query: Owned entity throws incorrect tracking error
When Owned navigation is in base class and querying for derived type
```C#
public class Blog
    {
        public int Id { get; set; }
        public OwnedEntity OwnedEntity { get; set; }
    }

    public class SpecialBlog : Blog
    {

    }

    [Owned]
    public class OwnedEntity
    {
        public string OwnedProperty { get; set; }
    }

var query = db.Set<SpecialBlog>().ToList();
```

### PR DESCRIPTION
**Pull request by smitpatel**
Resolves #18024

### CODE REVIEW

File: src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs [hunk 1]
```diff
@@ -281,13 +281,13 @@ public Expression Inject(Expression expression)
                 var result = Visit(expression);
                 if (_trackQueryResults)
                 {
-                    bool containsOwner(IEntityType owner)
-                        => owner != null && (_visitedEntityTypes.Contains(owner) || containsOwner(owner.BaseType));
+                    bool ContainsOwner(IEntityType owner)
```
Comment (maumar) [inline src/EFCore/Query/ShapedQueryCompilingExpressionVisitor.cs]: nit: move it after return statement
